### ISSUE TITLE
`canonical_url` property is not applied

### ISSUE THREAD

**Issue by robingenz** [squidfunk/mkdocs-material#6197] opened 2023-10-16 07:35 UTC
### Context

I have migrated my blog posts from [dev.to](https://dev.to/robingenz/) to Material for MkDocs and would like to put a canonical link to the previous posts on dev.to, e.g.:

```html
<link rel="canonical" href="https://dev.to/capawesome/announcing-the-capacitor-nfc-plugin-1550">
```

### Bug description

I set the `canonical_url` property but it is not applied.

### Example

**Code** (`/docs/blog/posts/hello-world.md`):

```md
---
date: 2021-10-10
canonical_url: https://dev.to/capawesome/announcing-the-capacitor-nfc-plugin-1550
---

# Hello, world!
```

Current behavior:

```html
<link rel="canonical" href="http://127.0.0.1:8000/blog/2021/10/10/hello-world/">
```

Expected behavior:

```html
<link rel="canonical" href="https://dev.to/capawesome/announcing-the-capacitor-nfc-plugin-1550">
```

### Related links

I found just one example for the social cards:
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=canonical+url#tags

But according to this template it should be supported: https://github.com/squidfunk/mkdocs-material/blob/2742a707cca63b52d17466d0b918f8c411cf99b3/src/templates/base.html#L50

### Reproduction

[9.4.6-canonical-url.zip](https://github.com/squidfunk/mkdocs-material/files/12913361/9.4.6-canonical-url.zip)

### Steps to reproduce

1. Run the reproduction: `mkdocs serve`
2. Navigate to the blog post: [http://0.0.0.0:8000/blog/2021/10/10/hello-world/](http://0.0.0.0:8000/blog/2021/10/10/hello-world/)
3. Take a look at the page source

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment] 2023-10-16 08:17
Yes, this seems to be a bug, which would be fixed by:
```
21,22c21,22
<       {% if page.canonical_url %}
<         <link rel="canonical" href="{{ page.canonical_url }}">
---
>       {% if page.meta and page.meta.canonical_url %}
>         <link rel="canonical" href="{{ page.meta.canonical_url }}">
```

Do you want to do a pull request or should I?

**Comment by robingenz** [comment] 2023-10-16 08:29
Thanks for your help! I will create a PR.

**Comment by squidfunk** [comment] 2023-10-16 09:06
This is not a bug, it's working by design, as the [`canonical_url`](https://www.mkdocs.org/dev-guide/themes/#mkdocs.structure.pages.Page.canonical_url) is computed by MkDocs. It is not a value that you set manually, never has been. If you need to set it manually (first time this was requested), please use theme extension. Merging your PR will break automatically set canonical URLs for everyone else that doesn't set them explicitly, which may impede search engine rankings. Thus, we cannot progress here.

**Closed by squidfunk** 2023-10-16 09:06 UTC
Labels: bug

**Comment by alexvoss** [comment] 2023-10-16 09:23
Thanks for the clarification and sorry I confidently marched in the wrong direction. Hope this will help someone else in the future.

**Comment by squidfunk** [comment] 2023-10-16 09:27
No worries! Maybe it shows that it's always a good idea to check the MkDocs documentation, especially when it's concerning potential changes to [`base.html`](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/base.html). This template is deployed on tens of thousands of sites and changes to it should be thought of and evaluated very carefully ☺️

Since MkDocs introduced hooks in 1.4, doing small modifications with hooks is becoming a great alternative to theme extension, which we should also add examples for. The case discussed by OP could be one of those examples. It's only 3 lines of code, and it allows the author to completely customize behavior, whereas we would need to find a very general way to do it if done in template land.

**Comment by robingenz** [comment] 2023-10-16 10:43
> This is not a bug, it's working by design, as the [`canonical_url`](https://www.mkdocs.org/dev-guide/themes/#mkdocs.structure.pages.Page.canonical_url) is computed by MkDocs. It is not a value that you set manually, never has been. If you need to set it manually (first time this was requested), please use [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme). Merging your PR will break automatically set canonical URLs for everyone else that doesn't set them explicitly, which may impede search engine rankings. Thus, we cannot progress here.
> 
> **Edit**: it might be even simpler to just create a [hook](https://www.mkdocs.org/user-guide/configuration/#hooks) that allows to override the canonical URL for you. The canonical URL is [set during page creation](https://github.com/mkdocs/mkdocs/blob/44e6536060a711648830d439096dbe810b0774d2/mkdocs/structure/pages.py#L47), so something like the following should work
> 
> ```python
> def on_page_markdown(markdown, *, page, config, files):
>     if "canonical_url" in page.meta:
>          page.canonical_url = page.meta.canonical_url
> ```

Thanks, this worked! I just had to apply this change:

```diff
def on_page_markdown(markdown, *, page, config, files):
    if "canonical_url" in page.meta:
-         page.canonical_url = page.meta.canonical_url
+         page.canonical_url = page.meta["canonical_url"]
```

**Comment by squidfunk** [comment] 2023-10-16 11:39
Corrected my example, thanks!
