### ISSUE TITLE
Make section index page links more visible

### ISSUE THREAD

**Issue by ekoleda-codaio** [squidfunk/mkdocs-material#4832] opened 2023-01-05 19:06 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

When using both the feature `navigation.sections` and `navigation.indexes` you can get into situations where the section header is itself a link to an index page. For example, [on this page](https://coda.io/packs/build/latest/support/) the headers "Migration" and "Contributing" appear like other section headings, but are in fact clickable links to index pages.

![Screen Shot 2023-01-05 at 1 57 58 PM](https://user-images.githubusercontent.com/88106038/210859489-1895d3ab-8cc5-4c0b-a82a-91fc438f11d9.png)

On hover the color of the text changes to indicate there is a link, but prior to that there is no visual indication to the user that more content lives there.

I'm not sure what the best UI treatment should be, but it would be great if the clickable section headers were visually distinguished from the non-clickable ones.

### Use Cases

It would make it easier for users to discover content, or at least less likely to miss content that they are looking for.

**Comment by ekoleda-codaio** [comment] 2023-01-05 19:13
I should note that I think the issue exists to a lesser degree when using `navigation.indexes` on its own. Visually there is no difference between a grouping node with a page and one without. That said, I think people are more likely to click on the unbolded non-section grouping nodes than they are on the bolded section headers.

**Comment by squidfunk** [comment] 2023-01-05 20:04
Thanks for suggesting. So off the top of my head, the simplest thing we could probably do is make non-clickable sections greyish, while keeping clickable links black. Off course, it's trivial to apply further styling, but I think this might be a good default. It could look something like this:

<img width="197" alt="Bildschirmfoto 2023-01-05 um 21 04 03" src="https://user-images.githubusercontent.com/932156/210870074-32656bf4-5f74-49b3-910b-05d22547202b.png">

**Comment by ekoleda-codaio** [comment] 2023-01-05 20:16
Another approach, maybe a bit more involved, would be to have `navigation.indexes` not apply to section headers (or make that an option). I enabled `navigation.indexes` to help with pages nested under other pages, but for section headers maybe it makes sense to ignore that and keep the indexes as separate entries in the nav.

**Comment by squidfunk** [comment] 2023-01-05 21:32
I'm not sure I would agree – I think it's very useful that it applies to section headers. However, in the end it might be a matter of taste. As always, we try to strike a good balance here. If you have `navigation.indexes` enabled, and don't want to apply it to a section, you can always rename the file into something other than `index.md`.

**Comment by squidfunk** [comment] 2023-01-05 21:44
fc352ee44 is an attempt to improve discernability of section index pages in navigation. If that's not to the taste of the author, it can be easily changed with a little CSS, overriding the selectors that apply the styles.

**Comment by ekoleda-codaio** [comment] 2023-01-06 03:20
Thanks for the quick attention. I'll give it a try.

**Comment by squidfunk** [comment] 2023-01-08 12:07
Released as part of [9.0.3](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.3).

**Comment by marc2k3** [comment] 2023-01-08 16:21
I really dislike this change in 9.0.3 on the left. 9.0.2 on the right is far more pleasant.

![image](https://user-images.githubusercontent.com/62050527/211207025-55295c85-af09-466d-b086-209818fbc32b.png)

I need some CSS please. 😬

**Comment by squidfunk** [comment] 2023-01-08 16:23
Well, the points the author brought up are very relevant – it's unclear whether a section index is clickable or not. Do you have a better idea how we could distinguish both cases with alternate styling?

**Comment by marc2k3** [comment] 2023-01-08 17:22
In my particular use case, none of the section headers are clickable and with that lack of contrast, it just looks like a huge list with no grouping at all. I have no idea what any solution could look like. It's very much "not my thing" (tm)

Since I'm utterly clueless, I'll pin my github action to 9.0.2.

**Comment by squidfunk** [comment] 2023-01-08 17:56
It's trivial to override. Use the following CSS to revert to the previous behavior:

``` css
.md-nav__link[for] {
  color: var(--md-default-fg-color)
}
```

Please keep in mind that with a project of this size, it's impossible to please everybody. This is why this theme is extensible, hackable and easy to customize. We're putting a huge effort on keeping overriding as simple as possible. In this case, accessibility is clearly the priority, which is why we made links discernible.

**Comment by marc2k3** [comment] 2023-01-08 18:08
That's great, thanks.

**Comment by dr-br** [comment] 2023-01-10 14:10
Sorry for bumping in again (I opened #4841)
In this conversation here it is mentioned, that the gray color should denote, that a section is not clickable. However, the most basic case results in a gray but clickable section index (not sure if i interprete "section index" correctly):

```
site_name: My Docs
theme:
  name: material

nav:
  - Topic 1:
    - index0.md
    - index1.md
  - Topic 2:
    - index2.md
    - index3.md
```
results to this ("Topic 1" and "Topic 2" are clickable):
![grafik](https://user-images.githubusercontent.com/45423137/211571855-068ebe8a-db84-4f6e-8928-becec938e843.png)

I'm aware, that 3 lines of css can remedy this, however the statement gray == not clickable does not hold here.

**Comment by squidfunk** [comment] 2023-01-10 14:21
The behavior is correct – clickable in that case meant there's an actual page behind that section index. We might consider limiting the grey color to navigation section without index pages behind them, but that would make it less consistent.

**Comment by dr-br** [comment] 2023-01-10 14:47
Thanks for being that patient ;)

This minimal example
```
site_name: My Docs
theme:
  name: material
  features:
    - navigation.indexes
nav:
  - Topic 1:
    - folder0/index.md
    - folder0/index0.md
    - folder0/index1.md
  - Topic 2:
    - index2.md
    - index3.md
```
Results to this:

![grafik](https://user-images.githubusercontent.com/45423137/211582005-fcc0a67e-f63f-49e0-aca3-08f893f86048.png)

I'll try to figure out, how to make this more consistent.

**Comment by dr-br** [comment] 2023-01-10 15:07
Using `navigation.sections` makes the minimal example consistent, black == clickable. Without `navigation.sections`, "Topic 1" and "Topic 2" should remain black.
```
site_name: My Docs
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
nav:
  - Topic 1:
    - folder0/index.md
    - folder0/index0.md
    - folder0/index1.md
  - Topic 2:
    - index2.md
    - index3.md
```

![grafik](https://user-images.githubusercontent.com/45423137/211586841-49f55b87-13e2-478d-96c4-26d1ed6340b2.png)

**Comment by squidfunk** [comment] 2023-01-10 16:29
@dr-br Could I please ask you to provide [reproductions](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/) for both cases? It makes the life of us maintainers much easier.

**Comment by dr-br** [comment] 2023-01-10 16:46
It is my pleasure to do so:
[example_withoutNavigationSections.zip](https://github.com/squidfunk/mkdocs-material/files/10384848/example_withoutNavigationSections.zip)
[example_withNavigationSections.zip](https://github.com/squidfunk/mkdocs-material/files/10384853/example_withNavigationSections.zip)

The sample *withNavigationSections* is logically consistent.

**Comment by squidfunk** [comment] 2023-01-10 18:29
Thanks for the reproduction, made it trivial to inspect the situation! Fixed in 02637ef13. Only sections should now receive the grey color, regardless of `navigation.indexes`. I've also checked with `navigation.sections`.

Your example:

<img width="260" alt="Bildschirmfoto 2023-01-10 um 19 24 42" src="https://user-images.githubusercontent.com/932156/211632768-db0854a8-f790-417b-baae-f4122791a533.png">

Your example without `navigation.indexes`:

<img width="267" alt="Bildschirmfoto 2023-01-10 um 19 24 57" src="https://user-images.githubusercontent.com/932156/211632812-257b28d7-0f51-4b07-909b-982977fcb6b7.png">


Your example with `navigation.sections` and some deeper navigation added:

<img width="254" alt="Bildschirmfoto 2023-01-10 um 19 24 02" src="https://user-images.githubusercontent.com/932156/211632665-66dd31be-88a1-4b5d-a4fe-1b44c4e994ae.png">

**Comment by squidfunk** [comment] 2023-01-10 18:59
There was one additional case that needed to be handled, which is the titles of sections when `navigation.tabs` is enabled. This is fixed in ce5e3531c, so titles which do not lead to pages are now rendered grey again. Navigation with its thousand possibilities of combination can be a hellscape at times 😅

**Comment by dr-br** [comment] 2023-01-10 19:23
Excellent work. Thanks for reopening/fixing. I guess, the initial consideration of @ekoleda-codaio as well as the concerns of @marc2k3 have been met.
Grüße

**Comment by marc2k3** [comment] 2023-01-11 03:05
> There was one additional case that needed to be handled, which is the titles of sections when `navigation.tabs` is enabled. This is fixed in [ce5e353](https://github.com/squidfunk/mkdocs-material/commit/ce5e3531cf7f26f4234d83d51d79b5e0950907d7), so titles which do not lead to pages are now rendered grey again. Navigation with its thousand possibilities of combination can be a hellscape at times 😅

So this breaks my ability to style it using the CSS you gave me the other day. I tested the latest with 

`pip install https://github.com/squidfunk/mkdocs-material/archive/refs/heads/master.zip`

and this no longer works...

`.md-nav__link[for] { color: var(--md-default-fg-color) }`

After poking around a bit, I managed to "fix" it by adding `!important`.

**Comment by squidfunk** [comment] 2023-01-11 07:14
I think using `!important` is your safest bet in order to guard against further changes in the CSS. As I mentioned, the navigation CSS is necessarily complex due to the thousand different ways navigation can be defined.

**Comment by squidfunk** [comment] 2023-01-12 08:15
The latest changes were released as part of [9.0.4](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.4).

**Closed by squidfunk** 2023-01-12 08:15 UTC
Labels: enhancement, fix available

**Comment by krahets** [comment] 2023-01-29 10:02
> Well, the points the author brought up are very relevant – it's unclear whether a section index is clickable or not. Do you have a better idea how we could distinguish both cases with alternate styling?

I agree with @marc2k3 that the gray color is too weak to show the title clearly. 

- The title with gray color can not make me realize it is unclickable.
- I don't think it is necessary to distinguish them because the answer reveals when we hover the cursor on the title. 
- If it is necessary, could we add different default icons or symbols to distinguish them?

**Comment by squidfunk** [comment] 2023-01-29 12:05
You can achieve all of that with [customization](https://squidfunk.github.io/mkdocs-material/customization/). Please understand that Material for MkDocs is heavily opinionated and tries to provide sensible and great defaults. If that doesn't match your taste, the theme is very extensible and hackable. We can't please everyone, so we need to keep a common ground.
