### ISSUE TITLE
Search field X button unclear that it clears instead of closes

### ISSUE THREAD

**Issue by retnikt** [squidfunk/mkdocs-material#1069] opened 2019-04-11 10:59 UTC
## Description

The X button in the search field clears the field, when I (and potentially other users) thought it should close the field. I was about to submit an issue that it didn't close it, when I found #229 which made me realised that it clears the field - I think this should be changed to say "clear" instead of an X button.

### Expected behavior

The search overlay would close

### Actual behavior

The search field clears

### Steps to reproduce the bug

1. Focus the search field
2. Click the X button

### Package versions

* Python: 3.7.2
* MkDocs: 1.0.4
* Material: 4.1.1

**Comment by matjaeck** [comment] 2019-04-11 11:54
Probably a design decision but agree with retnikt that the "x" button can be misleading - misunderstood it too when using the theme for the first time.

**Comment by squidfunk** [comment] 2019-04-11 11:56
Well, the search UX is actually adapted from Google search - they do it exactly like that on mobile. I would think that they should know there stuff.

**Comment by matjaeck** [comment] 2019-04-11 12:03
IMO the issue is that there is no way to close the search overlay on screen when both the site and the overlay are visible (aside from clicking somewhere outside the overlay which is actually a common thing). Not sure how to improve it though.

**Comment by squidfunk** [comment] 2019-04-11 12:30
There's no plan changing this. It's solved this way in Material for more than two years and the theme is already deployed on a huge number of installations. Changing the UX on such a central feature will probably confuse users more than it helps. Furthermore, it's the way Google does it, and they should know their way around search. For this reason, I'm closing this issue. Hiding the button on desktop is very easy with CSS.

**Closed by squidfunk** 2019-04-11 12:30 UTC

**Comment by retnikt** [comment] 2019-04-11 14:57
Fair enough.

**Comment by Ir1d** [comment] 2019-08-23 14:14
@squidfunk what do you think about this: when clicking the x button, we close the seaerch bar if it is empty, and clears the bar if it's not.

**Comment by squidfunk** [comment] 2019-08-23 15:31
I would really prefer leaving it as is for the reasons stated.
