### ISSUE TITLE
TOC: The last anchor is always highlighted instead of the current

### ISSUE THREAD

**Issue by MarkParker5** [squidfunk/mkdocs-material#5980] opened 2023-09-10 02:55 UTC
### Bug description

The last anchor in TOC is always highlighted instead of the current one; toc.follow / navigation.tracking are not working properly, url always contains the last anchor.

It's happening everywhere: in my test project, at [mkdocs-material](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/) and [fastapi](https://fastapi.tiangolo.com/)

<img width="1408" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/34688010/1ca0b220-67a4-4d77-9815-a01380713cd5">

### Related links

https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking

### Reproduction

https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking

### Steps to reproduce

https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-09-10 06:09
Thanks for reporting. Duplicate of #4029. Detailed explanation i https://github.com/squidfunk/mkdocs-material/issues/4029#issuecomment-1157324543

**Closed by squidfunk** 2023-09-10 06:09 UTC

**Comment by MarkParker5** [comment] 2023-09-10 06:34
UPD: just tested in incognito mode, it's working as expected. Probably, the reason is in my chrome extensions

**Comment by squidfunk** [comment] 2023-09-10 06:53
Thanks! Yes, that sounds about right.
