### ISSUE TITLE
Blog post metadata is slightly vertically scrollable on small screens

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#6169] opened 2023-10-10 12:15 UTC
### Bug description

Blog post metadata on small screens (less than 1220px width) can be slightly scrolled along the y-axis although there's enough space to show the complete metadata without scrolling. Scrolling makes sense on large screens (1220px width or more) when the metadata is placed in the sidebar and the screen height is insufficient to show the complete metadata, but scrolling should be disabled on small screens.

![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/caa7f800-90ab-4314-a98d-f925fb89b950)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Setting up a blog](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/)

### Reproduction

[9.4.5-blog-metadata-scroll-small-screen.zip](https://github.com/squidfunk/mkdocs-material/files/12856981/9.4.5-blog-metadata-scroll-small-screen.zip)

### Steps to reproduce

1. Start the reproduction site.
2. Go to http://localhost:8000/blog/2023/01/31/lege-est-in-sit-est/.
3. Reduce the browser's viewport width to less than 1220px.
4. Scroll to the blog post metadata section above the footer.
5. Hover the blog post metadata with the mouse, observe the visible vertical scrollbar only for the metadata container, scroll via mouse wheel and observe some slight scrolling only within the metadata block.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment] 2023-10-11 07:32
Thanks for the reproduction. I can confirm this for Firefox, Safari and Chrome. The scrollbars seem to be implemented deliberately, I assume with good reason. The question, then, is probably only one of making it less likely that they appear. Perhaps there is a tweak that @squidfunk can apply.

In the meantime, the `overflow-y` property is set to `auto` on a `div` with the class `.md-sidebar__scrollwrap`. If you are sure that this will not cause problems for your site you could override this in [extra.css](https://squidfunk.github.io/mkdocs-material/customization/#additional-css):

```
.md-sidebar__scrollwrap {
  overflow-y: visible
}
```

Hope this helps.

**Comment by squidfunk** [comment] 2023-10-14 08:28
Thanks for reporting! Indeed, the sidebar which hosts the blog post information has several shortcomings that need to be addressed, which we will do when working on the blog templates again. For now, 2800e7ea6 should be a bandaid.

**Comment by squidfunk** [comment] 2023-10-14 08:29
Oh, and thanks for all of the great bug reports and reproductions that you're submitting lately, @sisp. Really good work that helps us to identify the root causes of the reported problems quickly to fix them.

**Comment by sisp** [comment] 2023-10-14 08:39
Thanks for fixing this problem so promptly. :pray:

I'm glad to help, at the very least through helpful reports. :slightly_smiling_face: Thanks for your fantastic work on this project! :tada:

**Comment by squidfunk** [comment] 2023-10-14 08:50
Released as part of [9.4.6](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.6).

**Closed by squidfunk** 2023-10-14 08:50 UTC
Labels: bug, resolved, 🏆 perfect
