### ISSUE TITLE
Error: The "tags" plugin is not installed 

### ISSUE THREAD

**Issue by Realvincentyuan** [squidfunk/mkdocs-material#3942] opened 2022-05-21 10:51 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I used mkdocs-material 8.2.15 through pip and followed the steps in https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/ to set up tags.

The error is Error: The "tags" plugin is not installed.

### Expected behaviour

Tags should work as expected shown in the https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/

### Actual behaviour

It cannot build the docs at all

### Steps to reproduce

Please directly see our site source code: https://github.com/BulletTech/BulletTech

### Package versions

- Python: `3.9.7`
- MkDocs: `1.2.3`
- Material: `8.2.15`

### Configuration

```yaml
see here: https://github.com/BulletTech/BulletTech/blob/main/mkdocs.yml
```

### System information

Deployed in GitHub using GitHub action

**Comment by squidfunk** [comment] 2022-05-22 05:55
Thanks for reporting. However, I'm having trouble reproducing the issue. I've checked your GitHub Actions workflow and found a [commit](https://github.com/BulletTech/BulletTech/commit/bbb230f58b452bb8bc87fff1937bbd1c76e27340) with enabled tags plugin that builds successfully. For this reason, I believe you solved the problem, but did not close this issue. Please note that troubleshooting issues takes a lot of my time away from maintaining the project, especially when they appear to be non-issues but misconfiguration that could be solved by the author 😕 Closing.

**Closed by squidfunk** 2022-05-22 05:55 UTC

**Comment by Realvincentyuan** [comment] 2022-05-22 08:29
Hi @squidfunk,

In fact the workflow never worked when I wanted to add a tag index, I suggest to adding more examples as I saw a few people reporting this issue already. It is a great new feature so hopefully this is taken seriously.

**Comment by Realvincentyuan** [comment] 2022-05-22 08:32
@squidfunk 

Add that I cannot build the doc locally by calling `mkdocs serve` and the error is the same, I tried to install the seemingly relevant tags packages but it did not work either

**Comment by squidfunk** [comment] 2022-05-22 10:41
> In fact the workflow never worked when I wanted to add a tag index

This is a different issue from what is contained in the issue title, which says "The tags plugin is not installed". As the workflow was successfully completed and the project built with the tags plugin being active, it is not an issue. The tags plugin is installed and it works as expected. If you're having trouble when specifying the `tags_file` option, please provide a detailed description and a fully self-contained example, so I'm able to help you. Thank you.

> I suggest to adding more examples as I saw a few people reporting this issue already.

Then why did you open a new issue? You checked " ... there are no open or closed issues that are related to my problem". Please comment on the existing issue if the error was already reported.

> Add that I cannot build the doc locally by calling mkdocs serve and the error is the same, I tried to install the seemingly relevant tags packages but it did not work either

The tags package does not need to be installed. The documentation says it is "built-in", thus there is no third-party package that needs to be installed. The documentation is very clear about that.

**Comment by Realvincentyuan** [comment] 2022-05-22 13:44
> > In fact the workflow never worked when I wanted to add a tag index
> 
> This is a different issue from what is contained in the issue title, which says "The tags plugin is not installed". As the workflow was successfully completed and the project built with the tags plugin being active, it is not an issue. The tags plugin is installed and it works as expected. If you're having trouble when specifying the `tags_file` option, please provide a detailed description and a fully self-contained example, so I'm able to help you. Thank you.
> 
> > I suggest to adding more examples as I saw a few people reporting this issue already.
> 
> Then why did you open a new issue? You checked " ... there are no open or closed issues that are related to my problem". Please comment on the existing issue if the error was already reported.
> 
> > Add that I cannot build the doc locally by calling mkdocs serve and the error is the same, I tried to install the seemingly relevant tags packages but it did not work either
> 
> The tags package does not need to be installed. The documentation says it is "built-in", thus there is no third-party package that needs to be installed. The documentation is very clear about that.

@squidfunk . I also figured this my issue is different from the previous one so I opened a new issue, and I saw the `built-in` keyword so it looked strange when I saw the error was `the package is not installed`. 

In fact as long as I add the `tag_file` option, the error will show up as you can see in the errors of workflow. If `tag_file` option is not added, even thought the deployment passed without issue, you can see the tags are not rendered. So literally it did not work, even without explicit error.

Example post: https://bullettech.github.io/BulletTech/Main_Course/Deep_Learning/2022-05-20-CNN-Explainer/

**Comment by squidfunk** [comment] 2022-05-22 14:19
> In fact as long as I add the tag_file option

It's [`tags_file`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#tags-file), not `tag_file`. Might be the cause:

``` yaml
plugins:
  - tags:
      tags_file: tags.md
```

**Comment by Realvincentyuan** [comment] 2022-05-23 01:04
> 

@squidfunk 

I used `tags_file` in the code, I just typed `tag_file` in this conversation, as you see the workflow still failed.

https://github.com/BulletTech/BulletTech/runs/6547510040?check_suite_focus=true

**Comment by squidfunk** [comment] 2022-05-23 05:49
This sounds like an indentation error. Please make sure that the values are indented correctly.
