### ISSUE TITLE
Social cards do not render

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#6476] opened 2023-12-10 06:20 UTC
### Context

Since Discord tries fetching something, my guess is that versioning is not supported with social cards

### Bug description

Slack will immediately render text without the card:

![image](https://github.com/squidfunk/mkdocs-material/assets/9677399/b5df89db-a16a-4c5c-9829-937894397bc0)

Discord will render text but then continue attempting to fetch the card:

![image](https://github.com/squidfunk/mkdocs-material/assets/9677399/b6b4e70b-b732-4477-95a2-bf6ecb0b24a6)

### Related links

https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/

### Reproduction

This is the site https://hatch.pypa.io/dev/

### Steps to reproduce

Let Slack or Discord rendered that link

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-12-10 09:21
Thanks for reporting. Unfortunately, this issue does not contain a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), as demanded by our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) which you have assured to have read. Judging from your [`mkdocs.yml`](https://github.com/pypa/hatch/blob/master/mkdocs.yml) your site is quite complex, so the problem you#re describing might or might not be caused by Material for MkDocs.

Closing, as there's nothing we can do here. We can reopen when a reproduction that demonstrates the issue was provided.

**Comment by ofek** [comment] 2023-12-10 14:32
[9.5.1+insiders.4.47.0-social-card-no-image.zip](https://github.com/squidfunk/mkdocs-material/files/13628112/9.5.1%2Binsiders.4.47.0-social-card-no-image.zip)

**Comment by ofek** [comment] 2023-12-10 14:40
As I suspected, versioning is not yet compatible with social cards. When inspecting the page I see this among other things:

```html
<meta property=og:image content=https://hatch.pypa.io/latest/dev/assets/images/social/index.png>
```

**Comment by ofek** [comment] 2023-12-10 14:47
Okay, I think the issue is:

```yaml
https://hatch.pypa.io/latest/
```

I defined it as such because I wanted to prevent everybody everywhere getting a redirect, but perhaps there is no other option if I want social cards to work other than to get rid of `/latest/`?

**Comment by squidfunk** [comment] 2023-12-10 15:03
Yes, please remove `latest` and just define a redirect. This might have other consequences as well, and is definitely not something we can solve in the social plugin. We could, in theory, add another setting to the templates to specify a divergent path, but that would make little to no sense and cause more confusion that it would help, so we're not considering that.

**Closed by squidfunk** 2023-12-10 15:03 UTC
Labels: needs reproduction
