### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'toggle'

### ISSUE THREAD

**Issue by qdel** [squidfunk/mkdocs-material#2528] opened 2021-04-06 15:38 UTC
## Description

The mkdocs-material tag 7.1.0 available on pip does not work out of the box.

### Expected behavior

It should work!

### Actual behavior

```shell
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 87, in _build_template
    output = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/material/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/usr/local/lib/python3.9/site-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.9/site-packages/material/base.html", line 118, in top-level template code
    {% block header %}
  File "/usr/local/lib/python3.9/site-packages/material/base.html", line 119, in block "header"
    {% include "partials/header.html" %}
  File "/usr/local/lib/python3.9/site-packages/material/partials/header.html", line 36, in top-level template code
    <label class="md-header__button md-icon" title="{{ option.toggle.name }}" for="__palette_{{ loop.index0 or loop.length }}" hidden>
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'toggle'
```

### Steps to reproduce the bug

1. Use a docker container with:

```Dockerfile
FROM python:alpine
RUN apk add python3-dev gcc musl-dev && \
    pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin
```

### Package versions

* Python: `python --version`
Python 3.9.4
* MkDocs: `mkdocs --version`
mkdocs, version 1.1.2 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)
* Material: `pip show mkdocs-material | grep -E ^Version`
Version: 7.1.0

### Project configuration

``` yaml
site_name: template
theme:
    name: material
    palette:
        - scheme: preference
nav:
    - 'index.md'
    - 'submenu.md'
    - Titre:
        - 'submenu2.md'
plugins:
    - search
    - mermaid2:
        version: 8.9.0
        arguments:
            theme: |
              ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
```

### Workaround

It works correctly if i use mkdocs-material==7.0.7:

```Dockerfile
FROM python:alpine
RUN apk add python3-dev gcc musl-dev && \
    pip install mkdocs mkdocs-material==7.0.7 mkdocs-mermaid2-plugin
```

**Comment by squidfunk** [comment] 2021-04-06 15:45
Thanks for reporting. This is a duplicate of #2527 and #2511. Closing.

When reporting issues, it's best to first use the search, as this is already the second duplicate.

**Closed by squidfunk** 2021-04-06 15:45 UTC
