### ISSUE TITLE
Border displayed around expand button during animation on Firefox

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#5072] opened 2023-02-20 12:25 UTC
### Bug description

On Firefox, a small border is displayed around the "expand" button during its animation:

https://user-images.githubusercontent.com/2234833/220106623-cdfba791-98ab-412a-8a02-8249833b1442.mov

<br>This does not happen on Chrome:

https://user-images.githubusercontent.com/2234833/220105574-e2d0fa4f-7fdc-4a80-84bd-0ebd28218e5f.mov

### Related links

None

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10784296/example.zip)

### Steps to reproduce

1. Build the sample project.
2. Click on the expand button next to "Section".

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-02-22 18:09
Thanks for reporting! While it is not completely fixable, I think I found a good solution in 1663d84b0. The rotation is now defined on the icon (pseudo element), not the containing element, and by setting `border-radius` to the same value as the containing element the issue is almost entirely gone. Here's a video with a bright color which makes it particularly apparent:

https://user-images.githubusercontent.com/932156/220717710-f3d9a81a-a1cf-4afe-82a1-d7dbe63419d4.mp4

---

Note that the video itself has compression artifacts 😅 Let's hope that this get fixed in Firefox soon.

**Comment by wilhelmer** [comment] 2023-02-22 19:29
The bug is 2 years old, so I wouldn't count on it 😜 But it's therefore even better that you fixed it, worth the effort. Thanks!

**Comment by squidfunk** [comment] 2023-02-23 13:27
Released as part of [9.0.14](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.14).

**Closed by squidfunk** 2023-02-23 13:27 UTC
Labels: bug, resolved
