### ISSUE TITLE
Search freeze on first search

### ISSUE THREAD

**Issue by gridphp** [squidfunk/mkdocs-material#904] opened 2018-10-19 20:09 UTC
## Description

When ever we open the page first time and click on search box, it freezes for almost 10 seconds.

### Expected behavior

Should be instant like in other themes OR show what it is doing.

### Actual behavior

Freezing the whole window

### Steps to reproduce the bug

1. I've around 20 MD files with 5000 lines of text. 
2. Open main page and click search box
3. Wait and enjoy the slow speed.

In this screencast, i pressed button instantly but results were way too late.
https://i.imgur.com/KZU3G66.gifv

I changed theme to readthedocs, and tried as well which does not freeze.
Let me know what i am missing.

### Package versions

* Python: `3.7`
* MkDocs: `1.0.4`
* Material: `3.0.4`

### Project configuration

``` yaml
site_name: ................
site_description: .......... Documentation
# site_url:
site_author: '..............'
site_url: 'https://........../docs'

# Copyright
copyright: 'Copyright &copy; 2010 - 2018'

nav:
    - Getting Started:
      - 'Setup' : 'index.md'
      - 'Creating' : 'creating.md'
    - Customization:
      - 'Selecting Columns' : 'selecting-columns.md'
      - 'Column Options' : 'column-options.md'
      - 'Options' : 'options.md'
    - Features:
      - 'Master Detail' : 'master-detail.md'
      - 'Sub' : 'sub.md'
      - 'Exporting Data' : 'exporting-data.md'
      - 'Importing Data' : 'importing-data.md'
      - 'Conditional Formatting' : 'conditional-formatting.md'
      - 'Grouping' : 'grouping.md'
      - 'Grouping Headers' : 'grouping-headers.md'
      - 'Search' : 'search.md'
      - 'Events' : 'events.md'
      - 'Validation' : 'validation.md'
      - 'Upload Files' : 'upload-files.md'
      - 'Summary' : 'summary.md'
      - 'Autocomplete' : 'autocomplete.md'
    - Layout & UI:
      - 'Responsive Design' : 'responsive-design.md'
      - 'Localization' : 'localization.md'
      - 'Themes' : 'themes.md'
    - Databases:
      - 'Connecting with SQL Server' : 'connecting-with-sql-server.md'
      - 'Connecting with Postgres' : 'connecting-with-postgres.md'
      - 'Connecting with Oracle' : 'connecting-with-oracle.md'
      - 'Debug Mode' : 'debug-mode.md'
    - FAQs:
      - 'General' : 'faq-general.md'
      - 'Appearance' : 'faq-appearance.md'
      - 'Column Appearance' : 'faq-column-appearance.md'
      - 'Column Settings' : 'faq-column-settings.md'
      - 'Dialog Customization' : 'faq-dialog-customization.md'
      - 'Javascript API' : 'faq-javascript-api.md'
      - 'Databases' : 'faq-databases.md'
      - 'Master Detail' : 'faq-master-detail.md'
      - 'Export' : 'faq-export.md'
      - 'Misc' : 'faq-misc.md'
theme:
    logo: 'https://.............png'
    name: material
    favicon: 'css/favicon.gif'

# Customization
extra:
  feature:  
    tabs: true
  search:
  #   tokenizer: '[\s\-\.]+'
    language: 'en'
    # prebuild_index: true

site_dir: ../docs
docs_dir: md


extra_css:
    - extra/extra.css
extra_javascript:
    - extra/extra.js
```

### System information

* OS: Win10
* Browser: Chrome Version 70.0.3538.67 (Official Build) (64-bit)

**Comment by civalin** [comment] 2018-10-20 04:29
I get the same problem too. It maybe due to the lacking of prebuild index?

If put 10000 words within *whole* system. A significant delay will be showed when first time I click the search bar. In this word number level, using with default `en` search engine settings (with default tokenizer), in my browser and testing environment, will get about 2 seconds delay.

10000 words are really easy to reach. I using [wikipedia: poetry](https://en.wikipedia.org/wiki/Poetry) as test data, this document has about 12000 words.

**Comment by gridphp** [comment] 2018-10-20 16:27
Any comments from author?

**Comment by squidfunk** [comment] 2018-10-26 10:58
Note that #906 must also be taken care of during the prebuild of the index, which introduces problems.

**Comment by squidfunk** [comment] 2018-11-04 16:53
Closing this as not fixable (at least with a reasonable effort). If someone wants to go ahead on web worker support, feel free to PR. This should mitigate the freezing of the interface. If somebody comes up with a good plan which addresses the issues I stated above, I'm happy to discuss potential solutions.

**Closed by squidfunk** 2018-11-04 16:53 UTC
Labels: discussion

**Comment by wilhelmer** [comment] 2019-09-11 11:00
From the documentation:

> While MkDocs 1.0 supports prebuilding the search index, Material currently doesn't support this setting as the default search behavior of the original theme was heavily modified for the sake of a better UX. **Integration is possible, but a small subset of the features Material provides will not be portable to the prebuilt index mainly due to missing localization.**

So this issue **is** fixable after all? The only problem is missing localization and a "small subset of features"? Can we do anything to assist you?

**Comment by squidfunk** [comment] 2019-09-11 11:44
It's mainly related to how the data is indexed from JSON by the theme. Missing localization is actually a huge show stopper. I don#t really know whether it can be done, maybe someone can try and build a POC. If it's possible while retaining all (or most) functionality and degrades gracefully, we can integrate it into master. https://github.com/squidfunk/mkdocs-material/issues/904#issuecomment-431656804 provides further information.

**Comment by wilhelmer** [comment] 2019-09-11 12:29
What about offering the `prebuild_index` option for English projects only? Would be way better than nothing. The freeze is super annoying on our project, takes 3-4 seconds before the user can search anything (>300 pages).

**Comment by squidfunk** [comment] 2019-09-11 12:36
Another approach is to move search to a web worker. However, I haven't decided what's the best approach that benefits everybody. Maybe forking the search plugin and moving the changes made in JavaScript into it.

**Comment by wilhelmer** [comment] 2019-09-11 12:55
If the problem is already solved in MkDocs by offering `prebuild_index`, and the Material template doesn't support this option, I think the best approach is to make that option work instead of implementing a different solution.

Can you give an example of what the "small subset of the features Material provides will not be portable" includes? E.g., what would be missing if that subset wouldn't be ported?

**Comment by squidfunk** [comment] 2019-09-11 12:59
The whole search as it is would not work. The main problem is that there would be no intelligent grouping of results. Currently, results in sub-sections are merged into their containing page. The search results would just appear as in any other theme.

**Comment by coliff** [comment] 2019-09-11 13:09
My understanding on this issue (and I may well be wrong :-) ) The search file is prebuilt. You can see how it works by loading https://squidfunk.github.io/mkdocs-material/ - then opening the Network panel in Chrome Dev Tools, disabling cache and then clicking on the Search input after the page has finished loading. You'll see that it then downloads: https://squidfunk.github.io/mkdocs-material/search/search_index.json. That particular file is 39KB (gzipped) so is quite fast, but on larger sites it means you need to wait for that file to download - causing a delay.
I think the solution lies in that file should 'preload' somehow once the page has finished loading (so it doesn't delay the page rendering). I took a look at trying to resolve this a while ago by adding a preload script but it didn't work as expected (it preloaded the file as expected/desired but the fetch on clicking the search meant that it downloaded again)

I **love** the user interface of the MkDocs-Material search with the grouped search results, real-time underlining of the search term in the results and displaying the number of matching results - it's beautiful and elegant. I just wish that the `search_index.json` file could be preloaded somehow (but not sure how to fix).

**Comment by wilhelmer** [comment] 2019-09-11 13:11
Okay, so what if enabling `prebuild_index` would disable the UX improvements, i.e., fall back to the default MkDocs search? So if we can't have top UX **and** top performance, we can at least pick a preference.

**Comment by squidfunk** [comment] 2019-09-11 13:12
Two different searches? Honestly, nothing I would want to maintain.

**Comment by wilhelmer** [comment] 2019-09-11 13:27
I don't get the concept of `prebuild_index` option anyway. If I enable it, the file size of my `search_index.json` increases from 6 MB to 17 MB. So while it may be nice to have the JSON preloaded, if the download size triples, the whole thing doesn't make much sense to me.

So yeah, making the process asynchronous or at least tell the user what's going on, while keeping the search index file as small as possible, sounds better.

**Comment by wilhelmer** [comment] 2019-09-12 07:16
This is a top priority issue for us. If it's fixable, it needs to be fixed. If you don't have time to look further into this, which I understand, I will find someone who can do it.

**Comment by Kludex** [comment] 2020-08-19 17:24
By any chance, do you guys know if this is the same behavior [FastAPI](https://fastapi.tiangolo.com/) is having?

**Comment by squidfunk** [comment] 2020-08-19 17:36
Shouldn't be, search was moved to a web worker and shouldn't freeze anymore.

**Comment by Kludex** [comment] 2020-08-19 17:47
As you've replied so fast, I will ask something, I hope you can reply here. If it bothers you, I can create a question issue.

So, there are a lot of complaining about this:
![image](https://user-images.githubusercontent.com/7353520/90670865-22f78b00-e254-11ea-86ce-a77c021695ba.png)

This usually happens after some searches, meaning that it remains the way you see in the image above forever. The way I solve it right now is to open a new window. Any ideas on what it can be? If you're curious: https://github.com/tiangolo/fastapi/blob/master/docs/en/mkdocs.yml

**Comment by squidfunk** [comment] 2020-08-19 17:51
No, that shouldn't be. You may open an issue with instructions to reproduce the problem, so we can solve it!

**Comment by Kludex** [comment] 2020-08-19 17:53
Thank you! :)
