### ISSUE TITLE
Vertical scrollbars on MathJax formulas in material version 6.1.7

### ISSUE THREAD

**Issue by fjp** [squidfunk/mkdocs-material#2142] opened 2020-12-21 08:20 UTC
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

## Description

The following formula shows a vertical scrollbar using MathJax. I know there exist other related issues to this (for example: #2048 and #484) which solve this but the problem seems to be still there:

```
$$
v_i = \frac{\Delta s_i}{\Delta t_i}
$$
```

![image](https://user-images.githubusercontent.com/1286618/102754772-be694b80-436d-11eb-951f-a1834a745cdd.png)
![image](https://user-images.githubusercontent.com/1286618/102754902-f2dd0780-436d-11eb-8f3a-ad4ed690b66c.png)

You can find the documentation where this happens hostet here using github-pages: 
https://fjp.at/diffbot/theory/motion-and-odometry/#distance-velocity-and-time

I tested locally with the default mkdocs theme and there it works, no scrollbars appear.

I am using a [custom_dir](https://github.com/fjp/diffbot/tree/noetic-devel/docs/custom_theme) for the required javascript and added arithmatex in my [mkdocs.yml](https://github.com/fjp/diffbot/blob/noetic-devel/mkdocs.yml#L12)

### Expected behavior

No vertical scrollbars on mathjax formulas

### Package versions

* Python: `python --version`: 3.8.5
* MkDocs: `mkdocs --version`: 1.1.2 from /home/fjp/.local/lib/python3.8/site-packages/mkdocs (Python 3.8)
* Material: `pip show mkdocs-material | grep -E ^Version`: 6.1.7

### Project configuration

``` yaml
theme:
  name: material
  highlightjs: true
  custom_dir: docs/custom_theme

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
```

### System information

* OS: Ubuntu 20.04
* Browser: Tested with Chromium, Chrome, Firefox

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment] 2020-12-21 10:46
Thanks for reporting. I can reproduce this on iOS Safari, but not on macOS (which is the system I'm using). It's definitely a bug, but should be easy to fix.

**Comment by squidfunk** [comment] 2020-12-21 19:14
Could you try to apply the following extra CSS to see whether the error goes away?

``` css
.md-typeset div.arithmatex {
  overflow: initial;
  overflow-x: auto;
}
```

**Comment by fjp** [comment] 2020-12-21 22:31
Thank you @squidfunk for the snippet. Unfortunately this doesn't seem to help, the scrollbars appear unchanged. I have added your css inside a new `scroll.css` of the `docs/css/` folder. Then in the `main.html` I use: 

```
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ base_url }}/css/scroll.css">
{% endblock styles %}
```

I have also tried with `extra_css` option in my `mkdocs.yml`:

```
extra_css:
  - docs/css/scroll.css
```

After serving it locally with `mkdocs serve` the scrollbars are still here unfortunately and nothing seems changed. Did I forget to configure something?

However, I can also confirm that it works (even without applied css changes) on macOS. Only Ubuntu 20.04 shows the scrollbars. Don't know about Windows.

**Comment by squidfunk** [comment] 2020-12-21 23:19
The link might be incorrect - you don't need the `docs` prefix. Can you check and make sure that your extra CSS file is correctly loaded by the browser, i.e. It doesn't 404?

**Comment by fjp** [comment] 2020-12-22 11:31
Thank you @squidfunk for the hints. I tried without docs and checked that the css is in the source by inspecting with chrome. The line: `<link rel="stylesheet" href="../../css/scroll.css">` is in the page source but the scrollbars are still here.

**Comment by squidfunk** [comment] 2020-12-22 16:43
The selector in my last potential fix wasn't correct. I think I may have a fix. I tested with Firefox and IE on Windows, and while I couldn't reproduce the scrollbars, the formula was slightly cut off. Removing the `overflow` in afff64df fixed it.

You can either try and check the latest `master`, or add the following additional CSS:

``` css
.md-typeset div.arithmatex > * {
  overflow: initial;
}
```

**Comment by squidfunk** [comment] 2020-12-22 17:48
So @facelessuser was so nice to check whether the problem you described happens on the official docs on Ubuntu/Firefox and it doesn't. There's no vertical scrollbar shown. Thus, the problem might be related to your customizations, or we just didn't manage to find out the Markdown you used.

I'm closing this issue as not reproducible. In case the issue persists, please provide a minimal, reproducible test case, including Markdown and MkDocs configuration on a mint Material installation, i.e. without customizations.

**Comment by squidfunk** [comment] 2020-12-22 17:51
Ha! I managed to reproduce it, I should have used your example from the start. So it seems it doesn't happen with the examples used in the official docs, but the formula needs to have a certain height, so the overflow is triggered.

**Comment by fjp** [comment] 2020-12-22 18:21
Awesome, thanks @squidfunk. I tried [with your CSS](https://github.com/squidfunk/mkdocs-material/issues/2142#issuecomment-749647783) and it works perfect, no scrollbars anymore :+1: 

Will this fix be in the next release and do you know when it will be released on https://pypi.org/project/mkdocs-material/? So that I don't need the extra css.

**Comment by squidfunk** [comment] 2020-12-22 18:45
Yes, it will be part of 6.2.3. I issued three releases today, including the all-new navigation stuff from Insiders, so I suggest we wait for a little and let things cool down, and include some bugfixes for issues that might be the result of the latest changes.

**Comment by squidfunk** [comment] 2020-12-27 10:46
6.2.3 was just released.

**Closed by squidfunk** 2020-12-27 10:46 UTC
Labels: bug, fix available
