### ISSUE TITLE
PHP highlighting only works when code block begins with <?php

### ISSUE THREAD

**Issue by seanmadsen** [squidfunk/mkdocs-material#138] opened 2017-01-31 17:23 UTC
## Description

I'm able to achieve good code highlighting in PHP code, but only when the code begins with `<?php`. I would like a way to highlight PHP code without having to insert anything into the code block that will display within in the presented code.

### When using `<?php`
````
```
<?php
$a = array("foo" => 0, "bar" => 1);
foreach ($a as $key => $value) {
  // comment
  echo "{$key} => {$value}" . PHP_EOL;
}
```
````
![11](https://cloud.githubusercontent.com/assets/42411/22475586/98fcae36-e79c-11e6-8db3-dc873014ca80.png)

This highlighting is good, but I don't want to insert `<?php` into all of my php code blocks because (1) it clutters the final presentation, and (2) will confuse some users who think they need to actually write `<?php` in the example being documented, and (3) is just a tiny bit more work to type.

### When using ` ```php `

I would prefer to write my code blocks as follows: 

````
```php
$a = array("foo" => 0, "bar" => 1);
foreach ($a as $key => $value) {
  // comment
  echo "{$key} => {$value}" . PHP_EOL;
}
```
````
but using the ` ```php ` syntax hint does not seem to take affect. With this markdown, I see no code highlighting at all. 

![12](https://cloud.githubusercontent.com/assets/42411/22475889/bc63c872-e79d-11e6-81d2-97d38a265c23.png)

### Without any language hints

If I don't mention PHP, I get some highlighting, but it's done so poorly that it's actually worse than no highlighting at all. 

````
```
$a = array("foo" => 0, "bar" => 1);
foreach ($a as $key => $value) {
  // comment
  echo "{$key} => {$value}" . PHP_EOL;
}
```
````

![10](https://cloud.githubusercontent.com/assets/42411/22475962/fadb492c-e79d-11e6-954d-a4bf9ed02bdd.png)

### Other notes

* With the three examples above, I see different markup for each, when inspecting with a browser inspector. (e.g. all elements have `class="x"` in example that produces no highlighting)
* PHP code highlighting works for me in the `readthedocs` theme by using ` ```php `
* Language hinting seems to work well within Material for other languages when I do ` ```js ` or ` ```python `, but not PHP. 
* I've read #41 and #30 but this seems to be a separate issue

## Package versions

* Python: `python --version` 2.7.6
* MkDocs: `mkdocs --version` 0.16.1
* Material: `pip show mkdocs-material | grep -E ^Version` 1.0.3
* Pygments: `pip show pygments | grep -E ^Version` 2.2.0

## Project configuration

``` yaml
site_name: Foo
theme: material
markdown_extensions:
  - codehilite
pages:
- Home: index.md
```

I've also tried `- codehilite(css_class=code)` (as recommended in other issues I read) but that produced no highlighting at all.

## System information

* OS: Linux Mint
* Browser: Firefox & Chrome

**Comment by facelessuser** [comment] 2017-01-31 17:53
Material (by default) relies on Pygments to do the highlighting.  MkDocs' `readthedocs` theme I believe uses highlight.js.  Either theme can use either highlighter.  Personally when I used the `readthedocs`, I removed highlight.js and used Pygments instead.  I didn't like how highlight.js would try and auto-guess my languages (and would highlight certain boxes wrong) etc.  And I prefer not loading even more JS on pages if I can avoid it.

Pygments' lexer for PHP looks for, at a minimum, `<?` to start highlighting.  That's just how it is.  You could disable Pyments  by using `codehilite` extension without Pygments support via (`use_pygments=False`).  And then include highlight.js.  If you don't like the auto-guessing, you can write your own highlight.js loader (which I've done before), and look for code blocks with languages assigned to them.

It is also possible you could write a Python Markdown extension that post-processes code blocks for PHP and finds and removes `<?php`.  I don't think it's worth it, but you could.

Outside of highlight.js, there are even more JavaScript highlight options.

**Comment by facelessuser** [comment] 2017-01-31 18:01
Yet another option could be to fork Pygment's PHP lexer and remove the requirement for `<?`.  Then just use it with your docs.

    ```my-php-lexer
    Some code
    ````

**Comment by facelessuser** [comment] 2017-01-31 18:14
By the way.  When you don't specify and you were getting bad highlighting...that was Pygments guessing, I always turn off guessing so I don't usually have that occur.  It most likely was guessing some non-PHP language as PHP requires `<?` as mentioned earlier.

**Comment by facelessuser** [comment] 2017-01-31 18:59
It looks like Pygments does have an option to control this feature called [`startinline`](http://pygments.org/docs/lexers/#lexers-for-php-and-related-languages).  Current PythonMarkdown extensions don't support passing in such options, but it *could* be done.  But this would be via an extension, not Material directly.

**Comment by facelessuser** [comment] 2017-01-31 19:06
This may be something I could implement in `pymdown-extensions`.  Maybe allow a user to specify a new language aliases like `php-inline` and give it the translation `php` and the options `startinline=True`.  Essentially you could extend the current language list with a pre-configured language variants.

Maybe I'll implement this.  I might actually get some use out of something like this.

**Comment by squidfunk** [comment] 2017-01-31 22:28
Really cool you think about integrating this into PyMdown, but wouldn't it be better to PR this feature in Python Markdown?

**Comment by facelessuser** [comment] 2017-01-31 23:21
> Really cool you think about integrating this into PyMdown, but wouldn't it be better to PR this feature in Python Markdown?

I'll be honest.  Python Markdown is in maintenance mode until 3.0.   That means bug fixes only. Also, the author is quite busy, and not sure when he'll get around to finishing 3.0.  So if I code up a solution, it will most likely go to code purgatory and await 3.0.  See Python Markdown's pull requests.  I've gotten a number of bug fixes pushed through, but new features aren't going to make it.

SuperFences came about because there is a promise of better support for fences in 3.0 due to a redesign, but we don't know when the redesign will drop.  SuperFences is kind of a stop gap solution -- one which required quite a bit of fancy hackery.  I imagine when 3.0 hits with better fences, SuperFences might be reduced to something that does UML only.  But maybe not.

There is an issue open currently about extending the Pygments options on the Python Markdown repo, but I am not sure how that is going to look.  You can read the owner's response, but there is no clear direction yet, and basically it is stated that if people want the feature now, they should fork or develop their own until 3.0 drops.

I get the impression that Python Markdown would specify the options alongside the language name, but I don't know if I care for that to be honest (and maybe it won't be like that at all).  I don't want to specify `startinline` every time.  The current `hl_lines` option is fine like this as it is a per instance setting.  But beyond that, I think it gets cumbersome.  I especially don't think this will translate to InlineHilite well (which I support), but I would want support for Pygment options there too.

So maybe SuperFences will stick around to replace fences if I don't like how the options are handled in new fences, albeit it would be redesigned to take advantage of the internal Markdown API redesign.

End of ramblings.

---

If I want a solution in less than 6 months to a year (or longer), I can do it myself and design a methodology that works well for fences **and** InlineHilite (at least in the way **I** want to work).  I think my current idea would take minimal effort to pull off.  If Python Markdown ends up heading down a path I like, I can simply deprecate support for it and people can adopt the original -- that was originally the plan for SuperFences anyways.  But I imagine it will be quite some time before 3.0 drops.

I think creating pseudo language profiles via the extension options resonates well with me.  It's flexible for the user.  They define what they want, and not what they don't.  I don't have to update the syntax if a new option requiring something more complex arrives as the extension parameters can take almost anything as is, and it would just get passed onto Pygments -- no processing needed from me.

**Comment by seanmadsen** [comment] 2017-01-31 23:54
Thanks to both of you for the detailed thoughts!

@facelessuser [said](https://github.com/squidfunk/mkdocs-material/issues/138#issuecomment-276457337):
> It looks like Pygments does have an option to control this feature called `startinline`. Current PythonMarkdown extensions don't support passing in such options, but it *could* be done. But this would be via an extension, not Material directly.

I'm interested in pursuing this solution, at least to some extent (though I may give up if it's too much work or too hard). Can you say a little more about how I would set `startinline=true` for the PHP lexer in pygments? 

As a plan B I'll use `highlight.js` (or similar) within a theme extension of Material. 

Looks like pygments produces better results though so I'd like to stick with it if possible. But the more I think about it, the more opposed I am to writing `<?php` at the beginning of each code block. I'm setting up a system where dozens of people are editing content that has a lot of PHP code blocks in hundreds of markdown files, and I want the editing process be as straightforward as possible, thus I like how ` ```php ` is consistent with ` ```js ` and less prone to content errors with new content editors.

**Comment by facelessuser** [comment] 2017-02-01 00:23
@seanmadsen 
> I'm interested in pursuing this solution, at least to some extent (though I may give up if it's too much work or too hard). Can you say a little more about how I would set startinline=true for the PHP lexer in pygments?

This is what I imagine it will work like.  In this example we are going to add two language profiles.  

1. We include codehilite as usual (I disable guessing).
2. We include inlinehilite if you want inline highlighted code, and superfences for highlighted nested code.
3. Under either inlinehilite or superfences, we define our new languages (I imagine I will have it so that if you define under one, the other can see them as well).  In the example below we define an `php-inline` profile and a Python 3 console (`pycon3`) profile.

In mkdocs.yml

```yaml
markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
      extend_pygment_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
```

And in Markdown, now we can do this:

````
Inline PHP

```php-inline
$a = array("foo" => 0, "bar" => 1);
foreach ($a as $key => $value) {
  // comment
  echo "{$key} => {$value}" . PHP_EOL;
}
```

Normal PHP

```php
<?php
$a = array("foo" => 0, "bar" => 1);
foreach ($a as $key => $value) {
  // comment
  echo "{$key} => {$value}" . PHP_EOL;
}
```

Python 3 console

```pycon3
>>> a = 'foo'
>>> print a
foo
>>> 1 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```
````

Should be easy.

**Comment by seanmadsen** [comment] 2017-02-01 00:41
Thanks @facelessuser I really appreciate your help on this. 

I've tried the `mkdocs.yml` configuration you've recommended, but when I run `mkdocs serve` I get the following error message: 

```txt
KeyError: u'extend_pygment_lang'
```

Any advice? 

I'll also say that if I can set configuration to override the behavior of ` ```php ` to use `startinline: true` that would be preferable instead of adding a new language `php-inline`.

**Comment by facelessuser** [comment] 2017-02-01 00:44
I haven't implemented it yet :smile:.

**Comment by seanmadsen** [comment] 2017-02-01 00:51
ohhhh!  :man_facepalming: ha! :laughing: ok thanks. I look forward to this someday.

**Comment by facelessuser** [comment] 2017-02-01 00:53
I'll probably through up a branch tonight.  Like I mentioned before, it requires minimal code.

**Comment by facelessuser** [comment] 2017-02-01 03:12
Here's the branch: https://github.com/facelessuser/pymdown-extensions/tree/pygments-options.

**Comment by facelessuser** [comment] 2017-02-01 03:12
The actual setting is `extend_pygments_lang`.

**Comment by seanmadsen** [comment] 2017-02-01 04:10
@facelessuser this is very nice! Thank you :clap: 

For anyone else landing here and looking for a **successful work-around**, here's what I did: 

```bash
sudo pip uninstall pymdown-extensions
cd ~
git clone https://github.com/facelessuser/pymdown-extensions
cd pymdown-extensions
git checkout -b pygments-options origin/pygments-options
python setup.py build
sudo python setup.py install
```
`mkdocs.yml`:

```yaml
markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
```

note that I set `name: php` which (to my satisfaction) overrode the default ` ```php ` behavior. 

:+1:

**Comment by facelessuser** [comment] 2017-02-01 06:42
Glad it worked for you.  I imagine there will be some cleanup before it gets released (whenever I decide that should happen), but that should all be internal.

**Comment by squidfunk** [comment] 2017-02-01 08:31
@facelessuser Awesome work! Thanks also for the explanation on Python Markdown. I understand you started PyMdown as a response to that. I will close the issue now, since the problem is "solved", at least there exist some workarounds and it has nothing to do with Material in particular.

If you want, we can add some admonition/tip under the codehilite documentation, linking to a section in your docs describing how to configure/override this. Feel free to PR.

**Closed** 2017-02-01 08:31 UTC

**Comment by facelessuser** [comment] 2017-02-01 14:06
> I understand you started PyMdown as a response to that. 

Yeah, that was the start, then it kind of turned into making document writing more enjoyable for myself.

When it gets released, I might add a note to the docs here. I'll definitely have a note over in PyMdown.  It at least needs to be documented somewhere.  I guess if it becomes a question you get asked frequently, then we'll definitely add it to the docs here. It's one of those things where I'm not sure how much should be explained here vs there.

**Comment by facelessuser** [comment] 2017-02-05 19:27
FYI, the final form of this might actually change even though I wasn't planning it.  I am looking to generally decouple pymdown highlighting from CodeHilite as I am potentially going to expose more Pygments settings and we will deviate even more from CodeHilite.  But by default, SuperFences and InlineHilite will still source settings from CodeHilite and provide only features that CodeHilite provides.

I am thinking about creating an extension that configures highlighting globally for pymdown extensions instead of having some settings shared in a confusing manner.  So if sourcing settings from CodeHilite was disabled for the SuperFences and/or InlineHilite, those extensions would instead utilize this new extension allowing them to take advantage of more advanced features.  And they could all be tweaked in one place instead of having two different extensions that can configure them separately, but work globally.

Anyways, nothing is certain, but I want people to be aware that this might possibly be more different than what is outlined here.

So in general, legacy behavior would mostly be preserved and affect very few people.  This would most likely be part of a `2.0` release as this would be a significant change.  I will leave the current branch I mentioned here untouched and probably create a new branch with the final feature.

I would advise just following https://github.com/facelessuser/pymdown-extensions/issues/54 for further developments.  I am open to suggestions as I try and iron all this out.

**Comment by squidfunk** [comment] 2017-02-05 20:16
Sounds great!

**Comment by facelessuser** [comment] 2017-02-12 02:26
Final implementation is here in pull request: https://github.com/facelessuser/pymdown-extensions/pull/56.

CodeHilite support should continue to work as usual, but to get the special feature of extending pygments language lists with custom languages with different options, you will have to setup `pymdownx.highlight` extension and set `use_codehilite_settings` to `False` in InlineHilite and SuperFences.  For consistency, you may need to set `css_class` to `codehilite` in the InlineHilite and SuperFences as well.

Anyways, on demand line options will also be available as well much like `hl_lines`.  Now you can use `linenums="1"` to enable line numbers on a fence block and specify starting line.  There are some other options I exposed as well, but I don't find them quite as useful as the starting line.  In the future I may expose more, but this is all I care to expose in the immediate future.  This is scheduled for a 2.0 release.

**Comment by facelessuser** [comment] 2017-02-12 23:32
FYI 2.0 is released.  Documentation on the Highlight extension that contains this feature is here: http://facelessuser.github.io/pymdown-extensions/extensions/highlight/.  Please file issues or ask questions over at https://github.com/facelessuser/pymdown-extensions/issues if you encounter problems.

**Comment by squidfunk** [comment] 2017-02-13 09:10
Looks great. I need to check it out when I find a moment. However, what CSS/JS changes did you make to Material? Your PyMdown installation seems a little broken (arrows and overflowing sidebar):

![bildschirmfoto 2017-02-13 um 10 09 12](https://cloud.githubusercontent.com/assets/932156/22877205/97de5382-f1d4-11e6-8b4a-40177a3103aa.png)

**Comment by facelessuser** [comment] 2017-02-13 14:03
Good question.  Man, I didn't notice that.  I'll take a look.

**Comment by facelessuser** [comment] 2017-02-13 14:09
I override your footer to add a comment about EmojiOne in the footer.  I was apparently on an older footer.  The arrows are now fixed.

What do you mean by overflowing sidebar?

**Comment by squidfunk** [comment] 2017-02-13 14:12
The sidebar runs in the footer, if you watch closely (The "License" is partly written on the footer). This shouldn't happen, and it doesn't for me on 1.0.3 - there should be spacing at the bottom, like in the following image:

![bildschirmfoto 2017-02-13 um 15 11 17](https://cloud.githubusercontent.com/assets/932156/22886574/cc12666e-f1fe-11e6-963d-68e4fce981ce.png)

I was just wondering why this happens, as it could be something I should fix.

**Comment by facelessuser** [comment] 2017-02-13 14:21
Hmm. That is weird.  After removing **all** custom CSS **and** removing my footer override, I still see the issue.  I think it's a Material thing.

**Comment by squidfunk** [comment] 2017-02-13 14:24
Just tried fiddeling around with your docs - it's related to `md-typeset__table`. When I remove it, everything is fine. Will file a new issue.

**Comment by facelessuser** [comment] 2017-02-13 14:29
Good catch.  Just figured that was how it was supposed to work with a lot of entries in the sidebar.

**Comment by squidfunk** [comment] 2017-02-13 15:30
Filed in https://github.com/squidfunk/mkdocs-material/issues/153 - will look into this as soon as possible.

**Comment by BernhardK91** [comment] 2024-08-16 19:13
If anyone is stumbling over this issue via Google (as I did), I was able to force PHP highlighting even with the `php` declaration:

Example:

````markdown
```php title="tests/Feature/MyFeatureTest.php"
use Tests\TestCase;

class MyFeatureTest extends TestCase
{
    //...
}
```
````

In the config file `mkdocs.yml`:

```markdown title="index.js"
markdown_extensions:
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
```

That way, PHP code blocks render as PHP even when not starting with `<?php`.
