### ISSUE TITLE
Hide Latest Release repo info (insiders)

### ISSUE THREAD

**Issue by HendrikK** [squidfunk/mkdocs-material#2481] opened 2021-03-22 12:49 UTC
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Allow insiders **not** to display the latest release tag in the repo info.

### Use Cases

UI Design choice

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/4612319/111992082-eb640080-8b0c-11eb-8377-31ea57fb94e0.png)

**Comment by squidfunk** [comment] 2021-03-22 12:59
Thanks for suggesting. Could you elaborate on the why behind that feature request?

**Comment by squidfunk** [comment] 2021-03-22 13:07
On a side note, you can just use some extra CSS to hide the release tag:

``` css
.md-source__fact md-source__fact--version {
  display: none;
}
.md-source__fact md-source__fact--stars::before {
  margin-left: 0;
}
```

**Comment by squidfunk** [comment] 2021-03-23 06:53
Closing - the CSS solution I posted is the way to go, as it’s super simple to add and omits the need for further configuration.

**Closed by squidfunk** 2021-03-23 06:53 UTC
Labels: input needed

**Comment by squidfunk** [comment] 2022-04-06 16:21
I'm not sure where the problem is. What do you mean by 'can't activate'?

Follow this guide and use the exact same directory structure:
https://squidfunk.github.io/mkdocs-material/customization/#additional-css

**Comment by jlipps** [comment] 2022-04-06 16:28
That is what I thought I have been doing. Here is my docs structure from the root of the repo:

```
|- packages/appium/docs
|  |- mkdocs-en.yml
|  |- en
|  |  |- index.md
```

so where should I put `stylesheets/extra.css`? I have tried to put it in: `packages/appium/docs`, `packages/appium/docs/en`, and `packages/appium/docs/en/docs`. And in none of these places is the extra CSS incorporated into the site.

My `mkdocs-en.yml` sets `docs_dir` to `en`, so when `mkdocs serve` is run, it treats `packages/appium/docs/en` as the root for building the English language docs.

**Comment by squidfunk** [comment] 2022-04-06 16:59
Hmm, I don't have enough information about your setup, but my best guess would be: `en/stylesheets/extra.css`. Note that the customization guide and the whole documentation assumes that you did not change the `docs_dir`, as that would be a deliberate decision to make. Thus, `docs` refers to the value of the `docs_dir` for simplicity.

If your `docs_dir` is `en`, then this is the location where the customization must go.

**Comment by jlipps** [comment] 2022-04-06 17:06
Got it. Yeah, that's what I originally assumed. I put it in `en/stylesheets/extra.css`, and added this to `mkdocs-en.yml`:

```
extra:
  extra_css:
    - stylesheets/extra.css
```

And the extra CSS was not included. Hence my question above.

I ran `mkdocs serve` with the `-v` flag, and saw that `stylesheets/extra.css` was included. I could access it in the browser at `http://localhost:8000/docs/en/stylesheets/extra.css`. But I could not see this file included as an extra `<link` in the html head, or the CSS incorporated into the minified bundle. I also tried updating the extra block to:

```
extra:
  extra_css:
    - /docs/en/stylesheets/extra.css
```

In case we wanted a server-absolute path for the browser to read from. No luck in any case.

**Comment by squidfunk** [comment] 2022-04-06 17:09
As I said, I don't know your setup. My advice would be to try it on a mint installation and then work your way towards your documentation. I've just tested it, and extra stylesheets still work nicely. Thus, the error lies somewhere within your setup.

If you have any further questions, please create a new discussion, since the problems you're experiencing have nothing to do with the original topic in the first place. Better not spam this issue 😊

**Comment by jlipps** [comment] 2022-04-06 17:13
OK, looking at the mkdocs docs, I figured it out. This was incorrect:

```
extra:
  extra_css:
    - stylesheets/extra.css
```

it should have been:

```
extra_css:
  - stylesheets/extra.css
```

Apologies, I thought I copied/pasted this from your docs but I guess I made up where it should go. Anyway, thanks for your help!
