### ISSUE TITLE
Pages with sections that display completely will shift their URL to the last section when loaded

### ISSUE THREAD

**Issue by jj-jitterbit** [squidfunk/mkdocs-material#4029] opened 2022-06-15 22:11 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Pages with sections that display completely will, when loaded, scroll to the bottom of the table of contents, shift their URL, and the last section will be highlighted in the table of contents.

Any MkDocs Material Theme page can have this. it is due to automatic highlighting of the current entry in the table of contents of the right sidebar.

I first noticed this on the short landing page of our site, https://developer.jitterbit.com/ .

### Expected behaviour

I would expect it to stay at the top, just like any page that is not completely displayed.

### Actual behaviour

Pages with sections that are completely displayed will, when loaded, scroll to the bottom of the table of contents and the last section will be highlighted in the table of contents.

This is a page that has multiple heads on it and hence a table of contents in the right sidebar.

Completely displayed means the content fits in the viewport and there is no vertical scroll bar.

When the page URL is loaded, the scrolling and highlighting of the table of contents will be at the bottom and the last item in the table contents will be highlighted.

### Steps to reproduce

This can be reproduced with the Material for MkDocs website.

1. Go to the [Setting up the header](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/) page.
2. It will load normally, and unless you have a very tall monitor, it will load and look something like this: 
<img width="1547" alt="Screen Shot 2022-06-15 at 2 56 35 PM" src="https://user-images.githubusercontent.com/34282269/173938489-214beab9-e5c8-4e11-bff4-187838cfd433.png">
3. Now, change your view by "Zoom out" (Command-hyphen on Safari on macOS) so that the viewport changes and you can see all of the page content. The URL will change and add the last anchor of the table of contents: 

```
https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#mark-as-read
```
and the page will look like this:
<img width="1547" alt="Screen Shot 2022-06-15 at 2 56 56 PM" src="https://user-images.githubusercontent.com/34282269/173939330-79feee58-5c82-47fd-9242-83479e40b292.png">

5. Notice that the last entry in the table of contents ("Mark as read") is now in blue.

Though this is somewhat contrived as an example, it's the easiest way of showing that any page whose content fits in the viewport will have this issue and its URL modified by the automatic scrolling.

### Package versions

Whatever the reference site is using.

### Configuration

```yaml
ibid.
```

### System information

Any os or browser exhibits this.

**Comment by squidfunk** [comment] 2022-06-16 07:23
Thanks for reporting! This is expected behavior, as it fixes the problem when the penultimate section is very long and the last section is very short, so the viewport has not scrolled past the last section to activate it in the table of contents. In that case, the active section would be the penultimate section. Now, with navigation.tracking enabled, when a user scrolls down completely, the penultimate section would be active, so when she copies the link from the URL, it wouldn't be a link to the last, but to the penultimate section.

This caused confusion in the past. For this reason, when scrolling down, we're always activating the last section which makes sense. I agree that it has the side effect of the table of contents highlighting the last section, but honestly, the majority of pages in regular documentation are longer than the viewport (as can be seen on our documentation), which means that this behavior is very rarely triggered. Moreover, it's unlikely that short pages contain many entries in the table of contents.

Closing as working as intended.

**Closed** 2022-06-16 07:24 UTC

**Comment by jj-jitterbit** [comment] 2022-06-16 17:41
@squidfunk Is it possible to special case this?

I agree that few pages have this issue. However, we've developed a style of documentation where we have overview and navigation pages that introduce major topics that are short and have a few sections on them. Generally two or three sections, all displayed at the same time. And so this behavior gets triggered.

I can understand why you made the choice that you did (solving the problem of the penultimate rather than the last section being selected), but this is a case where the content height is less than the viewport size. Is it possible to turn that behavior off for that case, and not activate the last section?

If I wanted to investigate this as a possibility or for a PR, can you tell where I should start looking?

**Comment by squidfunk** [comment] 2022-06-16 17:58
I'm happy to merge a PR that ticks the requirements I have outlined in my last comment. However, I can't guarantee that I'll merge it, mainly because of how rendering performance might be affected. In general, handling special cases might mean more for the browser to do – see the [recent fix for tooltips](https://github.com/squidfunk/mkdocs-material/issues/4026#issuecomment-1157495822) for an example.

Thus, yes, it's possible, but in my opinion, the trouble and increase in maintenance are not worth it. The logic is implemented as part of the [table of contents component](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/javascripts/components/toc/index.ts), which tracks scroll progress and decides what to activate:

https://github.com/squidfunk/mkdocs-material/blob/48380132a6c5192bb43930688c8dd2d02fa8922c/src/assets/javascripts/components/toc/index.ts#L191-L211
