### ISSUE TITLE
Footnotes glitches

### ISSUE THREAD

**Issue by amittel** [squidfunk/mkdocs-material#273] opened 2017-04-11 10:31 UTC
## Description
Just found some glitches when using footnotes as seen in the pictures.
* Number a little bit too tall for header
* Number of footnote is seen in the menu
* If using a list in the footnote you get an extra line

![footnotes](https://cloud.githubusercontent.com/assets/822396/24904885/4427bb88-1eb2-11e7-8fa4-099aa55d7e97.png)

### Package versions

* Python: `2.7.10`
* MkDocs: ` 0.16.3`
* Material: `1.5.2`

### System information

* OS: Win10 x64
* Browser: Chrome Version 57.0.2987.133 (64-bit)

**Comment by squidfunk** [comment] 2017-04-13 12:02
1. I will investigate in the size of the footnote in the header, but it's the same relative size as in normal text - 80%.
2. Not fixable by Material - this problem originates in the Python Markdown extension which is upstream to MkDocs which in turn is upstream to Material.
3. Also not fixable, because those list items are block elements.

**Comment by facelessuser** [comment] 2017-04-13 12:58
Number 3 is by design in Python Markdown.

**Comment by squidfunk** [comment] 2017-04-13 13:00
@facelessuser Yeah, it's actually by design in HTML/CSS. A list element is (by default and for a reason) of display type `block` and the link of type `inline`.

**Comment by facelessuser** [comment] 2017-04-13 15:10
I would further argue that for issue number 2 that it isn't actually a problem, but by design. I suspect if you brought this up as an issue on the Python Markdown repo that it would be considered to work as expected.  Header text for table of contents takes the HTML text under the header.  It doesn't worry what sub element it is under.  And it definitely isn't looking at classes assigned to each element to try and determine if it is something it should avoid.  Any element, whether it's a sup element or not, is treated the same and all text from under the header are taken and have the style stripped for the title.

I say all of this mainly because sometimes a sup is not a footnote.  That means you then have to scan for specific classes.  That opens the door even further to other things people might want to ignore complicating the footnotes extension further.

I would argue that using a footnote in the header is probably not the most appropriate, but this is an opinionated answer.  I would generally put the footnote under that section on the first actual reference to `pinout` in the content, not the header.  Again this is just my opinion.

With all of that said, you could fork the footnotes extension and roll you own that can ignore specific elements or elements with certain classes applied to them.  That is probably the answer you'd get on the Python Markdown repo.

**Comment by squidfunk** [comment] 2017-04-22 12:50
So the size of the footnote actually looks good to me - it's 80% of the font size of the outer element. If you want to make it smaller or even fixed size, you can do so with custom CSS. However, the line next to the footnote was not correctly sized, I fixed that in a recent commit and will release it as 1.6.0.

**Closed by squidfunk** 2017-04-22 12:50 UTC
