### ISSUE TITLE
Meta tags incorrectly removed when using navigation.instant in combination with system/dark/light palette

### ISSUE THREAD

**Issue by ThomasTNO** [squidfunk/mkdocs-material#6846] opened 2024-02-27 14:02 UTC
### Bug description

On initial load the following meta tags are automatically added to `<head>`
```html
<meta name="theme-color" content="some_value">
<meta name="color-scheme" content="some_other_value">
```

When `navigation.instant` is set in `mkdocs.yml`, unexpectedly these tags are removed when navigating the page and clicking on internal links. The removal of the tags result in the scrollbar colours switching back to browser default (e.g. light) instead of the expected (e.g. dark).

After some triaging it seems that they are removed in the `inject()`-function in https://github.com/squidfunk/mkdocs-material/blob/7b83b57d1c041f586cc0a3231c5103a1f6466160/src/templates/assets/javascripts/integrations/instant/index.ts#L177

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[9.5.11-meta-tag-removal.zip](https://github.com/squidfunk/mkdocs-material/files/14420681/9.5.11-meta-tag-removal.zip)

### Steps to reproduce

1. Load website
2. Click a navigation link
3. Toggle palette mode
4. Observe that scrollbar no longer toggles based on palette
5. Observe that meta tags are missing 

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2024-02-28 01:56
Thanks for reporting! Definitely a regression introduced in [9.5.5](https://github.com/squidfunk/mkdocs-material/releases/tag/9.5.5), where we refactored instant navigation. Also thanks for taking the time to create a PR – I'll look into it!

**Comment by squidfunk** [comment] 2024-02-29 03:14
Thanks again for reporting and taking the time to raise a PR. I've investigated, and came to the conclusion that for now, I've added a small bandaid in d366a45fd to fix the problem. The solution you proposed in #6847 would unmount and mount the palette component on every navigation, which in general is unnecessary, as it persists across navigation, and would impact performance. I've added a TODO to revisit this topic next time we work on instant navigation ☺️

**Comment by squidfunk** [comment] 2024-02-29 03:23
Released as part of [9.5.12](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.12).

**Closed by squidfunk** 2024-02-29 03:23 UTC
Labels: bug, resolved

**Comment by ThomasTNO** [comment] 2024-02-29 19:58
Makes sense, both options are suboptimal and I do get your performance > maintainability argument in this case. Great that you listed the TODO for future reference.

Thanks for the swift action.

**Comment by kamilkrzyskow** [comment] 2024-02-29 22:48
Based on testing in: 
- https://github.com/squidfunk/mkdocs-material/discussions/6788#discussioncomment-8513647

This might've been a regression from [9.4.2](https://github.com/squidfunk/mkdocs-material/releases/tag/9.4.2) and not 9.5.5
Don't know if it matters, as a regression is still a regression, but perhaps it's a valid thing to point out :v:

**Comment by squidfunk** [comment] 2024-03-01 00:27
@kamilkrzyskow you are right – I attributed it to 9.5.5 because I did a big refactoring there, but we introduced the meta tags swapping logic in 9.4.2. I'm not sure why I missed that. Thanks!
