### ISSUE TITLE
toc.integrate causes undesired indentation in left nav

### ISSUE THREAD

**Issue by castedo** [squidfunk/mkdocs-material#6779] opened 2024-02-12 19:34 UTC
### Context

Material for MkDocs is awesome! I love it!

Here is a fix to this bug:
https://github.com/castedo/mkdocs-material-bug1/blob/main/docs/style/extra.css

Probably not the right fix, but it is what I current hack into my websites.

### Bug description

When I build with mkdocs-material 9.4.8 and 9.4.14 and 9.5.9 and use `theme: features: toc.integrate` I see an unexpected indentation in the left nav.

With the attached repo case, I see the following: 
![dislike_nav](https://github.com/squidfunk/mkdocs-material/assets/1416766/95da5c25-4968-4192-bf32-77604ddedac0)

But what I expected and wanted is:
![nav_expected](https://github.com/squidfunk/mkdocs-material/assets/1416766/fedd9e10-51c4-4e5d-a44d-5aabaa002eef)
which is consistent with what I see in the docs:
![setup docs](https://squidfunk.github.io/mkdocs-material/assets/screenshots/toc-integrate.png)

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration

### Reproduction

[repro.zip](https://github.com/squidfunk/mkdocs-material/files/14249495/repro.zip)

You can also clone https://github.com/castedo/mkdocs-material-bug1 which has the same contents as the zip.

### Steps to reproduce

`mkdocs build` or `mkdocs serve` on the repro example above.

You can uncomment the `extra_css: - styles/extra.css` lines to fix the problem.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2024-02-19 06:06
Thanks for reporting. It appears that this was caused by remnants of the latest navigation refactoring. 7bbc9f9 fixes the reported issue, and another problem I discovered where the integrated table of contents of top-level pages when navigation tabs are activated is moved to the left.

**Comment by squidfunk** [comment] 2024-02-19 06:20
Released as part of [9.5.10](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.10).

**Closed by squidfunk** 2024-02-19 06:20 UTC
Labels: bug, resolved
