### ISSUE TITLE
highlight.scss not loading in some browsers (was: Change in syntax highlighting >v7.3.6)

### ISSUE THREAD

**Issue by 2e0byo** [squidfunk/mkdocs-material#3402] opened 2022-01-01 13:38 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Syntax highlighting appears not to work with versions > 7.3.6 using what I think (doubtless incorrectly) is the correct bare minimum mkdocs.yml.

### Expected behaviour

Code should be syntax highlighted (with pygments) in the output.

### Actual behaviour

With versions <=v7.3.6 highlighting works as expected.  With versions >v7.3.6 it doesn't, and I can't get it running. 

### Steps to reproduce

- create a new empty dir
- create the minimal mkdocs.yml below
- put
  ```js
  a = "78"
  ```
  in `docs/index.md`
- put
  ```toml
  [tool.poetry]
  name = "hl"
  version = "0.1.0"
  description = ""
  authors = ["me"]

  [tool.poetry.dependencies]
  python = "^3.10"
  mkdocs = "^1.2.3"
  mkdocs-material = "v7.3.6"
  ```
  in `pyproject.toml`
- run `poetry install` followed by `mkdocs serve` -> correctly highlighted 
- run `poetry install mkdocs-material=latest` -> no highlighting

### Package versions

- Python: `python --version`: Python 3.10.1
- MkDocs: `mkdocs --version`:  1.2.3
- Material: `pip show mkdocs-material | grep -E ^Version`: 7.3.6 / > 8

### Configuration

```yaml
site_name: Highlight test

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
```

### System information

- Operating system: Arch Linux
- Browser: qutebrowser

**Comment by 2e0byo** [comment] 2022-01-01 13:55
Apologies: this is a browser issue (something has changed in the css).  I can confirm that highlighing works correctly in Chrome.  I'll bisect and figure out what's going on and then either close this or replace it with a new issue.

**Comment by 2e0byo** [comment] 2022-01-01 14:17
Having bisected, this is introduced by fa9f906c2bd91a76e4d8803dbb744145be2adb77.  Specifically, in qutebrowser the highlighted elements are not inheriting stylye from `pymarkdownx/_highlight.scss` even though the stylesheet is correctly loaded as a resource.

Non exhaustive list of correct and incorrect browsers:

## Working
- Chrome
- Firefox

## Not Working
- Safari (via browserstack)
- Qutebrowser

**Comment by squidfunk** [comment] 2022-01-01 14:19
Thanks for reporting. I can't reproduce it on Safari (macOS). Highlighting works as expected:

<img width="722" alt="Bildschirmfoto 2022-01-01 um 15 18 35" src="https://user-images.githubusercontent.com/932156/147852617-1ea4377d-3dbb-444a-8df6-3d18f366c745.png">

**Comment by 2e0byo** [comment] 2022-01-01 14:21
What's that from?  I guessed the docs but failed to find (will keep looking).

If this is a qutebrowser bug I'll file it elsewhere.  Safari made me think it might not be---but I don't have a real mac to test on.

**Comment by squidfunk** [comment] 2022-01-01 14:23
https://squidfunk.github.io/mkdocs-material/creating-your-site/#minimal-configuration

**Comment by 2e0byo** [comment] 2022-01-01 14:42
I can confirm that that link shows no highlighting in qutebrowser (=unimportant) and in at least one old safari---iOS 12.5.5 = Safari 12 (?).  I can't seem to find a free browser testing site which allows testing against multiple safaris, so I have no idea at what point Safari started behaving.

I don't know if this is issue is worth looking into, but since I do need to target older browsers I'll just pin the version at 7.3.6 for the time being.  I'm not sure why the style is not properly inhereting from pymdownx's highlight style.

Many thanks for an excellent tool!

**Comment by squidfunk** [comment] 2022-01-01 15:06
I understand the need to support older browsers and if you come up with a fix, I'm happy to merge it. Nonetheless, I consider this out of scope for now. Material for MkDocs currently aims to support all browsers [not older than 2 years](https://github.com/squidfunk/mkdocs-material/blob/master/.browserslistrc) with relevant market share. I may revisit this topic at some point in the future. However, syntax highlighting not being applied is something I (personally) can live with, as long as the page itself works.

**Closed by squidfunk** 2022-01-01 15:06 UTC
Labels: input needed

**Comment by squidfunk** [comment] 2022-01-01 15:07
Addendum: you can fork the theme and change the `.browserlistrc` to `last 4 years`.
