### ISSUE TITLE
The scroll bar disappeared on the sidebar and title bar

### ISSUE THREAD

**Issue by dyphn1** [squidfunk/mkdocs-material#3280] opened 2021-12-01 05:18 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After upgrade the latest version (8.0.2) the webview seems wrong. the user cannot scroll the title bar & side bar

### Expected behaviour

In the old version (6.0.0) my webview can have drop down list.  
![圖片](https://user-images.githubusercontent.com/16703356/144175356-5e3929c6-21b4-44ff-b917-d2d0d9319cc5.png)

and scrollbar in the side bar  
![圖片](https://user-images.githubusercontent.com/16703356/144175431-26ace23f-2528-41cd-afcb-697e97574aa8.png)

show the single page in the HOME page.  
![圖片](https://user-images.githubusercontent.com/16703356/144175643-5bfa0133-43f6-47e7-843c-67c169bfd567.png)

### Actual behaviour

but in the new version (8.0.2) all of these has disappeared.
and the HOME page will list the single page anymore.
![圖片](https://user-images.githubusercontent.com/16703356/144175885-cecfe287-cda9-4aae-b7f9-f183bdb90d17.png)  
![圖片](https://user-images.githubusercontent.com/16703356/144175905-afd5e572-05be-4cab-8703-b41094bed925.png)  
![圖片](https://user-images.githubusercontent.com/16703356/144175685-4c25ad75-6930-4e00-8b42-e760e174ffa7.png)  

### Steps to reproduce

1. install the mkdocs-material (6.0.0) and mkdocs build
2. zip the site folder 
3. install the mkdocs-material (8.0.2) and mkdocs build
4. compare the site folder with old version

### Package versions

| | Version |
| :-- | :-- |
| python | 3.9.5 |
| mkdocs | 1.2.3 |
| mkdocs-localsearch | 0.9.1 |
| mkdocs-material | 8.0.2 |
| mkdocs-material-extensions | 1.0.3 |
| mkdocs-with-pdf | 0.9.3 |

### Configuration

```yaml
site_name: H2OIDE
nav:
  - HOME: index.md
  - Getting Started: getting-started.md
  - Shortcut Functions: h2oide/shortcut-functions.md
  - Build BIOS:
    - Introduction: h2oide/build/build.md
    - Settings: h2oide/build/build-settings.md
    - Sign Image: h2oide/build/sign-image.md
    - Stitch Image: h2oide/build/stitch-image.md
    - Remote Build: h2oide/build/remote-build.md
  - Environment Options:
    - Account Manager: h2oide/environment-options/account-manager.md
    - Code Comments: h2oide/environment-options/code-comments.md
    - Errors: h2oide/environment-options/errors.md
    - File Header: h2oide/environment-options/file-header.md
    - Font & Colors: h2oide/environment-options/font-and-colors.md
    - Function Header: h2oide/environment-options/function-header.md
    - General: h2oide/environment-options/general.md
    - Hex Editor: h2oide/environment-options/hex-editor.md
    - Hotkey: h2oide/environment-options/hotkey.md
    - Language Settings: h2oide/environment-options/language.md
    - Notifications: h2oide/environment-options/notifications.md
    - Output Window: h2oide/environment-options/output-window.md
    - Text Editor: h2oide/environment-options/text-editor.md
    - Theme: h2oide/environment-options/theme.md
    - Workspace: h2oide/environment-options/workspace.md
  - Views: 
    - Bookmark List: h2oide/bookmark-list.md
    - Code Definition Window: h2oide/code-definition-window.md
    - Error List: h2oide/error-list.md
    - File Browser: h2oide/file-browser.md
    - Find & Replace: h2oide/find-and-replace.md
    - Function Map: h2oide/function-map.md
    - Output Window: h2oide/output-window.md
    - Project Browser: h2oide/project-browser.md
    - Project View: h2oide/project-view.md
    - Property Window: h2oide/property-window.md
    - Qick Find: h2oide/quick-find.md
    - Symbol Window: h2oide/symbol-window.md
  - Feature Catalog Manager:
    - Introduction: feature-catalog-manager/feature-catalog-manager.md 
    - Catalog Files:
      - IFC: feature-catalog-manager/catalog-file/ifc.md
      - PFC: feature-catalog-manager/catalog-file/pfc.md
      - PPF: feature-catalog-manager/catalog-file/ppf.md
      - PRF: feature-catalog-manager/catalog-file/prf.md
    - Feature Tree View: feature-catalog-manager/function-page/feature-treeview.md
    - Function Page: 
      - Check-in: feature-catalog-manager/function-page/feature-checkin.md
      - Log: feature-catalog-manager/function-page/feature-log.md
      - Project Download: feature-catalog-manager/function-page/feature-project-download.md
      - Revert: feature-catalog-manager/function-page/feature-revert.md
      - Settings: feature-catalog-manager/function-page/feature-settings.md
      - Tag: feature-catalog-manager/function-page/feature-tag.md
      - Tree: feature-catalog-manager/function-page/feature-tree.md
      - Update: feature-catalog-manager/function-page/feature-update.md
      - Version: feature-catalog-manager/function-page/feature-version.md
    - Operations:
      - Automark: feature-catalog-manager/operations/operations-automark.md  
      - Bookmark: feature-catalog-manager/operations/operations-bookmark.md
      - Branch: feature-catalog-manager/operations/operations-branch.md
      - Conflict Handle: feature-catalog-manager/operations/operations-conflict-handle.md
      - Diff: feature-catalog-manager/operations/operations-diff.md
      - Patch: feature-catalog-manager/operations/operations-patch.md
      - Split: feature-catalog-manager/operations/operations-split.md
      - Tag: feature-catalog-manager/operations/operations-tag.md
    - Q&A:
      - Deleted Tag by Mistake: feature-catalog-manager/question-and-answer/deleted-tag-by-mistake.md
      - Gerrit Questions: feature-catalog-manager/question-and-answer/gerrit-questions.md
      - GIT Application & Service Contacts: feature-catalog-manager/question-and-answer/git-application-and-service-contacts.md
      - How to Create a Feature for the First Time?: feature-catalog-manager/question-and-answer/how-to-create-a-feature-for-the-first-time.md
      - How to Export a Solution?: feature-catalog-manager/question-and-answer/how-to-export-a-solution.md
      - How to Set the Ignore Path for Feature?: feature-catalog-manager/question-and-answer/how-to-set-ignore-path-for-feature.md
      - How to Update the History.txt File?: feature-catalog-manager/question-and-answer/how-to-update-the-history.txt-file.md
      - How to Upgrade Rev 5.4 Architecture to Rev 5.5 Architecture?: feature-catalog-manager/question-and-answer/how-to-upgrade-rev-5.4-architecture-to-rev-5.5-architecture.md
      - What is a Feature?: feature-catalog-manager/question-and-answer/what-is-a-feature.md
      - What is PFCM?: feature-catalog-manager/question-and-answer/what-is-pfcm.md
      - What is the User Account in H2OIDE?: feature-catalog-manager/question-and-answer/what-is-the-user-account-in-h2oide.md
      - Why do You need Multiple Repositories?: feature-catalog-manager/question-and-answer/why-do-you-need-multiple-repositories.md
    - Changelog:
      - Comment: feature-catalog-manager/changelog/comment.md
      - v4.8.7.0: feature-catalog-manager/changelog/4.8.7.0.md
      - v4.8.6.0: feature-catalog-manager/changelog/4.8.6.0.md
      - v4.8.5.0: feature-catalog-manager/changelog/4.8.5.0.md
      - v4.8.4.0: feature-catalog-manager/changelog/4.8.4.0.md
      - v4.8.3.0: feature-catalog-manager/changelog/4.8.3.0.md
      - v4.8.2.0: feature-catalog-manager/changelog/4.8.2.0.md
      - v4.8.1.0: feature-catalog-manager/changelog/4.8.1.0.md
      - v4.8.0.0: feature-catalog-manager/changelog/4.8.0.0.md
      - v4.7.0.0: feature-catalog-manager/changelog/4.7.0.0.md
      - v4.6.6.3: feature-catalog-manager/changelog/4.6.6.3.md
      - v4.6.6.2: feature-catalog-manager/changelog/4.6.6.2.md
      - v4.6.6.1: feature-catalog-manager/changelog/4.6.6.1.md
      - v4.6.5.0: feature-catalog-manager/changelog/4.6.5.0.md
      - v4.6.4.0: feature-catalog-manager/changelog/4.6.4.0.md
      - v4.6.3.3: feature-catalog-manager/changelog/4.6.3.3.md
      - v4.6.3.2: feature-catalog-manager/changelog/4.6.3.2.md
      - v4.6.2.1: feature-catalog-manager/changelog/4.6.2.1.md
      - v4.6.1.0: feature-catalog-manager/changelog/4.6.1.0.md
      - v4.6.0.0: feature-catalog-manager/changelog/4.6.0.0.md
      - v4.5.2.0: feature-catalog-manager/changelog/4.5.2.0.md
      - v4.5.1.3: feature-catalog-manager/changelog/4.5.1.3.md
      - v4.5.1.2: feature-catalog-manager/changelog/4.5.1.2.md
      - v4.5.1.1: feature-catalog-manager/changelog/4.5.1.1.md
      - v4.5.0.0: feature-catalog-manager/changelog/4.5.0.0.md
      - v4.4.1.1: feature-catalog-manager/changelog/4.4.1.1.md
      - v4.4.0.0: feature-catalog-manager/changelog/4.4.0.0.md
      - v4.3.0.0: feature-catalog-manager/changelog/4.3.0.0.md
      - v4.2.1.1: feature-catalog-manager/changelog/4.2.1.1.md
      - v4.2.0.0: feature-catalog-manager/changelog/4.2.0.0.md
      - v4.1.0.0: feature-catalog-manager/changelog/4.1.0.0.md
      - v4.0.1.1: feature-catalog-manager/changelog/4.0.1.1.md
      - v4.0.0.0: feature-catalog-manager/changelog/4.0.0.0.md
      - v3.0.3.3: feature-catalog-manager/changelog/3.0.3.3.md
      - v3.0.2.2: feature-catalog-manager/changelog/3.0.2.2.md
      - v3.0.1.1: feature-catalog-manager/changelog/3.0.1.1.md
      - v3.0.0.0: feature-catalog-manager/changelog/3.0.0.0.md
      - v2.7.2.1: feature-catalog-manager/changelog/2.7.2.1.md
      - v2.7.1.0: feature-catalog-manager/changelog/2.7.1.0.md
      - v2.6.2.1: feature-catalog-manager/changelog/2.6.2.1.md
      - v2.6.1.0: feature-catalog-manager/changelog/2.6.1.0.md
      - v2.5.1.0: feature-catalog-manager/changelog/2.5.1.0.md
      - v2.4.4.3: feature-catalog-manager/changelog/2.4.4.3.md
      - v2.4.3.2: feature-catalog-manager/changelog/2.4.3.2.md
      - v2.4.2.1: feature-catalog-manager/changelog/2.4.2.1.md
      - v2.4.1.0: feature-catalog-manager/changelog/2.4.1.0.md
      - v2.3.1.0: feature-catalog-manager/changelog/2.3.1.0.md
      - v2.2.1.0: feature-catalog-manager/changelog/2.2.1.0.md
      - v2.1.2.1: feature-catalog-manager/changelog/2.1.2.1.md
      - v2.1.1.0: feature-catalog-manager/changelog/2.1.1.0.md
      - v2.0.4.2: feature-catalog-manager/changelog/2.0.4.2.md
      - v2.0.4.1: feature-catalog-manager/changelog/2.0.4.1.md
      - v2.0.3.0: feature-catalog-manager/changelog/2.0.3.0.md
      - v2.0.2.1: feature-catalog-manager/changelog/2.0.2.1.md
      - v2.0.2.0: feature-catalog-manager/changelog/2.0.2.0.md
      - v2.0.1.1: feature-catalog-manager/changelog/2.0.1.1.md
      - v2.0.0.0: feature-catalog-manager/changelog/2.0.0.0.md
      - v1.1.0.2: feature-catalog-manager/changelog/1.1.0.2.md
      - v1.0.0.1: feature-catalog-manager/changelog/1.0.0.1.md
  - Source Control Manager: 
    - Introduction: source-control-manager/source-control-manager.md
  - Tools/ Addins:
    - BIOS Setup Editor:
      - Introduction: addins/setup/setup.md 
      - Link: addins/setup/setup-link.md
    - Checkpoint Editor:
      - Introduction: addins/checkpoint/checkpoint.md 
    - EDID Editor:
      - Introduction: addins/edid/edid.md 
    - Flash Device Editor:
      - Introduction: addins/flash-device/flash-device.md 
    - Flash Map Editor:
      - Introduction: addins/flash-map/flash-map.md 
    - GPIO Editor:
      - Introduction: addins/gpio/gpio.md 
    - Hotkey Editor:
      - Introduction: addins/hotkey/hotkey.md 
    - Logo Editor:
      - Introduction: addins/logo/logo.md 
    - Microcode Editor:
      - Introduction: addins/microcode/microcode.md 
    - Notification Editor:
      - Introduction: addins/notification/notification.md 
    - OEM Service Editor:
      - Introduction: addins/oem-service/oem-service.md 
    - Option ROM Manger:
      - Introduction: addins/option-rom/option-rom.md 
    - PCD Editor:
      - Introduction: addins/pcd-editor/pcd-editor.md 
    - PCI IRQ Routing Editor:
      - Introduction: addins/pci-irq-routing/pci-irq-routing.md 
    - Setup Document Generator:
      - Introduction: addins/setup-document-generator/setup-document-generator.md 
    - SMBIOS Editor:
      - Introduction: addins/smbios/smbios.md 
    - SPD Editor:
      - Introduction: addins/spd/spd.md 
    - SSID/ SVID Editor:
      - Introduction: addins/ssidsvid/ssid-svid.md 
    - Source Solution Retrieval (SSR):
      - Introduction: addins/ssr/ssr.md 
    - Super I/O Editor:
      - Introduction: addins/super-io/super-io.md 
    - UEFI Driver Editor:
      - Introduction: addins/uefi-driver/uefi-driver.md 
    - UEFI Variable Editor:
      - Introduction: addins/uefi-variable/uefi-variable.md 
    - Verb Table Editor:
      - Introduction: addins/verb-table/verb-table.md 
  - Downloads: downloads.md
  - License: license.md
  - About: about.md
theme:
  name: material
  logo: img/H2O_logoW_64.png
  favicon: img/favicon.png
  custom_dir: overrides
  language: en
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
markdown_extensions:
# Admonitions
  - admonition
# Content tabs
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
# Formatting
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
# Icons + Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
# Image
  - attr_list
extra:
  version:
    method: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/insydesw
      name: Twitter
    - icon: fontawesome/brands/facebook-square
      link: https://www.facebook.com/insydesoftware
      name: Facebook
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/insyde-software
      name: Linkedin
    - icon: fontawesome/solid/home
      link: https://www.insyde.com/
      name: Insyde
copyright: Copyright &copy; 2020 - 2021 Insyde Software Corp. All Rights Reserved.
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - localsearch
  - with-pdf
```

### System information

* OS: windows10 10.0.19043 (x64)
* Browser:  firefox 94.0.2 (x64)

**Comment by squidfunk** [comment] 2021-12-01 09:44
So you've upgraded from version 6 to version 8 – did you go through the upgrade guide? Also, from your `mkdocs.yml` I see that you have overrides in place. If you comment those out, does it work again? The fact that the sidebar is not scrollable (and probably the search does not display) means that the JavaScript could not be executed because some elements in the templates could not be found. Please make sure to go through the [upgrade guide](https://squidfunk.github.io/mkdocs-material/upgrade/). Removing your overrides and migrating them to the latest template updates is key when making major version jumps.

Closing as not reproducible.

**Closed by squidfunk** 2021-12-01 09:44 UTC

**Comment by linoferreira** [comment] 2022-06-06 14:24
> So you've upgraded from version 6 to version 8 – did you go through the upgrade guide? Also, from your `mkdocs.yml` I see that you have overrides in place. If you comment those out, does it work again? The fact that the sidebar is not scrollable (and probably the search does not display) means that the JavaScript could not be executed because some elements in the templates could not be found. Please make sure to go through the [upgrade guide](https://squidfunk.github.io/mkdocs-material/upgrade/). Removing your overrides and migrating them to the latest template updates is key when making major version jumps.
> 
> Closing as not reproducible.

Thank you for this comment, the scrollbar wasn't showing on my site (even though the sidebar was longer than the screen) and doing a clean install with the latest version (8.3.2) fixed it.
