### ISSUE TITLE
Cypress.IO tests to improve your work

### ISSUE THREAD

**Issue by rogoit** [squidfunk/mkdocs-material#4266] opened 2022-08-21 11:44 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I want to setup E2E tests to give you a cance to make all the clicks you have to to every time in one automatic process.

### Use Cases

Maybe you can give me a url and something you have implementes as feature.

I also will do a german YouTube series about my work here, when this is ok for you.
https://www.youtube.com/watch?v=fYRfNYgBsco&list=PLKrKzhBjw2Y9ceCxO3ollOc4eIVPAjiHs&index=12

Feel free to get in touch with me. You told me you worfk on sunday. We can do a video call later in evening if you want.

See you
Roland

**Comment by squidfunk** [comment] 2022-08-27 09:23
Thanks for suggesting! I've thought on and off about adding end-to-end tests to this project, but my conclusion is that the project is so amazingly complex that E2E tests would barely help to secure the quality of this project. The reason is that we have dozens of configuration options that significantly alter the HTML and/or behavior of the resulting documentation page, which we'd need to test in all combinations. For instance, we have support for 58 languages – we would need to define a test case for each of those languages to make sure that at least search works. This is impractical from a maintenance and runtime perspective.

Furthermore, implementations between the community edition and [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) sometimes differ, which means even more effort would be needed. As much as I want to add tests, I've decided at some point that it's currently not feasible with the time I have to work on this project. Also, when we implement tests, they would need to be maintained for which I don't have the time to do – it's already hard for me to keep up with bug fixing, feature development and community management.

Closing as (currently) not planned.

**Closed by squidfunk** 2022-08-27 09:23 UTC
Labels: needs investigation

**Comment by HonkingGoose** [comment] 2022-09-08 10:25
Hi @squidfunk! 👋 

Thanks again for making this awesome project!

I see you're not keen on adding Cypress tests. But have you seen Happo [^happo] tests? They are visual "snapshots" of your website, that may help you spot "bad changes". Maybe you can run Happo on the production documentation site to catch regressions?

I hope idea is helpful for you. 😉 

[^happo]: [Happo homepage](https://happo.io/)
