### ISSUE TITLE
Style missing https://squidfunk.github.io/mkdocs-material 

### ISSUE THREAD

**Issue by CarGod** [squidfunk/mkdocs-material#2588] opened 2021-04-21 08:21 UTC
**Unable to display normally：** https://squidfunk.github.io/mkdocs-material 

There's a 404 error

![image](https://user-images.githubusercontent.com/20295772/115521263-92c78500-a2bd-11eb-95de-f7f789d36acc.png)

![image](https://user-images.githubusercontent.com/20295772/115521138-70356c00-a2bd-11eb-8d1f-8f94d1b29eb3.png)

**Comment by squidfunk** [comment] 2021-04-21 09:52
Oops, my fault. 😅 Thanks for reporting! Fixed in the last commit – Duplicate of #2587.

**Closed by squidfunk** 2021-04-21 09:52 UTC
