### ISSUE TITLE
Default favicon is always included in output

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#1760] opened 2020-06-15 11:50 UTC
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

When changing the default favicon via ...

```yaml
theme:
  favicon: images/favicon.png
```

... then this icon is correctly used in the output, but the default favicon is still copied to `[site_dir]/assets/images/favicon.png`.

Tested with Windows and macOS.

### Expected behavior

Only one favicon file should be included in the output.

### Actual behavior

Two favicons are included in the output: the default icon and the custom icon. 

### Steps to reproduce the bug

1. Create a blank project with `mkdocs new`.
2. Change `mkdocs.yml` to:

```yaml
site_name: My Docs
theme:
  name: material
  favicon: images/favicon.png
```
3. Run `mkdocs build`.

Output folder structure:

![15-06-_2020_13-47-46](https://user-images.githubusercontent.com/2234833/84654082-dbc8e300-af0e-11ea-98e1-40259b178281.png)

**Comment by squidfunk** [comment] 2020-06-15 14:23
Exact duplicate of #1282 (of which you are the author 😉) - note that problem 2. In the linked issue was fixed in upstream.

**Comment by wilhelmer** [comment] 2020-06-15 14:29
Oh my, guess I'm getting old 😁 Sorry.

So it's only fixable by a) overriding, b) post processing.

Hope I'll remember it this time 🤞

**Comment by squidfunk** [comment] 2020-06-15 14:33
> So it's only fixable by a) overriding, b) post processing.

Correct 😊 Closing as answered.

**Closed by squidfunk** 2020-06-15 14:33 UTC

**Comment by wilhelmer** [comment] 2020-06-15 20:02
Follow-up: You can actually use [mkdocs-exclude](https://github.com/apenwarr/mkdocs-exclude) to exclude the orphan file. IMHO, this is the most elegant solution:

```yml
plugins:
    - exclude:
        glob:
            - assets/images/favicon.png
```
