### ISSUE TITLE
Navigation expansion become slow at a certain version

### ISSUE THREAD

**Issue by HydrogenSulfate** [squidfunk/mkdocs-material#6188] opened 2023-10-14 05:46 UTC
### Bug description

I have found that navigation expansion bevaviour become different between mkdocs-material-9.1.20 and current version. 

1. Only one navigation will be expand and others will be auto collapsed
2. Expansion speed is slower than 9.1.20 version at least 10x, which should be expanded at once in 9.1.20.

current mkdocs-material
![image](https://github.com/squidfunk/mkdocs-material/assets/23737287/0b582f42-9bfb-4741-b357-2582190d8954)

mkdocs-material==9.1.20
![image](https://github.com/squidfunk/mkdocs-material/assets/23737287/04a599d2-f241-4e9b-830d-686a641b3609)

 

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

https://paddlescience-docs.readthedocs.io/zh/latest/zh/examples/volterra_ide/

### Steps to reproduce

1. install newest material and render document of https://github.com/PaddlePaddle/PaddleScience.git
2. install 9.1.20 material and render document of https://github.com/PaddlePaddle/PaddleScience.git

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-10-14 07:11
Thanks for reporting. You checked that you added a `zip` with a reproduction but you did not. We need a reproduction, as demanded by our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) to look into it. A link to a page is not a reproduction we can use to debug and fix the issue.

**Comment by HydrogenSulfate** [comment] 2023-10-14 07:34
> Thanks for reporting. You checked that you added a `zip` with a reproduction but you did not. We need a reproduction, as demanded by our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) to look into it. A link to a page is not a reproduction we can use to debug and fix the issue. Please provide the reproduction, attach it to the issue, and we will look into it.
[9.4.5-expand_slow.zip](https://github.com/squidfunk/mkdocs-material/files/12903470/9.4.5-expand_slow.zip)


oh I see it and there is the zip file.

**Comment by squidfunk** [comment] 2023-10-14 08:33
Thanks for providing the reproduction. However, **it is not minimal**, you just zipped up your entire project. There are hundreds of lines of `mkdocs.yml`, dozens of plugins, and very likely a lot of features enabled that are not necessary to observe the problem. Please reduce it to a minimal reproduction, so we can budget the time to help you.

We're closing [this issues as incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues), and we'll reopen it once you invested the time into providing a minimal reproduction. 

Thank you very much.

**Closed by squidfunk** 2023-10-14 08:33 UTC
Labels: needs reproduction

**Comment by HydrogenSulfate** [comment] 2023-10-14 08:46
> Thanks for providing the reproduction. However, **it is not minimal**, you just zipped up your entire project. There are hundreds of lines of `mkdocs.yml`, dozens of plugins, and very likely a lot of features enabled that are not necessary to observe the problem. Please reduce it to a minimal reproduction, so we can budget the time to help you.
> 
> We're closing [this issues as incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues), and we'll reopen it once you invested the time into providing a minimal reproduction.
> 
> Thank you very much.

I have located to the `navigation.prune`, this option make expand speed much slower, might because it will only render those expaned content but collapsed as descripted below:
> [When pruning is enabled, only the visible navigation items are included in the rendered HTML](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-pruning)

I will disable this optional till it is fixed. Thanks a lot for reply.

**Comment by squidfunk** [comment] 2023-10-14 10:15
`navigation.prune` and `navigation.expand` are incompatible, [as mentioned on our documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-pruning):

<img width="735" alt="Bildschirm­foto 2023-10-14 um 12 14 02" src="https://github.com/squidfunk/mkdocs-material/assets/932156/d2bb0917-fb35-4f0a-8644-87d663825970">


Thus, it's working as intended.

**Comment by HydrogenSulfate** [comment] 2023-10-14 16:14
> `navigation.prune` and `navigation.expand` are incompatible, [as mentioned on our documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-pruning):
> 
> <img alt="Bildschirm­foto 2023-10-14 um 12 14 02" width="735" src="https://user-images.githubusercontent.com/932156/275192422-d2bb0917-fb35-4f0a-8644-87d663825970.png">
> Thus, it's working as intended.

Actually I do not enable `navigation.expand` in PaddleScience as below.

![image](https://github.com/squidfunk/mkdocs-material/assets/23737287/b2f80fca-324e-4d4e-95e3-e0ee7515547c)


Anyway it works for newest mkdocs-material with `navigation.prune` disabled.
