### ISSUE TITLE
404.html looks incorrect

### ISSUE THREAD

**Issue by renoger** [squidfunk/mkdocs-material#1550] opened 2020-03-29 17:03 UTC
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Low priority for me as I´m using the site locally, but I see that the 404 page renders in a weird way.

![issue4](https://user-images.githubusercontent.com/62448529/77855315-efa65800-71ef-11ea-8180-e816683a2c76.gif)

### Steps to reproduce the bug

1. mkdocs build your project and open the generated 404.html file

### Package versions

* Python: 3.7.0
* MkDocs: 1.1
* Material: 5.0.0rc4

### System information

* OS: Win10
* Browser: Chrome

**Comment by squidfunk** [comment] 2020-03-29 17:14
That is actually a limitation of MkDocs, not Material for MkDocs. It's exactly the same for the original theme and caused by the absolute paths of the assets. This is the `mkdocs` theme:

<img width="1552" alt="Bildschirmfoto 2020-03-29 um 19 13 19" src="https://user-images.githubusercontent.com/932156/77855564-7576d300-71f1-11ea-92d0-6094b4c008f7.png">

**Comment by renoger** [comment] 2020-03-29 17:27
I did not since it was still rendering fine last week with the same project. (under v4.4.3)
Let me see if I can narrow it down.

**Comment by squidfunk** [comment] 2020-03-29 17:41
When you open the site locally, i.e. using the `file://` protocol it cannot work when you set `site_url` to some other domain.

**Comment by renoger** [comment] 2020-03-29 18:19
I actually never set `site_url` in my configuration file.

**Comment by squidfunk** [comment] 2020-03-29 18:25
Can you reproduce this error with the default theme? You just need to set `theme: mkdocs`.

**Comment by renoger** [comment] 2020-03-29 18:41
I can, if i use the default theme I see the same as your screenshot.

**Comment by squidfunk** [comment] 2020-03-29 18:49
Then this is not a problem with this project, but with MkDocs 😊

**Comment by renoger** [comment] 2020-03-29 18:54
I see, something must have changed then going from MkDocs v1.0 to 1.1.
Thanks

**Comment by squidfunk** [comment] 2020-03-29 18:59
Possible. I'm closing this issue and encourage you to create a new issue on their issue tracker. Unfortunately, we cannot do anything about it.

**Closed by squidfunk** 2020-03-29 18:59 UTC
