### ISSUE TITLE
Version switcher fails to stay on the same page when `canonical_version` is set in mike  

### ISSUE THREAD

**Issue by kevinh-hcl** [squidfunk/mkdocs-material#7226] opened 2024-05-31 07:57 UTC
### Context

We are using `mkdocs-material` together with `mike` for our documentation. 

To improve SEO we set the `canonical_version` in `mike`. This sets the `rel="canonical"` `link` on every page and also leads to the `sitemap.xml` in each version using the canonical links (with `latest`). This seems to be the expected way of handling canonical URLs according to [Google Search Central](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls) and others.

### Bug description

When switching from a sub page of any version to a version that was built **with** the `canonical_version` you get redirected to the homepage of the version. The expected behaviour would be to stay on the same sub page, but in a different version.

From what I can see this is probably due to `mkdocs-material` using the sitemap of the version to determine if a sub page is available in that version. Since the sitemap always uses the `canonical_version` instead of the actual version, the page is not found and it falls back to the homepage. 

### Related links

**Related documentation**
- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Setting up versioning - Stay on the same page when switching versions](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#stay-on-the-same-page-when-switching-versions)

**Pointer from a previous discussion**
- [kamilkrzyskow seems to have the right idea in this discussion about the `latest` in all `sitemap.xml`](https://github.com/squidfunk/mkdocs-material/discussions/6809#discussioncomment-8551776)

**Related `mike` documentation and code**
- [mike: configuration options](https://github.com/jimporter/mike?tab=readme-ov-file#configuration)
- [mike: building `site_url` from `canonical_version`](https://github.com/jimporter/mike/blob/master/mike/mkdocs_plugin.py#L46-L49)

**Reproduction in a fork from `mkdocs-material-example-versioning`**
- [Setting `canonical_version`](https://github.com/kevinh-hcl/mkdocs-material-example-versioning/commit/37d9188bea97c801623d041368f604c60546f376)
- [Github Pages Version `0.5` (with `canonical_version`).](https://kevinh-hcl.github.io/mkdocs-material-example-versioning/0.5/bar/) You can switch **FROM** this versions to others just fine
- [Github Pages Version `0.4`.](https://kevinh-hcl.github.io/mkdocs-material-example-versioning/0.4/bar/) Switch **TO** `0.5` and get redirected to the homepage
- [`0.5` sitemap](https://kevinh-hcl.github.io/mkdocs-material-example-versioning/0.5/sitemap.xml)
- [`0.4` sitemap](https://kevinh-hcl.github.io/mkdocs-material-example-versioning/0.4/sitemap.xml)

### Reproduction

[9.5.25-version-switcher-canonical.zip](https://github.com/user-attachments/files/15510187/9.5.25-version-switcher-canonical.zip)

### Steps to reproduce

1. unzip `9.5.25-version-switcher-canonical.zip` and navigate to the extracted folder
2. (Optional: I had to remove the venv due to the size limitation in the .zip upload. Please follow https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#environment to create a venv and activate it)
3. Install the dependencies using `pip install --upgrade --force-reinstall mike==2.1.1 mkdocs-material==9.5.25 mkdocs==1.6.0`
4. In `mkdocs.yml` remove the `- info` from the `plugins` section and save the changes
5. Deploy a first version using `mike deploy canonical`
6. In `mkdocs.yml` remove the `canonical_version: latest` from `mike` in the `plugins` section and save the changes
7. Deploy a second version using `mike deploy no-canonical latest`
8. Serve the documentation locally using `mike serve`

**Working as expected:**
1. Open http://localhost:8000/canonical/subpage/
2. Switch to the **no-canonical** version
3. The version shows the correct page
4. (Optional: check http://localhost:8000/no-canonical/sitemap.xml of the target version)

**Not working as expected:**
1. Open http://localhost:8000/no-canonical/subpage/
2. Switch to the **canonical** version
3. Redirected to the homepage 
4. (Optional: check http://localhost:8000/canonical/sitemap.xml of the target version)

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-05-31 08:18
Thanks for reporting and the very detailed explanations. Yes, it sounds like a currently unhandled combination of configuration settings when using mike. I'm not sure it's a bug, since we don't advertise the `canonical_version` setting anywhere in our documentation, so I'll tag this as an chance request. Since you have already invested some time into tracking down the cause, would you like to work on this in a PR? Happy to collaborate. Shouldn't be too hard to support ☺️

**Comment by kevinh-hcl** [comment] 2024-05-31 14:45
Thank you. I drafted a first idea of how this could be handled in https://github.com/squidfunk/mkdocs-material/pull/7227. Any feedback is appreciated

**Comment by squidfunk** [comment] 2024-06-01 11:00
Thanks for the PR! Please give me some time to check it out and give it a spin.

**Comment by ilyagr** [comment] 2024-07-09 02:32
I'm trying an alternative approach to fixing this in #7350. That approach should also make the version switcher work correctly with `mike serve` again.

**Comment by squidfunk** [comment] 2024-09-27 07:53
Reopening until released.

**Comment by squidfunk** [comment] 2024-09-29 08:01
Released as part of [9.5.39](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.39).

**Closed by squidfunk** 2024-09-29 08:01 UTC
Labels: change request, resolved
