### ISSUE TITLE
Navbar color flickering

### ISSUE THREAD

**Issue by nebulade** [squidfunk/mkdocs-material#538] opened 2017-10-25 19:52 UTC
## Description

When setting a non default color in `mkdocs.yml` every page load will animate from the default color to the one set in the config file. This presumably happens since the default color is applied first, then the new style is applied, which triggers the color change. This is mostly obvious when changing pages or simply ctrl+r the page again and again. The ugly result is an appeared flickering, depending on how fast the browser renders.

### Package versions

* Python: 3.6.2
* MkDocs: 0.16.3
* Material: master (but there since some time)

### Project configuration

``` yaml
extra:
  palette:
    primary: 'blue grey'
```

### System information

* OS: Linux 
* Browser: Chrome and Firefox Nightly (it is less obvious in older FF versions)

Thanks for all the great work happening in this project, I really enjoy using it!

**Comment by martinbira** [comment] 2017-10-25 20:38
I have experienced this behaviour as well as I use a custom color scheme.

**Comment by nebulade** [comment] 2017-10-25 20:42
Maybe there is an easy way to build the assets with a different default color instead?

**Comment by squidfunk** [comment] 2017-10-25 21:23
Well, I haven't seen this before on any site, but in theory it could happen due to the transitions defined. You can always customize the theme and build it with your own colors. I will look into the transition stuff, but I haven't seen it anywhere flickering before.

**Comment by squidfunk** [comment] 2017-11-01 11:36
I really cannot reproduce it. Tested on Chrome, Safari, Firefox, iOS, IE, Edge... I'm seeing it nowhere. Still very strange, because in theory it should only happen when CSS is applied afterwards. This could happen due to the `application.palette.css` being loaded later, but it's directly after the `application.css` and before the browser renders anything.

**Comment by makshh** [comment] 2017-11-01 19:25
I can't reproduce it as well.

**Comment by nebulade** [comment] 2017-11-02 11:02
To be honest I have a hard time reproducing this myself now with the latest version 2 release. I cannot see though which change would have affected this, but it is better now.

**Comment by squidfunk** [comment] 2017-11-02 11:12
Is it better or is it gone?

**Comment by nebulade** [comment] 2017-11-02 19:01
just checked in with other people here and it seems to be gone. So maybe some unrelated css changes fixed that? I guess we can close it. Thanks for the responses though.

**Comment by squidfunk** [comment] 2017-11-03 15:11
Yeah, it may actually be related to putting Modernizr after the CSS as done in #558. I'm closing this issue, please feel free to re-open it if it happens again.

**Closed by squidfunk** 2017-11-03 15:11 UTC
Labels: bug
