### ISSUE TITLE
Mastodon social link

### ISSUE THREAD

**Issue by EmberHeartshine** [squidfunk/mkdocs-material#4790] opened 2022-12-21 16:41 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Using the social link functionality described in [the documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links) is easy enough, but Mastodon specifically has the requirement of including a `rel="me"` property of the `a` tag in order to make the link appear "verified" on Mastodon. would it be possible to add that somehow? I'm not sure what that would entail.

### Use Cases

This would allow mkdocs-material pages to be "verified" on Mastodon profiles without needing to add a separate link.

**Comment by squidfunk** [comment] 2022-12-21 23:53
Exact duplicate of #4752.

**Closed by squidfunk** 2022-12-21 23:53 UTC

**Comment by EmberHeartshine** [comment] 2022-12-22 01:28
FYI Q&A is not indexed with issues when searching.

**Comment by squidfunk** [comment] 2022-12-22 08:43
Okay, I take that back then. GitHub search could be better, I agree.
