### ISSUE TITLE
Insiders tag plugin conflicts with markdown_extensions.toc

### ISSUE THREAD

**Issue by kcgthb** [squidfunk/mkdocs-material#7191] opened 2024-05-17 01:28 UTC
### Context

The new Insiders tag plugin rewrite conflicts with the `markdown_extensions.toc` extension.

### Bug description

When the `markdown_extensions.toc` extension is used and `toc_depth` option is set to a value <6, the new Insiders tag plugin doesn't generate tag listings.

### Related links

- [ `markdown_extensions.toc` extension](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/table-of-contents)
- [`tags` plugin](https://squidfunk.github.io/mkdocs-material/plugins/tags/#listings)

### Reproduction

[9.5.23+insiders.4.53.8-no-tags-list-with-toc.zip](https://github.com/squidfunk/mkdocs-material/files/15342593/9.5.23%2Binsiders.4.53.8-no-tags-list-with-toc.zip)

### Steps to reproduce

1. enable `plugins.tags` in `mkdocs.yml`
2. set `markdown_extensions.tac.toc_depth: 6` in `mkdocs.yml` 
3. `<!-- material/tags -->` doesn't generate anything

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-05-17 13:18
Thanks for reporting! Fixed in . The problem is that the tags plugin needs to somehow hook into the TOC generation, and it does so by just appending the maximum headline, so the tags listing is listed under the preceding headline. This is a pretty dirty hack, but otherwise, it would be much more difficult to pull this off, as we'd need to parse the Markdown again, and isolate which was the last headline before the tags headline.

When the maximum level is changed, it stops as reported. Now, the plugin will read the maximum level from the configuration of the table of contents extension and use that for injecting listings.

Is that the optimal solution? Very far from it, but we need to work with what Python Markdown and MkDocs gives us. We'll investigate in the future if we can improve the implementation and make it less hacky. I hope that in the meantime, the reported problem can be considered fixed.

**Comment by kcgthb** [comment] 2024-05-17 18:51
Thank you for the quick fix! Much appreciated.

**Comment by kcgthb** [comment] 2024-05-17 23:31
I can confirm that this commit resolves the issue for us, so closing this issue now.

**Comment by squidfunk** [comment] 2024-05-18 06:03
Great! Keeping open until released.

**Closed** 2024-05-20 11:05 UTC
Labels: bug, resolved
