### ISSUE TITLE
Fail to initialize searching index for languages other than 'en'

### ISSUE THREAD

**Issue by peaceiris** [squidfunk/mkdocs-material#1854] opened 2020-08-04 08:48 UTC
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Version 5.5.1 and 5.5.2 fails to initialize search index with Japanese search mode but version 5.5.0 works well.

### Expected behavior

`5.5.0` works well.

```
git clone https://github.com/SI-Aizu/documentation.git
cd ./documentation
git checkout cd36072
docker-compose up
```

Open <http://0.0.0.0:8888/>, search with a Japanese word or an English word, it works well.

```console
$ docker-compose run --rm --entrypoint=bash mkdocs
$ python --version
Python 3.8.5
$ mkdocs --version
mkdocs, version 1.1.2 from /usr/local/lib/python3.8/site-packages/mkdocs (Python 3.8)
$ pip show mkdocs-material | grep -E ^Version
Version: 5.5.0
```

### Actual behavior

In 5.5.1 and 5.5.2, it shows only the message `Initializing search` and I cannot search with any word (any language). My browser console (Google Chrome) put the following error.

```sh
git clone https://github.com/SI-Aizu/documentation.git
cd ./documentation
git checkout a654e3b
docker-compose up
```

<img width="376" alt="Screen Shot 2020-08-04 at 17 33 13" src="https://user-images.githubusercontent.com/30958501/89272102-9c9a5100-d678-11ea-8c65-537c90739371.png">

```
Uncaught TypeError: Cannot set property 'stemmerSupport' of undefined    index.ts:63
    at lunr.stemmer.support.min.js:1
    at lunr.stemmer.support.min.js:1
    at lunr.stemmer.support.min.js:1
    at index.ts:63
    at a (index.ts:85)
    at index.ts:109
```

<img width="759" alt="Screen Shot 2020-08-04 at 17 20 11" src="https://user-images.githubusercontent.com/30958501/89270758-c488b500-d676-11ea-933e-121e23fa06b0.png">

```console
$ docker-compose run --rm --entrypoint=bash mkdocs
$ python --version
Python 3.8.5
$ mkdocs --version
mkdocs, version 1.1.2 from /usr/local/lib/python3.8/site-packages/mkdocs (Python 3.8)
$ pip show mkdocs-material | grep -E ^Version
Version: 5.5.1
```

### Steps to reproduce the bug

I already wrote about this above.

### Package versions

I already wrote about this above.

### Project configuration

I am using the same configuration between the 3 versions.

``` yaml
# Project information
site_name: 'SI-Aizu Documentation'
site_description: 'SI-Aizu Documentation'
site_author: 'SI-Aizu'
site_url: 'https://si-aizu.github.io/documentation'

# Copyright
copyright: '&copy; 2020 SI-Aizu'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/SI-Aizu/documentation'
edit_uri: 'https://github.com/SI-Aizu/documentation/edit/main/docs'

# Configuration
docs_dir: 'docs'
theme:
  name: 'material'
  language: 'ja'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    primary: indigo
    accent: orange
  # features:
  #   - tabs
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  #icon:
    #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: '_'

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - ja

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'assets/css/custom.css'
extra:
  # manifest: 'manifest.json'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/SI-Aizu/documentation'
```

### System information

* OS: macOS Mojave 10.14.6
* Browser:
  * Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)
  * Microsoft Edge Version 84.0.522.52 (Official build) (64-bit)

**Comment by squidfunk** [comment] 2020-08-04 09:30
Thanks for reporting - it's actually related to all other languages, I'll look into it asap.

**Comment by squidfunk** [comment] 2020-08-04 10:53
Fixed in 13412008.

The problem was related to a change in bundling. With 5.5.1, we switched from `expose-loader` to the `ProvidePlugin`, which is generally a more natural fit, as we only want to prepend `lunr` to the search worker output. The problem is, that the minifier will now eradicate the `global.lunr` assignment, removing it from the global scope, which triggered a cascade of errors. 

The referenced commit switches back to `expose-loader` (which was updated to 1.0.0).

**Comment by squidfunk** [comment] 2020-08-04 10:59
Released as part of 5.5.3.

**Closed by squidfunk** 2020-08-04 10:59 UTC
Labels: bug

**Comment by peaceiris** [comment] 2020-08-04 11:21
This was fixed in 5.5.3! Thank you for the quick fix.

**Comment by ryo1988** [comment] 2020-09-29 04:33
In 6.0.1, if you specify 'ja', it remains "Initializing search".

**Comment by squidfunk** [comment] 2020-09-29 06:41
I can't reproduce this, Japanese search works on a clean installation for me:

![screenshot-0-0-0-0-8000-1601361624363](https://user-images.githubusercontent.com/932156/94522189-869bad80-022f-11eb-906e-8fbe0d86c77e.png)

**Comment by ryo1988** [comment] 2020-09-29 12:21
Thanks for the confirmation.
We have created a reproduction environment.

https://github.com/ryo1988/mkdocsTest

Clone it and Run it.

- Run.4.6.3.bat OK
- Run.6.0.1.bat NG

![image](https://user-images.githubusercontent.com/6487424/94556937-de223380-0298-11eb-82c6-3aa6a558382f.png)

ENVIRONMENT:
- Windows 10 Pro 19041.508
- Chrome 85.0.4183.121 Official Build 64 bit
- Python 3.8.6 Windows x86-64 web-based installer https://www.python.org/downloads/release/python-386/

**Comment by squidfunk** [comment] 2020-09-29 12:43
Thanks for providing the reproduction. However, it's exactly the same as the one I posted in my last comment and I'm yet unable to reproduce the error you're seeing.

**Comment by ryo1988** [comment] 2020-09-29 15:55
When I tried 5.0.0, it was not successful.
I changed the "HKEY_CLASSES_ROOT\.js\Content Type" in the registry from "text/plain" to "text/javascript" and it became OK.
Do I have to set the "HKEY_CLASSES_ROOT\.js\Content Type" in the registry to "text/javascript"?

**Comment by TACO-Chloe** [comment] 2021-01-22 07:34
Fail to initialize searching on **### mobile**.
Than **### web** can search anything .. 

version  :
mkdocs                         1.1.2
mkdocs-material            6.2.4
