### ISSUE TITLE
Social card plugin can't use logo from theme custom_dir

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#5128] opened 2023-03-02 03:18 UTC
### Context

We share assets between our (multilingual) sites by storing them in our theme override directory, as discussed in #2346.

### Bug description

When `theme.logo` is set to a logo in `theme.custom_dir` instead of `docs_dir`, social cards fail to generate with the error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/[...]/docs/assets/img/logo.svg'
```

The plugin should ideally be looking in the merged assets directory rather than the directory in `docs_dir` specifically.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
- #2346 

### Reproduction

[Archive.zip](https://github.com/squidfunk/mkdocs-material/files/10867197/Archive.zip)

### Steps to reproduce

1. Store logo SVG in `[custom_dir]/assets` instead of `docs/assets`
2. Set `theme.logo` to `assets/img/logo.svg`
3. Enable social card plugin

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-03-02 08:23
Thanks for reporting. Duplicate of #4920 which is currently not fixable. I'll add a note to the docs that this is currently a limitation. The social card plugin will receive an update in the future, which will resolve this limitation.

**Comment by squidfunk** [comment] 2023-03-02 08:24
Workaround in https://github.com/squidfunk/mkdocs-material/issues/4920#issuecomment-1407387385.

**Comment by squidfunk** [comment] 2023-05-02 09:20
Fixed, thanks to the awesome work of @kamilkrzyskow!

**Closed** 2023-05-02 09:20 UTC
Labels: duplicate
