### ISSUE TITLE
Cannot search headers containing colon (`:`)

### ISSUE THREAD

**Issue by TWiStErRob** [squidfunk/mkdocs-material#4884] opened 2023-01-18 14:29 UTC
### Bug description

When a symbol is defined as a separator, we expect that symbol to searchable, that is the search string being tokenized exactly the same as the docs contents. Based on observations it looks like this is not the case with the built-in plugin.

### Related links

- [plugins.search.separator docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search-plugin)
- Original observation of this issue from @viceice and @HonkingGoose in [Renovate's docs](https://github.com/renovatebot/renovatebot.github.io/issues/264) and our investigation history.

### Reproduction

Created by following
1. https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/
2. https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search-plugin
3. Configure separator to include spaces, dash and colon

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10447301/example.zip) (browse same [sources on GitHub](https://github.com/TWiStErRob/repros/tree/master/mkdocs/material-colon-search))

### Steps to reproduce

1. remove `- info` from `plugins:`
2. `mkdocs serve`
3. Search for `dash-separated` and observe match:
![image](https://user-images.githubusercontent.com/2906988/213195282-88c84ebe-8c2a-47e3-b655-3e2124a2f122.png)
4. Search for `colon:separated` and be baffled:
![image](https://user-images.githubusercontent.com/2906988/213195807-ed522430-0c02-48a1-a002-cfd979d59aa2.png)
5. For control, search for `separated` and observe tokenization works:
![image](https://user-images.githubusercontent.com/2906988/213195522-cb01b92a-289e-4ed4-a16f-c032b03b412a.png)
6. Try `"colon:separated"` 🤞 it works because that's the usual for "exact match":
![image](https://user-images.githubusercontent.com/2906988/213196322-8d853413-3423-4333-9bbc-5bc64cbc9352.png)

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment] 2023-01-18 14:44
Thanks for reporting. This is a feature and not a bug 😉 `:` is considered a control character that allows to specify which field to search on. For example `title:foo` will only search the title of documents for `foo`.  What we might be able to do is to allow for `:` as long as the word before the colon is not the name of a field, but I'm not sure this is a good idea, because then behaviour for `title`, `text` and `tags` differs from the rest of cases.

Normally, this isn't a problem because people don't search for `:`. I'll check if we can somehow limit to active fields, but if that doesn't prove to be viable, you might still fork the theme and adjust the query lexing stage:

https://github.com/squidfunk/mkdocs-material/blob/6119df5d56fcdc90e25c5b1a47f7d2eba77f589e/src/assets/javascripts/integrations/search/query/_/index.ts#L63-L84

**Comment by squidfunk** [comment] 2023-01-28 13:01
Fixed in a6436bd48. When the query lexer returns an unknown field, we transform the query to replace the `:` with whitespace, so the search pipeline doesn't consider this as a field name. Note that the query lexing approach is very new and needs to be better incorporated into the search worker. I'll tackle this when I work on search the next time, which will be very soon given how many open change requests concerning search there currently are.

For the time being, this fix should make the search in your docs functional again 😊

**Comment by squidfunk** [comment] 2023-01-28 13:02
I closed this too early. We need to keep this open until the fix is released.

**Comment by viceice** [comment] 2023-01-28 13:03
thanks for working on this. ❤️

**Comment by squidfunk** [comment] 2023-01-28 14:04
Released as part of [9.0.7](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.7)

**Closed by squidfunk** 2023-01-28 14:04 UTC
Labels: bug, resolved

**Comment by HonkingGoose** [comment] 2023-02-01 10:40
I can confirm that `9.0.7` fixed this problem for us in production as well.

Thank you very much for working on this, and getting it fixed so quickly! ❤️
