### ISSUE TITLE
Regression (7.3.2): Left navbar with tabs should not render for tabs with no subpages

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#3109] opened 2021-10-16 00:13 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

[A regression via our CI for docs has been noticed](https://github.com/docker-mailserver/docker-mailserver/pull/2244) when updating the docker image version for `squidfunk/mkdocs-material`.

The left nav (DOM node `ul.md-nav__list`) now includes a single link rendered below our tabs when there are no subpages (the tab is a direct markdown file).

HTML has been identified between both, the same node exists, just in the past the nav list has been hidden visually. Presumably a CSS regression?

Example from `mkdocs.yml`:

```yml
nav:
  # These top-level keys with direct page values should not render a redundant left nav:
  - 'Home': index.md
  - 'Introduction': introduction.md
  # Examples tab has subpages, it should render a left nav:
  - 'Examples':
    - 'Tutorials':
      - 'Basic Installation': examples/tutorials/basic-installation.md
      - 'Mailserver behind Proxy': examples/tutorials/mailserver-behind-proxy.md
```

### Expected behaviour

Tabs that have no subpages should have an empty left side-bar.

![Screenshot_20211016_124526](https://user-images.githubusercontent.com/5098581/137564944-ea30ef32-9653-4b6b-86e8-4b95b7dd7356.png)

![Screenshot_20211016_124541](https://user-images.githubusercontent.com/5098581/137564953-c72aa4d7-e258-4e44-a873-9ed32a7d66ff.png)

### Actual behaviour

Tabs that have no subpages are rendering a side-bar with a single link to the same page.

![Screenshot_20211016_124345](https://user-images.githubusercontent.com/5098581/137564870-3144b195-0c44-4047-a51b-77e2769db203.png)

![Screenshot_20211016_124433](https://user-images.githubusercontent.com/5098581/137564906-5cf6dc2b-7b8a-49a8-b0e2-fa17ff49c8dc.png)

### Steps to reproduce

1. Our docs can be built from our repo `docs/` folder, here is the [`mkdocs.yml`](https://github.com/docker-mailserver/docker-mailserver/blob/fb77d3f7210ff4501f454020809a72704a350d48/docs/mkdocs.yml) from that location.
2. We presently build docs via docker image with the tag `7.3.0`, a recent PR to update to `7.3.2` is where regression was noticed via our CI deploy preview.

```bash
docker run \
  --rm \
  -v "${PWD}:/docs" \
  squidfunk/mkdocs-material:7.3.2 build --strict
```

A more minimal reproduction will be identified and this issue updated.

### Package versions

All handled via the official `squiidfunk/mkdocs-material` Docker image. If necessary, this information can be pulled from that, release tag `7.3.2` is a known regression, `7.3.0` a known good state.

---

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
[`mkdocs.yml`](https://github.com/docker-mailserver/docker-mailserver/blob/fb77d3f7210ff4501f454020809a72704a350d48/docs/mkdocs.yml). Once a minimal reproduction is done, this will be updated with the minimal `mkdocs.yml` contents to reproduce.
```

### System information

This is for my system, but other users have different OS and browsers. The docs are built via Github CI with the official Docker image.

- Operating system: Linux (Manjaro)
- Browser: Only tested on Brave (Chromium)

**Comment by polarathene** [comment] 2021-10-16 00:46
Affected HTML node:

```html
<a href="." class="md-nav__link md-nav__link--active">
Home
</a>
```

Selector/path:

```js
document.querySelector("body > div.md-container > main > div > div.md-sidebar.md-sidebar--primary > div > div > nav > ul > li.md-nav__item.md-nav__item--active > a")
```

---

CSS difference identified as:

Good (`7.3.0`):
```
@media screen and (min-width: 76.25em)
.md-nav--lifted>.md-nav__list>.md-nav__item--active>.md-nav__link {
    display: none;
}
```

Bad (`7.3.2`):

```
@media screen and (min-width: 76.25em)
.md-nav--lifted>.md-nav__list>.md-nav__item--active>.md-nav__link {
    font-weight: 700;
    margin-top: 0;
    padding: 0 .6rem;
    pointer-events: none;
}
```

**Comment by squidfunk** [comment] 2021-10-17 08:52
Thanks for reporting and taking the time to dive into this issue. It's actually intended behavior.

The behavior you're saying to be expected was introduced __as a regression__ in the refactoring of the`navigation.tabs` feature which was done as part of 6.2.0. Prior to this version it was [not possible to link single pages as tabs](https://github.com/squidfunk/mkdocs-material/issues/2125#issuecomment-744360768). 6.2.0 got rid of the automatic-grouping behavior. Related issues:

- #2072 
- #2125 
- #2472 
- #3076

If you check a version prior to 6.2.0, you'll see the exact same behavior as reported in this issue. 7.3.2 fixed some compatibility issues of the `navigation.tabs`, `navigation.sections` and `navigation.indexes` features, and also fixed the regression – behavior is now normalized across all navigation features. While I understand that it might not be what you want, it's the canonical behavior that Material for MkDocs offers. It's also important for the `toc.integrate` feature, which renders the table of contents as part of the navigation tree on the left. Prior to 7.3.2, the integrated table of contents on single-page tabs appeared a little lost without the page title above it. This is now fixed (albeit the spacing is not correct, which I just discovered and will look into straight away):

![screenshot-localhost-8000-mkdocs-material-foo-1634460599747](https://user-images.githubusercontent.com/932156/137619561-8d2936b4-6c0c-4d05-909c-58611b826b36.png)

**Comment by squidfunk** [comment] 2021-10-17 08:53
Closing, as it's working as intended.

**Closed by squidfunk** 2021-10-17 08:53 UTC

**Comment by squidfunk** [comment] 2021-10-17 09:44
f073fb2c2 fixes the spacing issue I just discovered. The integrated TOC should now always align with its parent page.

**Comment by squidfunk** [comment] 2021-10-17 09:48
> No worries, thanks for the detailed response. We'll just add it as another fix on our end to maintain 👍

My previous comment might give a good start on how to craft a CSS selector to achieve the desired behavior.

> I'm not sure in what situation you'd want the left nav rendered with a single link item to the same page like my screenshot shows, but I can understand that may not be considered a problem on your end.

I completely understand the use case and wish for the desired behavior. However, navigation is so complex because of the many options that influence each other, that I try to not introduce more of it. 7.3.2. actually reduced complexity.

Thanks for your understanding!
