### ISSUE TITLE
Code highlighting colours the whole line in --md-code-hl-color

### ISSUE THREAD

**Issue by mocdaniel** [squidfunk/mkdocs-material#6017] opened 2023-09-14 18:10 UTC
### Context

I'm working on a freshly setup instance of Material for MkDocs and code highlighting seems to be off, compared to the results [shown in the docs](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines).

<img width="693" alt="strange code highlighting" src="https://github.com/squidfunk/mkdocs-material/assets/28064429/2434b4d4-350e-4879-bc93-937db90c5983">

### Bug description

Compared to the example from the docs, the result rendered on my end is

a) yellowish instead of blue

b) renders the whole line in `--md-code-hl-color` instead of just the left border and the remainder in `--md-code-hl-color` according to my dev tools:

```css
.highlight .hll {
    background-color: var(--md-code-hl-color);
    display: block;
    margin: 0 -1.1764705882em;
    padding: 0 1.1764705882em;
}
```

My related configuration looks like this, I went by the book, i.e. the docs, if not mistaken:

```yaml
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
```

### Related links

I took a good look at the `pygments`/`Highlight` configuration:
- [https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight)

as well as the docs regarding how to do highlighting and how to theme it:
- [https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines)
- [https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#custom-syntax-theme](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#custom-syntax-theme)

I managed to get the bluish highlight working this way, but it still covered the whole line in the darker variant and omitted the `--light` variant altogether.

### Reproduction

[9.3.1-highlight-wrong-css.zip](https://github.com/squidfunk/mkdocs-material/files/12611942/9.3.1-highlight-wrong-css.zip)

### Steps to reproduce

1. Enable code highlighting as per my example and the documentation linked above
2. Run `mkdocs serve` or `mkdocs build`
3. Open the result and see code highlighting be different from the examples in the docs linked above

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment] 2023-09-15 11:15
Hi,

thanks for the report and the reproduction. I have run it and see the same result as you do. However, when I compiled the reproduction earlier using my mkdocs install the issue did not appear. I was using the insiders version, though. Let me see if I can figure out where this comes from and get back to you. (I just started to contribute to material-mkdocs, so may take a little longer than squidfunk would, please bear with me.)

Cheers,

Alex

**Comment by alexvoss** [comment] 2023-09-15 12:49
Quick update: I found no relevant differences in what `mkdocs build` produces once the info plugin is deactivated again. As far as I can tell, both the insiders and the public version produce the same html for the code segment. This suggests to me that it is not some regression in mkdocs-material but that the difference lies in the pymdownx plugin or its dependencies. I will have a look to see if I can spot what the crucial difference is there and figure out if the intended behaviour changed there or whether it is a regression on their part.

**Comment by alexvoss** [comment] 2023-09-15 13:19
@facelessuser thanks, that is good to know. I will have a look - mainly to learn about the interactions between mkdocs, mkdocs-material, plugins and JS libraries / CSS used. I am a new contributor, so this is a useful exercise, methinks.

**Comment by alexvoss** [comment] 2023-09-15 13:48
Ok, I think I understand what is going on. There is a difference in `_highlight.scss` between the public version and the insiders version. Sorry, took me a little to figure out where to look. It seems trivial, so will make a pull request to see if squidfunk is happy to change it. This merely involves adding a `box-shadow` to the highlighted lines and changing the highlight color to be the same as shown in the documentation.

**Comment by alexvoss** [comment] 2023-09-15 16:06
Alright, pull request #6024 should fix this unwanted divergence between public and insider.

**Comment by mocdaniel** [comment] 2023-09-15 17:23
Wow, that was fast! Thanks for your efforts, let's wait for a merge ^^

**Comment by alexvoss** [comment] 2023-09-18 16:21
I managed to create a pull request but not actually request a review from squidfunk, which is now fixed.

**Comment by squidfunk** [comment] 2023-09-18 18:05
Fixed via #6024, thanks for @alexvoss!

**Comment by squidfunk** [comment] 2023-09-19 07:11
Released as part of [9.3.2](https://squidfunk.github.io/mkdocs-material/changelog/#9.3.2).

**Closed by squidfunk** 2023-09-19 07:11 UTC
Labels: bug, resolved

**Comment by bforbis** [comment] 2024-04-04 17:31
Hello, sorry to barge in here but could you take a look at the above linked ticket from backstage and tell me if this highlighting change is intentional, or do I have some sort of incompatibility? I have a large set of mkdocs documentation that was using these full line highlighting and they have now suddenly switched to only highlighting the side of the line with no background color once upgrading `mkdocs-material`. In my case I do not get the background color as [linked in the docs](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines)

**Comment by squidfunk** [comment] 2024-04-05 01:01
As highlighting works without problems on our side, the problem can be anywhere, as I understand that Backstage does heavy customization of Material for MkDocs. Thus, I recommend stripping down customizations on your side one-by-one to isolate the cause of this. In any case, it's a downstream customization. You may ask on our discussion board for help, but we don't consider this to be an issue on our side, as everything is working as expected.
