### ISSUE TITLE
Search index for gh_pages not updating

### ISSUE THREAD

**Issue by jicowan** [squidfunk/mkdocs-material#3861] opened 2022-04-29 16:45 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

I am hosting mkdocs/material theme on GitHub. The search index no longer is being updated. When I type a search in the search bar, it only returns results for old content. None of the new content appears in the search results. 

### Expected behaviour

I would expect the index to be update with each rebuild of the documentation. 

### Actual behaviour

No search results appear in the search bar results

### Steps to reproduce

1. Update content
2. Publish content
3. Search content

### Package versions

Using image squidfunk/mkdocs-material:8.2.6 to build docs

### Configuration

```yaml
site_name: EKS Best Practices Guides
repo_url: "https://github.com/aws/aws-eks-best-practices"
docs_dir: "content"
theme: 
  name: material
  icon: 
    repo: fontawesome/brands/github
  features: 
    - tabs
nav:
  - Guides: 
    - Introduction: 'index.md'
  ...
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
plugins: 
    - search
        indexing: 'full'
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
```

### System information

- Operating system: OSX
- Browser: Chrome

**Comment by squidfunk** [comment] 2022-04-29 17:06
Thanks for reporting. Could you please check if the contents of `search/search_index.json` are correct, i.e. your changes are reflected in the file? For example, the search index for Material for MkDocs is located [here](https://squidfunk.github.io/mkdocs-material/search/search_index.json).

**Comment by jicowan** [comment] 2022-04-29 18:46
Thanks @squidfunk. The `search_index.json` file appears to be populated with the updates. Here's a small snippet: 
```text
{"config":{"indexing":"full","lang":["en"],"min_search_length":3,"prebuild_index":false,"separator":"[\\s\\-]+"},"docs":[{"location":"","text":"Introduction \u00b6 Welcome to the EKS Best Practices Guides...
```
How do you force a full reload? I know, for example, that my document contains the text `ECR` and `images` but no results are returned when I search for these words. Is there a limit as to how many results mkdocs will return? Will it show no results if there are too many matches?

**Comment by squidfunk** [comment] 2022-04-29 20:24
Okay, thanks! You can force a full reload with CMD+SHIFT+R (or CTRL+SHIFT+R on Windows, I think).

> Is there a limit as to how many results mkdocs will return? Will it show no results if there are too many matches?

No limit, all results are returned. There's no such thing as "too many matches", all matches are always shown.

The web server serving the search index says "cache this for 10 minutes, then ask me again". Thus, the browser won't request the search index anew. This is actually a reasonable configuration. However, if you don't like it, you might change the caching headers of the webserver, but that's not possible for GitHub Pages. Thus, "fixing" this is beyond the scope of this project because we're only building a static site. You might contact GitHub and ask them whether this is intended behavior, but there's nothing we can do about it and I don't think GitHub will change anything because of reasonable defaults.

Closing.

**Closed by squidfunk** 2022-04-29 20:24 UTC
Labels: input needed

**Comment by franekp** [comment] 2023-01-24 12:24
> This is actually a reasonable configuration. However, if you don't like it, you might change the caching headers of the webserver, but that's not possible for GitHub Pages.

I'd say that it's a reasonable expectation that a static site will "just work" on default settings on most webservers.

At least I would add a big warning in the docs about "setting up site search" that you need to configure your webserver to serve the search index with appropriate cache-control, otherwise **some results will be missing from search**. For example, I am using `python -m http.server`, with even worse outcome of the **index never refreshing at all**.

> Thus, "fixing" this is beyond the scope of this project because we're only building a static site.
I'd say it's a big enough issue that it's worth fixing. It's a standard practice to append a content hash at the end of a filename to avoid browser and network caches serving stale content. And in case of search index, it's quite important that the content is up-to-date.

Also, fixing this at the level of cache-control has the additional downside of repeatedly downloading the index, even when nothing has changed. And it can be quite a few megabytes.

**Comment by squidfunk** [comment] 2023-01-24 12:58
Appending a content hash to the search index is likely to cause problems with third-party plugins that alter the search index, e.g. the [exclude search plugin](https://github.com/chrieke/mkdocs-exclude-search/blob/72eb003ac73d448d906a13facdfec938fb3d44d7/mkdocs_exclude_search/plugin.py#L213). Thus, we would need to implement a canonical way for the MkDocs ecosystem, not only for Material for MkDocs. I don't think this is doable with reasonable effort, given how simple a cache-header-based solution is.

**Comment by franekp** [comment] 2023-01-24 22:22
Thank you for fast response :)

Yes, I forgot that this is entangled with the rest of MkDocs. I think I have read somewhere that the search plugin has been remade from scratch for mkdocs-material, but that probably doesn't include the first stage that generates index.

**Comment by squidfunk** [comment] 2023-01-25 06:33
> I think I have read somewhere that the search plugin has been remade from scratch for mkdocs-material, and that gave me the wrong impression that this kind of change would be local to mkdocs-material.

Material for MkDocs ships a rewritten search plugin, yes, but it still strives to be compatible with all other third-party plugin that extend or alter search functionality.
