### ISSUE TITLE
material 5.x does not render Font Awesome icons in mermaid diagrams

### ISSUE THREAD

**Issue by snim2** [squidfunk/mkdocs-material#1698] opened 2020-05-15 11:08 UTC
## Description

Mermaid diagrams can be embedded in `mkdocs-material` sites, and can contain FA icons. This worked in v4.x of `mkdocs-material` but the icons do not appear when upgrading to v5.x.

### Expected behavior

Nice Font Awesome icons can appear in mermaid diagrams:

![mermaid-fa-working](https://user-images.githubusercontent.com/97674/82043413-754c6d00-96a3-11ea-9359-bb55d5fb7998.png)

### Actual behavior

Nice Font Awesome icons in mermaid diagrams disappear:

![mermaid-fa-broken](https://user-images.githubusercontent.com/97674/82043452-86957980-96a3-11ea-89ed-493edcba452a.png)

### Steps to reproduce the bug

1. Start with a `mkdocs-material` site using version 4.x of `material` that contains a mermaid diagram with Font Awesome icons.
2. Upgrade to version 5.x of `material`
3. Run `mkdocs serve` and notice that the icons in the diagram have vanished

### More information

Using Chrome Inspect, it looks like there is no network traffic with the fontawesome site when `mkdocs-material 5.x` is used. So, I suspect the problem here is maybe something to do with parsing the Markdown and using custom superfences. I appreciate that it's not feasible to make `material` work with every Javascript library that people might want to use, but I wonder whether there's an obvious workaround that I'm missing here?

### Package versions

Working versions:

* Python:  3.7
* MkDocs: 1.0.4
* Material: 4.4.0

Buggy versions:

* Python:  3.8
* MkDocs: 1.1.1
* Material: 5.1.6

Both using mermaid 8.5.0, which can be downloaded from here: [jsdelivr](https://www.jsdelivr.com/package/npm/mermaid).

### Project configuration

``` yaml
site_name: ''
theme:
    name: 'material'
extra_javascript:
    - 'assets/javascript/mermaid.min.js'
markdown_extensions:
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_div_format
nav:
    - Home: index.md
```

### Example test case

`docs/index.md`:

I don't think nested triple ticks are going to play well with GitHub Markdown, so I've turned \` into a single quote mark here:

```
'''mermaid
graph LR
    A["Search icon fa:fa-search"]
    B["List icon fa:fa-list-alt"]
    A --> B
'''
```

### System information

* OS: Ubuntu 20.04
* Browser: Chromium (from snap), also Firefox

**Comment by squidfunk** [comment] 2020-05-15 12:04
Duplicate of #1577

**Comment by snim2** [comment] 2020-05-15 12:47
I'm not sure that it's a duplicate. In the original project, I can use FA icons in ordinary text, but not in diagrams:

![screenshot-fa-mermaid](https://user-images.githubusercontent.com/97674/82051819-80f36000-96b2-11ea-962f-15ef20dfc44d.png)

and using the usual `material` syntax within the diagram does not work:

![fa-again](https://user-images.githubusercontent.com/97674/82051844-8e104f00-96b2-11ea-99bf-874b0f187fdc.png)

(apologies, I should have added this to the original report)

**Comment by facelessuser** [comment] 2020-05-15 12:49
Markdown content is not parsed in custom fences. Markdown syntax is not part of Mermaid syntax.

**Comment by snim2** [comment] 2020-05-15 12:51
Yes, that's clearly why the second example doesn't work, but I'm not sure about the first?

**Comment by squidfunk** [comment] 2020-05-15 12:57
You have to integrate the FontAwesome icon font yourself, that should do the trick.

**Comment by facelessuser** [comment] 2020-05-15 13:00
With that said, Mermaid support is achievable through custom fences as I do provide such examples in pymdown extension's documentation, but I do not actively provide custom solution support to users. It is up to the user to discover how to integrate their desired custom features on their own by reading the documentation of what they are trying to integrate ( in this case Mermaid documentation).

If there is a limitation that is imposed by pymdown extensions that frustrates integration, and you'd like to create an issue to discuss that, then I'm willing to do so, but in this case, you are trying parse Markdown content inside the Mermaid parser which is never going to happen. If Mermaid provides a way to include font icon content, you should include the font and utilize that method.

**Comment by squidfunk** [comment] 2020-05-16 11:05
I'm closing this, as it's either configuration related (include FontAwesome via extra JS) or a feature requests for pymdown extensions.

**Closed by squidfunk** 2020-05-16 11:05 UTC
