### ISSUE TITLE
Some (Material) Icons missing

### ISSUE THREAD

**Issue by PDDStudio** [squidfunk/mkdocs-material#1657] opened 2020-04-28 12:36 UTC
## Description

I tried changing my documentation's icon.  
I wanted to use the material icon for [`description`](https://material.io/resources/icons/?icon=description&style=baseline).

I've an old documentation which was written with mkdocs aswell, where this icon exists.

If I now try to change the icon and run the build, it will fail.

When browsing through the material icons in the `.icons` folder and comparing the names with the ones on the material site, I recognized that a few icons are named differently or don't exist at all. (`description` being one of these).

I'm not sure if this issue is only with Material Icons, or if this issue exists with Octicons/FontAwesome as well.

### Expected behavior

Build should succeed and icon should be visible.

### Actual behavior

Build fails because some icons are missing. (`description` being one of these)

### Steps to reproduce the bug

Change `theme.icon.logo` to `material/description`.

**Comment by PDDStudio** [comment] 2020-04-28 12:41
Copying the `description.svg` into my `.icons` folder would fix the build locally, but as I'm using CI it will fail there before deployment.  
I'm also not sure whether this is an issue related to this repo or to an external source, but I think you might be able to redirect it if its not.

**Comment by squidfunk** [comment] 2020-04-28 13:35
#1634

**Comment by PDDStudio** [comment] 2020-04-29 22:48
@squidfunk thanks for referencing. Is there already an issue created in the upstream repository? I couldn't find any links to open issues in that conversation.

**Comment by squidfunk** [comment] 2020-04-30 05:28
I’d not consider it an upstream issue, as we practically switched upstreams. It’s just that the upstream does not contain all the stick icons or contains them under a different name.

**Comment by squidfunk** [comment] 2020-04-30 07:15
Closing as duplicate of #1634.

**Closed by squidfunk** 2020-04-30 07:15 UTC
