### ISSUE TITLE
PHP Code Highlighting is inconsistent with a default installation

### ISSUE THREAD

**Issue by timgavin** [squidfunk/mkdocs-material#2022] opened 2020-10-31 21:05 UTC
- [X] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [X] ... the problem doesn't occur with the default MkDocs template
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

## Description

I've read the other issues relating to code highlighting but none have fixed this issue: PHP syntax highlighting is not consistent with a default installation.

Inline highlighting is also not colored as in the documentation with the python `range()` example.

### Expected behavior

I expect putting PHP code into blocks marked  ` ```php` would color it, plus inline highlighting should be colored.

### Actual behavior

The text is gray; it's only somewhat colored if adding `<?php ?>` tags. However, I shouldn't have to add `<?php ?>` tags to all of my code, as that will clutter up the docs and reduce readability, especially when I'm only describing variables and functions.

#### 1. Installed material theme

```
$ pip install mkdocs-material
Requirement already satisfied: mkdocs-material in /usr/local/lib/python3.8/site-packages (6.0.2)
Requirement already satisfied: markdown>=3.2 in /usr/local/lib/python3.8/site-packages (from mkdocs-material) (3.3)
Requirement already satisfied: mkdocs-material-extensions>=1.0 in /usr/local/lib/python3.8/site-packages (from mkdocs-material) (1.0.1)
Requirement already satisfied: pymdown-extensions>=7.0 in /usr/local/lib/python3.8/site-packages (from mkdocs-material) (8.0.1)
Requirement already satisfied: mkdocs>=1.1 in /usr/local/lib/python3.8/site-packages (from mkdocs-material) (1.1.2)
Requirement already satisfied: Pygments>=2.4 in /usr/local/lib/python3.8/site-packages (from mkdocs-material) (2.7.1)
Requirement already satisfied: tornado>=5.0 in /usr/local/lib/python3.8/site-packages (from mkdocs>=1.1->mkdocs-material) (6.0.4)
Requirement already satisfied: livereload>=2.5.1 in /usr/local/lib/python3.8/site-packages (from mkdocs>=1.1->mkdocs-material) (2.6.3)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.8/site-packages (from mkdocs>=1.1->mkdocs-material) (5.3.1)
Requirement already satisfied: click>=3.3 in /usr/local/lib/python3.8/site-packages (from mkdocs>=1.1->mkdocs-material) (7.1.2)
Requirement already satisfied: lunr[languages]==0.5.8 in /usr/local/lib/python3.8/site-packages (from mkdocs>=1.1->mkdocs-material) (0.5.8)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.8/site-packages (from mkdocs>=1.1->mkdocs-material) (2.11.2)
Requirement already satisfied: six in /usr/local/lib/python3.8/site-packages (from livereload>=2.5.1->mkdocs>=1.1->mkdocs-material) (1.15.0)
Requirement already satisfied: future>=0.16.0 in /usr/local/lib/python3.8/site-packages (from lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material) (0.18.2)
Requirement already satisfied: nltk>=3.2.5; python_version > "2.7" and extra == "languages" in /usr/local/lib/python3.8/site-packages (from lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material) (3.5)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/site-packages (from Jinja2>=2.10.1->mkdocs>=1.1->mkdocs-material) (1.1.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/site-packages (from nltk>=3.2.5; python_version > "2.7" and extra == "languages"->lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material) (4.50.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/site-packages (from nltk>=3.2.5; python_version > "2.7" and extra == "languages"->lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material) (0.17.0)
Requirement already satisfied: regex in /usr/local/lib/python3.8/site-packages (from nltk>=3.2.5; python_version > "2.7" and extra == "languages"->lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material) (2020.10.11)
```

#### 2. Created directory

```
tim: $ mkdir mkdocs-material
tim: $ cd mkdocs-material/
tim: $ mkdocs new .
INFO    -  Writing config file: ./mkdocs.yml 
INFO    -  Writing initial docs: ./docs/index.md 
```

#### 3. Added theme and extensions to mkdocs.yaml

```
site_name: My Docs

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
```

#### 4. Edited index.md (indented for readability)

```
    # Welcome to MkDocs

    ```php
    $var = 'foobar';
    ```

    ```php
    <?php $var = 'foobar'; ?>
    ```

    I have `#!php $foo` foo.

    I have `#!php <?=$foo?>` foo.

    ```html
    <html>
	<head></head>
    </html>
    ```
```

#### 5. Result

<img width="412" alt="Screen Shot 2020-10-31 at 1 41 32 PM" src="https://user-images.githubusercontent.com/1012049/97789818-c7654a00-1b80-11eb-8480-3669f568eb72.png">



### Package versions

<!-- Please provide all package versions -->

* Python: `3.8.6`
* MkDocs: `1.1.2`
* Material: `6.0.2`

### Project configuration

``` yaml
site_name: My Docs

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
```

### System information

* OS: macOS Catalina 10.15.7
* Browser: Safari 14.0

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment] 2020-10-31 21:59
Please see https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#extended-pygments-lexer-options

**Comment by squidfunk** [comment] 2020-11-01 09:59
Closing as an exact duplicate of #1417, #506, and #1381. It's a configuration issue of the Highlight extension after all.

> I've read the other issues relating to code highlighting but none have fixed this issue: PHP syntax highlighting is not consistent with a default installation.

I don't know what you mean by _default installation_, but you're probably referring to that the behavior you desire doesn't work out-of-the-box. While that may be correct, it can easily be configured through the [Highlight extension]( https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#extended-pygments-lexer-options) as I also noted in my last comment.

The Material theme cannot provide defaults for Markdown extensions, it's just not technically possible. For this reason, we can only list reasonable defaults in our very own documentation, referring to the extension's documentation for further consulting.

**Closed by squidfunk** 2020-11-01 09:59 UTC
