### ISSUE TITLE
Seperate logic for the tabs link

### ISSUE THREAD

**Issue by krahets** [squidfunk/mkdocs-material#4756] opened 2022-12-13 17:42 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

It is really helpful to enable tabs link which makes it easier to switch code blocks of different languages.

```
theme:
  features:
    - content.tabs.link
```

However, I'm wondering enable `tabs link` for some tabs (like code blocks).

```
=== "Java"
    ...

=== "C++"
    ...
```

And disable `tabs link` for other tabs (like slides consisting of multiple images).

```
=== "Step 1"
    [figures1.png](...)

=== "Step 2"
    [figures2.png](...)
```

Is there any way to implement this feature? Thanks!

### Use Cases

I'm wondering enable `tabs link` for some tabs (like code blocks), and disable `tabs link` for other tabs (like slides consisting of multiple images).

**Comment by squidfunk** [comment] 2022-12-13 17:49
Duplicate of #4175.

**Closed by squidfunk** 2022-12-13 17:49 UTC
