### ISSUE TITLE
Update Spanish translations

### ISSUE THREAD

**Issue by aitor-medrano** [squidfunk/mkdocs-material#4939] opened 2023-01-29 10:19 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### Language availability

- [X] I've checked the [list of available languages](https://bit.ly/33vFDD0)

### Translations

```Jinja
{% macro t(key) %}{{ {
  "language": "es",
  "action.edit": "Editar esta página",
  "action.skip": "Saltar a contenido",
  "action.view": "Ver el código fuente de esta página",
  "announce.dismiss": "No volver a mostrar",
  "blog.archive": "Archivo",
  "blog.categories": "Categorías",
  "blog.categories.in": "en",
  "blog.continue": "Continuar leyendo",
  "blog.draft": "Borrador",
  "blog.index": "Volver al índice",
  "blog.meta": "Metadatos",
  "blog.references": "Enlaces relacionados",
  "clipboard.copy": "Copiar al portapapeles",
  "clipboard.copied": "Copiado al portapapeles",
  "consent.accept": "Aceptar",
  "consent.manage": "Gestionar cookies",
  "consent.reject": "Rechazar",
  "footer": "Pie",
  "footer.next": "Siguiente",
  "footer.previous": "Anterior",
  "header": "Cabecera",
  "meta.comments": "Comentarios",
  "meta.source": "Fuente",
  "nav": "Navegación",
  "readtime.one": "1 minutos de lectura",
  "readtime.other": "# minutos de lectura",
  "rss.created": "archivo RSS",
  "rss.updated": "archivo RSS de contenido actualizado",
  "search": "Buscar",
  "search.placeholder": "Búsqueda",
  "search.share": "Compartir",
  "search.reset": "Limpiar",
  "search.result.initializer": "Inicializando búsqueda",
  "search.result.placeholder": "Teclee para comenzar búsqueda",
  "search.result.none": "No se encontraron documentos",
  "search.result.one": "1 documento encontrado",
  "search.result.other": "# documentos encontrados",
  "search.result.more.one": "1 más en esta página",
  "search.result.more.other": "# más en esta página",
  "search.result.term.missing": "Falta",
  "select.language": "Seleccionar idioma",
  "select.version": "Seleccionar versión",
  "source": "Ir al repositorio",
  "source.file.contributors": "Colaboradores",
  "source.file.date.created": "Creado",
  "source.file.date.updated": "Última actualización",
  "tabs": "Pestañas",
  "toc": "Tabla de contenidos",
  "top": "Volver al principio"
}[key] }}{% endmacro %}
```

**Comment by squidfunk** [comment] 2023-01-29 11:05
Many thanks! Duplicate of #4932 – @lazarusA already updated them, and this all happened overnight for us which is why I haven't updated them yet 😉

**Closed by squidfunk** 2023-01-29 11:05 UTC
