### ISSUE TITLE
Unable to build `9.5.3-insiders-4.49.1` with `tags` plugin on Netlify (Python 3.8)

### ISSUE THREAD

**Issue by shepherdjerred** [squidfunk/mkdocs-material#6627] opened 2024-01-08 22:21 UTC
### Bug description

`9.5.3-insiders-4.49.1` with the `tags` plugin does not build on Python 3.8:

```
$ pipenv install
Creating a virtualenv for this project...
Pipfile: /Users/jerred/git/posit/docs.rstudio.com/Pipfile
Using /Users/jerred/.local/share/mise/installs/python/3.8/bin/python3.8 (3.8.18) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.8.18.final.0-64 in 551ms
  creator CPython3Posix(dest=/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/jerred/Library/Application Support/virtualenv)
    added seed packages: pip==23.2.1, setuptools==68.1.2, wheel==0.41.2
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F
Installing dependencies from Pipfile.lock (922421)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

$ pipenv run mkdocs build
Traceback (most recent call last):
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/__main__.py", line 283, in build_command
    cfg = config.load_config(**kwargs)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/base.py", line 378, in load_config
    errors, warnings = cfg.validate()
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/base.py", line 230, in validate
    run_failed, run_warnings = self._validate()
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 182, in validate
    return self.run_validation(value)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1064, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1102, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1120, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 184, in load
    module = import_module(match.group('module'))
  File "/Users/jerred/.local/share/mise/installs/python/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/material/plugins/tags/plugin.py", line 28, in <module>
    from material.utilities.filter import PageFilter
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/material/utilities/filter/__init__.py", line 32, in <module>
    class Filter:
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/material/utilities/filter/__init__.py", line 51, in Filter
    def __call__(self, value: str, ref: str | None = None) -> bool:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType
```

[Union types](https://peps.python.org/pep-0604/) were added in Python 3.10, but Netlify only supports Python 3.8. Netlify [does not plan to support newer versions](https://answers.netlify.com/t/how-to-use-python-3-10/51685/10).

### Related links

- https://github.com/tiangolo/typer/issues/371
- https://answers.netlify.com/t/how-to-use-python-3-10/51685/10
- https://peps.python.org/pep-0604/

### Reproduction

[mkdocs.zip](https://github.com/squidfunk/mkdocs-material/files/13866764/mkdocs.zip)

### Steps to reproduce

1. Install Python 3.8
2. Create a project using `9.5.3-insiders-4.49.1`
3. Enable the `tags` plugin
4. Run `mkdocs build`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by evan-flynn-apexai** [comment] 2024-01-09 00:12
fyi @shepherdjerred the last insiders tag before this breaking change was `9.5.2-insiders-4.47.1` :+1:

**Comment by squidfunk** [comment] 2024-01-09 01:52
Thanks for reporting! We're definitely interested in supporting Python 3.8, so this is an oversight on our side. It should be fixed with [`691849d`](https://github.com/squidfunk/mkdocs-material-insiders/commit/691849d60eabbf71684e8fabf06b82f815e1dc77). Note that we're also working on setting up a proper testing environment right now, so that we catch problems like this earlier, but it is still a way to go. We hope to finish it before 3.8 EOL 😅

I'm quite amazed to read that Netlify isn't doing anything to support newer Python versions. Are there maybe alternative platforms that could be used?

**Comment by shepherdjerred** [comment] 2024-01-09 03:09
Thanks for such a quick fix!

> Are there maybe alternative platforms that could be used?

It's pretty embarrassing that Netlify hasn't updated their supported Python versions. We only use Netlify for deploy previews since it's so convenient and already setup. I'm sure there are alternatives, but we just haven't prioritized it.

**Comment by shepherdjerred** [comment] 2024-01-09 03:39
I tried with the latest commit on master (https://github.com/squidfunk/mkdocs-material-insiders/commit/8721121c2ce4151d86fe868d5f8c9ca7257b9708)

I now see this error:

```
$ pipenv run mkdocs build
Traceback (most recent call last):
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/__main__.py", line 283, in build_command
    cfg = config.load_config(**kwargs)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/base.py", line 378, in load_config
    errors, warnings = cfg.validate()
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/base.py", line 230, in validate
    run_failed, run_warnings = self._validate()
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 182, in validate
    return self.run_validation(value)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1064, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1102, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1120, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 184, in load
    module = import_module(match.group('module'))
  File "/Users/jerred/.local/share/mise/installs/python/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/material/plugins/tags/plugin.py", line 35, in <module>
    from .config import TagsConfig
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/material/plugins/tags/config.py", line 30, in <module>
    from .structure.listing import ListingConfig
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/material/plugins/tags/structure/listing/__init__.py", line 30, in <module>
    from .config import ListingConfig
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/material/plugins/tags/structure/listing/config.py", line 23, in <module>
    from material.plugins.tags.structure.tag.options import TagSet
  File "/Users/jerred/.local/share/virtualenvs/docs.rstudio.com-TOJwUm7F/lib/python3.8/site-packages/material/plugins/tags/structure/tag/options.py", line 32, in <module>
    class TagSet(BaseConfigOption[set[Tag]]):
TypeError: 'type' object is not subscriptable
```

**Comment by squidfunk** [comment] 2024-01-09 10:25
Fixed in [`210aedf`](https://github.com/squidfunk/mkdocs-material-insiders/commit/210aedfb61aaf884c390a6a6f3e15559c312fe9e). I'm so much looking forward to 3.8 EOL 😅

**Comment by normandy7** [comment] 2024-01-09 10:29
> Fixed in [`210aedf`](https://github.com/squidfunk/mkdocs-material-insiders/commit/210aedfb61aaf884c390a6a6f3e15559c312fe9e). I'm so much looking forward to 3.8 EOL 😅

Any idea when we can expect a release? 🙂

**Comment by squidfunk** [comment] 2024-01-09 10:31
As soon as we know that all issues are fixed. My testing shows that the latest commit fixes all issues with Python 3.8. If you can confirm that I can push out a release in 15min.

**Comment by squidfunk** [comment] 2024-01-09 10:43
Okay, I went ahead and released the changes because I'm quite confident that this should be fixed. Sorry for the inconvenience, but I'm happy that we could resolve it in half a day. Released as part of [9.5.3+insiders-4.49.2](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.49.2).

**Closed by squidfunk** 2024-01-09 10:43 UTC
Labels: bug, resolved

**Comment by normandy7** [comment] 2024-01-09 10:49
I can confirm that our build (also on Python 3.8) no longer fails when installing from the commit you mentioned. Thanks!

**Comment by shepherdjerred** [comment] 2024-01-09 20:41
That worked for me. Thanks again for fixing this so quickly.
