### ISSUE TITLE
Tabbed content alignment

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#1502] opened 2020-03-11 02:10 UTC
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

When last we discussed the formatting of tabs, it was mentioned that we no longer expand in mobile. But what it actually seems like is that we are now always expanded with no kind of padding for the content. This is from the official deployment preview of 5.0.0rc1.

![chrome_ncDCdbbq69](https://user-images.githubusercontent.com/1055125/76374853-ef5e1f80-6309-11ea-98a7-fc83382bcba8.png)

Ignoring the overflow issue, we see that content is completely unpadded.

I was under the impression that the content was aligned with admonition content. What I think we were supposed to get was something more like this where paragraphs and everything is padding like admonitions. Only child code blocks would simply expand.

![chrome_J3CSuPbO6j](https://user-images.githubusercontent.com/1055125/76375065-84611880-630a-11ea-8ea9-87e7afb2a9fc.png)

Maybe this was not the intention? This is what I thought we were getting at least, and personally what I'd like to request. At the very least there should be some tweaks as the table in the first issue is cut off some (shadow rendered off screen and the overflow scrollbar.

### Expected behavior

Tabbed content should be slightly padding like admonitions and details etc. Single code blocks should fill the tab. At the very least overflow and a slight padding should be provided to avoid clipping of container shadows.

### Actual behavior

See above.

### Package versions

* Python: Any
* MkDocs: Any
* Material: 5.0.0rc1

### System information

* OS:  Any
* Browser: Any

**Comment by facelessuser** [comment] 2020-03-11 06:08
Note: if content does get padding and code gets stretched (if only child) remember to update `.hll` width. I just spent too long playing with that in a pull. Every time code padding changes, `.hll` padding should be updated as well.

**Comment by squidfunk** [comment] 2020-03-11 09:21
I can't reproduce the spacing that is off on the code containers. On the [official docs](https://deploy-preview-1486--mkdocs-material-preview.netlify.com/getting-started/#with-docker-recommended) it looks like this in Chrome:

Desktop:

<img width="734" alt="Bildschirmfoto 2020-03-11 um 10 18 22" src="https://user-images.githubusercontent.com/932156/76401098-a8ac0c00-6381-11ea-988c-07981412504e.png">

Mobile:

<img width="488" alt="Bildschirmfoto 2020-03-11 um 10 19 09" src="https://user-images.githubusercontent.com/932156/76401168-c6797100-6381-11ea-89fb-c79106662c71.png">

In https://github.com/squidfunk/mkdocs-material/pull/1497#issuecomment-597103766 I discussed that I'd see tabs as a measure for alternate regular content, and not as a callout like details or admonition. Callouts have smaller text sizes, which the tabs didn't have from the beginning. For this reason they are aligned like regular content which makes it impossible to stretch them on mobile, as now we have code tabs and regular tabs, and stretching would only be applicable to code tabs.

**Comment by squidfunk** [comment] 2020-03-11 09:22
However, the overflow issue is interesting. I'll try to reproduce it.

**Comment by squidfunk** [comment] 2020-03-11 09:40
I think removing the `overflow: auto` on tabbed content (and giving it `visible` essentially) will resolve the issue. `overflow: auto` induces margin collapse which will break the spacing of the scroll wrapping, but letting the margins collapse will result in a scrollable table on overflow, just as with normal tables.

**Comment by squidfunk** [comment] 2020-03-11 09:58
The `overflow` issue [should be fixed](https://deploy-preview-1486--mkdocs-material-preview.netlify.com/extensions/pymdown/#tabbed) as of 4d386df1

**Comment by facelessuser** [comment] 2020-03-11 11:39
Ah, I misunderstood the intention then. Thanks for the fix.

**Comment by facelessuser** [comment] 2020-03-11 12:51
I guess it works fine unless you nest the tabs.

![chrome_0LLO1l5L0A](https://user-images.githubusercontent.com/1055125/76417949-6a9fef80-6363-11ea-8e9b-b8ea7db7e886.png)

You might consider this an edge case though. I'm thinking locally I'm going to allow this, so I'll probably use `overflow: hidden`. It'll still clip shadows a bit.

----

I realize that I'm going in a different direction, and I've accepted that, so I'm thinking of treating them locally as containers and will probably reduce the text and add padding like admonitions.

I'm using them in places like here's a tab with source, and here is one with results, and in this case, I'd like to use the same construct, even when using tabs, and even if I wouldn't normally want to nest tabs, in this case it makes sense:

![chrome_LvMJcltfs1](https://user-images.githubusercontent.com/1055125/76418659-9e2f4980-6364-11ea-85ea-e600bb767190.png)

For me, though I understand where you are coming from, I have a hard time being so rigid.

**Comment by squidfunk** [comment] 2020-03-11 13:38
What you're observing is more related to scroll wrapping inside nested content again. Might be fixable, though.

**Comment by facelessuser** [comment] 2020-03-11 13:41
I still have much to learn :slightly_smiling_face:.

**Comment by squidfunk** [comment] 2020-03-11 13:42
We can improve a lot on the situation if we replace a lot of the spacing under `.md-typeset` with `em`s instead of `rem`s.

**Comment by squidfunk** [comment] 2020-03-11 13:55
Try 447d409b.

**Comment by facelessuser** [comment] 2020-03-11 20:04
Works for me, and I'm able to adjust tabs to fit my needs without issues, so :+1: .

**Comment by squidfunk** [comment] 2020-03-12 16:38
Just released RC 2. Please re-open if the issue persists.

**Closed by squidfunk** 2020-03-12 16:38 UTC
Labels: bug
