### ISSUE TITLE
Code block line numbers are behaving weird when saving document to PDF with Edge "Save as PDF"

### ISSUE THREAD

**Issue by r3m0s** [squidfunk/mkdocs-material#5457] opened 2023-05-01 16:01 UTC
### Context

When I save a document to PDF the line numbers of code-blocks that are too wide for A4-Pages start to mismatch. The lines of the code block are wrapped correctly, but the line-numbers no longer match because of the wrapping at the end of the block. Here an Example:

![image](https://user-images.githubusercontent.com/61869080/235481905-104cb4e2-ae88-41da-b8f6-2a2979baa84b.png)

Expected behavior would be that wrapped lines do not get a number.

### Bug description

I know it is not a super urgent and important feature, but I frequently print/save specific sites to PDF to share a document with others. Is this problem with the code lines directly related to material or is it an extension that has to be adjusted? Anyone has some further insight in this?

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code+blo#__codelineno-4-2

### Reproduction

![Screenshot 2023-05-01 175159](https://user-images.githubusercontent.com/61869080/235483119-cac7fbd3-6fc9-44e5-b4c4-3b96c4654fa1.png)

### Steps to reproduce

1. Create code block with long lines
2. Save Page as PDF from Edge browser
3. Code block lines inside PDF file are wrapped, but line numbers do not match

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [ ] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by katharinalisalin** [comment] 2023-05-02 06:13
Thanks for reporting.
To help us investigate and address the problem, please follow our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/) and create a **minimal reproduction .zip** with the assistance of our [reproduction guide](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). Using our [info plugin](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file), described in our reproduction guide, to create your reproduction .zip will help you rule out that your issue is caused by any customizations or other plugins, and it helps us look into your issue faster.
Unfortunately, as you have not provided a reproduction at this time, we are unable to investigate further. As a result, we will mark this issue as [incomplete](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#incomplete-issues) and close it for now. However, please feel free to reopen the issue once you have provided a reproduction .zip, and we will be happy to assist you further. Thank you.

**Closed by katharinalisalin** 2023-05-02 06:13 UTC
