### ISSUE TITLE
Announcement bar appears & disappears on page load

### ISSUE THREAD

**Issue by bradumbaugh** [squidfunk/mkdocs-material#3615] opened 2022-02-23 01:50 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
   
   (I didn't test this configuration, since I'm seeing it on the published docs for the theme)

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

This came up in Gitter recently, and I said I'd report it if I saw it again, so here we are :)

The announcement bar is flickering (appearing and disappearing) each time I the page loads. Seeing this on the live site for the Material for MkDocs theme: https://squidfunk.github.io/mkdocs-material

https://user-images.githubusercontent.com/6285/155249241-e98b5cf3-1b8e-41ba-8d5b-3fe864ce25ab.mov

### Expected behaviour

Announcement bar stays hidden on page load

### Actual behaviour

Each page load, announcement bar appears and disappears

### Steps to reproduce

Visit https://squidfunk.github.io/mkdocs-material and observe the behavior 

(I suspect maybe it won't show up for everyone, but that's how I'm seeing it!)

### Package versions

n/a — live site as published

### Configuration

```yaml
n/a — live site as published
```

### System information

- Safari 15.2
- macOS 12.1

**Comment by squidfunk** [comment] 2022-02-23 07:45
Thanks for reporting. Does it happen in Incognito mode? It doesn't for me, so it looked like it's related to some extension. Furthermore, after I cleared session storage and local storage, the problem is gone.

**Comment by caseyamp** [comment] 2022-02-24 20:52
This was happening to me and I had to remove `announce.dismiss` from features in mkdocs.yml. It hasn't happened since I disabled the feature.

**Comment by squidfunk** [comment] 2022-02-24 21:29
@caseyamp thanks for reporting. That's expected, because without this feature the announcement bar will always be visible. I'm still trying to find the root cause, but I suspect it's a browser extension, as the problem went away for me in Incognito mode and after I cleared the browser cache. If not, I'm very interested in fixing it, but I need a reproduction.

Can you verify whether the issue persists in Incognito mode or when you clear local/sessions storage?

**Comment by caseyamp** [comment] 2022-02-24 22:46
@squidfunk -- I just re-enabled the feature, added an announcement, then tested:
 - It doesn't happen in Chrome Incognito mode. 
 - It does happen when I clear the cache in Chrome. 
 - It doesn't happen in Safari

**Comment by squidfunk** [comment] 2022-02-24 23:42
Thanks! Then I'm pretty sure it's a browser extension that is causing this. I haven't isolated the one that does, though.

**Comment by caseyamp** [comment] 2022-02-24 23:48
@squidfunk the only ones I have are LastPass, Okta, and Zoom Scheduler. I can't disable them because it's a company-managed account. I hope that helps narrow it down.

**Comment by squidfunk** [comment] 2022-02-25 08:57
Thanks. I don't have any of those extensions installed, weird. Maybe it's Chrome, I don't know. It's certainly nothing that we can fix, as it's only happening on Chrome, so I'm currently considering this not reproducible.

@caseyamp did you clear local and session storage or the browser cache? Those are two different things, make sure to clear both storages: https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/

@bradumbaugh did you have a chance to test out the things I've listed in https://github.com/squidfunk/mkdocs-material/issues/3615#issuecomment-1048518282?

**Comment by bradumbaugh** [comment] 2022-02-28 17:17
@squidfunk Terribly sorry for the slow response here, have had a busy few days. A couple of things:

- Just to make sure we're on the same page, I'm seeing this issue in Safari, not Chrome
- It doesn't seem to happen in a private browser window

From my perspective, since we can't repro this reliably, feel free to close this issue. I'll keep poking at it and see if I can come up with a more reliable approach to make it happen.

**Comment by squidfunk** [comment] 2022-02-28 18:02
@bradumbaugh thanks! I'm not able to reproduce it in Safari either. I'd say we close it until reproducible.

**Closed by squidfunk** 2022-02-28 18:02 UTC
Labels: not reproducible
