### ISSUE TITLE
Footer overlaps with vertical navigation sections on small screens

### ISSUE THREAD

**Issue by odysseu** [squidfunk/mkdocs-material#6118] opened 2023-10-02 09:22 UTC
### Context

I saw this bug on a gitlab-pages I built with your (great) tool; and actually could reproduce it to your site 🥲

### Bug description

Hi, similar to the issue regarding blog and footer overlap (https://github.com/squidfunk/mkdocs-material/issues/6094),
| comment | screenshot |
| --- | --- |
| the vertical [navigation sections](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections) on the left-side of the site overlaps with the footer. | ![image](https://github.com/squidfunk/mkdocs-material/assets/55583423/1f7f62de-06a8-47e7-9177-18fb4f0ccced) |

### Related links

- [Official site's page where bug can be seen](https://squidfunk.github.io/mkdocs-material/reference/)
- [Similar issue where blog and footer overlab](https://github.com/squidfunk/mkdocs-material/issues/6094)

### Reproduction

no need for zip as it appears on the official site

### Steps to reproduce

0 - got to official doc
1 - Reduce the browser's viewport width to less than 1220px
2 - Scroll to the footer section

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-10-02 09:30
Thanks for reporting. Please, please, please respect our work and time and __always__ stick to our [bug reporting](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) process, which clearly states that [__we need a reproduction__](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#reproduction). We're helping our users __for free__ and this mandates that you always stick to what is asked for. Why? Because I have no idea under what circumstance this problem occurs without more data:

![screenshot-squidfunk-github-io-mkdocs-material-reference-1696238771481](https://github.com/squidfunk/mkdocs-material/assets/932156/67d87d28-d214-41e5-b5f6-32033caf0f6b)

To be clear, below 1220px the sidebar is hidden, so we have no idea why this is triggered. We're missing important information, i.e., browser, zoom level, etc. Closing as not reproducible.

**Closed by squidfunk** 2023-10-02 09:30 UTC

**Comment by odysseu** [comment] 2023-10-03 07:26
Right, apologies for the missing reproducibility.

More context:

- firefox 115.2.1esr (64 bits)
- zoom at which it is not ok : 120 % and 133% only.
- screen size is 1366 x 768 pixels

| screenshot 120% | screenshot 133% |
| --- | --- |
| ![image](https://github.com/squidfunk/mkdocs-material/assets/55583423/3add73db-e3cb-49ff-bbeb-630e4363bded) | ![image](https://github.com/squidfunk/mkdocs-material/assets/55583423/f535066e-8075-454d-a95f-192484f5794e) |

Here is the .zip of the site: [mkdocs-material-9.4.3.zip](https://github.com/squidfunk/mkdocs-material/files/12789690/mkdocs-material-9.4.3.zip)

**Comment by squidfunk** [comment] 2023-10-03 08:43
Okay, so regardless of the fact that I'm not happy when users don't follow our bug reporting guidelines, as it necessitates more of our time that we could otherwise invest into actually fixing bugs and creating new useful features, I just had an idea: why not try subpixel values to bring the min- and max-width breakpoints together? I've tested at various zoom levels and it seems to do the trick. Thus, potential fix in 442bd1b07.
