### ISSUE TITLE
cyclic dependency with mkdocs-material-extensions

### ISSUE THREAD

**Issue by cbpr** [squidfunk/mkdocs-material#1866] opened 2020-08-12 10:56 UTC
There is a cyclic dependency in the requirements of packages `mkdocs-material` and `mkdocs-material-extensions`.

I mean `pipdeptree -p mkdocs-material` should not complain about this:
```
------------------------------------------------------------------------
Warning!! Cyclic dependencies found:
* mkdocs-material => mkdocs-material-extensions => mkdocs-material
* mkdocs-material-extensions => mkdocs-material => mkdocs-material-extensions
------------------------------------------------------------------------

```

### Package versions
At least I see this with
* Python: `python --version` 3.8.2
* MkDocs: `mkdocs --version` 1.1.2
* Material: `pip show mkdocs-material | grep -E ^Version` 5.5.3

### System information
Seen in both Ubuntu 20.04 and Windows 10.

**Comment by squidfunk** [comment] 2020-08-12 11:05
Duplicate of #1674

**Closed** 2020-08-12 11:05 UTC
