### ISSUE TITLE
Header Tabs not visible when browser window size is reduced

### ISSUE THREAD

**Issue by unclsams** [squidfunk/mkdocs-material#3278] opened 2021-11-30 21:11 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I realized this only after I recvd a complaint from an user - Either using Firefox or Chrome when the browser size is reduced none of the tabs in the header are visible. User gets no clue that there exist some tabs...unless the browser window is resized.
I observed the same issue in mobile devices too - but this isnt a concern for my target users.

### Expected behaviour

Make all tabs visible in the header even when window size is reduced

### Actual behaviour

Either using Firefox or Chrome when the browser size is reduced none of the tabs in the header are visible.

### Steps to reproduce

reduce browser window size

### Package versions

- Python: `python --version`     : 3.7
- MkDocs: `mkdocs --version`: from Sep 2021

### Configuration

```yaml
Internal SITE
```

### System information

- Operating system: ...Linux
- Browser: ...Firefox & Chrome

**Comment by squidfunk** [comment] 2021-11-30 21:23
Thanks for reporting. The navigation tabs are only shown a long as the menu is not collapsed into the drawer (hamburger menu), which is any screen size above `1220px`. This is intended behavior and has been like that since tabs were first introduced in version 1.1.0.

Closing, as it’s working as intended.

**Closed by squidfunk** 2021-11-30 21:23 UTC
