### ISSUE TITLE
URL with anchors does not work properly

### ISSUE THREAD

**Issue by aborruso** [squidfunk/mkdocs-material#3289] opened 2021-12-02 12:23 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have in [this page](https://ondata.github.io/guidaVisiData/configurazione/#importare-un-modulo-python) the below hyperlink.

The URL is `https://ondata.github.io/guidaVisiData/lavorareRighe/#filtri-tramite-espressione-python-basata-su-piu-colonne`

![image](https://user-images.githubusercontent.com/30607/144420482-b9c6c30d-037e-40d5-a3fe-19c5a4843e4e.png)

If I click on it, starting from [here](https://ondata.github.io/guidaVisiData/configurazione/#importare-un-modulo-python) the pages does not scroll to that anchor.

If I open directly it, it works and [the page scrolls properly](https://ondata.github.io/guidaVisiData/lavorareRighe/#filtri-tramite-espressione-python-basata-su-piu-colonne).

### Expected behaviour

To have the right page scrolling

### Actual behaviour

It opens the page at its start

### Steps to reproduce

I have written in the description

### Package versions

- Python: `python --version`

Python 3.9.2

- MkDocs: `mkdocs --version`

mkdocs, version 1.2.3

- Material: `pip show mkdocs-material | grep -E ^Version`

Local Version: 8.0.0, but online Version: 8.0.2

### Configuration

```yaml
This one https://github.com/ondata/guidaVisiData/blob/master/mkdocs.yml
```

### System information

Win 10
The last chrome

**Comment by squidfunk** [comment] 2021-12-02 12:48
Thanks for reporting. Please provide a minimal reproducible example in Markdown which I can use for debugging.

**Comment by squidfunk** [comment] 2021-12-02 12:49
Or wait, you're using instant loading, which means that this is a duplicate of #3274. Closing as duplicate.

**Closed by squidfunk** 2021-12-02 12:49 UTC

**Comment by aborruso** [comment] 2021-12-02 13:00
Now it works, thank you
