### ISSUE TITLE
Text shift if print page with collapsible blocks

### ISSUE THREAD

**Issue by mitpro** [squidfunk/mkdocs-material#2549] opened 2021-04-12 08:51 UTC
Hi

## Description

after updating to mkdocs-material 7 my pdf export (Chrome pdf-print) went wrong.
Pages with collapsible blocks `??? note` or `???+ note` got a whitespace on first page. 

![2021-04-12 10_39_09-with collapsible blocks - ZNK Dokumentation](https://user-images.githubusercontent.com/12111420/114366621-e8908480-9b7b-11eb-987d-dde268182e49.png)

First line is the Heading:

```` md
# with collapsible blocks 
....
??? note "Issue"
    ....
````

### Expected behavior

No Whitespaces on first page.

Replacing the block with non-collapsible block `!!! note` solves this issue.

![2021-04-12 10_41_20-without collapsible blocks - ZNK Dokumentation](https://user-images.githubusercontent.com/12111420/114366672-f2b28300-9b7b-11eb-9632-eda670410585.png)

```` md
# without collapsible blocks 
....
!!! note "Issue"
    ....
````

### Package versions

Python     3.8.0
mkdocs     1.1.2
mkdocs-material     7.1.1
mkdocs-material-extensions     1.0.1

### Project configuration

``` yaml
site_name: Documentation

use_directory_urls: false

theme:
  name: material 
  font: false
  language: de
  #favicon: assets/images/favicon.png
  favicon: assets/logo/e92063.ico
  logo: assets/logo/white.ico
  custom_dir: theme
  palette:
    # Light mode
    - blue: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.top

markdown_extensions:
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - footnotes
  - abbr
  - toc:
      toc_depth : "1-4"
      permalink: true

plugins:
  - search:
        min_search_length: 2
        lang: de
        separator: '[\s\-\.]+'
  - localsearch
  - table-reader
  - macros:
      include_dir: include
  - progress

repo_url: xxxx
edit_uri: xxxx
```

### System information

OS: Windows 10 x64 1909
Browser: Chrome 87.0.4280.88

**Comment by squidfunk** [comment] 2021-04-15 19:37
I'm sorry, but I'm having a hard time reproducing this. Please provide some Markdown that reproduces this problem, so we can fix it. It could be related to `page-break-inside: avoid` which is defined for Admonitions, so they don't wrap around pages, but we need to verify this first.

**Comment by mitpro** [comment] 2021-04-16 13:23
Try to detect the only reason and found out: it is related to big pictures at sites end:

```` markdown
# TEST

test123123

## kapitel yy

Text1

??? note "E-Mail"

    text123

## kapitel xx

Text2

1. erstens
2. zweitens
   


![bild](./res/text-test.svg)
````

## without picture 

to compare without the picture:

```` markdown "diff"
- ![bild](./res/text-test.svg)
+ [bild](./res/text-test.svg)
````

Output:

![2021-04-16 15_08_52-TEST - ZNK Dokumentation](https://user-images.githubusercontent.com/12111420/115029437-426bb400-9ec6-11eb-8e7f-68682c3c9d4a.png)

## with picture at the end

![2021-04-16 15_08_18-TEST - ZNK Dokumentation](https://user-images.githubusercontent.com/12111420/115029767-9aa2b600-9ec6-11eb-81bd-b2246677d098.png)

## with non collapse

```` markdown
+ ??? note "E-Mail"
- !!! note "E-Mail"
````

![2021-04-16 15_18_12-TEST - ZNK Dokumentation](https://user-images.githubusercontent.com/12111420/115030110-06851e80-9ec7-11eb-9a23-6e3370eaf020.png)

**Comment by squidfunk** [comment] 2021-04-18 09:02
Thanks, the following Markdown reproduces the problem on macOS, Chrome:

``` markdown
# TEST

test123123

## kapitel yy

Text1

??? note "E-Mail"

    text123

## kapitel xx

Text2

1. erstens
2. zweitens
   
![bild](https://picsum.photos/400/600)

```

**Comment by squidfunk** [comment] 2021-04-18 09:14
I believe that this is a rendering issue with Chrome that cannot be fixed easily. It's actually, very strange. I've invested half an hour now trying to mitigate the issue, but nothing has helped so far. I'm also not able to reproduce it with Safari or Firefox, and it seems to be related to `details` elements, as you've already noticed. When replaced with an admonition (which is a `div`), the problem vanishes.

**Comment by squidfunk** [comment] 2021-04-20 09:37
Closing as unfixable.

**Closed by squidfunk** 2021-04-20 09:37 UTC
Labels: bug, not fixable
