### ISSUE TITLE
Mermaid Viewer Control box?  How can we use it?

### ISSUE THREAD

**Issue by bschollnick** [squidfunk/mkdocs-material#7190] opened 2024-05-16 17:11 UTC
### Description

https://github.com/squidfunk/mkdocs-material/blob/master/docs/reference/diagrams.md#using-flowcharts

The "Using Flowcharts" mermaid has a control panel next to it, with panning, reload, and zoom in/out controls.  
I can't seem to find any documentation regarding it, I can see in the HTML the "mermaid viewer control box" controls, but the raw code of the page doesn't contain anything that would produce this?

![image](https://github.com/squidfunk/mkdocs-material/assets/979558/7a929b9c-437a-43f1-b26a-4d4111aadba6)

And the mkdocs.yml doesn't appear to have anything unusual in it?

How can we use these controls?

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)](https://github.com/squidfunk/mkdocs-material/blob/master/docs/reference/diagrams.md#using-flowcharts)

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by alexvoss** [comment] 2024-05-16 17:35
You are looking at the documentation on GitHub? That would be GitHub's rendering of the Markdown and the embedded Mermain diagrams. The same question has come up before, see https://github.com/squidfunk/mkdocs-material/issues/5208.

**Comment by bschollnick** [comment] 2024-05-16 18:17
> That would be GitHub's rendering of the Markdown and the embedded Mermain diagrams.

Not trying to be contrary, but I'm confused by this, why aren't any of the other mermaid diagrams on that page showing that functionality?

**Comment by alexvoss** [comment] 2024-05-16 18:23
Hm. They are for me:

<img width="723" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/4134224/97bab385-739f-471b-98a1-b10af4eba41f">

Am I holding the wrong end of the stick?

**Comment by facelessuser** [comment] 2024-05-16 18:30
Mermaid does not provide control box themselves. If you see that on GitHub, it is because GitHub has added their own control box implementation. I see these in GitHub's rendering as well, but this is not a built-in mermaid feature. If you have doubts about it, please check out Mermaid's documentation: https://mermaid.js.org/intro/.

**Comment by squidfunk** [comment] 2024-05-17 11:29
Thanks for reporting. Closing as exact duplicate of #5208.

**Closed by squidfunk** 2024-05-17 11:29 UTC
Labels: documentation
