### ISSUE TITLE
Using blog and tags plugins in combination results in wrong links to Blog index

### ISSUE THREAD

**Issue by vedranmiletic** [squidfunk/mkdocs-material#5952] opened 2023-09-03 08:56 UTC
### Bug description

When `blog` and `tags` plugins are enabled together, the links to Blog index will be rendered as linking to the *last page* of the index instead of the first page.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Setting up tags](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/)
- [Setting up a blog](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/)

### Reproduction

[9.2.7-using-blog-and-tags-in-combination.zip](https://github.com/squidfunk/mkdocs-material/files/12505546/9.2.7-using-blog-and-tags-in-combination.zip)

### Steps to reproduce

1. `mkdocs serve`
2. observe that the link on the Home page points to the second page of the Blog index
3. remove `tags` plugin configuration from `plugins` section in `mkdocs.yml`
4. observe that the same link is now generated correctly

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-09-03 10:49
Fixed in 84cb91b21. I think I found all cases and refactored how paginated views are handled during rendering with a more resilient approach. The problem reported was not exclusive to the tags plugin, but also happened when you went to the second page of the archive, and then clicked on "Latest posts", also ending up on the last page.

**Comment by vedranmiletic** [comment] 2023-09-03 19:57
This commit actually causes a regression, which in my case manifests as `ERROR   -  Error building page 'blog/archive/2010.md': Page(title='2010', url='/blog/archive/2010/') is not in list`. I will prepare a minimal example for that one.

**Comment by vedranmiletic** [comment] 2023-09-03 20:27
[9.2.7-url-not-in-list-regression.zip](https://github.com/squidfunk/mkdocs-material/files/12507471/9.2.7-url-not-in-list-regression.zip)

Note that I am not really using version 9.2.7 here, but the git master (and I have independently bisected the bad commit to 84cb91b). The error I get is:

```
INFO    -  Building documentation...
INFO    -  Cleaning site directory
ERROR   -  Error building page 'blog/archive/1990.md': Page(title='1990', url='/blog/archive/1990/') is not in list
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 349, in build
    _build_page(
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 222, in _build_page
    context = config.plugins.on_page_context(context, page=page, config=config, nav=nav)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 583, in on_page_context
    return self.run_event('page_context', context, page=page, config=config, nav=nav)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
  File "/home/vedranmiletic/.local/lib/python3.9/site-packages/material/plugins/blog/plugin.py", line 347, in on_page_context
    items[items.index(view)] = page
ValueError: Page(title='1990', url='/blog/archive/1990/') is not in list
```

**Comment by squidfunk** [comment] 2023-09-04 05:56
Thanks, looking into it.

**Comment by squidfunk** [comment] 2023-09-04 07:55
Fixed in 682d1761e. Thanks again for testing and providing the minimal reproduction – it only happened with 3 pages or more. I've tested the head of master against all reproductions we received related to the blog and think that it's finally stable... until the next bug appears 😅 If you can confirm that it works for you, we can release it today with the other fixes.

**Comment by vedranmiletic** [comment] 2023-09-04 09:07
> If you can confirm that it works for you, we can release it today with the other fixes.

Unfortunately not, the original bug seems to be back, both on the test case and real-world sites. I made sure several times that I am using the right version. Can you check on your side?

**Comment by squidfunk** [comment] 2023-09-04 11:34
Yes, the bug is back. I only checked the links in the navigation and they were all correct. I'll take a look.

**Comment by squidfunk** [comment] 2023-09-04 12:07
... and the next attempt in fc566cf0e. The links should now all be correct, unless I've missing something.

**Comment by squidfunk** [comment] 2023-09-04 17:05
@vedranmiletic when you find some time, it would be great if you could verify if your issue is now fixed. We're waiting with the next release until this issue is fixed, so it would be awesome if you could check if the problem is gone ☺️

**Comment by vedranmiletic** [comment] 2023-09-04 18:43
Sure, go ahead. The issue looks fixed to me now. Thanks!

There is another small unrelated issue with `tags` and `navigation.sections`, but I will report that separately tomorrow.

**Comment by squidfunk** [comment] 2023-09-04 19:42
Thanks! Released as part of [9.2.8](https://squidfunk.github.io/mkdocs-material/changelog/#9.2.8).

**Closed by squidfunk** 2023-09-04 19:42 UTC
Labels: bug, resolved

**Comment by L3V147H4N** [comment] 2023-11-24 14:27
hello @squidfunk 
this is still happening for me, I just tested today.. However it happens even when I disable tags
im getting `ValueError: View(title=[blank], url='/blog/') is not in list`

I get this just by including the `blog` plugin

**Comment by L3V147H4N** [comment] 2023-11-24 14:31
@squidfunk nevermind the rushed questions.. I fixed it by including `- Blog: './blog/index.md'` in the `nav` configuration
