### ISSUE TITLE
Use of privacy plugin with git-revision-date-localized plugin & type of timeago causes build to fail

### ISSUE THREAD

**Issue by nint8835** [squidfunk/mkdocs-material#5778] opened 2023-07-31 01:00 UTC
### Bug description

Upon enabling both the `privacy` plugin and the `git-revision-date-localized` plugin, and setting the `type` value for `git-revision-date-localized` to `timeago`, attempting to build the site will begin failing with the following error:

```
Traceback (most recent call last):
  File "/home/nint8835/Development/privacy-bug-repro/venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 304, in build
    files = config.plugins.on_files(files, config=config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/mkdocs/plugins.py", line 533, in on_files
    return self.run_event('files', files, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nint8835/Development/privacy-bug-repro/venv/lib/python3.11/site-packages/material/plugins/privacy/plugin.py", line 118, in on_files
    url = urlparse(script.path)
                   ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'path'
```

This only occurs when specifically those 3 combination of things have been done. The issue can be worked around by:
- Removing the `type` config on `git-revision-date-localized` or changing it to a different value, such as `datetime`
- Removing the `git-revision-date-localized` plugin entirely
- Removing the `privacy` plugin

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Privacy plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin)
- [git-revision-date-localized plugin](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=git+date#document-dates)
- #5772 - initially thought this was the issue I was encountering but removing all my `extra_javascript` config never fixed it

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/12210524/example.zip)

### Steps to reproduce

1. Install dependencies
2. Run `mkdocs serve` or `mkdocs build`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-07-31 13:30
Thanks for reporting. Meh. I think this MkDocs update will cause some more headaches because of the changed internal API. So the problem originates in the `git-revision-date-localized-plugin` but the privacy plugin should certainly not choke on that. Investigating...

**Comment by squidfunk** [comment] 2023-07-31 13:44
Okay, so I'm confident that this must be raised to the `git-revision-date-localized-plugin` as well, as it adds the value as a plain string to the `config.extra_javascript` list. It must now be wrapped like so:

``` py
from mkdocs.config.config_options import ExtraScriptValue
config.extra_javascript.append(ExtraScriptValue(path))
```

... at least that's how I read the API changes in MkDocs 1.5. However, as said, we can detect those cases in the privacy plugin and correct them, because otherwise we'll be having problems with each and every plugin that adds libraries to `config.extra_javascript` that hasn't been updated. Thus we fixed it in squidfunk/mkdocs-material-insiders@bb108f58d.

**Comment by squidfunk** [comment] 2023-07-31 13:50
Oh, and thanks for the excellent reproduction!

**Comment by nint8835** [comment] 2023-07-31 13:50
Tested and confirmed working, thanks for the quick fix! Was on the fence about whether to report here or to `git-revision-date-localized-plugin`, I'll go ahead and also report the issue you mentioned to them.

**Comment by squidfunk** [comment] 2023-08-01 11:38
Released as part of [insiders-4.38.1](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.38.1).

**Closed by squidfunk** 2023-08-01 11:38 UTC
Labels: bug, resolved

**Comment by oprypin** [comment] 2023-08-02 10:21
I came to a conclusion that we'll never get rid of strings being put into `extra_javascript`, so instead it will be officially embraced. MkDocs itself will now also normally put strings into the list. And the type annotation can now be truthful.

* https://github.com/mkdocs/mkdocs/pull/3324

I would recommend changing this back to `config.extra_javascript.append(path_as_string)` - that's less likely to cause trouble at this time.

Sorry about the trouble.

**Comment by oprypin** [comment] 2023-08-02 10:22
Plugins that want to read `extra_javascript` items should use `str(item)` to just get the path. Or for querying more detailed info about it they need to check `isinstance` first.

**Comment by squidfunk** [comment] 2023-08-02 15:19
Thanks, @oprypin!

> Plugins that want to read extra_javascript items should use str(item) to just get the path. Or for querying more detailed info about it they need to check isinstance first.

This is exactly what we did in the privacy plugin, as it reads the values. We just normalize them and we're good.
