### ISSUE TITLE
Refreshing page will show Syntax error in mermaid graph sometimes

### ISSUE THREAD

**Issue by orenwang** [squidfunk/mkdocs-material#3232] opened 2021-11-17 09:19 UTC
### Contribution guidelines

- [x] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Refreshing page will show Syntax error in mermaid graph sometimes. This shows in the [Official Docs](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#using-flowcharts) for me. Also, using mkdocs serve/build reproduces the same bug.

![image](https://user-images.githubusercontent.com/13847926/142171499-b55968c0-c83d-42c0-bd12-34895b99663a.png)

### Expected behaviour

Always show the correctly rendered MermaidJS graph.

### Actual behaviour

Sometimes normal, while sometimes not.

Refreshing page but with cache disabled can solve this problem...

### Steps to reproduce

Just keep refreshing the page.

### Package versions

Doesn't matter.

### Configuration

```yaml
Doesn't matter.
```

### System information

- Operating system: Mac OS / Windows.
- Browser: Chrome / Firefox

**Comment by squidfunk** [comment] 2021-11-17 09:34
Thanks for reporting! It's not reproducible for me in Chrome but in Firefox.

**Comment by squidfunk** [comment] 2021-11-17 09:41
The semantics of `startOnLoad` seems to have changed with the latest update. Likely related:

- #3171

**Comment by orenwang** [comment] 2021-11-17 09:52
> The semantics of `startOnLoad` seem to have changed with the latest update. Likely related:
> 
> * [Upgrade mermaid.js version and/or make configurable #3171](https://github.com/squidfunk/mkdocs-material/issues/3171)

Thanks for the quick response @squidfunk . I've tested earlier with prior versions to the aforementioned MR of mkdocs-material locally, which brings older version of MermaidJS too. Same problem. Still no clue why this is the case.
Also, totally fine on websites with MermaidJS alone (without mkdocs-material). Thus, I suspect maybe the <pre> or <code> tags bring some confusions to MermaidJS.

**Comment by squidfunk** [comment] 2021-11-17 10:12
The problem is that the moment Mermaid.js is loaded it will immediately try and parse all elements with the `.mermaid` class. The documentation says that `startOnLoad` should be set to `false`, but this does not work properly. It appears if the Mermaid.js can be loaded from cache, Mermaid will sometimes not pick up the configuration and start processing before one can tell it to not `startOnLoad`.

**Comment by squidfunk** [comment] 2021-11-17 10:19
Potential fix in [`f8b74c207`](https://github.com/squidfunk/mkdocs-material-insiders/commit/f8b74c207be7e3b22661dfffbad51daf0110243d). My testing shows that this mitigates the issue. I'll look into it when I find some time to refactor this section. It's really sad that Mermaid has such a bad API design.

**Comment by facelessuser** [comment] 2021-11-17 15:41
I've actually never seen this issue. I am not currently using Material's solution yet, but I've never had to strip off the class and add it back. I never see the syntax error. I've tried refreshing a bunch in my own docs...

**Comment by facelessuser** [comment] 2021-11-17 15:45
I guess I can't reproduce it in the official docs either... 🤷🏻

**Comment by facelessuser** [comment] 2021-11-17 15:58
I take it back. I can reproduce it in Firefox, but only with Material's solution. So I must be doing something different in my solution than what Material is doing. I do not have to strip out `mermaid` classes and then add them back.

**Comment by squidfunk** [comment] 2021-11-17 16:59
Yes, it's related to the usage of `pre/code` blocks which Mermaid chokes on. IMHO, temporarily removing the class is the only option, as it will leave the auto-mounting logic with nothing to render.

**Comment by facelessuser** [comment] 2021-11-17 17:20
That's weird as I am also using `pre/code` but having no issues. It must be something with how Material is specifically doing things.

**Comment by squidfunk** [comment] 2021-11-17 17:35
How are you initializing/loading Mermaid?

**Comment by facelessuser** [comment] 2021-11-17 18:24
I don't think Mermaid runs async, but I do it the same way as I do MathJax which does use async 🤷🏻 :

- Setup: https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/js/extra-loader.js#L30
- Subscribe: https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/js/extra-loader.js#L55
- Actual code: https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/js/uml.js
- Loader included here: https://github.com/facelessuser/pymdown-extensions/blob/main/mkdocs.yml#L171
- Config included here https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/html/libs.html#L2 which is, in turn, included here https://github.com/facelessuser/pymdown-extensions/blob/main/docs/theme/main.html#L5. I recently just bundled it as I have a plugin that patches all my repos with the customizations and I don't really customize my Mermaid config per repo, so I just wanted it included directly in the theme.

I don't know how much any of this info will help, but maybe there is something that stands out.

**Comment by orenwang** [comment] 2021-11-18 01:07
Thanks for fix. It works perfectly for me now!

Removing & adding back the class selector does seem a bit hacky but shouldn't be a problem as I see it.

**Comment by squidfunk** [comment] 2021-11-18 07:34
@facelessuser I guess the problem lies within the fact that Material will automatically include Mermaid.js when it sees an element tagged with a `.mermaid` class. The configuration you use is more predictable because Mermaid is always loaded in a deterministic way. Since Material will auto-mount, it's hardly possible to stop Mermaid when it's loaded from cache, since it will start running right away – no chance to tell it to `startOnLoad: false`. I've also tried this with the deprecated global settings to no avail. For this reason, I believe removing/adding back the CSS class is the most solid approach, since you're taking everything from Mermaid away it could automatically run on, and run it explicitly afterwards.

**Comment by facelessuser** [comment] 2021-11-18 12:53
Ah, makes sense.

**Comment by squidfunk** [comment] 2021-11-20 08:08
The fix was just released as part of 7.3.6-insiders-3.2.3.

**Closed by squidfunk** 2021-11-20 08:08 UTC
Labels: bug, fix available

**Comment by Guts** [comment] 2021-11-26 14:09
Thanks a lot @orenwang, this is exactly the problem that has been blocking us for a while. Hurray, it's finally fixed :pray:!

**Comment by orenwang** [comment] 2021-11-26 14:16
@Guts You are welcome. Glad it helped!

**Comment by zacharysarah** [comment] 2022-05-27 04:01
Thanks for this discussion--it helped us diagnose a similar issue on the Kubernetes website. 🙇🏻
