### ISSUE TITLE
[Bug] [UI] CTRL + Click of Navigation Group causes overlap

### ISSUE THREAD

**Issue by CPritch** [squidfunk/mkdocs-material#1177] opened 2019-07-18 11:04 UTC
## Description

CTRL + Click of navigation sub menus causes text to be overlaid.

### Expected behavior

CTRL + Click of navigation group should expand the group with no text overlapping.

![image](https://user-images.githubusercontent.com/29358433/61452480-b8d72d00-a953-11e9-90ca-0d0fb2d2834c.png)

### Actual behavior

Navigation subitems overlap with sibling navigation items.

![image](https://user-images.githubusercontent.com/29358433/61452452-a9f07a80-a953-11e9-9037-4419e64272e4.png)

### Steps to reproduce the bug

1. CTRL + Click a navigation group

### Package versions

* Python: 3.7.2
* MkDocs: 1.0.4
* Material: 4.4.0

### System information

* OS: Windows 10
* Browser:  FireFox

**Comment by squidfunk** [comment] 2019-07-18 11:53
Thanks for reporting. Why are you using <kbd>CTRL</kbd> in the first place to click on the navigation? I'm trying to understand whether this is an edge case or common.

**Comment by CPritch** [comment] 2019-07-18 12:13
@squidfunk definitely an edge case, just thought you'd like to track it as housekeeping at some point.

**Comment by squidfunk** [comment] 2019-07-18 12:36
@CPritch okay great. I managed to reproduce it in Firefox, macOS (using <kbd>CMD</kb>). I'll see if it's fixable, but probably won't invest too much time in it.

**Comment by CPritch** [comment] 2019-07-22 12:20
If it helps I can see that the checkbox fails to be checked when CTRL is held. Therefore the checkbox always returns the same state when the event is triggered in your `Collapse` class for the Nav.

More specifically [this line](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/javascripts/components/Material/Nav/Collapse.js#L74) always returns true/false if CTRL is held.

I'm not familiar enough with your component structure to see where the toggling event is fired but I'd put money on it being there. Also must say, very organised codebase for fairly vanilla js components, did you structure it yourself?

**Comment by squidfunk** [comment] 2019-07-22 13:47
@CPritch thanks for your research. Will look into it when I find some time!

> I'm not familiar enough with your component structure to see where the toggling event is fired but I'd put money on it being there. Also must say, very organised codebase for fairly vanilla js components, did you structure the componentised UI yourself?

it's built from scratch, yeah. Probably feels a bit dated by now. I'm actually trying to find some time to migrate to RxJS as this would make configuration and hooking into Material much easier, but can't put a timeline on that.

**Comment by CPritch** [comment] 2019-07-24 08:04
@squidfunk you should see some of the React projects I've had to work on, I'd argue good structure is timeless haha. If you ever want some help with that migration I'm happy to help. Looking for projects to contribute to. My day to day is React + TS and inhouse Component Framework/WebApp development. Happy to fork and demonstrate some example migrated code to RxJS.

**Comment by squidfunk** [comment] 2019-07-24 08:26
@CPritch I'm a big advocate of React, but it's not a good fit for this project as templating is handled by Jinja. RxJS however seems to be a good fit. Feel free to check out the `refactor/typescript` branch, which I created to start migrating to TypeScript and RxJS. My main idea was to refactor the code base to be more "hookable" (i.e. when people want to alter certain JavaScript behaviors of Material). You might need to merge `master` back in, as the branch was created quite some time ago and migrate to RxJS 6.

I would really love going forward on this topic, introducing unit tests, i.e. modernizing the code base. If you like, we can discuss specific issues and possible architectures over at your fork.

**Comment by Stanzilla** [comment] 2019-11-25 18:42
I ran into this problem myself and I noticed that it also happens when you select the text of the above menu https://i.imgur.com/X0B4jtP.gifv

**Comment by squidfunk** [comment] 2019-11-25 19:10
Both cases will be fixed in v5.

**Comment by Stanzilla** [comment] 2019-11-25 19:10
@squidfunk is the fix backportable?

**Comment by squidfunk** [comment] 2019-11-25 19:12
Nope. The new JS architecture is incompatible with the current one.

**Comment by squidfunk** [comment] 2020-03-10 17:06
[Material for MkDocs 5.0.0rc1](https://github.com/squidfunk/mkdocs-material/issues/1498) is out which fixes this issue 😀 Let's test and improve it together!

**Closed by squidfunk** 2020-03-10 17:06 UTC
Labels: bug
