### ISSUE TITLE
Regression in Bar Text Menu in mkdocs-material

### ISSUE THREAD

**Issue by MasonT8198** [squidfunk/mkdocs-material#3235] opened 2021-11-19 04:46 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The selector bar seems to be broken on a site I contribute to and your site as well https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker

### Expected behaviour

It's supposed to make a bar that you can select between different forms of text interchangeably

### Actual behaviour

Broken, no selector, looks completely voided

### Steps to reproduce

Go To: https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker

### Package versions

N/A

### Configuration

```yaml
site_name:https://www.xemu.app
site_address:https://xemu.app/docs/disc-images/
```

### System information

- Operating system: Windows 10, Linux
- Browser: Microsoft Edge, Google Chrome, Firefox, Opera GX, and Firefox ESR

**Comment by squidfunk** [comment] 2021-11-19 07:01
I'm not sure I understand your request. Could you please explain what you mean by selector bar? Maybe provide a screenshot to make it clearer and explain in more detail what you're expecting and what's actually there.

**Comment by MasonT8198** [comment] 2021-11-19 12:35
> I'm not sure I understand your request. Could you please explain what you mean by selector bar? Maybe provide a screenshot to make it clearer and explain in more detail what you're expecting and what's actually there.

Sorry, this is what has broken https://user-images.githubusercontent.com/72317541/122335665-a1bb6400-cf09-11eb-8a1c-9fa5bfebb7a6.png

**Comment by squidfunk** [comment] 2021-11-19 13:34
Tabs are not broken, they work as expected, see for example:
https://squidfunk.github.io/mkdocs-material/creating-your-site/#previewing-as-you-write

<img width="711" alt="Bildschirmfoto 2021-11-19 um 14 34 09" src="https://user-images.githubusercontent.com/932156/142631279-2d5db070-5b0d-400d-893b-b149e92841cf.png">

Closing, as it's working as intended.

**Closed by squidfunk** 2021-11-19 13:34 UTC
Labels: input needed
