### ISSUE TITLE
Instant loading causes redirects not function

### ISSUE THREAD

**Issue by amartin3225** [squidfunk/mkdocs-material#1959] opened 2020-10-01 20:08 UTC
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

When using mkdocs-material 6.0.1, I seem to be unable to use the [instant loading](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading) feature while also using the [redirects](https://squidfunk.github.io/mkdocs-material/deprecations/#redirect) plugin. I do not see any mention in the documentation of these two things being incompatible, but when I enable instant loading as shown below, redirects fail with an error.

### Expected behavior

The expected behavior is that clicking on a page that should be redirected (and is defined in `redirect_maps` in `mkdocs.yml`) will be redirected to the target page.

### Actual behavior

Attempting to click on a page that should be redirected results in several `undefined` strings being printed to the page (with the menu bar but no content, just blank) and the following being printed in the console:

```
Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at Object.next (VM20816:6028)
    at a._next (Subscriber.js:47)
    at a.next (Subscriber.js:25)
    at o.next (Subject.js:29)
    at o.next (ReplaySubject.js:22)
    at a._next (Subscriber.js:47)
    at a.next (Subscriber.js:25)
    at map.js:7
    at i.e._next (OperatorSubscriber.js:9)
    at i.next (Subscriber.js:25)

reportUnhandledError.js:9 
```

### Steps to reproduce the bug

1. configure mkdocs.yml with both the instant loading feature and the redirects plugin as shown below
1. build and deploy mkdocs
1. attempt to click on a page that should be redirected to another page

### Package versions

Running python 3.6.9 and the following packages:

```
mkdocs                                    1.1.2
mkdocs-git-revision-date-localized-plugin 0.7.2
mkdocs-material                           6.0.1
mkdocs-material-extensions                1.0
mkdocs-redirects                          1.0.1
```

### Project configuration

``` yaml
theme:
  name: 'material'
  features:
    - navigation.instant


plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - redirects:
      redirect_maps:
        example/old/page.md: example/new/page.md
```

### System information

* OS: Ubuntu Windows 10
* Browser: Google Chrome

**Comment by squidfunk** [comment] 2020-10-02 08:39
Instant loading should only intercept links that are part of `sitemap.xml`. I checked, and redirects don't seem to be added there, so it should just do a complete reload of the page. If that doesn't happen, it's a bug.

**Comment by squidfunk** [comment] 2020-10-04 11:43
I cannot reproduce this issue. Does it only happen when you deploy the documentation? Also, did you set `site_url`?

**Comment by amartin3225** [comment] 2020-10-05 20:20
Thanks for the fast reply! Yes, `site_url` is set. I think the problem is I'd like a way to have the old path still exist in the navigation menu (so a user can still find it at the old location but when they click on it, they are redirected to the new location). I have been doing this by creating a blank `example/old/page.md` file in the old location in addition to adding the redirect to `redirect_maps` as noted above. As you suggested, this blank page is getting added to the sitemaep. When I remove the blank `example/old/page.md`, this problem goes away (and you can't click on the old page in the menu since it no longer exists).

Is there a way to use this new form of redirect and also have the page exist at the old location in the navigation structure?

**Comment by kcgthb** [comment] 2020-10-05 20:40
I guess that's one of the limitations of the new way of using redirects with the `mkdocs-redirects` plugin, unfortunately.

Slight digression, but I also miss the old Metadata way of being able to chain redirects: like older_page redirects to old_page, old_page redirects to new page, and a user would redirected from older_page to new_page directly. 
Now, you have to make old_page redirect to new_page, and older_page redirect to new_page too for things to work the same way. One can argue it's structurally better, but it's certainly more effort to maintain. :)

**Comment by squidfunk** [comment] 2020-10-05 20:53
Im afraid that’s not supported. It’s a rather odd case to use redirects, IMHO. Redirects should more or less be used to ensure external links don’t 404. 

It should be possible to support instant loading to work with this, but I’d consider this at as an edge case. No plan to support it, sorry.

**Comment by squidfunk** [comment] 2020-10-06 06:55
Closing this issue. Supporting this is possible, but it's an edge case and I currently don't see much value going down this road. If many people are experiencing this issue, we might consider adding it in the future.

Nevertheless, you have three options:

1. Don't use instant loading, if you want to link redirects from nav
2. Add a post-processing step to remove the redirected pages from `sitemap.xml` after building
3. Copy the respective block from the 5.x template and extend the theme to use the old way of metadata redirects

**Closed by squidfunk** 2020-10-06 06:55 UTC
Labels: bug, not reproducible
