### ISSUE TITLE
Add an emoji in the first level section title broke the page title when scrolling

### ISSUE THREAD

**Issue by Enn83** [squidfunk/mkdocs-material#5893] opened 2023-08-25 07:17 UTC
### Context

Hi!

I recently upgraded `mkdocs-material` from `9.0.15` to `9.2.3` (and `mkdocs` from `1.4.2` to `1.5.2`) and I notice that all pages where the title depends on the markdown section and include an emoji are shifted downwards.

A markdown section is something like that:
```md
# Intégration et Déploiement Continu sur :simple-gitlab: Gitlab
```

### Bug description

When adding an emoji in a first level section title in the markdown page, I expect `mkdocs-material` to display, at least, the emoji code (for example `:simple-gitlab:`). It should looks like that:

![Capture d’écran 2023-08-24 154410](https://github.com/squidfunk/mkdocs-material/assets/46783975/dcebad1a-82b1-445d-b250-8ef7aa34bafb)

... or even display the emoji (if `typeset` plugin is not needed, otherwise the emoji code is sufficient).

But since the `mkdocs-material` update, it now looks like that:

![262990551-07eea56f-4224-4739-b70e-97467274e8e7](https://github.com/squidfunk/mkdocs-material/assets/46783975/555a71e9-3530-4a63-906a-17617c1d0be3)

(*Private informations in the screen are hidden*)

### Related links

- [The `typeset` plugin](https://squidfunk.github.io/mkdocs-material/reference/#built-in-typeset-plugin),
- I didn't find a page in the documentation where an emoji was in the title and displayed while scrolling...

### Reproduction

I made this minimal reproductible example `.zip` file:

[mkdocs-material-emoji-title-bug.zip](https://github.com/squidfunk/mkdocs-material/files/12436637/mkdocs-material-emoji-title-bug.zip)
***Edit:** More minimal example.*

**Note :** I tried using the step described in [Creating a reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file) and adding `plugins: - info`, but it gave me an `importlib.metadata` import error while doing `mkdocs serve` or `mkdocs build`, so I made the zip file at hand.

### Steps to reproduce

1. Download the `.zip` file and unzip it, then go inside.
2. Go inside the `mkdocs/` folder.
3. Type `pipenv install` in a terminal (_to install packages in virtualenv_),
4. ... and type `pipenv shell` (_to enable this virtualenv_).
5. Then type `mkdocs serve`.
6. Open a browser in `http://127.0.0.1:8000/`.
7. Scroll down in the main page.

You should notice the page title bug because of the emoji.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-08-26 10:42
Thanks for reporting! Indeed, the issue is quite apparent and this behavior is definitely new. However, it's not happening due to changed behavior in Material for MkDocs, but due to [MkDocs now determining the page title in a different way](https://www.mkdocs.org/about/release-notes/#page-titles-will-be-deduced-from-any-style-of-heading). Previously, all HTML was stripped from the title, which make a lot of sense because the header and navigation sidebars are not designed to host arbitrary markup. This happens with the `readthedocs` theme as well:

![screenshot-localhost-8000-1693046326821](https://github.com/squidfunk/mkdocs-material/assets/932156/2afb6262-bde4-4727-b0e3-c5c4da035873)

For this reason, this issue must be taken upstream, as it will impact many different parts that are likely not prepared to handle markup inside titles, for example the search page of the `readthedocs` theme:

![screenshot-localhost-8000-search-html-1693046416877](https://github.com/squidfunk/mkdocs-material/assets/932156/b8f7105a-3f4f-4536-a472-b2342b625b6c)

We designed the [`typeset` plugin](https://squidfunk.github.io/mkdocs-material/reference/#built-in-typeset-plugin) to account for those issues exactly – to provide an opt-in way for themes to display rich markup, but as can be seen easily, it requires a lot of careful thinking. Closing as upstream issue.

**Closed by squidfunk** 2023-08-26 10:42 UTC
Labels: needs investigation
