### ISSUE TITLE
Editable variables in code block

### ISSUE THREAD

**Issue by TheKangaroo** [squidfunk/mkdocs-material#7556] opened 2024-09-23 09:13 UTC
### Description

It would be very useful for technical documentation to allow users to edit variable values live in the code blogs before copying.
I saw this on Google Cloud Docs and was hoping I could do the same with Materials.
Maybe I couldn't find it because I don't know exactly how to describe it, but I don't think it's possible with Materials at the moment.

Here is an example from Google Cloud Docs: https://cloud.google.com/kubernetes-engine/docs/how-to/creating-an-autopilot-cluster#create_an_autopilot_cluster

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

What I really like about Google Cloud Docs is that I can type in the values for my usecase and then just copy and paste the command into my terminal as is. This is much more convenient than having to copy a block of code with placeholders like "<name_here>" and having to edit it in my terminal.

### Visuals

![image](https://github.com/user-attachments/assets/109c7640-8d5a-4d45-8604-eae80dbf708c)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment] 2024-09-23 09:18
Thanks for suggesting! Unfortunately, this is currently out of scope for Material for MkDocs and an exact duplicate of:

- #5527 
- #4332

Closing as duplicate.

**Closed by squidfunk** 2024-09-23 09:18 UTC

**Comment by TheKangaroo** [comment] 2024-09-23 09:32
I'm sorry I didn't find them myself when I searched for github issues. I think it was because I did not know how to name the feature correctly.
Anyway, thanks for the quick reply and for pointing out the other problems.
