### ISSUE TITLE
Recent changes break whole word search

### ISSUE THREAD

**Issue by nebulade** [squidfunk/mkdocs-material#419] opened 2017-07-28 09:53 UTC
## Description

The latest release (1.7.5) breaks some search patterns for whole words. In this case typing `restor` in the search field correctly shows matches for the whole word `restore` while when the whole word is typed into the search field, the search results are empty.

This can be tested with a small md file with the following contents:
```
## Restore

Apps can be restored to a previous backup by clicking on the `Restore` button.
```
The previous version (1.7.4) does not have this issue.

**Comment by squidfunk** [comment] 2017-07-28 09:58
This has to do with the default stemming by lunr, fixed in `master` which disabled stemming, and about to be released.

**Comment by nebulade** [comment] 2017-07-28 10:07
Thats awesome. Thanks!

**Comment by squidfunk** [comment] 2017-08-02 13:56
Fixed in 1.8.0

**Closed by squidfunk** 2017-08-02 13:56 UTC
Labels: bug, fixed in master

**Comment by kevung** [comment] 2020-06-06 13:32
Hello everybody,
I encounter the same problem as @nebulade  with mkdocs-material-5.2.2. 
Are there other people noticing this regression?

**Comment by kevung** [comment] 2020-06-06 14:13
The problem I encounter seems to be a problem from Mkdocs-Material.
The search is fully working when the language is in english, but fails in french, for example.

The search is fine with a `mkdocs.yml`:
```
site_name: test

theme:
  language: en
  name: material

plugins:
  - search

use_directory_urls: false
nav:
  - Intro: index.md
```
but does not work with this `mkdocs.yml`
```
site_name: technique/trajectoire

theme:
  language: fr
  name: material

plugins:
  - search

nav:
  - Intro: index.md
```

**Comment by squidfunk** [comment] 2020-06-06 14:18
Possibly related to #1603 and #1675

**Comment by connerxyz** [comment] 2021-04-02 21:34
Hello, I'm experiencing a very similar issue with 7.0.4. I've read through this issue and #1603 and #1605. 

I get what appears to be no search results for certain whole words which appears to be because of stemming, (e.g. "refer" returns results for partial matches of "reference", but "reference" itself returns no results).

I noticed the comment that [stemming was disabled](https://github.com/squidfunk/mkdocs-material/issues/419#issuecomment-318612571)... and I saw [the suggestion] to extend the theme and override `en.html` partial... But I don't see any stemming there. I experimented with removing the `trimmer` from the pipeline without any affect

I understand there's a difference of mkdocs vs. the material theme, and complexity of accommodating search use-cases across many languages.

What I don't understand is why whole words wouldn't be indexed in addition to stemmed words? From a user POV you want to be able to search for whole words (regardless of stemming) and aren't these whole words defined by the separator?

**Comment by squidfunk** [comment] 2021-04-03 05:44
Thanks for reporting. If you can narrow it down to a small reproducible case and two versions that work / don't, we can debug it. The official docs work with that very use case you mentioned, i.e. "reference" [returns results](https://squidfunk.github.io/mkdocs-material-insiders/?q=reference)

**Comment by connerxyz** [comment] 2021-04-05 19:28
I've found the problem has something to do with `prebuild_index: true`.

## Not working example.

Search configuration in `mkdocs.yml` looks like...

```
plugins:  # https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
  - search:  # https://squidfunk.github.io/mkdocs-material/plugins/search/
      lang: en
      separator: '[\s\-\.]+'
      prebuild_index: true
  - macros
```

![image](https://user-images.githubusercontent.com/3486466/113616241-77504f00-961a-11eb-9e11-71a81baa3e60.png)

<img width="926" alt="Screen Shot 2021-04-05 at 2 23 02 PM" src="https://user-images.githubusercontent.com/3486466/113616274-7cad9980-961a-11eb-881c-04426dda7bd7.png">

## Working example

```
plugins:  # https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
  - search:  # https://squidfunk.github.io/mkdocs-material/plugins/search/
      lang: en
      separator: '[\s\-\.]+'
  - macros
```

<img width="922" alt="Screen Shot 2021-04-05 at 2 27 39 PM" src="https://user-images.githubusercontent.com/3486466/113616760-21c87200-961b-11eb-92a1-1bda2ad1dd2a.png">

**Comment by connerxyz** [comment] 2021-04-05 19:36
PS – How do you enable the query string `/q=reference`? Thanks.

**Comment by squidfunk** [comment] 2021-04-05 19:40
@connerxyz ah yeah, prebuilding the index does not honor the pipeline, which excludes stemming by default. I think I also mentioned this on some issue on the MkDocs issue tracker some time ago.

> PS – How do you enable the query string /?q=reference? Thanks.

Deep linking of search results is one part of [sharing search results](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-sharing), currently only available via Insiders 😉

**Comment by connerxyz** [comment] 2021-04-06 14:59
Good stuff. I love your funding model, with the goals etc. This is a great project/community. Thanks.
