### ISSUE TITLE
Code higlight is not rendering correctly if the code block is indented 

### ISSUE THREAD

**Issue by svekars** [squidfunk/mkdocs-material#1504] opened 2020-03-11 18:01 UTC
__I checked that...__

- [X] ... the documentation does not mention anything about my problem
- [X] ... the problem doesn't occur with the default MkDocs template
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... there are no open or closed issues that are related to my problem

## Description

If the code block is indented and has highlighted lines in it, the formatting renders incorrectly:

![Screen Shot 2020-03-10 at 12 12 54 PM (2)](https://user-images.githubusercontent.com/5317992/76350344-ce290f00-62c8-11ea-9a1e-9ffa2a5ac68a.png)

The source file:
<img width="595" alt="Screen Shot 2020-03-10 at 12 15 43 PM" src="https://user-images.githubusercontent.com/5317992/76350402-ed27a100-62c8-11ea-8b10-9755bec2fce7.png">

### Expected behavior

The `namespace` line should be indented as all the lines above. 

### Actual behavior

The line is shifted to the left.

### Steps to reproduce the bug

1. Create and .md file and add a code block with line higlithing as on the screenshot above. The code must be in a sequence of steps and indented (2 spaces)as on the screenshot.
2. Run `mkdocs serve` to see the result.

### Package versions

```
$ python --version
Python 3.7.4

$ mkdocs --version
mkdocs, version 1.0.4 from /usr/local/lib/python3.7/site-packages/mkdocs (Python 3.7)

$ pip show mkdocs-material | grep -E ^Version
Version: 4.4.2
```

### Project configuration

https://github.com/pachyderm/pachyderm/blob/master/doc/mkdocs-master.yml

### System information

* OS: macOS
* Browser: Chrome

**Comment by facelessuser** [comment] 2020-03-11 18:15
Python Markdown requires 4 spaces for indentation.

**Comment by svekars** [comment] 2020-03-11 18:29
So, correctly if I misunderstand how this supposed to work in mkdocs-material:
If I specify `hl_lines "# #"` in a code block, these lines should be highlighted no matter whether they are indented in the code block or not. So if I have something like this:

```
``` hl_lines="3 4"
 pachctl list pipeline --raw \
     | jq -r '.pipeline.name' \
     | xargs -P3 -n1 -I{} pachctl stop pipeline {}
```
```
lines 3 and 4 should be highlighted and the code should be rendered with the same indentation as in the source code.

But I get this instead:

![Screen Shot 2020-03-11 at 11 26 50 AM (2)](https://user-images.githubusercontent.com/5317992/76450724-7f907900-638b-11ea-8c1f-6e7bfcadbdd1.png)

If I remove highlighting this is what I get (the indentation is correct):

![Screen Shot 2020-03-11 at 11 28 23 AM (2)](https://user-images.githubusercontent.com/5317992/76450748-8919e100-638b-11ea-8692-3cde1acc72df.png)

This looks like a bug to me.

**Comment by facelessuser** [comment] 2020-03-11 18:52
Apologies, I read over your code issue fairly quickly and thought you were complaining that indented code with 2 spaces wasn't working (which you are), but I interpreted it as non-fenced code, but now I see that you are complaining about fenced code. And I see you are talking abut formatting.

So I took your code you just posed (as it is the only copy/pastable example provided) and entered it into my documents in a fenced code block. 1st I did it with no indentation, 2nd I did it with 2 spaces (which shouldn't trigger normal code indentation unless it is 4 spaces):

This is what I got (2 space indented example):

````
  ``` hl_lines="3"
  pachctl list pipeline --raw \
      | jq -r '.pipeline.name' \
      | xargs -P3 -n1 -I{} pachctl stop pipeline {}
  ```
````

Output:

![highlight](https://user-images.githubusercontent.com/1055125/76452567-f8490280-6396-11ea-83fe-36b4e5c5ba9f.png)

So, I don't see an issue. If there was an issue, it wouldn't be a MkDocs Material issue, it would be with Python Markdown, or my Repo `pymdown-extensions` as it appears you are using SuperFences. But I don't see an issue, maybe it is because you are using it improperly under a list? A new paragraph (or block) shoudl be indented 4 spaces under a list.

**Comment by svekars** [comment] 2020-03-11 19:05
Thank you for testing this so quickly! I appreciate it. This example is not under a list. It's just a line without indentation. Could it be that the style is being overwritten somehow? And if so, any ideas where to look into this issue? Or maybe you have any other ideas what could be wrong?

**Comment by facelessuser** [comment] 2020-03-11 19:33
I'd need `markdown` version, `pymdown-extensions` version, and a copy/pastable broken example. Or maybe a repo with instructions on how to install dependencies and/or prep the environment for document building.

**Comment by squidfunk** [comment] 2020-03-11 20:32
Is it possibly related to the still unmerged PR of yours, @facelessuser?

**Comment by facelessuser** [comment] 2020-03-11 20:34
Nope, this is `Version: 4.4.2` of Material.

**Comment by squidfunk** [comment] 2020-03-12 08:55
Note that the image the OP posted shows a non-monospace font in the `.hll`, so the issue is almost certainly with the CSS

**Comment by facelessuser** [comment] 2020-03-12 12:18
I worked with them on Gitter. I was not able to reproduce, and there was a lot of costum stuff in their repo. I don't think there is anything to be done in this issue. I believe it was a user environment issue.

**Comment by squidfunk** [comment] 2020-03-12 13:36
Alright then, closing then. Thanks for your help!

**Closed by squidfunk** 2020-03-12 13:36 UTC
