### ISSUE TITLE
Extend mapping of multi-language blog post to normal pages and sections

### ISSUE THREAD

**Issue by janvanveldhuizen** [squidfunk/mkdocs-material#6518] opened 2023-12-17 13:27 UTC
### Context

https://github.com/squidfunk/mkdocs-material/issues/4835 makes it possible to map blog posts to their translations, to help navigating to the proper page after switching the language.

### Description

It would be nice to have a similar mapping strategy for normal pages and even sections.
This requires normal pages to have a header just like blog posts.
Assume you have a page named: who-am-i.md
```
---
alternate:
  de: wer-bin-ich.md
  fr: qui-suis-je.md
```

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

From a user perspective this would mean that the names of pages can be in the language the page is written in. That makes it a more natural experience for people navigating through the website.

I noticed that https://github.com/squidfunk/mkdocs-material/issues/4835 even works when sections (# links) have the same name. That's cool. Would it go too far to add a mapping for that as well? In the current version, the navigation jumps to the home page of the other language when a section name does not correspond with the translated page.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexvoss** [comment] 2023-12-17 13:54
One issue I see with the suggestion to put the mapping into the page header is that each page involved would need to have this mapping, meaning that information would be duplicated. IMHO a single source approach would be better. The [i18n plugin](https://gitlab.com/mkdocs-i18n/mkdocs-i18n) puts the mapping into `mkdocs.yml`. I would prefer a separate mapping file because I don't think that `mkdocs.yml` should be the place where literally everything ends up that is not page content.

**Comment by squidfunk** [comment] 2023-12-17 14:23
Thanks for suggesting. I'm not sure I understand. https://github.com/squidfunk/mkdocs-material-insiders/pull/75 implements this not only for blog post, but for all pages. Are you referring to this pull request?

> One issue I see with the suggestion to put the mapping into the page header is that each page involved would need to have this mapping, meaning that information would be duplicated. IMHO a single source approach would be better. The [i18n plugin](https://gitlab.com/mkdocs-i18n/mkdocs-i18n) puts the mapping into mkdocs.yml. I would prefer a separate mapping file because I don't think that mkdocs.yml should be the place where literally everything ends up that is not page content.

I disagree. IMHO, to preserve locality, it should be better to do the mapping in the Markdown files. However, we can most likely allow for alternate ways to specify the mapping, but IMHO, central mappings are hard to maintain.

**Comment by alexvoss** [comment] 2023-12-17 15:43
I bet that maintaining multiple mappings distributed over many files is more difficult but then perhaps you have already thought about that and found a workable solution? (Last time I checked,) 18n assumes there is a main language and all mappings go from there to the different language versions. So, only 1:n mappings required instead of n:n. The documentation on [extra.alternate](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector) currently does not suggest that a similar logic is at play?

**Comment by squidfunk** [comment] 2023-12-17 16:21
i18n mapping does the mapping implicitly by using the file names. If you have the same filenames, the mapping is automatic for the projects plugin as well, so it's only necessary if file names are not the same across languages. I'm not sure how the i18n plugin solves this for incoherent file names. I think in the end, we'll just allow both, because it will heavily depend on the use case whether you should chose one or the other.

**Comment by squidfunk** [comment] 2023-12-17 16:22
I agree however that local mappings are likely more to maintain, that's right. Hmm... maybe in the end we'll find an almost automatic solution, that'd be really awesome.

**Comment by alexvoss** [comment] 2023-12-17 17:57
> how the i18n plugin solves this for incoherent file names

Right, I should have been clearer about what I was talking about, which was the mapping of the navigation structure, not the slugs. I do believe the slugs are the same for different language versions, at least back when I was using it. I kept wondering if that was perhaps a good thing.

**Comment by squidfunk** [comment] 2023-12-17 18:07
We might make all of this much, much simpler by introducing `slug` for common pages (not only blog posts), so the slug can be explicitly set from the page, or by somehow extending MkDocs to set the slug from the title of the post. Im not sure what this might break though,  because usually, the title is inferred from the file name, so this might be a catch-22.

**Comment by janvanveldhuizen** [comment] 2023-12-17 20:59
Just my two cents: I believe the mapping should be the responsibility of the markdown file itself. Keeping everything in one file is straightforward and easy to maintain, in my opinion. If the names of the pages in each language are kept identical, that would certainly be the simplest solution. However, if not, the mapping could be included in the front-matter part of the file's header.

It becomes more complicated when navigating to an anchor within the page, which is a common occurrence in markdown files. For instance, if you have an about.md page with sections 'intro' and 'career', this would generate URLs like 'about/#intro' and 'about/#career'. In the 'use cases' mentioned above, I stated that the language switcher would redirect to the home page of the other language. However, upon further testing, I observed that it actually jumps to the top of the page in the selected language. I think that's an acceptable behavior.

**Comment by squidfunk** [comment] 2023-12-17 21:11
> In the 'use cases' mentioned above, I stated that the language switcher would redirect to the home page of the other language. However, upon further testing, I observed that it actually jumps to the top of the page in the selected language. I think that's an acceptable behavior.

So this issue is resolved? Sorry, I'm really having a hard time to understand what it is exactly you're trying to solve.

**Comment by squidfunk** [comment] 2023-12-18 17:26
I'm closing this issue, because I just checked and things are working as intended. As I mentioned in https://github.com/squidfunk/mkdocs-material/issues/6518#issuecomment-1859186930, there's an open PR at https://github.com/squidfunk/mkdocs-material-insiders/pull/75 that implements the `alternate` metadata property. This PR does not solely work for blogs, but for all pages, if the projects plugin is used. I've attached a minimal reproduction that demonstrates it for all pages. For example, navigate to "Questions" and switch to the German "Fragen" and back:

[multi-language-switch.zip](https://github.com/squidfunk/mkdocs-material/files/13706672/multi-language-switch.zip)


I've yet not received any feedback on the PR, so let's please continue the discussion there.

**Closed by squidfunk** 2023-12-18 17:26 UTC
Labels: needs input
