### ISSUE TITLE
`content.tooltips` feature breaks abbreviation hover in tab titles

### ISSUE THREAD

**Issue by johnthagen** [squidfunk/mkdocs-material#7010] opened 2024-04-04 13:15 UTC
### Bug description

Enabling

```yaml
  features:
    - content.tooltips
 ```

Breaks the hover text for an abbreviation when it is located in the title of a tab enabled with

```yaml
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
 ```

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=ab#abbreviations
- https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=tab#tabbed

### Reproduction

[9.5.17-content-tooltips-breaks-abbr-in-tab-title.zip](https://github.com/squidfunk/mkdocs-material/files/14871768/9.5.17-content-tooltips-breaks-abbr-in-tab-title.zip)

### Steps to reproduce

1. Hover over tab title that contains an abbreviation, note that a partial, blank box is shown below the cursor

<img width="154" alt="Screenshot 2024-04-04 at 9 12 45 AM" src="https://github.com/squidfunk/mkdocs-material/assets/10340167/19e2ff56-dbfd-4a29-bf50-1858221d6010">

Instead it should show the abbreviation as hover text (e.g., disable `content.tooltips`):

<img width="188" alt="Screenshot 2024-04-04 at 9 13 59 AM" src="https://github.com/squidfunk/mkdocs-material/assets/10340167/bc10bae9-f1be-450e-8374-30cea15b8290">

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-04-04 14:58
Thanks for reporting. Exact duplicate of #6488. Closing as duplicate.

**Closed by squidfunk** 2024-04-04 14:58 UTC

**Comment by johnthagen** [comment] 2024-04-04 15:01
@squidfunk Thanks! Sorry, I search the issues but didn't find that one.

**Comment by squidfunk** [comment] 2024-04-04 15:03
Yeah, your title is actually better than the one used in #6488. I'm stealing it 😉
