### ISSUE TITLE
Search field alignment issue on screen < 1220px

### ISSUE THREAD

**Issue by matjaeck** [squidfunk/mkdocs-material#1068] opened 2019-04-11 00:23 UTC
Description:

For screen sizes < 1220px the alignment of content inner and search is not working. The end of the content should align with the end of the search widget, like it does in >= 1220px. This is caused by erroneous margins of the source widget. I have a fix at https://github.com/matjaeck/mkdocs-material/commit/ce37adbde6b273f98a287b841adcc70a3a3cabe6 that is working for me, can PR if you want.

**Comment by squidfunk** [comment] 2019-04-11 07:17
Could you please provide a screenshot which shows what you mean exactly? Furthermore, the changes on your branch look a little hacky to me. Happy to find the root cause and fix it, but first we need a thorough description of the issue including some visual clues.

**Comment by matjaeck** [comment] 2019-04-11 09:05
See missing screenshots below:

<details>
>= 1220px

![material-align-2](https://user-images.githubusercontent.com/37185497/55943009-fd14ac00-5c45-11e9-9b3d-6aca2df5f5cc.png)

< 1220px (Alignment issue of search field and content container)

![material-align](https://user-images.githubusercontent.com/37185497/55943034-0867d780-5c46-11e9-9e4d-a3568cd7aad4.png)

</details>

This is how I calculated the `.md-header-nav__source` margins:

- tablet +: 230px width + 8px margin-right (`.md-header-nav__source`) + 4px margin-right (`.md-header-nav`) gives us the sidebar width, add 16px additional margin-left to account for `md-content-inner`'s margin-right of 16px.

- screen +: like above but add 24px margin-left to account for  `md-content-inner`'s margin-right of 24px.

Removed the padding-right from `md-source` since it appeared not needed to me, but maybe I'm missing something here.

The `margin-right: px2rem(-4px)` that I added in my branch to `md-source` is indeed a hacky workaround for an issue that I caused when allowing disabling the primary sidebar, so not relevant for upstream.

**Comment by squidfunk** [comment] 2019-04-11 09:17
Thanks for the detailed explanation! Will look into it when I find the time.

**Comment by matjaeck** [comment] 2019-04-11 19:18
FYI, I think the `margin-right: px2rem(-4px)` thing is actually fixing alignment issues resulting from different padding of `md-header-nav__button` and `md-search`, that only appear on tablet landscape + (when the search field is visible).

**Comment by squidfunk** [comment] 2019-04-28 08:22
Fixed in 50ea834. Moved spacing from `.md-nav-header__source` to `.md-search__inner` and added another breakpoint.

**Comment by squidfunk** [comment] 2019-04-28 10:08
Released as part of 4.2.0.

**Closed by squidfunk** 2019-04-28 10:08 UTC
Labels: bug, fixed in master
