### ISSUE TITLE
Blog plugin causes mkdocs build fail for mkdocs-material 2.9.0

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#5879] opened 2023-08-21 20:33 UTC
### Bug description

After updating MkDocs-material from 9.2.0b2 to 9.2.0 today did `mkdocs build` fail with a stacktrace.
I sadly cannot understand what it points towards nor what it means, but it seems to be related to the blog plugin as commenting it out in the mkdocs.yml builds the site as expected.

Full stacktrace: https://paste.helpch.at/epopumuceb.lua

First I thought this might be an error due to changes to the `.authors.yml` file which mkdocs-material did report properly, but after fixing those is the issue still persisting.

The documentation is build using Woodpecker-CI by setting up a Python Image (Python 3.11 by the looks of it) and the executing `pip install -r requirements.txt` followed by `mkdocs build`. Tho local reproduction tests also show the same errors, so it's unlikely to be bound to the env or software used.

For transparency, here are files and logs related to the failed CI runs:

- Logs: https://ci.codeberg.org/repos/12455/pipeline/42/3
- CI config used: https://ci.codeberg.org/repos/12455/pipeline/42/config

### Related links

- [Setting up a blog](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/)
  - [`pagination_format`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#+blog.pagination_format) to double-check the option is spelled right
  - [`Adding authors`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#adding-authors) was looked at for the new format mentioned by the plugin which doesn't seem to be in the docs yet.

### Reproduction

[mkdocs-2.9.0-build-errors.zip](https://github.com/squidfunk/mkdocs-material/files/12402121/mkdocs-2.9.0-build-errors.zip)

### Steps to reproduce

1. Download mkdocs-material 2.9.0
2. Setup mkdocs.yml with bare-bones settings and blog plugin configuration
3. Create post folder and blog post file
4. Run `mkdocs serve` or `mkdocs build`

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-08-21 21:02
Fixed in 7099ea60a. There were several cases that were not handled. The error reported originated from using the blog plugin on the top-level. The blog plugin was completely rewritten, so it's expected that there are some cases we missed.

Note that you did not define an authors file, which is why the plugin errors and can't find `user`. If you remove the authors setting or define an authors file, the error is gone.

**Comment by squidfunk** [comment] 2023-08-21 21:10
Released as part of [9.2.1](https://squidfunk.github.io/mkdocs-material/changelog/#9.2.1).

**Closed by squidfunk** 2023-08-21 21:10 UTC
Labels: bug, resolved

**Comment by Andre601** [comment] 2023-08-21 21:48
> Fixed in [7099ea6](https://github.com/squidfunk/mkdocs-material/commit/7099ea60a9f6894d95c88c2e94db72f5474f502e). There were several cases that were not handled. The error reported originated from using the blog plugin on the top-level. The blog plugin was completely rewritten, so it's expected that there are some cases we missed.
> 
> Note that you did not define an authors file, which is why the plugin errors and can't find `user`. If you remove the authors setting or define an authors file, the error is gone.

That's kinda strange... I have a `.authors.yml` file in the docs directory from the beta which worked back then, so I guess that behaviour changed too?
Since my blog_dir is the docs dir itself, should the file remain there?
It's currently looking like this: https://codeberg.org/Andre601/blog-source/src/branch/master/docs/.authors.yml

**Comment by Andre601** [comment] 2023-08-21 22:27
The error seems to persist: https://ci.codeberg.org/repos/12455/pipeline/43/3

Current mkdocs.yml: https://codeberg.org/Andre601/blog-source/src/branch/master/mkdocs.yml

**Comment by vedranmiletic** [comment] 2023-08-21 23:06
I get a different error from @Andre601:

```
Traceback (most recent call last):
  File "/home/vedranmiletic/software/mkdocs-venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/mkdocs/__main__.py", line 283, in build_command
    cfg = config.load_config(**kwargs)
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/mkdocs/config/base.py", line 378, in load_config
    errors, warnings = cfg.validate()
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/mkdocs/config/base.py", line 230, in validate
    run_failed, run_warnings = self._validate()
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 182, in validate
    return self.run_validation(value)
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 1064, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 1100, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 1118, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/material/plugins/blog/plugin.py", line 44, in <module>
    from .structure import Archive, Category, Excerpt, Post, View
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/material/plugins/blog/structure/__init__.py", line 203, in <module>
    class View(Page):
  File "/home/vedranmiletic/software/mkdocs-venv/lib/python3.9/site-packages/material/plugins/blog/structure/__init__.py", line 206, in View
    def __init__(self, title: str | None, file: File, config: MkDocsConfig):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

The new or old structure of `.authors.yml` doesn't make any difference. Should I try to create a minimal example?

**Comment by squidfunk** [comment] 2023-08-22 05:27
@Andre601 this looks like a different error, probably like #5880.

@vedranmiletic Yes, we definitely need a minimal reproduction, so please create a new issue.

**Comment by squidfunk** [comment] 2023-08-22 05:29
> That's kinda strange... I have a .authors.yml file in the docs directory from the beta which worked back then, so I guess that behaviour changed too?

The reproduction did not contain an `.authors.yml`, probably because the info plugin did not add it. Thus this might be a bug (or undesired behavior) in the info plugin.

**Comment by vedranmiletic** [comment] 2023-08-22 08:54
@squidfunk thanks! Done in #5881.

**Comment by squidfunk** [comment] 2023-08-22 12:07
I've checked whether the `info` plugin omits files – it packs everything that is in the `docs_dir`. Thus, the `.authors.yml` file was likely not defined, or I'm not sure why it was missing from the archive:

```
  example/docs/.authors.yml 13.0 B
  example/docs/.overrides/extra.js 2.0 B
  example/docs/index.md 282.0 B
  example/docs/posts/some/other/path/post-2.md 2.0 B
  example/docs/posts/post-1.md 2.0 B
  example/mkdocs.yml 93.0 B
  example/platform.json 61.0 B
  example/requirements.lock.txt 390.0 B

  example.zip 2.2 kB
```

**Comment by Andre601** [comment] 2023-08-22 12:33
I may have missed a setup step in the minimal reproduction as I made a bare-bones setup. But I can guarantee (As shown by the shared links) that the repo this appears on actually has a `.authors.yml` file present.

I'll double check the repro setup and see if I missed the authors file.

**Comment by Andre601** [comment] 2023-08-22 12:35
On a unrelated note: The info plugin seems to handle the name you give a bit differently when providing dots in the name. As an example my last zip generated by it was named `mkdocs-29.zip` iirc

It's obviously not that big of a deal. Just something I found worth pointing out.

**Comment by Andre601** [comment] 2023-08-22 12:41
Alright. The `.authors.yml` file was indeed missing.

Adding it makes the serve and build command work fine on my Desktop. Tho, that makes the cause of the CI failing even more confusing given the Authors file is present.

**Comment by Andre601** [comment] 2023-08-22 17:57
Want to quickly mention that the build now works on the CI using 2.9.3, so there probably was a fix for that too. Thanks
