### ISSUE TITLE
Title meta data not applied consistency

### ISSUE THREAD

**Issue by dtw-chriss** [squidfunk/mkdocs-material#761] opened 2018-04-13 15:02 UTC
## Description

When a title property is listed in the template it is only visibility on the navigation when it is active else it uses the file name.  Switches back and forth.

### Expected behavior

If there is a title property is would used consistently within the site.

**Comment by squidfunk** [comment] 2018-04-13 15:43
Sorry, I don't really understand your request. Can you provide some more information.

**Comment by dtw-chriss** [comment] 2018-04-13 17:05
Sorry, hopefully these screen shots clear it up.


1)      Add title yaml/header

[cid:image001.png@01D3D327.EF04F0A0]


2)      Initial view of left side navigation it uses the file name
[cid:image002.png@01D3D327.EF04F0A0]


3)      Once you click on a navigation item is uses the title
[cid:image003.png@01D3D327.EF04F0A0]

**Comment by squidfunk** [comment] 2018-04-13 17:32
No images attached.

**Comment by dtw-chriss** [comment] 2018-04-13 18:03
Sorry, hopefully these screen shots clear it up.


1)      Add title yaml/header


![one](https://user-images.githubusercontent.com/38356466/38750507-240b320c-3f23-11e8-9315-edb7c31e92aa.png)

2)      Initial view of left side navigation it uses the file name

![2](https://user-images.githubusercontent.com/38356466/38750552-4856601e-3f23-11e8-9207-71304676998f.png)


3)      Once you click on a navigation item is uses the title


![3](https://user-images.githubusercontent.com/38356466/38750555-4aab71ba-3f23-11e8-9af6-a7313b8b54b9.png)

**Comment by squidfunk** [comment] 2018-04-15 10:06
This looks exactly like an issue with MkDocs that was already reported [here](https://github.com/mkdocs/mkdocs/issues/1347). Material can't do anything about it.

**Comment by squidfunk** [comment] 2018-04-19 11:57
Closing as duplicate of linked upstream issue.

**Closed by squidfunk** 2018-04-19 11:57 UTC
