### ISSUE TITLE
Anchor tracking for TOC not working with anchors within tables

### ISSUE THREAD

**Issue by mh166** [squidfunk/mkdocs-material#4689] opened 2022-11-29 10:10 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

As [discussed previously](https://github.com/mkdocs/mkdocs/discussions/3038#discussioncomment-4149646), I went ahead and added custom anchors to the page's TOC.

Unfortunately, when scrolling down, anchors that reside within a `<table>` are not tracked correctly.

From what I've seen, [src/assets/javascripts/components/toc/index.ts](https://github.com/squidfunk/mkdocs-material/blob/13655d68f5c3514f1a03733ef7b2ecb96bc0d2fe/src/assets/javascripts/components/toc/index.ts) is responsible for this functionality. Maybe somewhere starting from [Line #158](https://github.com/squidfunk/mkdocs-material/blob/13655d68f5c3514f1a03733ef7b2ecb96bc0d2fe/src/assets/javascripts/components/toc/index.ts#L158)? Unfortunately, it's above my level of expertise to understand where the strange behaviour is coming from.

### Expected behaviour

Within the TOC, the section currently in view should be highlighted.

### Actual behaviour

This does work only for anchors that DO NOT reside within a `<table>`. Those behave absolutely correctly.

But with those inside a `<table>` it is strange: is the page scrolled to the very top, an anchor from within the table is highlighted as active - even though it's not in view. And once you start scrolling, those anchors apparently get ignored.

### Steps to reproduce

**Result:**
- Just take a look at my [example page](https://mh166.github.io/mkdocs-custom-anchors/). This is a minimal project to demo this problem.

**Try for yourself:**
- [The source code](https://github.com/mh166/mkdocs-custom-anchors) is also available
  - Using the [`customAnchors.py` hook](https://github.com/mh166/mkdocs-custom-anchors/blob/main/customAnchors.py), I look for `<strong>` tags containing the `id="..."` attribute. Those get added to the TOC.
- With the `mkdoc`'s default theme, everything works as expected (clone the repo and remove the material theme definition from the config

### Package versions

- Python: `3.9.4`
- MkDocs: `1.4.0`
- Material: `8.5.3`

### Configuration

```yaml
# Can be found here: https://github.com/mh166/mkdocs-custom-anchors/blob/main/mkdocs.yml

site_name: "Demo: problem with anchors within tables"
theme:
  name: material
markdown_extensions:
  - attr_list
copyright: mh166
extra_css:
  - extra.css

hooks:
  - customAnchors.py
```

### System information

I've tried on Windows 10 using multiple browsers (Chrome, Edge, Opera). All show the same behaviour.

**Comment by squidfunk** [comment] 2022-12-12 22:02
Thanks for reporting. So yes, it's a bug which stems from the problem that the offset in tables is relative to the table, not to the page. That's actually related to #3453 and #4217. I need some time to generalize the fix, which will also fix this problem.

**Comment by squidfunk** [comment] 2023-01-08 10:54
Fixed in 318903db5. Thanks for the excellent reproduction – that made fixing quite simple. I'll revisit how we can generalize offset computation once annotations are released into the community edition once the next funding goal is hit, which I expect to be in February or March. 😊

Releasing a new feature always yields significant refactoring opportunities, like for search recently. Related:

- #4217
- #3453

**Comment by squidfunk** [comment] 2023-01-08 12:07
Released as part of [9.0.3](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.3).

**Closed by squidfunk** 2023-01-08 12:07 UTC
Labels: bug, fix available

**Comment by mh166** [comment] 2023-01-13 13:26
Thanks so much! Glad my example was of help. I'm excited to try this next week and roll back some of my hacky workarounds (mostly visually disabling the tracking... 😅).

Please keep up the great work you do! This project is absolutely amazing! ✨

**Comment by MartinKjunior** [comment] 2023-10-10 17:09
@squidfunk This has been closed as fixed, but I've just tried using the annotations inside my table and I'm experiencing this old bug where the annotation is displayed at the very top of the page instead of where the annotation button is placed. I used `<div>`s to set up the annotation because `{ .annotate }` did not work for me. This is an example of a code that causes this behaviour
```
<div class="annotate" markdown>
| header | header | header | header | header | header |
| -- | -- | -- | -- | -- | -- |
| -- | -- | -- | -- | (1) | -- |
</div>

1.  test
```
and these are my mkdocs.yml
```
site_name: Contrast-agent based perfusion MRI lexicon (CAPLEX) v1.0.1
site_description: CAPLEX
site_author: Open Science Initiative for Perfusion Imaging (OSIPI)

theme:
  name: material
  logo: OSIPI_logo.png
  icon:
    annotation: 
      material/plus-circle
      

docs_dir: docs

nav:
  - Overview: 
      - About Caplex: index.md
      - CAPLEX structure: structure.md
  - Sections:
    - Q - Quantities: quantities.md
    - M - Perfusion models: perfusionModels.md
    - P - Perfusion processes: perfusionProcesses.md
    - G - General purpose processes: generalPurposeProcesses.md
    - D - Derived processes: derivedProcesses.md
    
  - DCE\DSC resources: 
    - DCE literature library: dceliterature.md
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      features:
        - search.suggest
      
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
``` Any help would be appreciated.
