### ISSUE TITLE
Unable to add child pages on the homepage with tabs enabled

### ISSUE THREAD

**Issue by RealOrangeOne** [squidfunk/mkdocs-material#3076] opened 2021-10-03 16:27 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When creating sections with `navigation.tabs` enabled, sibling pages (note: not sections) to the homepage appear as tabs rather than sections for the homepage tab itself. This works as expected for any other tab. Sections yes should appear as tabs, but sole pages should appear in the sidebar.

From some basic bisecting, I know this broke in version 6.2.0, which appears to be when the implementation was rewritten anyway. Since then it has not worked.

### Expected behaviour

For the homepage (`index.md`), if another page is created in the same directory (`another-page.md`), it shows up in the sidebar of the homepage.

### Actual behaviour

For the homepage (`index.md`), if another page is created in the same directory (`another-page.md`), it shows up as a tab.

Note that this works as expected for all other sections.

### Steps to reproduce

1. Create a basic mkdocs site
2. Attempt to add a file next to the `index.md` file
3. Build site, and observe behaviour

### Package versions

- Python: `python --version` 3.9.7
- MkDocs: `mkdocs --version` 1.2.2
- Material: `pip show mkdocs-material | grep -E ^Version` 7.3.1

### Configuration

```yaml
theme:
  name: 'material'
  icon:
    logo: fontawesome/solid/book
  favicon: 'favicon.ico'
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    primary: 'blue'
    accent: 'blue'
```
```


### System information

- Operating system: Linux
- Browser: Firefox

**Comment by squidfunk** [comment] 2021-10-03 17:27
Thanks for reporting. This is a duplicate of #2125 and an intended change in behavior which is [documented](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#fn:1). I don't have the time to go into detail why we this change was necessary, but if you read #1884, #2027 and #2125 it should be pretty clear that this change makes sense.

Also, behavior is almost identical if you regroup your pages:
https://github.com/squidfunk/mkdocs-material/issues/2125#issuecomment-744360768

**Closed by squidfunk** 2021-10-03 17:27 UTC
