### ISSUE TITLE
Reduce time to render pages with thousands of code blocks

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#3643] opened 2022-03-01 11:17 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

As outlined and demoed [here](https://github.com/squidfunk/mkdocs-material/issues/1887#issuecomment-1055221462), large topics can take a long time to render, up to 30 seconds, which makes them unusable. This only occurs when using the Material template.

@squidfunk has already looked at it, and it is most probably caused by the large amount of code blocks used in the sample topic. Other templates have less sophisticated handling of code blocks, which is why the issue doesn't occur when using other templates.

### Expected behaviour

Pages should render fast in all browsers, regardless of the template used.

### Actual behaviour

See description.

### Steps to reproduce

See sample project linked in the description.

### Package versions

- Python: 3.9.10
- MkDocs: 1.2.3
- Material: 8.2.3+insiders.4.10.0

### Configuration

See sample project linked in the description.

### System information

- Operating system: macOS
- Browser: Firefox, Chrome, Safari

**Comment by squidfunk** [comment] 2022-03-01 11:20
Thanks for reporting. Just for anyone else coming here – the problem is observed on a page with over 1.7k code blocks.

**Comment by squidfunk** [comment] 2022-03-06 12:53
This was an interesting problem to solve. The problem stems from excessive reading of the `Element.offset*` and `Element.scroll*` properties in order to determine whether a code block overflows or not, which is necessary to make it focusable via keyboard to allow for better accessibility, as requested in #1514. Since all code blocks are mounted on load, and the page in question has more than 1.700 of them, this process took forever to complete:

<img width="1552" alt="Bildschirmfoto 2022-03-06 um 13 43 59" src="https://user-images.githubusercontent.com/932156/156923770-d8ecad99-fa99-4ea4-8a5b-9473086ee78e.png">

While parsing the HTML takes the browser 1.4s, the user had to wait for another __35s__ until the browser becomes responsive again. Oops. Even worse: most of the work done is probably unnecessary, because the page is so long and most of the code blocks will probably never be interacted with.

This is now fixed in e71891f49, as code blocks will now only be mounted when they are visible. Parsing the HTML still takes around 1.4s, but the application will now mount in __less than 500ms__. I think that's a pretty good result:

<img width="1552" alt="Bildschirmfoto 2022-03-06 um 13 47 03" src="https://user-images.githubusercontent.com/932156/156923862-369bfaaa-17b6-43e4-98f8-3a84dcc8f651.png">

**Comment by squidfunk** [comment] 2022-03-06 13:28
Released as part of 8.2.5.

**Closed by squidfunk** 2022-03-06 13:28 UTC
Labels: enhancement, fix available
