### ISSUE TITLE
Sidebar icons disappear on hover in Safari

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#7380] opened 2024-07-21 17:36 UTC
### Context

Reported at https://github.com/privacyguides/privacyguides.org/issues/2635

### Bug description

When you hover over sidebar items with an icon in Safari the icon disappears:

![2024-07-21 at 12 22 04](https://github.com/user-attachments/assets/7c7a1754-b869-44fe-b84b-fa2e9eed49f8)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/plugins/typeset/
- https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#icons-emojis-in-sidebars

### Reproduction

[9.5.29+insiders.4.53.11-sidebar-icon-safari-bug.zip](https://github.com/user-attachments/files/16325461/9.5.29%2Binsiders.4.53.11-sidebar-icon-safari-bug.zip)

### Steps to reproduce

1. Add an icon to a page's front matter
2. Hover over page in navigation

### Browser

Safari

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-07-21 19:06
Thanks for reporting. Very weird catch. I think this is a rendering bug. I can reproduce it on Safari, but if I open the inspector, the bug cannot be observed – a heisenbug. Additionally, if I zoom in and out, the bug is fixed. Super strange...

**Comment by squidfunk** [comment] 2024-07-21 19:24
I think I fixed it in 906e966d6dcf77cce0ac4410d60c789007e8fd5a. It's seems to be similar to #3396, since adding `position: relative` fixes the issue, at least for me. Can you confirm?

**Comment by squidfunk** [comment] 2024-07-23 07:15
Released as part of [9.5.30](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.30).

**Closed by squidfunk** 2024-07-23 07:15 UTC
Labels: bug, resolved
