### ISSUE TITLE
Instant navigation: toc item requires two clicks after navigating away and returning

### ISSUE THREAD

**Issue by rachel-rigdon-sp** [squidfunk/mkdocs-material#7183] opened 2024-05-14 21:28 UTC
### Bug description

When using Instant Loading, selecting a link in the table of contents, navigating away, returning, and then selecting the same toc item does not jump to the id until the second click. 

I've confirmed this in Chrome, Firefox, and Edge.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://github.com/squidfunk/mkdocs-material/discussions/7050#discussioncomment-9437568

### Reproduction

[9.5.22+insiders.4.53.8-instant-nav-bug-repro.zip](https://github.com/squidfunk/mkdocs-material/files/15313886/9.5.22%2Binsiders.4.53.8-instant-nav-bug-repro.zip)

### Steps to reproduce

1. Select a right-side toc item.
2. Use the left-side navigation to go to another page.
3. Use the left-side navigation to return to the first page.
4. Select the same right-side toc item. It now requires two clicks to navigate to.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-05-15 05:12
Thanks for reporting! I'll investigate.

**Comment by squidfunk** [comment] 2024-05-15 05:33
Fixed in 485fa76fbc086f9b99f2291fbc0c6052c5a32d79! Thanks for the excellent issue and reproduction, that made isolating and fixing the issue really easy. The problem was that the `pathname` change was not properly detected, which is now ensured by the `document$` subscription and the double switch map on `location$`. The comment explains how it works:

https://github.com/squidfunk/mkdocs-material/blob/485fa76fbc086f9b99f2291fbc0c6052c5a32d79/src/templates/assets/javascripts/integrations/instant/index.ts#L366-L378

Perfect issue! Thanks for taking the time.

**Comment by rachel-rigdon-sp** [comment] 2024-05-15 13:51
Thank you so much for the fix! 🙌🏻

**Comment by squidfunk** [comment] 2024-05-15 15:41
Released as part of [9.5.23](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.23).

**Closed by squidfunk** 2024-05-15 15:41 UTC
Labels: bug, resolved, 🏆 perfect

**Comment by soronpo** [comment] 2024-05-19 13:14
Thank you so much!
