### ISSUE TITLE
Table of contents items sometimes don't blur on fast scrolling

### ISSUE THREAD

**Issue by makshh** [squidfunk/mkdocs-material#117] opened 2017-01-17 01:06 UTC
## Description

When I scroll through the documentation up and down some items in table of contents are not blurring (not always), also I'm not sure if states are updating on resize.

![Scrollfix](http://image.prntscr.com/image/1ce85362aecd432d86dadc6588b301e0.png)

### Expected behavior

Properly blurred elements

### Actual behavior

Items are not blurring properly when scrolling up and down

### Steps to reproduce the bug

1. Open for example release notes (demo page)
2. Scroll up and down (fast enough) to see that some items are not blurring

### Package versions
- MkDocs: 0.16.1
- Material: 1.0.2

### System information

- OS: MacOS
- Browser: Chrome/Firefox

This is a problem for me because I would like to always show only one expanded menu in table of contents (to save some space).

**Suggestion** [Bootstrap documentation approach](http://getbootstrap.com/components/) (I think it is a lot easier to determine where I'm on the site when I see active state of current elements rather than blurred scrolled elements. Also, it's nice that they show only one 2nd level menu at a time.

[Here is also a cool idea.](http://codepen.io/hakimel/pen/BpKNPg)

I like your idea with blurring elements and how it looks/animate when I scroll, but I think it's not that good for end user experience.

**Comment by squidfunk** [comment] 2017-01-17 09:01
The scrollfix is something else - it's targeted at the iPhone. You should not use this attribute for styling, as it is totally unrelated to blurring. However, I will look into the blurring when I find the time. 

The link you posted is in my opinion too distracting. I tried to make it as light as possible, so it doesn't get a lot of intention, because it's unimportant while scrolling - in my opinion the information is only needed when the user looks explicitly for the TOC.

**Comment by makshh** [comment] 2017-01-17 12:17
I meant `data-md-state="blur"` instead of scrollfix. Can I use this to style elements?

**Comment by squidfunk** [comment] 2017-01-17 13:11
Sure, it's related to the thing you're trying to accomplish.

**Comment by squidfunk** [comment] 2017-01-18 09:18
I tried to reproduce this yesterday but did not manage to. Can you provide a more detailed instruction how to reproduce?

**Comment by makshh** [comment] 2017-01-18 11:22
It's nothing special. I'm just opening your demo page and start scrolling, what I noticed is that it always works properly when I scroll for the first time (scroll speed doesn't matter). You can even try it with moving browser scrollbar using mouse. I tried this on Chrome and Firefox (on Firefox it's better, it occurs only when I try to scroll using browsers scrollbar instead of mouse wheel).

[Video link](https://sendvid.com/5tjqi13h)

**Comment by squidfunk** [comment] 2017-01-18 11:43
Managed to reproduce it scrolling with the scrollbar - not really used to on the Mac. Will provide a fix.

**Comment by squidfunk** [comment] 2017-01-22 12:06
Fixed in `master` with #32ffc58d128111031a085126ed36e8aee2dabd88. As soon as you confirm your bug fixed, I can release 1.0.3.

**Comment by makshh** [comment] 2017-01-22 12:29
It's fixed.

**Closed** 2017-01-22 13:01 UTC
Labels: bug
