### ISSUE TITLE
emojis in blog title render incorrectly on tags page

### ISSUE THREAD

**Issue by hellt** [squidfunk/mkdocs-material#5931] opened 2023-08-31 08:13 UTC
### Bug description

When blog title contains an emoji it renders incorrectly on 9.2.6 tags pages

<img width="724" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/5679861/7696e569-1eb8-43bb-b48d-9276540e01cb">
<hr/>
<img width="1500" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/5679861/ac01f3f3-23fd-45e2-8d2c-c287c0b059af">
<hr/>

In 9.1.6 the emojis were stripped on tag pages.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[9.2.6+insiders.4.40.2-emoji-tags.zip](https://github.com/squidfunk/mkdocs-material/files/12484022/9.2.6%2Binsiders.4.40.2-emoji-tags.zip)

### Steps to reproduce

1. add an emoji in the blog title
2. see how it is rendered on the tags page

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-08-31 08:17
Thanks for reporting. Duplicate of #5893, which was identified as an upstream issue and a regression in MkDocs 1.5:

- https://github.com/mkdocs/mkdocs/issues/3357

**Closed by squidfunk** 2023-08-31 08:17 UTC

**Comment by hellt** [comment] 2023-08-31 08:21
thanks @squidfunk 
is there a known workaround besides removing html from blog titles?

**Comment by squidfunk** [comment] 2023-08-31 09:05
Downgrade MkDocs to 1.4.x, but that would also mean you would need to go back to 9.1.21. If youÄ're using Insiders, this shouldn't be a big problem, but if not, you'll be losing blogging functionality. I really hope this will be fixed soon.
