### ISSUE TITLE
insiders 4.19.0 container fails to build with `Config value: 'plugins'. Error: The "git-revision-date-localized" plugin is not installed` error

### ISSUE THREAD

**Issue by hellt** [squidfunk/mkdocs-material#4058] opened 2022-06-25 19:25 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Automated pipeline for building insiders container fail with `Config value: 'plugins'. Error: The "git-revision-date-localized" plugin is not installed` for 4.19.0 version.
Previous versions do not have this isssue

<img width="825" alt="image" src="https://user-images.githubusercontent.com/5679861/175787870-f720a774-0d60-4ab4-aa56-4eb0e57812cc.png">

### Expected behaviour

build succeeds

### Actual behaviour

build fails

### Steps to reproduce

1. start building container image using pipelines from insiders repo

### Package versions

NA

### Configuration

```yaml
NA
```

### System information

NA

**Comment by squidfunk** [comment] 2022-06-25 19:44
Thanks for reporting. However, the plugin is optional, so it shouldn't fail. Authors should add the plugin themselves before building the container. Could you please provide a minimum reproducible example? Are you just building your fork or did you make changes?

**Comment by squidfunk** [comment] 2022-06-25 19:46
Ah wait. I think I know where this is coming from – the "checking" is done against our `mkdocs.yml` file, which defines the plugin. Since it is not installed, the check is not successful and the build fails. I see how we can exempt the plugin.

**Comment by hellt** [comment] 2022-06-25 19:56
I am following insiders installation manual and building a container out of unmodified insiders repo as I am using containerized mkdocs material package to build docs (not pip-based build)

My expectation was that the container that gets build in this job should have the necessary plugins for mkdocs-material to work (I do not see why it is useful to exclude some plugins, tbh).
Up till 4.19.0 it was working fine for me

**Comment by squidfunk** [comment] 2022-06-25 20:16
In general, we want to keep the image as small as possible. However, we can certainly add the following plugins, as they're now supported by Material for MkDocs Insiders and I expect an increasing number of people to be using them:

- `mkdocs-git-committers-plugin`
- `mkdocs-git-revision-date-localized`

**Comment by squidfunk** [comment] 2022-06-25 20:21
Fixed in squidfunk/mkdocs-material-insiders@1b25b3c1c59f0cc7032d5776ff88d8234859ba87 and released as part of 8.3.8+insiders-4.19.1

**Closed by squidfunk** 2022-06-25 20:21 UTC
Labels: input needed

**Comment by hellt** [comment] 2022-06-25 21:12
@squidfunk there is that issue with git security and gh actions that results in build failure
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/5679861/175790614-2480ade9-5a72-4001-8f30-c6f6db0f5c8e.png">

it can be fixed if you change the `docker run` command that test the build as follows

```bash
# before
docker run --rm -i -v ${PWD}:/docs ghcr.io/srl-labs/mkdocs-material-insiders build

# after
docker run -v ${PWD}:/docs --entrypoint ash ghcr.io/srl-labs/mkdocs-material-insiders -c 'git config --global --add safe.directory /docs; mkdocs build'
```

ref: https://github.com/srl-labs/learn-srlinux/blob/main/.github/workflows/cicd.yml#L70

**Comment by hellt** [comment] 2022-06-26 09:04
created a PR for insiders - https://github.com/squidfunk/mkdocs-material-insiders/pull/39
