### ISSUE TITLE
Same-page search result does not close search dropdown if search.highlight is disabled

### ISSUE THREAD

**Issue by jbms** [squidfunk/mkdocs-material#4829] opened 2023-01-05 04:26 UTC
### Bug description

When the `search.highlight` feature is disabled, and a search result URL is exactly the same as the current URL and contains a `#fragment`, then clicking on the search result does not close the search dropdown, which is confusing.

Additionally, there is some inconsistency as to whether the search query remains in the search bar:

- If `navigation.instant` is enabled, then the query always remains in the search bar after selecting a result
- If `navigation.instant` is disabled and `search.highlight` is enabled, the query never remains in the search bar after selecting a result, since the addition of the highlight term to the query string means the page is always reloaded.
- If `navigation.instant` is disabled and `search.highlight` is disabled, then if the result is on the same page, the query remains, otherwise the query does not remain.

### Related links

N/A

### Reproduction
[example.zip](https://github.com/squidfunk/mkdocs-material/files/10354968/example.zip)

### Steps to reproduce
1. Open reproduction in a browser.
2. Click on "Commands" in the right sidebar.
3. Enter "commands" in the search bar.
4. Select the "Commands" section in the search dropdown, and observe that the search dropdown remains open.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment] 2023-01-05 08:04
Thanks for reporting. However, this bug report is incomplete, as it doesn't include a reproduction and steps to reproduce. Please carefully read our new [bug reporting guide](https://squidfunk.github.io/mkdocs-material/bug-report/) and reopen the issue once you've provided all missing information.

**Comment by jbms** [comment] 2023-01-05 08:17
Note: A likely solution to the issue would be to add an `onclick` event handler to the result links that closes the search dropdown.

**Comment by jbms** [comment] 2023-01-05 19:02
I updated the issue description to include a reproduction.

**Comment by squidfunk** [comment] 2023-01-08 09:58
Fixed in 8a812aed8. The search now closes every time a search result is selected. Before, this was not handled, but rarely occurred, because it only affected same-page results for which the location didn't change, i.e. anchor already in view.

---

Thanks for providing the reproduction! I know that you're maintaining Sphinx Immaterial, a Sphinx-port of my work. I also understand that the new bug reporting process might feel a little boilerplatey at first, but it greatly helps us to provide bug fixes much quicker than ever before. Thanks for sticking to it!

**Comment by squidfunk** [comment] 2023-01-08 12:07
Released as part of [9.0.3](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.3).

**Closed by squidfunk** 2023-01-08 12:07 UTC
Labels: bug, fix available
