### ISSUE TITLE
`superfences` and `terraform` example generates duplicate output

### ISSUE THREAD

**Issue by michaelbrewer** [squidfunk/mkdocs-material#4238] opened 2022-08-11 06:58 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When creating an example with `<<` in to, the contents after is include twice ie:

````
```teraform
<<a
x
```
````

### Expected behaviour

Output should be:

```
<<a
x
```

### Actual behaviour

renders as

```
<<a
x
x
```

### Steps to reproduce

1. Create new blank project

```
python3 -m venv .venv
source .venv/bin/activate
pip install mkdocs-material
mkdocs new .
```

2. Update mkdocs.yml to be

```yaml
site_name: Example
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences
```

3. update index.md to be

````
```teraform
<<a
x
```
````

4. run `mkdocs serve`

Output will be

```
<<a
x
x
```

Or

1. `git clone https://github.com/michaelbrewer/mkdocs-github-issue.git`
2. `make dev serve`

### Package versions

- Python: `python --version`:  
Python 3.9.13
- MkDocs: `mkdocs --version`
mkdocs, version 1.3.1 from /Users/michaelbrewer/projects/python/mkdocs-eof/.venv/lib/python3.9/site-packages/mkdocs (Python 3.9)
- Material: `pip show mkdocs-material | grep -E ^Version`
Version: 8.3.9

### Configuration

```yaml
site_name: Example
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences
```

### System information

- Operating system: ...
- Browser: ...

**Comment by facelessuser** [comment] 2022-08-11 12:13
1. Posting images is fine, but if you are posting an example, please post it in plain text that can be copied and pasted as well.
2. Material is a theme, not a parser, `pymdownx.superfences` is an upstream dependencies that I maintain, so any bugs related to it should be filed on its [repo](https://github.com/facelessuser/pymdown-extensions).

Now, that I have all that out of the way 🙂...

I'm not sure what the squiggle line is, I assume that is an editor thing and doesn't relate to the actual text, but when I use:

````markdown
```teraform
<<a
x
```
````

I cannot reproduce:

<img width="630" alt="Screen Shot 2022-08-11 at 6 11 04 AM" src="https://user-images.githubusercontent.com/1055125/184130497-9d099e3f-5623-4398-b363-219dfde89e42.png">

We see when running just this plugin, as you've indicated above, that there are no issues:

````py
import markdown

MD = """
```teraform
<<a
x
```
"""

print(markdown.markdown(MD,  extensions=['pymdownx.superfences']))
````

Output:

```html
<div class="highlight"><pre><span></span><code>&lt;&lt;a
x
</code></pre></div>
```

**Comment by michaelbrewer** [comment] 2022-08-11 16:25
I will post a link to a repo example.

**Comment by facelessuser** [comment] 2022-08-11 16:54
Again, if you are able to reproduce with a minimal example, I'd create an issue over at the pymdown-extensions repo. Material is likely to have nothing to do with this issue. I'm more inclined to believe that you are using some other extension or MkDocs plugin that is interfering and causing this issue, but without a reproducible example, I can only guess at this point.

**Comment by michaelbrewer** [comment] 2022-08-11 17:01
It's easy to reproduce. I will push an issue there. And link the issues together.

**Comment by michaelbrewer** [comment] 2022-08-11 20:44
Deployed example is here: https://michaelbrewer.github.io/mkdocs-github-issue/

and source code is here: https://github.com/michaelbrewer/mkdocs-github-issue

I will add an issue on https://github.com/facelessuser/pymdown-extensions too

**Comment by michaelbrewer** [comment] 2022-08-11 20:58
````python3
import markdown

MD = """
```terraform
<<a
x
```
"""

print(markdown.markdown(MD,  extensions=['pymdownx.superfences']))
````

will output 

```html
<div class="highlight"><pre><span></span><code><span class="o">&lt;&lt;</span><span class="dl">a</span><span class="sh"></span>
<span class="err">x</span>
<span class="err">x</span><span class="w"></span>
</code></pre></div>
```

**Comment by michaelbrewer** [comment] 2022-08-11 21:06
Issue would logged at https://github.com/facelessuser/pymdown-extensions/issues/1784

**Comment by facelessuser** [comment] 2022-08-11 21:14
As I mentioned in the pymdown-extensions, this actually appears to be a Pygments bug as it can be reproduced simply by using their terraform highlighter in their online tool.

**Comment by michaelbrewer** [comment] 2022-08-11 22:56
Logged at the level down : https://github.com/pygments/pygments/issues/2205

**Comment by squidfunk** [comment] 2022-08-12 08:59
Thanks for your time researching, @facelessuser and @michaelbrewer. Closing as upstream issue.

**Closed by squidfunk** 2022-08-12 08:59 UTC

**Comment by michaelbrewer** [comment] 2022-08-13 01:15
pygments 2.13.0 will have this fixed when released

**Comment by facelessuser** [comment] 2022-08-13 01:21
Awesome! Glad we were able to narrow it down.
