### ISSUE TITLE
Social Cards Config Values Unrecognized

### ISSUE THREAD

**Issue by MasonEgger** [squidfunk/mkdocs-material#6824] opened 2024-02-24 16:41 UTC
### Context

I am trying to add social cards to my site using the latest Insiders build, and I keep getting an error that the configurations specified in the documentation are unrecognized.

### Bug description

I have the added the following plugin information to my `mkdocs.yml`
```
plugins:
  - search
  - social:
      cards_layout_dir: layouts
      cards_layout: custom
      debug: true
 ```
and created these directories as specified in the documentation. However, I keep getting the following Warning

```
WARNING -  Config value 'plugins': Plugin 'material/social' option 'debug': Unrecognised
           configuration name: debug
WARNING -  Config value 'plugins': Plugin 'material/social' option 'cards_layout_dir':
           Unrecognised configuration name: cards_layout_dir
WARNING -  Config value 'plugins': Plugin 'material/social' option 'cards_layout':
           Unrecognised configuration name: cards_layout
```

And the social cards are not being generated to the specification in `custom.yml`

### Related links

- [Social Card Customization](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#customization)

### Reproduction

[issue.zip](https://github.com/squidfunk/mkdocs-material/files/14393627/issue.zip)

### Steps to reproduce

1. Unzip the file
2. Run `mkdocs build`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by kamilkrzyskow** [comment] 2024-02-24 23:11
Hello @MasonEgger,
the error indicates that you're using the base `mkdocs-material` version without Insiders. 
You can check it using `pip show mkdocs-material` and the version should have a `+Insiders` and not just `9.5.11`

The `issue.zip` file you've provided wasn't created using the `info` plugin, as per the instructions: 
- https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file

Your `requirements.txt` file also contains `mkdocs-material==9.5.5`, so not the Insiders version. 
As a side-note I consider this file a bit over the top given how many packages it shows, unless it's only a temporary `pip freeze > requirements.txt` generated for the zip example.

So make sure you have Insiders installed:
```
pip uninstall mkdocs-material
pip install git+https://github.com/squidfunk/mkdocs-material-insiders
```

If the second command doesn't work then your `git` isn't configured with the account that has access to the repository.
Perhaps you'll have to use your GH_TOKEN: https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#installation

**Comment by squidfunk** [comment] 2024-02-25 01:21
Thanks for troubleshooting @kamilkrzyskow – the `requirements.txt` clearly shows that Insiders is not (correctly) installed. I'm closing this issue, since nothing has to be done on our side.

**Closed by squidfunk** 2024-02-25 01:21 UTC
