### ISSUE TITLE
Possible regression in Blog functionality

### ISSUE THREAD

**Issue by mikegrima** [squidfunk/mkdocs-material#5973] opened 2023-09-05 19:34 UTC
### Context

Hello:

I was utilizing the blog feature with the beta release 9.2.0b2. Dependabot has made updates to the latest version of `mkdocs-material`, and in the latest release there appears to be a regression.

### Bug description

When running `mkdocs build` or `mkdocs serve` on the latest versions of `mkdocs-material` (9.2.8), I encounter the following stack trace:

```python
mkdocs: commands[0]> mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/starfleet/starfleet/site
Traceback (most recent call last):
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/click/core.py", line [143](https://github.com/gemini-oss/starfleet/pull/91/checks#step:5:144)4, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/mkdocs/commands/build.py", line 311, in build
    nav = config.plugins.on_nav(nav, config=config, files=files)
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/mkdocs/plugins.py", line 536, in on_nav
    return self.run_event('nav', nav, config=config, files=files)
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
  File "/home/runner/work/starfleet/starfleet/.tox/mkdocs/lib/python3.10/site-packages/material/plugins/blog/plugin.py", line 180, in on_nav
    items[items.index(page)] = self.blog
ValueError: SectionPage(title='Blog', url='/starfleet/blog/') is not in list
mkdocs: exit 1 (0.84 seconds) /home/runner/work/starfleet/starfleet> mkdocs build pid=2686```
```

Here is a link to the GH action where this is happening: https://github.com/gemini-oss/starfleet/pull/91/checks

When going from the beta release of `9.2.0b2` to `9.2.8`, I had to make a change to the `.authors.yml` file, which I did accordingly: https://github.com/gemini-oss/starfleet/pull/91/files#diff-587acea3a21bb5b4b2aee25b9d125cbbb7611164d7e41b31bf1c91ffa15676f7.

However, for some reason, all real versions after the beta releases cause an issue. I haven't had time to pop a debugger in, but just wanted to get this documented in case anyone else saw this.

I see the error above regardless if I have the link to the blog in `mkdocs.yml`. That file is here: https://github.com/gemini-oss/starfleet/blob/main/mkdocs.yml.  I also made no changes to this file; only change made was to the authors file since the initial error message informed me of the schema change.

Also while going through the bug reporting page, I followed the instructions to disable the extra css as well as the `gen_files` plugin and it had no impact.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Source Repo](https://github.com/gemini-oss/starfleet/tree/main)
- [Draft PR to update version](https://github.com/gemini-oss/starfleet/pull/91)
- [Blog instructions that I followed](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#built-in-blog-plugin)
- [GH Actions output showing errors](https://github.com/gemini-oss/starfleet/actions/runs/6053763316/job/16429898851?pr=91)

### Reproduction

[9.2.8-blog-regression.zip](https://github.com/squidfunk/mkdocs-material/files/12527718/9.2.8-blog-regression.zip)

### Steps to reproduce

1. Update to the latest mkdocs and mkdocs material versions on PyPI
2. Run `mkdocs serve` or `mkdocs build`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-09-05 21:20
Thanks for reporting. This is a duplicate of https://github.com/squidfunk/mkdocs-material/issues/5971 – it's related to the section index plugin, where `SectionPage` is coming from (see stack trace). I think it was already reported upstream, but you should check back with the maintainer.

- https://github.com/oprypin/mkdocs-section-index/issues/18

**Closed by squidfunk** 2023-09-05 21:20 UTC

**Comment by squidfunk** [comment] 2023-09-05 21:40
Possible workaround: remove section-index and use Material for MkDocs [`navigation.indexes`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages) feature. If that doesn't work, please provide a minimal reproduction without the use of external plugins and we're happy to investigate.

**Comment by oprypin** [comment] 2023-09-05 23:04
It is not a duplicate of https://github.com/squidfunk/mkdocs-material/issues/5971

**Comment by squidfunk** [comment] 2023-09-06 05:56
@oprypin thanks for investigating! Checking again, it looks related to the fact that the section index plugin [replaces the page](https://github.com/oprypin/mkdocs-section-index/blob/8c064b04fc1e0eeeed60f3c671c9e0f7eb834654/mkdocs_section_index/plugin.py#L42-L43) in the navigation, so the page that was priorly assigned to the blog does not exist in the navigation anymore. Note that we currently have a hack in place to mount the blog at the correct location in the navigation:

https://github.com/squidfunk/mkdocs-material/blob/6ffc9f4364f30739a5b1342c17d375cf90e4a9c9/src/plugins/blog/plugin.py#L170-L192

This hack assumes that [the page that MkDocs created in `_data_to_navigation`](https://github.com/mkdocs/mkdocs/blob/94e9f17cd7a69e70c18ae282d55ba2f34f93c542/mkdocs/structure/nav.py#L203-L204) is still part of the navigation, which conflicts with the behavior of the section index plugin that replaces it, as it runs before the blog plugin due to the defined event priorities that we use in the blog plugin:

https://github.com/squidfunk/mkdocs-material/blob/6ffc9f4364f30739a5b1342c17d375cf90e4a9c9/src/plugins/blog/plugin.py#L161-L166

We already raised an issue upstream saying that MkDocs should probably allow plugins to create their own page objects to implement custom behaviors, which is, for example, necessary for blog posts, as all metadata must be available to generate archive and catgory files/pages, which we generate in `on_files`. We also proposed a PR to implement this proposal:

- https://github.com/mkdocs/mkdocs/issues/3367
- https://github.com/mkdocs/mkdocs/issues/3366

In general, it looks like it's a good time to rethink navigation population and page construction in MkDocs to allow for more sophisticated plugins like the blog plugin. The section index plugin also uses a (rather unorthodox? not sure) approach to circumvent the behavior that is fixed by the aforementioned PR [here](https://github.com/oprypin/mkdocs-section-index/blob/8c064b04fc1e0eeeed60f3c671c9e0f7eb834654/mkdocs_section_index/plugin.py#L33-L34).

Happy for any feedback and to gravitate towards a solution that makes the plugin ecosystem work together in a better and more empowering way ☺️ Until then, we must consider the section index plugin being incompatible with the blog plugin. As mentioned before, the `navigation.indexes` feature might be a good replacement, albeit there are currently still some minor issues that we need to work out:

- https://github.com/squidfunk/mkdocs-material/issues/5972

**Comment by mikegrima** [comment] 2023-09-06 19:51
Happy to report that using `navigation.indexes` works. I don't notice any differences between that and the prior plugin so I'm going to stick with `navigation.indexes`.

Thank you all!

**Comment by squidfunk** [comment] 2023-09-07 05:37
Thanks for checking back!
