### ISSUE TITLE
Automatic switch of dark mode / light mode

### ISSUE THREAD

**Issue by jrappen** [squidfunk/mkdocs-material#3244] opened 2021-11-23 12:34 UTC
### Description

With this config:

```yaml
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark-mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/theme-light-dark
        name: Switch to light-mode
```

or this config:

```yaml
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: indigo
      # toggle:
      #   icon: material/theme-light-dark
      #   name: Switch to dark-mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: red
      # toggle:
      #   icon: material/theme-light-dark
      #   name: Switch to light-mode
```

...

### Expected behaviour

... I would have assumed that MkDocs Material:

- [x] applies the color scheme for dark or light mode according to the system
- [ ] switches back and forth following the system when it changes

### Actual behaviour

... but it doesn't switch after the initial set up when changing the color scheme of the sytem.

### Package versions

- Python: `3.9.8`
- MkDocs: `1.2.3`
- MkDocs Material: `7.3.6`

**Comment by squidfunk** [comment] 2021-11-23 12:40
Duplicate of #3123

**Closed by squidfunk** 2021-11-23 12:40 UTC

**Comment by jrappen** [comment] 2021-11-23 14:09
this is rather a duplicate of #2727

**Comment by squidfunk** [comment] 2021-11-23 15:19
Yes, #2727 is also related, but #3123 explains in more detail why this change is currently unsupported and why it's not trivial to add. If you would like to work in this, a PR is appreciated. Please note https://github.com/squidfunk/mkdocs-material/issues/3123#issuecomment-945935509 and my other comments.

**Comment by squidfunk** [comment] 2022-06-11 09:34
I'm happy to announce that automatic dark/light mode was finally implemented and just released as part of [8.3.4+insiders-4.18.0.](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.18.0) I invite you to test-drive it on [our documentation](https://squidfunk.github.io/mkdocs-material/). Here's a short video showing how it works:

https://user-images.githubusercontent.com/932156/173182190-f5f9ab50-1a1e-414d-8184-530843f3362f.mp4

**Comment by mendax1234** [comment] 2023-07-23 04:07
Hi, @squidfunk After copying the example auto dark theme code into the `mkdocs.yml`, my website still can't change to the dark theme automatically. What else should l add to my project? Thanks!

**Comment by squidfunk** [comment] 2023-07-23 10:38
@mendax1234 are you using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/)? Note that [automatic dark mode](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode) is currently reserved to sponsors. If you're using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/), you followed our documentation and it doesn't work, please create a new issue with a reproduction.

**Comment by mendax1234** [comment] 2023-07-23 10:42
@squidfunk Sorry, I'm not an Insider and l was not familiar with how mkdocs-material theme works before.

**Comment by squidfunk** [comment] 2023-07-23 10:46
It's a good idea to read the Insiders guide to learn about our funding model. Additionally, all features that are reserved to sponsors are marked with a big __Sponsors only__ notice 😊
