### ISSUE TITLE
Automatically position the left navigation to the current page

### ISSUE THREAD

**Issue by walkccc** [squidfunk/mkdocs-material#2155] opened 2020-12-27 05:56 UTC
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Hi @squidfunk, thanks for providing this beautiful theme. 
I have an idea. Is it possible to position the left navigation to the current page?

### Use Cases

If we have over 1,000 pages, then for example, if we click on page 500, since it's not initially on the left nav (due to the height of the screen), after the rendering, we still can not see where we are in the left nav, and we have to scroll the scrollbar manually.

Maybe allowing the left navigation to automatically "position" with the current page is a good idea. No matter it's a click or by the search.

### Screenshots / Mockups

For example, when I click "1391. Check if There is a Valid Path in a Grid" page, the website will look like the following. In this way, I have no idea "where I am."

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/14782909/103164738-fa246b00-47dc-11eb-847a-a1b535ed208e.png">

However, I hope it look something like this:

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/14782909/103164744-0c9ea480-47dd-11eb-9b40-44a085936664.png">

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

Thank you.

**Comment by squidfunk** [comment] 2020-12-27 09:54
Thanks for suggesting. This was already proposed in #1271 and #1567, but there wasn't much feedback besides the OPs, so it seems that it's not really needed by many users. Let's see if this issue gets some upvotes 😊

**Comment by weitzman** [comment] 2020-12-27 10:46
Same issue at https://www.drush.org/commands/10.x/watchdog_show/. I've added my thumbs-up reaction to the initial post.

**Comment by squidfunk** [comment] 2020-12-30 11:08
Turns out this is pretty tricky to get right. The naive solution would be to use `Element.scrollIntoView`, but that yields inconsistent behavior across browsers and sometimes will re-position the entire page, which is very undesirable. I'm investigating other possibilities.

**Comment by squidfunk** [comment] 2020-12-30 11:52
Here's a working prototype for the table of contents, which will even follow when the user keeps on scrolling: https://twitter.com/squidfunk/status/1344249178168418304

I think we should solve this for both sidebars and allow to enable this functionality with two new feature flags.

**Comment by weitzman** [comment] 2020-12-30 12:57
Looks great. 

-  This works for the initial page view, or it only kicks in after a scroll? Initial page view is preferable.
- I agree that both sidebars are ideal.

**Comment by squidfunk** [comment] 2020-12-30 15:51
The idea is that the active entry is always visible, which also includes the initial load.

**Comment by AltarBeastiful** [comment] 2021-04-14 15:03
Looks great ! I believe only on initial page view will already solve many docs where the left menu is long, and we want to read the articles in a sequence. Is there a branch where you started work on this ? 

For reference, readthedocs solves that perfectly by scrolling the menu entry selected on top of the page : 
![menutotopreadthedocs](https://user-images.githubusercontent.com/3317699/114731896-62726a80-9d42-11eb-8f2b-d09fcf4bdad8.gif)

For comparison, when going through the articles of the FastAPI documentation, I'm having to scroll the menu each time to reach the next article :

![menutotomkdocs](https://user-images.githubusercontent.com/3317699/114732691-04925280-9d43-11eb-9fc5-d03c93d36282.gif)

**Comment by squidfunk** [comment] 2021-04-14 15:21
> Is there a branch where you started work on this?

Not yet! However, given the popularity of this feature request, I'll tackle it as one of the next things to implement.

**Comment by squidfunk** [comment] 2021-04-18 12:30
I've added experimental support for positioning correction in Insiders. I'm still figuring out how to generalize this for the table of contents and mobile view (as we have multiple layered panes on mobile), but when you [browse the Insiders documentation](https://squidfunk.github.io/mkdocs-material-insiders/reference/mathjax/) and reduce the height of the window (the lists are not that long), the positioning is automatically corrected.

Just stepping through the pages by pressing `n` (= next page) on the keyboard yields:

https://user-images.githubusercontent.com/932156/115145457-f0f03000-a051-11eb-8dc9-566c60e9d445.mp4

**Comment by squidfunk** [comment] 2021-07-10 16:31
I'm closing this issue, as Insiders will automatically position the navigation as originally proposed 😊 This was not a dedicated feature but a "silent" improvement. I'm revisiting the positioning later when I address the table of contents.

**Comment by alkisg** [comment] 2021-11-18 10:27
When can we expect this feature in the open version?
I don't see it in the [funding roadmap](https://squidfunk.github.io/mkdocs-material/insiders/#funding)...

**Comment by squidfunk** [comment] 2021-11-18 10:33
The reason it's not on the roadmap is it's still in prototype stage. I need to generalize the code to also apply to the table of contents. Since there were essentially no reactions on my last two comments, I've concluded that it isn't a priority.

**Comment by alkisg** [comment] 2021-11-18 10:39
Well personally I thought that since this issue was closed, it means it was already fixed, and it was only a matter of time to see it in the open version.

Do you need more input? If so, I would suggest that you reopen it, so that people know that the effort is ongoing...
(my experience from open source so far says that for every user that comments in an issue, there are 100-1000 more that are affected and don't even know how to locate the relevant issue, in order to even just press an upvote button...)

**Comment by squidfunk** [comment] 2021-11-18 11:08
Sure, we can reopen it until I manage to wrap this up with the table of contents and assign it to a funding goal.

> Do you need more input?

Well, at least some feedback would be great, yes. Fixing this issue, nobody left any feedback in nearly 3 months, which I read as no real interest from users. For this reason, I closed it, but I agree that it's good to put a label on when this will be released for general availability. As I wrote before, since there was no interest, I've considered it a prototype that is not ready for release.

**Comment by kgidarakos** [comment] 2021-11-18 11:25
I'd like to see this feature too.
Thanks in advance

**Comment by squidfunk** [comment] 2021-11-20 07:47
@kgidarakos it's already available in [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) – it's just not ready for official release. If you check out the [documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/) and make the page narrower so that the menu will overflow, you can see it in action. Screenrecording in https://github.com/squidfunk/mkdocs-material/issues/2155#issuecomment-821984363.

**Comment by kgidarakos** [comment] 2021-11-20 14:37
I believe that this feature is basic and by definition on all websites!  I hope you integrate it in the open version! 
Thank you in advance

**Comment by squidfunk** [comment] 2021-11-24 09:43
Again, this feature is already available as part of Insiders as of today. I just need to find some time to wrap it up, so the table of contents does also exhibit the same behavior. It's just in need of some refactoring.

I just updated the funding goals in 3b1ee9fa7ae836d376aa43876c7286a7894823aa and linked this feature to the [Scotch Bonnet](https://squidfunk.github.io/mkdocs-material/insiders/#8000-scotch-bonnet) funding goal.

**Comment by squidfunk** [comment] 2022-02-06 11:46
Insiders 4.8.0 was just released, adding two new features:

#### Sidebars automatically scroll to active item

As mentioned [in this comment](https://github.com/squidfunk/mkdocs-material/issues/2155#issuecomment-821984363), this was already working before, but not polished to a degree where I thought it was worth releasing/announcing. I polished the source in the latest Insiders release so that it reliably works for the navigation, as well as the table of contents. When you visit a page, the sidebar is automatically positioned to the currently active item.

Here's a narrow screenshot for demonstration, illustrating that active items in both sidebars are scrolled into view:

![screenshot-squidfunk-github-io-mkdocs-material-changelog-1644147256490](https://user-images.githubusercontent.com/932156/152678950-222a768e-9940-4341-b564-d783f6158d5b.png)

[Try it](https://squidfunk.github.io/mkdocs-material/changelog/#7.3.4) (narrow your window)

#### Anchor following table of contents

There's a new feature flag called [`toc.follow`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following) that enables anchor following for the table of contents. When the user scrolls, or jumps to another section of the site after the initial load, the active anchor in the table of contents is scrolled into view:

[Try it](https://squidfunk.github.io/mkdocs-material/changelog/#7.0.0) (scroll up and down)

https://user-images.githubusercontent.com/932156/152679223-780c4e6a-c3c0-43ef-8bc0-47c1bdfd3325.mp4

This resolves all problems stated in this issue, as now, the active items in both sidebars are always visible.

**Closed by squidfunk** 2022-02-06 11:46 UTC
Labels: enhancement, fix available

**Comment by pras-ram** [comment] 2022-02-13 13:42
Hi! How do I get this reflected in my current code? I updated to the latest version of MkDocs.

**Comment by squidfunk** [comment] 2022-02-13 13:47
This feature is currently only available through the [Insiders build](https://squidfunk.github.io/mkdocs-material/insiders/). If you want to use it right now, you're invited to [become a sponsor](https://squidfunk.github.io/mkdocs-material/insiders/#how-to-become-a-sponsor) and enroll in the Insiders program. You'll be granted access to the private repository in minutes and can use [all Insiders features](https://squidfunk.github.io/mkdocs-material/insiders/#available-features). Otherwise, you'd have to wait until [the funding goal is hit](https://squidfunk.github.io/mkdocs-material/insiders/#8000-scotch-bonnet).

**Comment by wilhelmer** [comment] 2022-02-25 16:33
@squidfunk There are strange things going on with the "Sidebars automatically scroll to active item" feature. In previous versions of our documentation, it worked in all browsers. Now, it only works in Chrome, but not in Firefox. I don't know which version caused the change, it's difficult to track down.

Can you confim it's not working in FF 97?

**Comment by squidfunk** [comment] 2022-02-25 16:40
Yes, I can confirm that it doesn't work in Firefox anymore. Please create a new issue, I'll look into it asap.

**Comment by SteniMariyaThomas** [comment] 2023-10-10 06:48
This is woring in mkdocs-material version 8.5.0 (https://squidfunk.github.io/mkdocs-material/changelog/#8.5.0)

But not working in latest version of mkdocs-material (9.4.4)

**Comment by squidfunk** [comment] 2023-10-10 08:26
@SteniMariyaThomas thanks, I looked into it any you're right. This is a regression triggered by the new animated sidebars. 

Fixed in 5824c6ca4e1323e199b92637fba03960c95b3f38.

**Comment by SteniMariyaThomas** [comment] 2023-10-10 09:53
> @SteniMariyaThomas thanks, I looked into it any you're right. This is a regression triggered by the new animated sidebars.
> 
> Fixed in [5824c6c](https://github.com/squidfunk/mkdocs-material/commit/5824c6ca4e1323e199b92637fba03960c95b3f38).

Thank you
