### ISSUE TITLE
Switching palette causes scroll position jump on Firefox

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#5939] opened 2023-09-01 09:18 UTC
### Bug description

The scroll position jumps upwards upon clicking the palette toggle on Firefox (v117.0, Ubuntu 20.04). For instance, if you scroll to the bottom of a page, then clicking the palette toggle several times will move the scroll position to the top of the page eventually. This is certainly not desired behavior.

It works fine for me on Chromium.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[9.2.6-palette-toggle-scroll-position.zip](https://github.com/squidfunk/mkdocs-material/files/12497425/9.2.6-palette-toggle-scroll-position.zip)

### Steps to reproduce

1. Open any page of the docs in the reproduction.
2. Scroll down, e.g. to the bottom of the page.
3. Click the palette toggle and observe how the scroll position jumps upwards upon every click of the toggle.

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by nejch** [comment] 2023-09-01 09:45
Just giving extra context:
* Fedora 38 amd64
* Firefox 116 I couldn't reproduce this.
* Firefox 117, after upgrade, I also get this behavior. 

---

[Screencast from 2023-09-01 11-43-45.webm](https://github.com/squidfunk/mkdocs-material/assets/16777978/bb63ded4-dcb3-491b-a978-2f1bad9180d3)

**Comment by squidfunk** [comment] 2023-09-01 10:49
> Simply follow the reproduction steps below, no need for a self-contained reproduction artifact.

Thanks for reporting. However, please provide a minimal reproduction. It is necessary, because it allows us to fix the bug much quicker. Otherwise we have to create the reproduction first.

**Comment by sisp** [comment] 2023-09-01 11:34
Okay, I've update the original post with a minimal reproduction.

**Comment by squidfunk** [comment] 2023-09-02 16:41
Fixed in e79ffab3a. Here's my analysis:

https://github.com/squidfunk/mkdocs-material/blob/e79ffab3ac1c46c5578f4281bbb721b6fbbc6a0f/src/assets/stylesheets/main/components/_header.scss#L244-L250

**Comment by squidfunk** [comment] 2023-09-02 17:09
Released as part of [9.2.7](https://squidfunk.github.io/mkdocs-material/changelog/#9.2.7).

**Closed by squidfunk** 2023-09-02 17:09 UTC
Labels: bug, resolved
