### ISSUE TITLE
Maximum recursion depth error when overriding a partial

### ISSUE THREAD

**Issue by mikegrima** [squidfunk/mkdocs-material#5533] opened 2023-05-19 20:41 UTC
### Context

Hello:

I am trying to add additional items to the footer of my mkdocs site, and am following the instructions here: https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials. However, every time I do this I keep hitting a:

`RecursionError: maximum recursion depth exceeded in comparison` exception when running `mkdocs serve`.

### Bug description

Making an override for a footer with the following directory tree:

```
.
└── project/
    ├── mkdocs.yml
    ├── mkdocs/
    │   ├── index.md
    │   └── ...
    └── mkdocs_overrides/
        └── partials/
            └── footer.html
```

And a `footer.html` with the following:

```
{% extends "partials/footer.html" %}

<h1>Hello!</h1>
```

Will result with the following stacktrace when running `mkdocs serve`:

```python
Traceback (most recent call last):
  File "/DIR/PATHbin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/DIR/PATHlib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/DIR/PATHlib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/DIR/PATHlib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/DIR/PATHlib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/DIR/PATHlib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/DIR/PATHlib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/DIR/PATHlib/python3.10/site-packages/mkdocs/commands/serve.py", line 83, in serve
    builder(config)
  File "/DIR/PATHlib/python3.10/site-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/DIR/PATHlib/python3.10/site-packages/mkdocs/commands/build.py", line 320, in build
    _build_theme_template(template, env, files, config, nav)
  File "/DIR/PATHlib/python3.10/site-packages/mkdocs/commands/build.py", line 118, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/DIR/PATHlib/python3.10/site-packages/mkdocs/commands/build.py", line 97, in _build_template
    output = template.render(context)
  File "/DIR/PATHlib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/DIR/PATHlib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/DIR/PATHlib/python3.10/site-packages/material/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/DIR/PATHlib/python3.10/site-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/DIR/PATHlib/python3.10/site-packages/material/base.html", line 192, in top-level template code
    {% block footer %}
  File "/DIR/PATHlib/python3.10/site-packages/material/base.html", line 193, in block 'footer'
    {% include "partials/footer.html" %}
  File "/DIR/PATH/mkdocs_overrides/partials/footer.html", line 1, in top-level template code
    {% extends "partials/footer.html" %}
  File "/DIR/PATH/mkdocs_overrides/partials/footer.html", line 1, in top-level template code
    {% extends "partials/footer.html" %}
  File "/DIR/PATH/mkdocs_overrides/partials/footer.html", line 1, in top-level template code
    {% extends "partials/footer.html" %}
  [Previous line repeated 973 more times]
  File "/DIR/PATHlib/python3.10/site-packages/jinja2/utils.py", line 466, in get
    return self[key]
  File "/DIR/PATHlib/python3.10/site-packages/jinja2/utils.py", line 504, in __getitem__
    rv = self._mapping[key]
RecursionError: maximum recursion depth exceeded in comparison
```

It's not clear what I'm doing wrong... I just want to add 1 more link to the footer so was trying to do this:
```
{% extends "footer.html" %}

{% block scripts %}
  <!-- Add scripts that need to run before here -->
  {{ super() }}
  <!-- Add scripts that need to run afterwards here -->
{% endblock %}

My extra footer link here.
```

... Unless I'm not remotely close to doing this correctly 😅 

### Related links

https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials

### Reproduction

Code is supplied above.

This is for an open source project with the mkdocs files here: https://github.com/gemini-oss/starfleet

### Steps to reproduce

1. Create the files with the code above
2. Run `mkdocs serve`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-05-20 08:03
Thanks for reporting. AFAIK, you cannot extend partials, you can only override them. You must drop the first line:

```
{% extends "partials/footer.html" %}
```

This has nothing to do with Material for MkDocs, but is the behavior of Jinja you're observing. Closing as upstream issue. Note that it's not really an issue but probably works by design. If you think it doesn't, please take this upstream.

**Closed by squidfunk** 2023-05-20 08:03 UTC

**Comment by mikegrima** [comment] 2023-05-20 12:49
@squidfunk- I just want to add another link to the footer. How do I do that? 😂

**Comment by squidfunk** [comment] 2023-05-20 13:38
Please see https://github.com/squidfunk/mkdocs-material/issues/3273#issuecomment-982475139.
