### ISSUE TITLE
Better documentation of navigation

### ISSUE THREAD

**Issue by staadecker** [squidfunk/mkdocs-material#7585] opened 2024-10-04 22:01 UTC
### Description

The [setting up navigation page](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/) provides many configuration settings but very little information on how to actually

a) organize directories when using e.g. the tabs
b) structure the `nav` section of the `mkdocs.yml` (do you include or not the `.md`? why does it not work for me when I don't lead with a title, etc.)
c) troubleshoot problems with navigation

### Related links

[setting up navigation page](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/)

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by alexvoss** [comment] 2024-10-05 05:00
Part of the problem is that some of this is not specific to Material for MkDocs but is [part of MkDocs itself](https://www.mkdocs.org/user-guide/configuration/#documentation-layout). 

As we have outlined in our recent blog post on [Transforming Material for MkDocs](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/), there are changes coming that we are working on in the background. Part of these changes will be an overhaul of the documentation. I am working on the information architecture for this at the moment and should soon be able to turn to the content. Inevitably, there will be a period of iterating over both, so please bear with us.

The question of how navigation is defined will be a big part of this, especially since it overlaps with [internationalization and versioning](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/#translations-and-versioning), topics that are most definitely on our radar.

**Comment by squidfunk** [comment] 2024-10-05 09:59
Yes the information is fragmented, because the MkDocs ecosystem is fragmented and the information is essentially contained in the MkDocs documentation. We can't mirror everything, but as @alexvoss said, we're working on a huge overhaul. Thus, we're not considering changes to the documentation right now, as it's not an easy fix – we need an entirely new information architecture, which is in the making. Closing as non-actionable.

**Closed by squidfunk** 2024-10-05 09:59 UTC
Labels: documentation
