### ISSUE TITLE
Tags listing is empty

### ISSUE THREAD

**Issue by normandy7** [squidfunk/mkdocs-material#6679] opened 2024-01-22 15:38 UTC
### Context

We have been using a relatively simple tags setup in which we

1. tag each page individually,
2. have a `tags.md` index page that simply lists all the tags.

For now, we just want to keep our current setup after the tags plugin was redone.

### Bug description

Since the tags plugin was redone, I can't get the tags listing to display. Nothing renders where `<!-- material/tags -->` is called.

Out of the extra configuration options, we only use `tags_allowed`. As far as I can tell, the only necessary adjustment should be to change the tags marker from `[TAGS]` to `<!-- material/tags -->`.

It does not matter whether we keep or remove the `tags_file` property and reference the `tags.md` page in the nav -- the tags listing is not rendered either way.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags
- https://squidfunk.github.io/mkdocs-material/plugins/tags/

### Reproduction

I can't provide a reproduction because we build with Insiders and I don't have "manual" access to it.

I did, however, remove all customizations as prescribed in the guidelines, but it did not affect the tags issue.

### Steps to reproduce

`mkdocs.yml` snippet:

```
plugins:
  - meta
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)'
  - tags:
      tags_allowed:
        - admin
        - collaboration
        - comparison
        - debugging
        - model-registry
        - platform
        - reproducibility
        - versioning
        - source-code
        - time-series
        - computer-vision
        - nlp
        - tabular-data
  - typeset

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: ["./reuse/"]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"
      permalink_title: Link to section
      toc_depth: 3
```

### Browser

- Chrome
- Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2024-01-23 00:28
Thanks for reporting.

> I can't provide a reproduction because we build with Insiders and I don't have "manual" access to it.

Unfortunately, without a reproduction, we can't investigate. In fact, the tags plugin works perfectly for us, so it must be some combination of things. The account having access to Insiders can fork the repository to your organization, and give you access. Please provide a reproduction, because we just cannot observe the error.

> As far as I can tell, the only necessary adjustment should be to change the tags marker from [TAGS] to .

You don't even need to do that, [because the tags plugin will do it for you](https://github.com/squidfunk/mkdocs-material-insiders/blob/519e74d701d16472172ff2729bb111cffe490d3e/src/plugins/tags/plugin.py#L238-L258) – we deliberately made the tags plugin backward compatible and will remove the [TAGS] marker in the next major release.

**Comment by normandy7** [comment] 2024-01-23 08:13
In our case, what happened was that the text `[TAGS]` was just displayed where the listing should have been 🤷🏻 

Some time back I reported another tags issue that concerned odd sorting behavior in the listing. I'll pin the Insiders version for now ([now that I know how to do it!](#6678)) but it seems like something is not working right with tags on our end, so I'll make sure to figure out our org perms so I can generate reproductions when needed.

Thanks!

**Comment by squidfunk** [comment] 2024-01-23 08:23
Great, thank you! We're happy to fix the issue quickly once we can isolate it. Closing for now – we'll reopen once we get a runnable reproduction that demonstrates the issue.

**Closed by squidfunk** 2024-01-23 08:23 UTC
Labels: needs reproduction

**Comment by squidfunk** [comment] 2024-01-23 08:25
> Some time back I reported another tags issue that concerned odd sorting behavior in the listing.

Jup, https://github.com/squidfunk/mkdocs-material/issues/5613 – we're still waiting for a reproduction as well, because again, it is working on our side and we cannot observe any problems.
