### ISSUE TITLE
Tags are not rendered correctly with snippets extension

### ISSUE THREAD

**Issue by SerTetora** [squidfunk/mkdocs-material#7516] opened 2024-09-11 14:38 UTC
### Bug description

I'm using [Snippets](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets) extension to include the content of one page into several other. If the included page contains [Tags](https://squidfunk.github.io/mkdocs-material/plugins/tags/) it renders incorrectly on the other pages.

Page 1:
![image](https://github.com/user-attachments/assets/79d170f1-cc8b-4b3a-b437-eae3e1c7a8fa)

Page 2:
![image](https://github.com/user-attachments/assets/e527f646-a6fb-400f-9bdc-a09e16d0aae8)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Tags](https://squidfunk.github.io/mkdocs-material/plugins/tags/)
- [Snippets](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets)

### Reproduction

[9.5.34-tags-snippets.zip](https://github.com/user-attachments/files/16965102/9.5.34-tags-snippets.zip)

### Steps to reproduce

1. `page1.md` contains tags
2. include `page1.md` into `page2.md` using snippets. `--8<-- "docs/page1.md"`
3. all other content renders correctly on `Page 2` except tags

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-09-11 16:37
Thanks for reporting!

> If I had to guess, it is likely that MkDocs Material parsers the frontmatter before Markdown parsing occurs. Snippets is handled in the Markdown processing step.

That is correct, we extract the tags in [`on_page_markdown`](https://github.com/squidfunk/mkdocs-material/blob/8df393d11158ebc87026e4eea9ed0c887eae2371/src/plugins/tags/plugin.py#L82-L103), which we have to do, because we need to generate the tags index which is [rendered into another Markdown file](https://github.com/squidfunk/mkdocs-material/blob/8df393d11158ebc87026e4eea9ed0c887eae2371/src/plugins/tags/plugin.py#L153-L175). If we would move the tags detection and rendering to a later stage (e.g. `on_page_content`), we essentially would need to generate HTML, because all pages have been rendered, so the only thing we can still influence is the HTML. The first thing that comes to my mind that will break is the table of contents that is generated as part of the tags index, as the tags generate headline so they can be linked to (a non-linkable tags index make no sense). This handling would now need to be implemented manually, including ensuring that anchors do not clash with existing ids in the HTML.

I'm taking this back to the drawing board with me (we're working in the background, see [our latest blog post](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/)), and we already have identified tags to be a really hard problem to get right with the limited abilities that MkDocs offers. Withthe current architecture of MkDocs this is not fixable, but we'll see what we can do 🤟

Closing as unfixable with reasonable effort.

**Closed by squidfunk** 2024-09-11 16:37 UTC

**Comment by squidfunk** [comment] 2024-09-11 16:41
... however, one other thing that comes to mind: this might also be a bug (or unintended behavior) in Snippets, as it renders the front matter verbatim. MkDocs should actually strip the front matter before passing this to the Markdown parser, so I'm not sure why it is still part of the included page. There should, in fact, be no tags. Oh and a workaround for using tags in pages with snippets is to copy them:

``` md
---
tags:
  - Examples
  - Templates
---

--8<-- "docs/page1.md"
```

**Comment by facelessuser** [comment] 2024-09-11 16:53
I doubt this is a bug of Snippets. It reads the file directly that you point it at. Remember, Python Markdown has no concept of documents in a site, it deals with one buffer given to it with no context of your site as a whole.

**Comment by squidfunk** [comment] 2024-09-11 19:07
Okay, then it's expected behavior, but kind of counter-intuitive when a Markdown file gets inlined together with front matter and the front matter is then printed verbatim, but yes, Snippets is text-only, so all good.

**Comment by SerTetora** [comment] 2024-09-12 08:16
Thank you for the explanation and suggesting a workaround!

In my case, if I don't want to have separate file with common content without tags, I can use the [nice feature of snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippet-lines) in page2.md.

```markdown
---
tags:
  - Examples
  - Templates
---

--8<-- "docs/page1.md:6"
```
