### ISSUE TITLE
tracking selects wrong anchor when adding header inside tabs

### ISSUE THREAD

**Issue by Jellyfrog** [squidfunk/mkdocs-material#3527] opened 2022-02-01 00:10 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Tracking selects wrong anchor when adding header inside tabs,
When visiting the site it appends `#toc-in-secondsub2` instead of nothing, or `#first`.

I added a full example here; https://github.com/Jellyfrog/materials-issue

### Expected behaviour

Not appending any anchor, or the first one

### Actual behaviour

Appending the last anchor

### Steps to reproduce

1. Run https://github.com/Jellyfrog/materials-issue
2. Observe it adding  #toc-in-secondsub2 in the url

### Package versions

- Python: `3.10.2`
- MkDocs: `1.2.3`
- Material: `8.1.9`

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
  features:
    - navigation.tracking

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
```

### System information

- Operating system: ...
- Browser: Latest Firefox and chrome

**Comment by squidfunk** [comment] 2022-02-01 07:41
Thanks for reporting.

The problem is that anchors in tabs other than the first will not work properly, because the element is hidden (second tab, first is active on load), and for this reason we [cannot compute its position](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/javascripts/components/toc/index.ts) which is necessary to perform anchor tracking. The general advice is not to put headers into content tabs, because there are other side-effects that we cannot fix (see related). Closing as not fixable. The usage of headers in tabs is discouraged.

_Related__
- https://github.com/squidfunk/mkdocs-material/issues/3376

**Closed by squidfunk** 2022-02-01 07:41 UTC
