### ISSUE TITLE
Search not working in Safari 13

### ISSUE THREAD

**Issue by rbournissent** [squidfunk/mkdocs-material#2533] opened 2021-04-08 15:18 UTC
* [x]  I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and agree with them
 
**I've found a bug and checked that ...**
 
* [x] the problem doesn't occur with the default MkDocs template
 * [x] the problem is not in any of my customizations (CSS, JS, template)
 * [x] the documentation does not mention anything about my problem
 * [x] there are no open or closed issues that are related to my problem
 
## Description
As the title suggests.
It does work as expected in Safari 14.
 
### Expected behavior
When typing into the search bar, some results should appear (or at least the "no results" placeholder)
 
### Actual behavior
Search functionality doesn't work. Typing in the search field doesn't do anything.
Error in console `TypeError: Argument 1 ('listener') to MediaQueryList.addListener must be a function`
 
### Steps to reproduce the bug
1. Go to [MkDocs Material website](https://squidfunk.github.io/mkdocs-material/)
2. Try to type something in the search bar in the top nav bar

### System information
* Browser: Safari 13.1.2

**Comment by squidfunk** [comment] 2021-04-10 08:49
Thanks for reporting! Fixed in bb57ea9b2. The error was a regression of our switch to the now-standard `MediaQueryList.addEventListener`, because `MediaQueryList.addListener` was deprecated. This, however, led to the problem reported in this issue. The commit reverts to the previous impementation.

**Comment by squidfunk** [comment] 2021-04-10 09:32
Released as part of 7.1.1.

**Closed by squidfunk** 2021-04-10 09:32 UTC
Labels: bug, fix available

**Comment by rbournissent** [comment] 2021-04-16 11:40
Thanks for the fix. The search functionality works fine in Safari 13 now. 

In Safari 11 there is another issue now (should I open a new issue for this? is Safari 11 too old to offer support for it?)

When the user tries to search, this error appears in the console: 
`TypeError: Object.keys(e.terms).filter(a=>!e.terms[a]).map(a=>[U("del",null,a)," "]).flat is not a function. (In 'Object.keys(e.terms).filter(a=>!e.terms[a]).map(a=>[U("del",null,a)," "]).flat()', 'Object.keys(e.terms).filter(a=>!e.terms[a]).map(a=>[U("del",null,a)," "]).flat' is undefined)`

Here's an screenshot of that happening in the MkDocs material website:
![image](https://user-images.githubusercontent.com/8206359/115019270-40e7bf00-9eb9-11eb-9dce-d2abaaf755ed.png)

**Comment by squidfunk** [comment] 2021-04-16 12:32
Thanks for noting. Safari 11 shipped in El Capitan, which came out in 2015, so 6 years ago. We support everything that is [not older than 4 years](https://github.com/squidfunk/mkdocs-material/blob/master/.browserslistrc).
