### ISSUE TITLE
Add metatag to style header bar on Android

### ISSUE THREAD

**Issue by digitalcraftsman** [squidfunk/mkdocs-material#39] opened 2016-07-23 16:36 UTC
With Chrome  v39 (for Anroid) websites are able to change the color of the header bar like native apps on their smartphones and tablets.

You've to add the following one-liner:

```
<meta name="theme-color" content="PRIMARY THEME COLOR">
```

For more information take a look at [this info page](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android) about the new feature.

**Comment by squidfunk** [comment] 2016-07-24 10:40
Great idea, thanks! If I add the style in master - can you verify it, take a screenshot and post it here. I'm an Apple kid ;-)

**Comment by digitalcraftsman** [comment] 2016-07-24 11:34
> If I add the style in master - can you verify it, take a screenshot and post it here.

Sure. Let's do it.

**Comment by squidfunk** [comment] 2016-07-24 11:51
Hmm the problem is that, practically, I don't have the color values which are set in the SCSS, so one would have to define it in the `mkdocs.yml` to integrate it into the HTML. That's not very sexy. I have to think about it first and will come back to you.

**Comment by squidfunk** [comment] 2016-12-26 18:12
I regret, it's not possible to do it easily without compromising the clean encapsulation that is currently present in the theme. The color values are defined in the CSS which is compiled, meaning afterwards the values are lost.

However, it can easily be solved by extending the template and adding the `meta` tag which is really easy in mkdocs 0.16: http://www.mkdocs.org/user-guide/configuration/#extra_templates

I will close this issue for now, since there is nothing we can do about it.

**Closed by squidfunk** 2016-12-26 18:12 UTC
Labels: enhancement

**Comment by squidfunk** [comment] 2018-06-13 08:52
Finally implemented, see #795
