### ISSUE TITLE
Parse markdown in nav and TOC

### ISSUE THREAD

**Issue by victorbnl** [squidfunk/mkdocs-material#2944] opened 2021-08-16 21:16 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Markdown in page and sections titles would be parsed in nav and TOC

### Use Cases

Put inline code in titles, any other markdown, or icons with `pymdownx.emoji`

### Screenshots / Mockups

![bildo](https://user-images.githubusercontent.com/39555268/129630144-1db0c466-f501-4153-a1de-733d173cbdd8.png) ![bildo](https://user-images.githubusercontent.com/39555268/129630478-d2b8bee4-db88-45c3-9dae-c3f9c89e36fa.png)

**Comment by squidfunk** [comment] 2021-08-17 06:32
Duplicate of #2318

---

_In the future, when you report an issue, please use the search first. It will save us both time. Furthermore, when you create an issue saying something is not rendered properly, always include a reproducible example._

**Closed by squidfunk** 2021-08-17 06:32 UTC

**Comment by victorbnl** [comment] 2021-08-17 10:54
Thanks for you answer and sorry, I didn't know how to search it
