### ISSUE TITLE
social plugin build issue

### ISSUE THREAD

**Issue by fengtality** [squidfunk/mkdocs-material#5493] opened 2023-05-09 13:37 UTC
### Bug description

I just started seeing errors in the build process related to social card plugins that is blocking deployment. Nothing changed in our docs, so I'm flagging this issue just in case.

Here's my Netlify build command:
```
pip install git+[https://$](https://%24/){GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git mkdocs-git-revision-date-plugin pillow cairosvg p && mkdocs build
```

I was able to resolve this issue by commenting out the social cards feature in (https://github.com/hummingbot/hummingbot-site/pull/188, but I'd like to bring them back.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-[Social cards](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=social)

### Reproduction

Here's the error from Netlify logs:

```
6:05:32 AM: Traceback (most recent call last):
6:05:32 AM:   File "/opt/buildhome/python3.8/bin/mkdocs", line 8, in <module>
6:05:32 AM:     sys.exit(cli())
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
6:05:32 AM:     return self.main(*args, **kwargs)
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
6:05:32 AM:     rv = self.invoke(ctx)
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
6:05:32 AM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
6:05:32 AM:     return ctx.invoke(self.callback, **ctx.params)
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
6:05:32 AM:     return callback(*args, **kwargs)
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/mkdocs/__main__.py", line 247, in build_command
6:05:32 AM:     cfg = config.load_config(**kwargs)
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/mkdocs/config/base.py", line 363, in load_config
6:05:32 AM:     errors, warnings = cfg.validate()
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/mkdocs/config/base.py", line 228, in validate
6:05:32 AM:     run_failed, run_warnings = self._validate()
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/mkdocs/config/base.py", line 186, in _validate
6:05:32 AM:     self[key] = config_option.validate(value)
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 148, in validate
6:05:32 AM:     return self.run_validation(value)
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 940, in run_validation
6:05:33 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
6:05:32 AM:     self.load_plugin_with_namespace(name, cfg)
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 976, in load_plugin_with_namespace
6:05:32 AM:     return (name, self.load_plugin(name, config))
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 994, in load_plugin
6:05:32 AM:     plugin_cls = self.installed_plugins[name].load()
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 210, in load
6:05:32 AM:     module = import_module(match.group('module'))
6:05:32 AM:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
6:05:32 AM:     return _bootstrap._gcd_import(name[level:], package, level)
6:05:32 AM:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
6:05:32 AM:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
6:05:32 AM:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
6:05:32 AM:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
6:05:32 AM:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
6:05:32 AM:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/material/plugins/social/plugin.py", line 48, in <module>
6:05:32 AM:     from material.plugins.social.layout import Layer, Layout, Line
6:05:32 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/material/plugins/social/layout.py", line 94, in <module>
6:05:32 AM:     def get_size(layer: Layer | Layout):
6:05:32 AM: TypeError: unsupported operand type(s) for |: '_TypedDictMeta' and '_TypedDictMeta'
6:05:32 AM: ​
6:05:32 AM: "build.command" failed                                        
6:05:32 AM: ────────────────────────────────────────────────────────────────
```

### Steps to reproduce

I wasn't able to reproduce the issue on my Mac

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-05-09 15:35
Should be fixed in [`44f0897`](https://github.com/squidfunk/mkdocs-material-insiders/commit/44f0897be795e52e1187b5b38b8464d83e0a7ddc). My research tells me that the pipe syntax for union typings was first introduced in 3.10. Using `Union[...]` achieves the same, so I switched to that syntax. I searched the code base and this seems to be the only instance. Could you try again with the `master` of Insiders?

**Comment by madkinsz** [comment] 2023-05-09 19:44
@squidfunk that does resolve that error but we're seeing another version compatibility issue

```
2:42:19 PM:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2:42:19 PM:     return _bootstrap._gcd_import(name[level:], package, level)
2:42:19 PM:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2:42:19 PM:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2:42:19 PM:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2:42:19 PM:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2:42:19 PM:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
2:42:19 PM:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2:42:19 PM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/material/plugins/social/plugin.py", line 56, in <module>
2:42:19 PM:     class SocialPlugin(BasePlugin[SocialConfig]):
2:42:19 PM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/material/plugins/social/plugin.py", line 641, in SocialPlugin
2:42:19 PM:     def _resolve_font(self, family: str, styles: set[str]):
2:42:19 PM: TypeError: 'type' object is not subscriptable
```

See https://github.com/PrefectHQ/prefect/pull/9501 for example

Thanks!

**Comment by madkinsz** [comment] 2023-05-09 19:46
FYI Netlify only supports Python 3.8 so it's important to maintain compatibility with 3.8 for many users. Your package also says it supports 3.7+ — might be worth running a CI workflow that tests the lowest compatible version too.

**Comment by squidfunk** [comment] 2023-05-10 07:20
Fixed in [`a9dda0990`](https://github.com/squidfunk/mkdocs-material-insiders/commit/a9dda0990c9b22b7efe7dd7ad9c8b8a775b9df7d) – tested with Python 3.7 and 3.8 and the social plugin now runs without errors in 3.8. 3.7 does not run due to the use of some typings, so we'll up the requirement to Python 3.8+. I'm sorry for the inconvenience this was causing you, and yes, we'll be working on improving compatibility testing in the future!

**Comment by squidfunk** [comment] 2023-05-10 07:21
Bumped the version to 3.8+ in 88515d26a.

**Comment by bilal-fazlani** [comment] 2023-05-12 12:48
Does not appear be to fixed in [a9dda0990](https://github.com/squidfunk/mkdocs-material-insiders/commit/a9dda0990c9b22b7efe7dd7ad9c8b8a775b9df7d) 

Checked on latest insider too 43c30522afe4bdbd89da17b0c3c314d17e621541

**Comment by squidfunk** [comment] 2023-05-12 12:55
@bilal-fazlani could you please create a reproduction? I'm not sure what you're now seeing, but I can't reproduce the error anymore.

**Comment by squidfunk** [comment] 2023-05-12 13:51
Released as part of [9.1.12+insiders-4.33.2](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.33.2). @bilal-fazlani if you manage to create a reproduction, please open a new issue.

**Closed by squidfunk** 2023-05-12 13:51 UTC
Labels: bug, resolved

**Comment by bilal-fazlani** [comment] 2023-05-12 14:28
Its working now. Not sure what was the issue but it was definitely on my local environment.

**Comment by squidfunk** [comment] 2023-05-27 12:48
As off [9.1.14+insiders-4.35.0](https://github.com/squidfunk/mkdocs-material-insiders/releases/tag/9.1.14-insiders-4.35.0), the social plugin should be compatible with Python 3.7. We replaced `TypedDict`, which was the main problem, with instances of `Config` when [adding validation to custom layouts.](https://github.com/squidfunk/mkdocs-material-insiders/blob/master/src/plugins/social/layout.py)

**Comment by shaloo** [comment] 2024-03-29 04:42
> Its working now. Not sure what was the issue but it was definitely on my local environment.

I began seeing the same issue again today with 3.8 (Netlify). Works fine in my local environment (Python 3.9). How did it get fixed for you?  I did not change the code - Netlify deployment is working for the same commit, but since March 27 the same commit build is failing with this zipfile error for google font loading in social plugin. Weird.

**Comment by alexvoss** [comment] 2024-03-29 07:11
Hi @shaloo, the Google Fonts issue is a separate issue documented here: https://github.com/squidfunk/mkdocs-material/issues/6983
