### ISSUE TITLE
Search Error (Invalid query) within Cypress Test Case

### ISSUE THREAD

**Issue by aku2nnya** [squidfunk/mkdocs-material#4463] opened 2022-10-05 23:21 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

When attempting to utilize the search component within cypress for testing purposes, it returns an error stating `Invalid query: searchedText - see bit.lyLinkToLunr`

Notes:
- This issue does not occur in normal use, but only within cypress
- Similar issue has been discussed [here](https://github.com/squidfunk/mkdocs-material/discussions/4024), but utilizing `mkdocs==1.3.0` with `mkdocs-material==8.3.5` did not solve the issue as commented there

### Expected behaviour

Utilizing the search component should successfully give search result without any errors.

### Actual behaviour

Search component returns `No matching documents` with the console showing an error stating `Invalid query: searchedText - see bit.lyLinkToLunr`

### Steps to reproduce

1. Open cypress (`npx cypress open`)
2. Run a simple test case on the docs which types any text into the search component
For example:
```
describe('Docs', function () {
    it(
        'Docs should search',
        function () {
            cy.get('form[name="search"]').should('be.visible').click().clear().type('test');
        }
    );
});
```

### Package versions

- Python: `3.10`
- MkDocs: `1.4.0`
- Material: `8.5.6`
- Cypress : `10.7.0`

Also tested with:
- Python: `3.9`
- MkDocs: `1.3.0`
- Material: `8.3.5` & `8.2.8`
- Cypress : `10.7.0`

### Configuration

```yaml
site_name: 'Docs'
theme:
    name: material
```

### System information

- Operating system: Mac OS: Catalina v10.15.7
- Browser: Cypress (Chrome, Electron and Firefox)

**Comment by squidfunk** [comment] 2022-10-06 00:31
Thanks for reporting.

> This issue does not occur in normal use, but only within cypress

Unfortunately, we can't offer support for all kinds of downstream libraries or projects consuming or building upon Material for MkDocs. I hope for your understanding. If you run into the same problem when using the site as a user (= manual use), I'm happy to look into it, but Cypress may be doing things that are outside of what we consider normal usage.

In any case, a reproduction that is not a test is necessary. Closing for the reasons stated.

**Closed by squidfunk** 2022-10-06 00:31 UTC
