### ISSUE TITLE
Authors in mobile view

### ISSUE THREAD

**Issue by davideriboli** [squidfunk/mkdocs-material#6117] opened 2023-10-02 08:48 UTC
### Context

Verified both locally and via GitHub Pages Action, using the latest available version of free M4Mkd.

Lang: IT.

### Bug description

Adding authors works fine if the site is called up from desktop, but in mobile view it overlays its infos on the site footer.

A CSS problem?

The enclosed image should be explanatory.

![M4MkdAuthorsPluginBug](https://github.com/squidfunk/mkdocs-material/assets/623043/2d8acfae-5e05-426d-a593-57564c1c992c)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Adding Authors](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#adding-authors)

### Reproduction

[9.4.2-example.zip](https://github.com/squidfunk/mkdocs-material/files/12781104/9.4.2-example.zip)

### Steps to reproduce

1. Activate Blog 
2. Create an author in .authors.yml file
3. Activate Authors
4. Write a post
5. Check it in mobile view

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-10-02 08:57
Thanks for reporting and providing the reproduction! This is an exact duplicate of #6094, which was already resolved. We'll issue a new release in the next hour.

**Closed by squidfunk** 2023-10-02 08:57 UTC
