### ISSUE TITLE
Feature request: Enable "navigation.expand" up to a specified level instead of all at once

### ISSUE THREAD

**Issue by iBug** [squidfunk/mkdocs-material#2927] opened 2021-08-10 13:53 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Make the feature `navigation.expand` accept a "level" so that nested items are expanded on page load only up to the level. An example configuration would be:

```yaml
theme:
  features:
    - navigation.expand
        level: 2
```

This would make the left nav list look like this upon initial page load:

```text
Level 1      ↓
  Level 2    ↓
    Level 3  →
```

A specified level of zero acts as if `navigation.expand` is not enabled at all. If level is unspecified, it defaults to infinity (i.e. retain current behavior that expands all items).

### Use Cases

For documentation sites with a good number of pages, expanding everything at once may make the list too long to scroll and hinders efficient navigation through the list. Expanding nothing, on the other hand, may still be inefficient for navigation with the most commonly accessed level of details lies on the 3rd level. It would be nice if the nav list can be expanded on page load, but only to level 1 or 2.

**Comment by squidfunk** [comment] 2021-08-10 14:04
Duplicate of #2818

**Closed by squidfunk** 2021-08-10 14:04 UTC
