### ISSUE TITLE
Missing Version Warning Message

### ISSUE THREAD

**Issue by clubanderson** [squidfunk/mkdocs-material#5570] opened 2023-05-29 00:46 UTC
### Context

trying to get version warning to appear when not viewing the current release of doc.

### Bug description

I had the outdated block working correctly and within the last week I changed something that caused the block to stop appearing.  I changed the the version default to 'stable' instead of 'latest.  After this change I can't see the outdated block.

### Related links

[Version Warning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning) banner does not show on any pages when an updated version is deployed.

### Reproduction

[Archive.zip](https://github.com/squidfunk/mkdocs-material/files/11587125/Archive.zip)

### Steps to reproduce

go to https://kubestellar.io
switch version from 'release-0.2' to 'main'
no banner appears

### Browser

Chrome, Safari

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-05-29 09:45
Thanks for reporting. Unfortunately, there are several problems with this issue:

- Your reproduction is 14.2 MB in size – far too big for us to investigate. There are too many documents and too many dependencies for us to install to get up and running. Please provide a minimal reproduction of the problem you're reporting. Also please make sure to follow our documentation on the version banner – the banner will be shown when 

- You did not remove your customizations as you checked. There are still overrides in place and additional JavaScript.

- Visiting your site does not allow us to debug and investigate the problem. We need concise and clear steps what you did to deploy your documentation. Without this information, it is impossible for us to understand whether the problem is in mike or Material for MkDocs. We don't know how you configured mike or deployed your existing documentation.

For this reason, we can only close this issue as not reproducible. Please note that we did not change anything on the versioning selector or the outdated banner within the last three months. [Latest change was here](https://github.com/squidfunk/mkdocs-material/commit/b25723571778ed175a7981a734afbb23a94c2ada).

**Closed by squidfunk** 2023-05-29 09:45 UTC
