### ISSUE TITLE
"Previous" page navigation labels disappear under 705px window width

### ISSUE THREAD

**Issue by denismcdonald** [squidfunk/mkdocs-material#3188] opened 2021-11-06 03:03 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When the window width goes below 705px (as best I can tell), the text within the left-hand-side `div.md-ellipsis` (the word "Previous" and the relevant page title) disappear.

### Expected behaviour

The expected behaviour would be to display the "Previous" navigation element wording, even when the window width is below 705px:

<img width="777" alt="Screen Shot 2021-11-06 at 1 39 41 pm" src="https://user-images.githubusercontent.com/14754197/140595300-08cde90a-8958-4780-8a15-17dc555b4780.png">

### Actual behaviour

The "Previous" text and its associated page title are omitted for window widths below 705px: 

<img width="693" alt="Screen Shot 2021-11-06 at 1 24 47 pm" src="https://user-images.githubusercontent.com/14754197/140595257-c281576d-a7e0-4816-96ae-54da07dd0737.png">

### Steps to reproduce

1. Navigate to a page where both "Previous" and "Next" footer navigation elements are expected.
2. Resize the window to below 705px.

### Package versions

- Python: 3.10.0
- MkDocs: 1.2.3
- Material: 7.3.6

### Configuration

```yaml
site_name: MyDocs
theme: material
```

### System information

- Operating system: MacOS 10.14.6
- Browser: Firefox 94.01 and Chrome 95.0.4638.69

**Comment by squidfunk** [comment] 2021-11-06 15:55
[Intended behavior](https://github.com/squidfunk/mkdocs-material/issues/491#issuecomment-336463386). Duplicate of:

- #491
- #696

**Closed by squidfunk** 2021-11-06 15:55 UTC

**Comment by denismcdonald** [comment] 2021-11-06 23:19
Apologies for not spotting [#491](https://github.com/squidfunk/mkdocs-material/issues/491).
