### ISSUE TITLE
Mermaid.js generated SVG pictures with too many blank spaces taking up space.

### ISSUE THREAD

**Issue by huangyinhaow** [squidfunk/mkdocs-material#4068] opened 2022-06-27 04:25 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If the block of code for mermaid is so long that it exceeds the height of the SVG that the target is generating, the upper and lower parts of the generated SVG will take up a lot of invalid space.

### Expected behaviour

SVG just happens to appear below the text

### Actual behaviour

![image](https://user-images.githubusercontent.com/64564727/175859490-b3f86486-0f59-4dab-804d-609d1ec223c0.png)

### Steps to reproduce

1. Write a markdown file
2. Insert a long block of mermaid code

### Package versions

- Python: 3.10
- MkDocs: 1.3.0
- Material: 8.3.6

### Configuration

```yaml
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: Windows 11 
- Browser: Edge 102

**Comment by huangyinhaow** [comment] 2022-06-27 04:26
Example:

```
#### 矛盾

世界上的一切事物都包含着既对立又统一的两个方面，也就是矛盾。

矛盾就是对立与统一。其中，对立是斗争性，统一是同一性。

!!! Example
    道家学说的代表老子说：有无相生，难易相成，长短相形，高下相倾，应声相和，前后相随。

**同一性**：

- 都处在一个统一体中：相互依赖，互为前提
- 都可以在一定条件下相互转化：相互渗透，相互包含

**斗争性**：

- 都有相互分离的倾向和趋势：相互排斥，相互对立

同一性是相对的，斗争性是绝对的。没有斗争性就没有同一性。

```mermaid
flowchart LR
pol((哲学)) -->|是| tech[学问]
pol -->|指导| a
tech -->|起源于| 追问和思考
tech --> techis{是}
techis --> 智慧之学 & 追求智慧之学 & worldview[世界观]
tech -.->|不是| a[具体科学] -->|概括总结| pol
tech --> qus{基本问题} --> source[物质与意识何者是本源] & ifknow[意识能否正确认识存在]
worldview -->|决定| way[方法论]
worldview --> worldt[特征] --> 系统的 & 理论化的
way --> teach[指导] --> know[认识世界] & change[改变世界]
source --> thing[物质是本源] & think[意识是本源]
thing --> otg[唯物主义]
think --> otk[唯心主义]
otg --> otg1[古代朴素唯物主义] & otg2[近代形而上学唯物主义] & otg3[辩证唯物主义和历史唯物主义]
otk --> 主观唯心主义 & 客观唯心主义
otg3 --> mks(马克思主义哲学)
ifknow --> ifknowcan[能] & ifknowcant[不能]
ifknowcan --> ifknowcan2[可知论]
ifknowcant --> ifknowcant2[不可知论]
ifknowcan2 --> mks
mks --> mkst[特征] --> people[人民性] & seci[科学性] & rev[革命性] & ftime[与时俱进性]
ftime --> 毛泽东思想 & 邓小平理论 & 三个代表重要思想 & 科学发展观 & 习近平新时代中国特色社会主义思想
```

```mermaid
flowchart LR
world((世界)) -->|是| thing[物质]
world -->|不是| think[意识]
world -->|包括| soci[人类社会] -->|产生| think
劳动 -->|产生| think
thing --- thinghave{有} --> 起源 & 发展史
thing --- thingt{特性} --> 客观实在 & reg[规律]
think -->|反映| thing -->|不依赖于| think -->|决定| thing
think -->|指导| do[实践] -->|改造| world
think --- thinkneed{需要} -->|尊重| reg
thinkneed -->|发挥| 主观能动性
```
```

**Comment by squidfunk** [comment] 2022-06-27 06:28
This is an exact duplicate of #3947. Closing.

**Closed by squidfunk** 2022-06-27 06:28 UTC

**Comment by huangyinhaow** [comment] 2022-06-27 07:30
Sorry, but mermaid2 plugin works well. It is not a mermaid bug.

![image](https://user-images.githubusercontent.com/64564727/175883920-09b9189a-38f8-4932-ac00-fba3998a9660.png)

**Comment by squidfunk** [comment] 2022-06-27 07:43
Thanks for providing the details. As we can see in your screenshot, it is clearly the `viewbox`'s height that seems to be calculated wrong. The SVG is generated by Mermaid.js – Material for MkDocs does no post- or pre-processing whatsoever. We're using Mermaid.js 9.0.1, so it might be related to version differences between our integration and the mermaid2 plugin. other than that, if the mermaid2 plugin solves your issue, you can use that in favor.

**Comment by squidfunk** [comment] 2022-06-27 07:44
[The mermaid2 plugin uses v8.8.0](https://github.com/fralau/mkdocs-mermaid2-plugin/blob/15db586301edc910c1bd36e11104c6bae9da56f0/mermaid2/plugin.py#L19):

**Comment by huangyinhaow** [comment] 2022-06-27 07:45
v8.8.0 works well too

**Comment by squidfunk** [comment] 2022-06-27 07:48
You can define a custom mermaid.js version like so: https://github.com/squidfunk/mkdocs-material/issues/3171#issuecomment-961204712

**Comment by huangyinhaow** [comment] 2022-06-27 07:51
I had tried it, but it does not work.

**Comment by huangyinhaow** [comment] 2022-06-27 09:01
Mermaid.js in material is faster than mermaid plugin, so please fix the bug, thank you!

**Comment by squidfunk** [comment] 2022-06-27 09:23
Thanks for testing the different versions. As I already noted in https://github.com/squidfunk/mkdocs-material/issues/3947#issuecomment-1135839253, this is an upstream bug:

- https://github.com/mermaid-js/mermaid/issues/2657

**Comment by huangyinhaow** [comment] 2022-06-27 09:28
> 感谢您测试不同的版本。正如我在[#3947（注释）](https://github.com/squidfunk/mkdocs-material/issues/3947#issuecomment-1135839253)中已经指出的那样，这是一个上游错误：
> 
> * [图中意想不到的垂直空间 美人鱼-js/美人鱼#2657](https://github.com/mermaid-js/mermaid/issues/2657)

But why mermaid plugin works well? Maybe you can fix it like the plugin.

**Comment by vermeerdirk** [comment] 2023-12-13 09:13
Just throwing a solution out here:
I do understand that the issue is in mermaid.js and should be resolved there.
However, as mentioned on similar posts here, setting the height property of the svg tag to 'auto' fixes it for my classdiagrams.
To do this, I changed the minified bundle that comes with the mkdocs-material package as follows:

mkdocs-matrial creates shadowroots for each diagram, in so avoiding other issues with duplicate id's etc, which is smart but it also makes it impossible to just use css to access elements (svg tag) inside the generated div tags.
Thankfully, there is a callback function we can use but we have to change the minified file for this. (or some sponsor could..maybe make it an option)

Edit: bundle.467223ff.min.js
Search for 'render' or 'mermaidAPI.render
Carefully change the code to set height of the svg to auto

```` javascript
        .................
	let t=`__mermaid_${ps++}`,r=C("div",{class:"mermaid"});
	// console.log('mermaid');
	mermaid.mermaidAPI.render(t,e.textContent,n=>{
	    // console.log('mermaid api render callback textcontent', e.textContent);
	    let o=r.attachShadow({mode:"closed"});
	    // console.log('object with attached Shadow root', o);
	    o.innerHTML=n,e.replaceWith(r);
	    // console.log('innerhtml set', o.innerHTML);
	    let firstSvg = o.querySelector('svg');
	    if (firstSvg) {
	        firstSvg.setAttribute('height', 'auto'); 
	    }
	})}),Gr.pipe(Z({ref:e}))}function ms(e,{target$:t,print$:r}){let n=!0;ret .......
````

Ofcourse, when upgrading mkdocs-material this solution is overwritten but in the meantime it's a workaround.
Also realize that it might create other issues elsewhere but for now, this works best for me
