### ISSUE TITLE
codeblocks titles not displaying correctly with tablesort feature

### ISSUE THREAD

**Issue by andynameistaken** [squidfunk/mkdocs-material#3314] opened 2021-12-06 21:52 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Using tablesort from documentation breaks displaying of titles in code blocks:

 

### Expected behaviour

![image](https://user-images.githubusercontent.com/15692002/144927321-50bbef2d-fc58-4060-a82b-4e5b47360f7a.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/15692002/144927179-8e2135b5-aaf3-4435-ac44-de07335ef997.png)

### Steps to reproduce

Follow guide from:
https://squidfunk.github.io/mkdocs-material/reference/data-tables/#configuration
to setup table sorting.

### Package versions

- Python: `python --version`
  - Python 3.9.9
- MkDocs: `mkdocs --version`
  -  version 1.2.3  
- Material: `pip show mkdocs-material | grep -E ^Version`
  - Version: 8.0.4

### Configuration

```yaml
# Project information
site_name: 'test'
site_description: 'test'
site_author: 'Andrzej Zahorski'
site_url: test


# Repository
# repo_name: ''
# repo_url: ''

# Copyright
copyright: 'Copyright &copy; 2021 Andrzej Zahorski'

# Plugins
plugins:
  - search
  - markmap
  - autolinks 
  - roamlinks
  # - with-pdf
  

  
  




## Extensions
markdown_extensions:    
  - mdx_truly_sane_lists
  - footnotes
  - pymdownx.highlight:
      linenums: true           
  - pymdownx.inlinehilite  
  - pymdownx.keys
  - pymdownx.snippets  
  - admonition
  - pymdownx.details  
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - tables

  # LaTeX
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid    
  - pymdownx.tabbed:
      alternate_style: true 
 



  - toc:
      permalink: true

# Configuration
theme:
  name: material
  font:
    text: Sarala
  features:
    - navigation.top
    - search.suggest    
    - search.highlight     
    - search.share        
    - navigation.indexes

  language: 'en'
  # logo: 'images/logo.png'
  # favicon: 'images/logo.png'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: green
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  

  
  

# Customisation
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andynameistaken
  generator: false

#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/retropieproject
    

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  # sortable data tables
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  

      
nav:
- test
```

### System information

- Operating system: macOS 10.15.7
- Browser: Google Chrome Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by squidfunk** [comment] 2021-12-06 22:27
Thanks for reporting. I'm not able to reproduce this. Here's a sortable table next to a code block with a title:

<img width="725" alt="Bildschirmfoto 2021-12-06 um 23 26 25" src="https://user-images.githubusercontent.com/932156/144932746-6510b1ea-9367-46bd-9f1a-26503501f46f.png">

Please provide a minimal reproducible example.

**Comment by squidfunk** [comment] 2021-12-06 22:51
Ah wait, you've added line numbers to that code block and yes, I'm also seeing it now. The selector to mount TableSort is too generic. Try the following, that should work well for data tables:

``` js
document$.subscribe(function() {
  var tables = document.querySelectorAll("article table:not([class])") // this line was adjusted
  tables.forEach(function(table) {
    new Tablesort(table)
  })
})
```

I've updated the documentation in 674e57ea6. No code needs to be changed in Material for MkDocs itself. Closing.

**Closed by squidfunk** 2021-12-06 22:51 UTC
Labels: not reproducible
