### ISSUE TITLE
Instant navigation breaks Isso comments

### ISSUE THREAD

**Issue by AlphaJack** [squidfunk/mkdocs-material#2338] opened 2021-02-24 11:52 UTC
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Enabling `navigation.instant` modified Isso requests URLs on first load. A page reload restores them.

### Expected behavior

Requests are sent to usual URLs

### Actual behavior

Requests are sent to a non existent URL

### Steps to reproduce the bug

My website has https://example.org/mkdocs/ set as site_url and loads on every page the following Isso code:

```html
{% block disqus %}
 {% if not page.is_homepage %}
  <script data-isso="https://example.org/comments" src="https://example.org/comments/js/embed.dev.js"></script>
  <section id="isso-thread"></section>
 {% endif %}
{% endblock %}
```

The file `embed.dev.js` is the minified version of this attached file: [embed.dev.js.txt](https://github.com/squidfunk/mkdocs-material/files/6035655/embed.dev.js.txt). It generates URLs from the "data-isso" attribute.

Without `navigation.instant`, comments are properly loaded:

- First load

| Code | Method | URL |
| --- | --- | --- |
| 200 | GET | https://example.org/mkdocs/PAGE |
| 200 | GET | https://example.org/comments/js/embed.dev.js |
| 200 | POST | https://example.org/comments/count |
| 200 | GET | https://example.org/comments/?uri=PAGE&nested_limit=5 |

- Page Reload

| Code | Method | URL |
| --- | --- | --- |
| 200 | GET | https://example.org/mkdocs/PAGE |
| 200 | GET | https://example.org/comments/js/embed.dev.js |
| 200 | POST | https://example.org/comments/count |
| 200 | GET | https://example.org/comments/?uri=PAGE&nested_limit=5 |

I noticed that by enabling `navigation.instant` the request URLs appear modified (XHR interceptor?), but only at the first load of the page.

A user has has in fact to press F5 everytime he changes page, otherwise he will see the comment section, but he won't be able to create or load comments.

- First load

| Code | Method | URL |
| --- | --- | --- |
| 200 | GET | https://example.org/mkdocs/PAGE |
| 200 | GET | https://example.org/comments/js/embed.dev.js |
| 404 | POST | https://example.org/assets/javascripts/bundle/count |
| 404 | GET | https://example.org/assets/javascripts/bundle/?uri=PAGE&nested_limit=5 |

- Page reload

| Code | Method | URL |
| --- | --- | --- |
| 200 | GET | https://example.org/mkdocs/PAGE |
| 200 | GET | https://example.org/comments/js/embed.dev.js |
| 200 | POST | https://example.org/comments/count |
| 200 | GET | https://example.org/comments/?uri=PAGE&nested_limit=5 |

I have tried with clean MkDocs directories multiple times and the problem always (and only) appears when enabling instant navigation.

### Package versions

* Python: `3.9`
* MkDocs: `1.1.2`
* Material: `7.0.0`

### System information

* OS: any
* Browser: any

**Comment by squidfunk** [comment] 2021-02-24 12:41
Could you check whether the behavior is the same with Material 6.2.8?

**Comment by AlphaJack** [comment] 2021-02-24 13:37
Just tried, it's the same

**Comment by squidfunk** [comment] 2021-02-24 17:12
Unfortunately, it's impossible for me to debug without a working example. If you could provide a fully self-contained repository, which I can check out, `pip install` and `mkdocs serve`, I may look into this, but note that I don't have an account for Isso. You can also investigate this yourself and PR, if you manage to find the reason for this. Note that instant loading will evaluate all `script` tags that are part of the `container` component:

https://github.com/squidfunk/mkdocs-material/blob/d6317dc51494309c7b09d4d80fa4611f1e6dc188/src/assets/javascripts/integrations/instant/index.ts#L294-L319

If you don't wish to proceed on this, another option is just to disable instant loading. We can only guarantee that it works without customizations after all, there are just too many possibilities.

**Comment by AlphaJack** [comment] 2021-02-24 19:40
I have sent you an email with demo instances and a self contained MkDocs folder, you should get comments loading even from `mkdocs serve`

**Comment by squidfunk** [comment] 2021-02-24 22:01
I’m sorry but I didn’t receive any email from you.

**Comment by squidfunk** [comment] 2021-02-25 15:03
Thanks for your email. However, this is just a bare repository without any customizations which doesn't run locally due to CORS issues (see screenshot below). I'm very sorry but I cannot invest too much time into problems with third-party integrations that are not officially supported by Material for MkDocs. If you manage to isolate the problem or provide a fix, I'm happy to merge it, but for now, I have to consider this a problem with customization. Thus I'm closing this issue.

<img width="1439" alt="Bildschirmfoto 2021-02-25 um 16 01 07" src="https://user-images.githubusercontent.com/932156/109172254-dcdf2f00-7782-11eb-9e2e-89fe67d94fca.png">

**Closed by squidfunk** 2021-02-25 15:03 UTC
Labels: bug, not reproducible

**Comment by AlphaJack** [comment] 2021-02-26 17:42
Have you even tried from http://127.0.0.1:8000 (the URL that MkDocs prints)?

**Comment by polarathene** [comment] 2021-02-28 23:10
@AlphaJack `127.0.0.1:8000` is equivalent to `localhost:8000`. Your website `jack-p2.cyou` is restricting access from third-party sites. How are you testing/reproducing on your end? If you're running the docs page from the same domain/server, you'd probably not encounter the CORS issue.

Despite this, why is Instant Navigation messing with URLs that aren't related to the docs? Perhaps the fix is just to have the option to configure a filter or exclusion list of domains so that certain URLs can be excluded if they exhibit issues?

**Comment by polarathene** [comment] 2021-03-01 01:23
Here's a quick example, you'd have an object from YAML config in `mkdocs.yml` that gets treated as `filterList`, and take the `el.src` for constructing a [URL object](https://developer.mozilla.org/en-US/docs/Web/API/URL) (note: I haven't handled error if value to `new URL()` would be invalid):

```js
concatMap(el => { 
       const script = createElement("script") 
       const {hostname, pathname} = new URL(el.src)
       const isExcluded = filterList[hostname] && filterList[hostname].some((s) => pathname.startsWith(s))

       if (el.src && !isExcluded) { 
```

Or here's a basic example of the functionality, use a REPL like JSBin to run it online, it uses the [`?.` optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), and I've aliased the destructured prop vars for a more terse equivalent:

```js
// An object with hostname as keys and arrays for paths (just use `/` if no filter path assigned)
let fl = {
  'jsbin.com': ['/help']
}

const {hostname: h, pathname: p} = new URL ('http://jsbin.com/help/getting-started')

if (fl?.[h].some((s) => p.startsWith(s))) {
  console.log(`Exclude rules matched: ${h}${p}`)
}
```

---

The CORS issue might be avoidable with setting a different value for the [script attribute `referrerpolicy`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script), but that's probably related to any third-party plugin generating the script tag to be concerned about rather than `mkdocs-material`.

**Comment by AlphaJack** [comment] 2021-03-01 11:05
@polarathene they are not properly equal because they appear to the browser as different origin. 
I whitelisted 127.0.0.1 because I thought he was going to use the URL printed by `mkdocs serve`, which I used to reproduce the issue locally, but he only tried from `localhost` (which he must have wrote manually in his browser) so he got the CORS issue. I then added "localhost" to the list of allowed origins, but he closed the issue and decided to not retry.

The first time I also sent him two other links to demos with or without instant navigation, so he could also see the wrong redirection to  [/count]() instead of [comments/count]() directly from the server, but he decided to gave up before even opening them.

> Perhaps the fix is just to have the option to configure a filter or exclusion list 

It could be, but my suggestion would be applying this behaviour only to a restricted lists of mkdocs/mkdocs-material generated URLs, like `javascripts` and `stylesheets`, in order to not interfere with URLs generated from other javascript files.

For instance, you can see from the file I attached in my first post that `endpoint + "/count"` is used, but somehow the final URL gets modified to [/count]() only the first time a page is loaded if instant navigation has been set. If I refresh the page or disable instant navigation, the problem is gone.

If he doesn't care about reopening this issue, I'll stick with instant navigation off.

**Comment by polarathene** [comment] 2021-03-02 01:47
> they are not properly equal because they appear to the browser as different origin.

@AlphaJack ah I see. I just reproduced locally to see for myself. I didn't know that CORS was that strict, thanks for pointing that out!

> I whitelisted 127.0.0.1 because I thought he was going to use the URL printed by `mkdocs serve`, which I used to reproduce the issue locally, but he only tried from `localhost` (which he must have wrote manually in his browser) so he got the CORS issue.

To be fair, it's quite common to access local web services for developers via localhost and not IP.

> I then added "localhost" to the list of allowed origins, but he closed the issue and decided to not retry.

This is kind of on you unfortunately and should have been handled in advanced if you knew they'd be treated as distinct at the time.

My interactions with the maintainer here has already given an impression that this behaviour is no surprise. Not that there's anything wrong with them prioritizing their time and focus on what matters to them. It'd probably help if you were a paying subscriber and if others drummed up demand for such.

Without that kind of support; I don't think you'll get much further assistance and just be deferred to maintaining your own patches (that usually aren't welcomed upstream). It has to be a more common issue for the maintainers users for it to matter. AFAIK they don't have any other regular contributors/maintainers (though I haven't looked too deeply), their stance is thus understandable.



> It could be, but my suggestion would be applying this behaviour only to a restricted lists of mkdocs/mkdocs-material generated URLs, like `javascripts` and `stylesheets`, in order to not interfere with URLs generated from other javascript files.

The snippet I provided above should work just as well for covering that, it just becomes a filter for what to apply Instant Nav to, instead of an exclusion filter. Sadly this kind of patch would probably be more fragile to maintain as a third-party (I don't personally have this problem btw).

---

> If he doesn't care about reopening this issue, I'll stick with instant navigation off.

Probably the best option. If the community grows large enough with time and the maintainership doesn't grow with it, you might see a community fork emerge that sees collaboration to address those needs.

My own experiences in wanting to improve `mkdocs-material` for others didn't go down well either. I'm encouraged to fork for such changes:

- I recently identified a typography UI bug and provided a fix for that but it [was quickly dismissed](https://github.com/squidfunk/mkdocs-material/issues/2369#issuecomment-787738204).
- Including a small plugin with fair justification of value to users and use-cases (previously in the project but removed due to citing file size concerns, but it's 323KB..). It was [also quickly dismissed](https://github.com/squidfunk/mkdocs-material/issues/2349#issuecomment-786582262), but with a new reason that accepting it would mean more maintenance and/or result in users requesting more plugins be added.

AFAIK, priorities are to focus on features for Insiders whilst keeping anything else beyond bug fixes (useful to insiders too) to a minimum for the community edition. Contributing PRs for features are welcomed, but at the same time it's been [expressed how that might not workout](https://github.com/squidfunk/mkdocs-material/discussions/2364#discussioncomment-417043) for feature based contributions, as the general interactions within issues would also suggest.

I get the impression this is more of a personal project / product that's open-sourced for the benefits of others, and the sponsorware subscription model introduced last year further solidifies that focus towards a product that can be monetized. I'm in full support of such an approach, but have come to realize this is not like most popular open-source community projects, it has different goals which restrict community contributions, especially with the split to an Insiders build now impacting that.

**Comment by polarathene** [comment] 2021-03-02 04:49
> my suggestion would be applying this behaviour only to a restricted lists of mkdocs/mkdocs-material generated URLs, like `javascripts` and `stylesheets`, in order to not interfere with URLs generated from other javascript files.

I don't mind taking a stab and contributing a PR for this btw. I don't know enough about the internals to know which URLs would be considered "safe" for Instant nav to touch.

~This project is all JS focused on client-side AFAIK, so it might not be able to infer as much information~ (**EDIT:** There's data from `mkdocs.yml` embedded into the HTML). Even then, other plugins might also contribute at build time outside of this project, so it's probably easier to support an exclusion list.

~If `/comments/count` were coming from the same hostname but different subpath. Eg `https://example.com/comments/count` and `https://example.com/some-page`, how would MkDocs pages be detected from non-pages/content? (exclusion filter makes more sense here)~ (**EDIT:** It has access to a sitemap from builds to identify MkDocs pages)

If the hostname is distinct (eg different subdomain or entire hostname), that would be a bit easier, by allowing Instant Nav to only work on any script/content for the hostname the page is running from.

---

For your case, you're hosting the docs under `example.com/mkdocs/`, thus filtering instant nav to only touch script URLs under that route would be sufficient?

If @squidfunk gives the go ahead, I'll create a PR.

**EDIT:** I've found that it's already aware of this base route via `config.base`, but it's possible that instant nav is meant to still work with third-party JS (external or from internal mkdocs plugins and user supplied JS). Probably best to be explicit about what to exclude like I suggested earlier then (could support both filters technically too).

---

<details>
<summary>Investigated this for you... Kinda</summary>

- There is a jinja partial used at build to have a config element in each page to lookup for reference. Data is passed in this way from `mkdocs.yml`.
- This projects TypeScript had me jumping all around the place :sweat_smile: but roughly performs the following:
  ```js
  const script = document.querySelector("#__config")
  let config = JSON.parse(script.innerText)
  config.base = new URL(config.base, new URL(location.href)).toString().replace(/\/$/, "")
  ```
- That gets used to establish the base URL such as `https://example.com/mkdocs` for you. Which the related [`sitemap.xml`](https://squidfunk.github.io/mkdocs-material/sitemap.xml)(using `mkdocs-material` as an example) is then sourced URLs for pages it's aware of at build time (`site_url` from `mkdocs.yml`). This base URL is then used to strip through all these URLs the base and replace it with whatever the deployed base was identified as (so it's not tied to the given domain, useful for temporary preview deploys).
- That then has an event listener trigger on it for when a link is clicked to check if it was one of those sitemap URLs, to perform the instant loading navigation with nav history state and other stuff... I'm going to stop here.

I thought I might have misunderstood what was described as the issue because of this (and the given examples of before/after with/without):

> *I noticed that by enabling navigation.instant the request URLs appear modified (XHR interceptor?), but only at the first load of the page.*

But now realize it's as the snippet above shows, not so much the URL being modified as it is stripping your script element and removing the isso data attribute..? The `assets/javascripts/bundle` path is due to the JS for this theme (with the instant nav logic) AFAIK, perhaps related to rxjs / observable handling.

I'm not entirely sure what's going on there as it seems to add the script tags to the DOM but for whatever reason is messing with the relative URL location that your third-party JS thinks it's running from; relative due to the lack of the data attribute I imagine as a fallback behaviour.

</details>

**Comment by polarathene** [comment] 2021-03-02 06:06
@AlphaJack just setup a reproduction on my end, the suggeted code works, but requires a third condition as the else condition is for script tags with JS text content instead of a source file, in both current conditions they replace the element.

Reproduction is easier with `mkdocs serve` (I just used an external JS file that logs some text to console, and added it to a markdown document as a script element referencing a JS file). If testing at the same `localhost:8000` but via `mkdocs build`, you need to configure `site_url` to this in `mkdocs.yml` otherwise instant loading won't work.

I also tested via Caddy to host the built docs, with the file provided externally of the site build to mimic the layout described here. I didn't see any reason to bother with CORS and requests though as that's unrelated to the issue.

Bug is specifically because of script tag replacement not keeping anything else. I'm not sure why that approach is taken instead of cloning the element properly, but it might be intentional for the feature.

**Comment by polarathene** [comment] 2021-03-02 07:29
Here's a partial fix.

The feature needs to add support in [the theme template](https://github.com/squidfunk/mkdocs-material/blob/73602b23e158c42021d41a31e254d8448f924aa6/src/base.html#L354), there doesn't appear to be support for passing in related config by default. I tested with an object in `theme.features` array that I could store the `excludeFromInstant` object in, this works but obviously hacky without official support.

```ts
  document$
    .pipe(
      skip(1),
      map(() => getComponentElement("container")),
      switchMap(el => of(...getElements("script", el))),
      concatMap(el => {
        const script = createElement("script")
        // `excludeFromInstant` needs to retrieve an object from `config`
        // eg: { 'localhost': ['/comments'] }
        const {hostname: h, pathname: p} = new URL(el.src)
        const shouldExclude = excludeFromInstant?.[h].some( (s) => p.startsWith(s) )

        if (el.src) {
          if (shouldExclude) {
            /* Don't replace this script element */
            return EMPTY
          }
          script.src = el.src
          replaceElement(el, script)

          /* Complete when script is loaded */
          return new Observable(observer => {
            script.onload = () => observer.complete()
          })

        /* Complete immediately */
        } else {
          script.textContent = el.textContent!
          replaceElement(el, script)
          return EMPTY
        }
      })
    )
      .subscribe()
```

I can confirm the issue via reproduction and have a fix that I can create a PR for if @squidfunk is interested in receiving one. I just need advice on how the setting should be approached (`theme.feature_config.nav.instant` perhaps?).

**Comment by squidfunk** [comment] 2021-03-02 08:04
Thanks for investigating. 

Before we proceed, it's necessary to provide a reproducible example. Also, I'm not all for making instant loading more complicated. We could add some logic to detect the script injection edge case, if possible, but other than that instant loading + third-party will always be a challenge. That's also why Material for MkDocs offers integrations like the Mermaid one.

**Comment by squidfunk** [comment] 2021-03-02 08:06
Also note that scripts that are _inside_ the `container` component (e.g. added in Markdown or theme extension) and scripts that are _outside_ the `container` (e.g. specified through `extra_js`). Only the former get replaced. This is intended to allow for adding page-scope and site-scope scripts.

**Comment by squidfunk** [comment] 2021-03-02 08:12
There's information in comments that were retrospectively hidden by the author that might be relevant:

> But now realize it's as the snippet above shows, not so much the URL being modified as it is stripping your script element and removing the isso data attribute..? The assets/javascripts/bundle path is due to the JS for this theme (with the instant nav logic) AFAIK, perhaps related to rxjs / observable handling.

> I'm not entirely sure what's going on there as it seems to add the script tags to the DOM but for whatever reason is messing with the relative URL location that your third-party JS thinks it's running from; relative due to the lack of the data attribute I imagine as a fallback behaviour.

The fix might just be to migrate all attributes over to the new `script` tag. Other than that, it might also be possible to just inject the original script element, if that works. It might not, which is why I chose to just replace the `src`, but `script` elements depending on `data-*` attributes will currently definitely not work with instant loading.

**Comment by AlphaJack** [comment] 2021-03-02 08:50
> Before we proceed, it's necessary to provide a reproducible example.

Here's the same zip I mailed you, also in case @polarathene would like to give it a try: [material-isso.zip](https://github.com/squidfunk/mkdocs-material/files/6067314/material-isso.zip)

Please **go back and forth** between "home" and "test", so you can see the actual behaviour. By reloading a page you will see that the error is gone:

first load
![first-load](https://user-images.githubusercontent.com/19962243/109622203-c4c93000-7b33-11eb-8da3-702024304c6d.png)

reload
![reload](https://user-images.githubusercontent.com/19962243/109622214-c98de400-7b33-11eb-9cf8-3718cc8b2c90.png)

**Comment by polarathene** [comment] 2021-03-02 09:17
> Before we proceed, it's necessary to provide a reproducible example

`docs/page-a.md`:

```md
# Page A
```

`docs/page-b.md`:

```md
# Page B
<script data-something="42" src="/js/whatever.js"></script>
```

`docs/js/whatever.js`:

```js
console.log("reproduction")
```

Something like that should be fine. It's late here and I just wanted to help out by investigating the actual issue and resolving it.

All that mattered was the data attribute was stripped due to element replacement. The `src` URL also gets modified too, but AFAIK that's not an issue.

> instant loading + third-party will always be a challenge.

Opting scripts out of instant loading while enjoying the benefits elsewhere doesn't have to be a challenge. The solution is provided above for anyone who would ever need it, most users won't need it.

All it requires is some where to pull config from of what to exclude and a separate bit of logic to check if the `src` matches with the prefix (eg a location of user scripts not necessarily hosted within the `docs_dir` or `theme.custom_dir`, external scripts can still share the same hostname).

> The fix might just be to migrate all attributes over to the new `script` tag. Other than that, it might also be possible to just inject the original script element, if that works. It might not, which is why I chose to just replace the `src`, but `script` elements depending on `data-*` attributes will currently definitely not work with instant loading.

The solution I shared works by ignoring any modification to the element. I had instant nav working nicely and the script working as expected without it losing the attribute.

> Also, I'm not all for making instant loading more complicated. 

It's not a great option to maintain a workaround separately, but it's up to you if you're going to allow it. I had a concern it might get shut down despite welcoming a solution for it via PR earlier.

**Comment by squidfunk** [comment] 2021-03-07 18:05
b6779114 now preserves all attributes of the `script` tag. This might fix the issue.
