### ISSUE TITLE
site search NOT working with multi languages configed (en+ja)

### ISSUE THREAD

**Issue by urna** [squidfunk/mkdocs-material#1038] opened 2019-03-19 03:24 UTC
when i leave the [extra:  search: language] empty, it works OK with english. 

some people mentioned if set to ja, it could support Chinese, so i tried, but the site search not working now. here is site url https://english.thingswell.cn/ 

version info:
Python 3.4.3
mkdocs, version 1.0.4
mkdocs_material-4.0.2.dist-info

config:
theme: material
site_url: https://english.thingswell.cn/
extra:
  search:
    language: 'en, ja'

but if i only set language to 'en' it works!

**Comment by squidfunk** [comment] 2019-03-19 07:32
Please see #1023. It‘s fixed in master but I’m currently on holiday until end of the week and didn’t manage to prepare a release. Also read the last comment in the linked issue.

**Comment by peaceiris** [comment] 2019-03-22 10:55
## Notes for visitors to this issue

You can avoid this problem to downgrade `mkdocs_material-4.0.1`

Let's looking forward to the next release. (`4.0.3` or later)

**Comment by squidfunk** [comment] 2019-03-22 18:25
Closing, as it is a duplicate of #1023.

**Closed by squidfunk** 2019-03-22 18:25 UTC
Labels: duplicate

**Comment by squidfunk** [comment] 2019-03-22 18:33
Released as part of 4.1.0. Note that you need to change `en, jp` to `en, ja`. `ja` is the official language code for Japanese, lunr-languages switched from `jp` to `ja` and provided an upgrade path still supporting `jp` as an alias, but it would be too costly to support both in Material. Therefore only `ja` is supported from now on.

**Comment by urna** [comment] 2019-03-23 10:43
confirmed it works well now!

**Comment by r8ssan** [comment] 2019-03-23 21:52
I was also in trouble but settled the matter.
 thanks!
