### ISSUE TITLE
Bugs with blog and navigation footer

### ISSUE THREAD

**Issue by mendax1234** [squidfunk/mkdocs-material#5945] opened 2023-09-02 06:47 UTC
### Context

<img width="924" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/62934294/594486dd-64b3-425c-85da-7aff96874a7b">

When l want to change to the `blog` session, the navigation footer displays `None`.

### Bug description

<img width="924" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/62934294/594486dd-64b3-425c-85da-7aff96874a7b">

When l want to change to the `blog` session, the navigation footer displays `None`.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

It doesn't need reproduction. You can see it at the bottom of this [page](https://squidfunk.github.io/mkdocs-material/insiders/)

### Steps to reproduce

Click the link above and scroll down to the bottom.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-09-02 10:30
Thanks for reporting.

> It doesn't need reproduction. You can see it at the bottom of this [page](https://squidfunk.github.io/mkdocs-material/insiders/)

Yes, we need a reproduction. If you don't provide one, we need to create one ourselves first to isolate the problem. Tryint to fix a bug in a large documentation project like Material for MkDocs takes much longer due to slower rebuilds than working on a very small isolated reproduction. Providing a reproduction is your appreciation of our time.

We're happy to fix it immediately, once you provide the reproduction.

**Comment by squidfunk** [comment] 2023-09-02 14:13
Fixed in 6e1c658a9. Next time, please respect our guidelines and provide a reproduction.

**Comment by squidfunk** [comment] 2023-09-02 17:09
Released as part of [9.2.7](https://squidfunk.github.io/mkdocs-material/changelog/#9.2.7).

**Closed by squidfunk** 2023-09-02 17:09 UTC
Labels: bug, resolved
