### ISSUE TITLE
Long abbreviations span large width and wrong position in the table

### ISSUE THREAD

**Issue by Lexachoc** [squidfunk/mkdocs-material#6760] opened 2024-02-11 03:02 UTC
### Bug description

When having long abbreviations, the tooltip will span the entire screen (I think it's related to this fix: https://github.com/squidfunk/mkdocs-material/issues/4810#issuecomment-1369065888 )
However, this is not so easy to read when using the desktop browser or a larger screen.
![image](https://github.com/squidfunk/mkdocs-material/assets/20377719/ec3c03bf-720e-4f1e-962f-630faaef2e8f)

I would expect that the tooltip width to be shorter (normal width but wrapped), I tried to change the `--md-tooltip-width` by including:
  - stylesheets/extra.css
```css
:root {
  --md-tooltip-width: 20rem !important;
}
```

But this doesn't work.

I also noticed that the tooltip is rendered in the wrong position when within a table:
![image](https://github.com/squidfunk/mkdocs-material/assets/20377719/4c5d409f-cfeb-45fa-b39c-b5b0e76ff50c)

It is related to #4217

So three expected behaviors:
1. Tooltips span the entire screen only when the screen size is smaller than the value of `--md-tooltip-width`.
2. When screen size larger than the value of `--md-tooltip-width`, the value of `--md-tooltip-width` is used as the width of the tooltip div.
3. If tooltip in tables, the position of the tooltip should be correct and should follow the two behaviors mentioned above.

Chrome: Version 121.0.6167.161
Edge: Version 121.0.2277.112
mkdocs-material version: 9.5.9

### Related links

- https://github.com/squidfunk/mkdocs-material/issues/4810#issuecomment-1369065888
- https://github.com/squidfunk/mkdocs-material/issues/4217

### Reproduction

[9.5.9-long-abbreviations-issue.zip](https://github.com/squidfunk/mkdocs-material/files/14231176/9.5.9-long-abbreviations-issue.zip)

### Steps to reproduce

1. unzip
2. run `mkdocs serve` in terminal
3. go to http://localhost:8000/

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2024-02-11 05:25
Thanks for reporting and for the reproduction. This is already fixed in [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/), as we swapped out the tooltip implementation to implement [footnote tooltips](https://squidfunk.github.io/mkdocs-material/reference/footnotes/#footnote-tooltips) and [instant previews](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-previews). Once we've collected a little more feedback on those features, we'll back port the new business logic which should also fix this problem ☺️

<img width="674" alt="Bildschirm­foto 2024-02-11 um 12 24 33" src="https://github.com/squidfunk/mkdocs-material/assets/932156/49343efd-71e8-4ddc-9be6-d473802d02e0">

**Comment by Lexachoc** [comment] 2024-02-11 07:37
@squidfunk Thank you for your quick reply! I'm glad that it is already fixed and the new features is wonderful!

**Comment by kamilkrzyskow** [comment] 2024-02-11 16:14
@Lexachoc The extra css:
```css
:root {
  --md-tooltip-width: 20rem !important;
}
```
isn't enough because by default it won't break words. I provided a temporary makeshift solution in a discussion here: https://github.com/squidfunk/mkdocs-material/discussions/6757#discussioncomment-8433750

**Comment by Lexachoc** [comment] 2024-02-11 17:17
@kamilkrzyskow Thank you! I tried your solution and it works great! Also for the tooltip fontsize CSS hint!
I also found that the default tooltip fontsize a bit small for me. Now it looks better when I set it to `font-size: 0.6rem;`

For a better look of the tooltip, I modified the CSS (from: https://github.com/squidfunk/mkdocs-material/discussions/6757#discussioncomment-8433750) to: 
```css
.md-tooltip, .md-tooltip--inline {
  max-width: 10rem;
  word-break: break-all;
  white-space: break-spaces;
}
```

This way there will be no extra spaces on the left and right side if the tooltip is shorter.
![image](https://github.com/squidfunk/mkdocs-material/assets/20377719/ed26a630-600c-4a1c-a505-f52cc5d25cf9)
![image](https://github.com/squidfunk/mkdocs-material/assets/20377719/78fa734f-fff8-42de-9b68-9dde5196350e)
![image](https://github.com/squidfunk/mkdocs-material/assets/20377719/161eb6a7-28bf-4201-980f-27ceb1a7700a)

Thank you again!

**Comment by squidfunk** [comment] 2024-04-14 07:37
Fixed in 599193edfae0d5c879788115075ef7a1eef2e266 – I backported the new tooltip implementation from Insiders in the [refactor/tooltip-positioning](https://github.com/squidfunk/mkdocs-material/tree/refactor/tooltip-positioning) branch! If you could spare a few minutes and check whether this fixes your issue, we can release it in the next days ☺️ Install with:

```
pip install git+https://github.com/squidfunk/mkdocs-material.git@refactor/tooltip-positioning
```

**Comment by Lexachoc** [comment] 2024-04-15 12:09
@squidfunk Thanks for this PR.

![image](https://github.com/squidfunk/mkdocs-material/assets/20377719/1adefbd5-c6a7-4a2e-8579-fd66927caf05)

I can confirm that the issue has been resolved.

**Comment by squidfunk** [comment] 2024-04-15 13:58
Thanks! Keeping open until released.

**Comment by squidfunk** [comment] 2024-04-16 03:49
Released as part of [9.5.18](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.18).

**Closed by squidfunk** 2024-04-16 03:49 UTC
Labels: bug, resolved

**Comment by oceanclub1970** [comment] 2024-04-16 20:04
Hi all, 

I updated to 9.5.18 and the following CSS no longer has any affect on my tooltips - what is the new way to specify the font size, colour etc?

```
.md-tooltip, .md-tooltip--inline {
    max-width: 15rem;
    word-break: normal;
    white-space: break-spaces;
	font-weight: normal;
}

.md-tooltip__inner,
.md-tooltip--inline .md-tooltip__inner {
	max-width: 15rem;
    font-size: 0.7rem;
	color: blue;
	font-weight: normal;
```

**Comment by Lexachoc** [comment] 2024-04-16 20:18
@oceanclub1970 

simply with will do the trick
```css
[role=tooltip]>.md-tooltip2__inner {
  font-size: 1rem;
}
```

Result:
![image](https://github.com/squidfunk/mkdocs-material/assets/20377719/e656150d-d700-441b-954d-b03740ed2b45)

**Comment by squidfunk** [comment] 2024-04-17 00:44
Thanks @Lexachoc for sharing! [Improved tooltips](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#improved-tooltips) are still experimental, which means we might change the implementation as we discover new problems on the way without considering it a breaking change.

Note that `.md-tooltip2*` is also a class name/scope that is ephemeral – right now we have two co-existing tooltip implementations that will be consolidated once everything is sorted out. We just needed to solve the bugs quickly, which is why I decided to let them co-exist for a short while. I hope for your understanding – adopting customizations like width and font size will be very easy as @Lexachoc pointed out.
