### ISSUE TITLE
Section display text alias overridden with same .md files

### ISSUE THREAD

**Issue by LizThompson93** [squidfunk/mkdocs-material#7192] opened 2024-05-17 21:57 UTC
### Context

There's many ways to organize my content and so I want the navigation to point towards the same .md file but with different names.

### Bug description

Expected: Material Mkdocs would respect the verbatim display text for a section in mkdocs.yml even when pointing towards the same .md file.

Placeholder example:
![image](https://github.com/squidfunk/mkdocs-material/assets/96261305/59bd1701-eede-4657-8708-7d50828ae3ad)

Current: Display text gets overridden to use the first one set. I expected more of a "what you set is what you get" consistent behavior.

![image](https://github.com/squidfunk/mkdocs-material/assets/96261305/4a38202a-b6a3-4fae-98e1-66aa9d037b33)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[9.5.23-example.zip](https://github.com/squidfunk/mkdocs-material/files/15358459/9.5.23-example.zip)

### Steps to reproduce

Set nav to:
```
  - Home: 'index.md'
  - 'French Cuisine':
    - 'Main Dishes': 'French Cuisine.md'
    - 'Dessert': 'French Cuisine.md'
  - 'Food Ideas': 'French Cuisine.md'
```

### Browser

Chrome, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [ ] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-05-18 06:11
Thanks for reporting and providing the reproduction. This is an upstream issue that has already been reported to the maintainers of MkDocs in https://github.com/mkdocs/mkdocs/issues/3428. If you wish to follow up on the reasoning why this will or cannot be implemented, it's a good idea to comment on this issue ☺️ Closing as upstream.

**Closed by squidfunk** 2024-05-18 06:11 UTC

**Comment by squidfunk** [comment] 2024-05-18 06:17
The moment I sent the comment, I realized that this is actually a different bug! I agree that MkDocs should not override the titles that are explicitly set in the `nav` entry, and this was the exact behavior until [the recent 1.6 release](https://github.com/mkdocs/mkdocs/releases/tag/1.6.0). For this reason, yes, it is related to https://github.com/mkdocs/mkdocs/issues/3428, but it is a different bug that should be reported to the maintainers of MkDocs. Could you open an issue upstream?

It is not specific to Material for MkDocs – also happens with the `mkdocs` theme:

![screenshot-localhost-8000-1716012841543](https://github.com/squidfunk/mkdocs-material/assets/932156/65c1f9ec-4bfe-4367-8f3d-b05e872e29f7)
