### ISSUE TITLE
Setting `dev_addr` to `localhost` breaks `navigation.instant` as of 9.4.3

### ISSUE THREAD

**Issue by johnthagen** [squidfunk/mkdocs-material#6204] opened 2023-10-16 14:38 UTC
### Context

Originally discussed at

- https://github.com/squidfunk/mkdocs-material/issues/6102#issuecomment-1764385578

### Bug description

Mkdocs has a [`dev_addr` configuration](https://www.mkdocs.org/user-guide/configuration/#dev_addr).

If the user configures this to:

```yaml
dev_addr: localhost:8001
```

This breaks the `navigation.instant` feature. Clicking on links in the navigation or within the pages will not update the contents on screen correctly.

<img width="386" alt="Screenshot 2023-10-16 at 10 33 56 AM" src="https://github.com/squidfunk/mkdocs-material/assets/10340167/c484bf9c-412d-43df-a2c3-943ed6541f44">

#### Solution 1

Note, that strictly speaking the Mkdocs docs state that the format should be `IP:Port`, and `localhost` is not an IP. Moving this to `127.0.0.1:8001` fixes this issue, but since it used to work, I thought I'd report to see if there are any other underlying issues to address.

Could this instead fail hard with a clear error message?

#### Solution 2

`9.4.2` release does not exhibit this "bug".

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation

### Reproduction

[9.4.6-dev_addr-localhost-navigation.zip](https://github.com/squidfunk/mkdocs-material/files/12918091/9.4.6-dev_addr-localhost-navigation.zip)

### Steps to reproduce

- Check out: https://github.com/johnthagen/python-blueprint/tree/mkdocs-dev_addr-bug-report
- [Install Poetry](https://python-poetry.org/docs/#installation)
- `poetry install`
- `nox -s docs_serve`

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment] 2023-10-16 15:05
What operating system are you on? Can you confirm that `localhost` resolves to `127.0.0.1`? (e.g., `nslookup localhost`) What does the network view in the browser's developer tools show? 

I built your site but running `mkdocs` directly, having installed packages only as `mkdocs` asked for them (not sure what 'poetry' and 'nox' are). It seems to be working fine on my machine, so I recon it is something about your machine or an interaction with other plugins and tools you are using. Hope this helps you narrow it down more.

**Comment by iBug** [comment] 2023-10-17 05:44
Doesn't make sense to me. I also could not reproduce on my machine (Ubuntu 22.04, kernel 5.15.0-86-generic, Python 3.10.12, other packages installed latest on a fresh venv). Maybe this is something macOS-specific.

Also it would help better if your ZIP contained a **minimal** reproduction, not something with poetry or nox or whatever.

**Comment by johnthagen** [comment] 2023-10-17 11:13
>  not something with poetry or nox or whatever.

The zip file itself has a `requiremens.lock.txt` in it, so that should be usable with bare `pip` and no need to use Poetry or nox. I included the Poetry/nox instructions for someone who wanted to check it out directly from my branch.

> Maybe this is something macOS-specific.

Perhaps the auto-reloader/server works differently on macOS? I've seen similar differences on Flask and other similar auto-reload projects in the past.

Since it worked on 9.4.2 and broke specifically starting at 9.4.3, I thought it was worth reporting in case there is something underlying. If the maintainer would like to close this issue, I'm also fine with that as well, since I was able to fix my particular issue by using `127.0.0.1` instead of `localhost`.

**Comment by iBug** [comment] 2023-10-17 11:23
You skipped the only bold word in my response: Please provide a **minimal** reproduction so others can actually look into it without various plugins interfering. Also, I reviewed [`9.4.2...9.4.3`](https://github.com/squidfunk/mkdocs-material/compare/9.4.2...9.4.3) and did not find anything that makes sense.

Based on those reviews, I'm inclined to believe there's something wrong with another component in your setup, and definitely not the theme's fault. Chances are very likely that you upgraded the faulty component along with the theme from 9.4.2 to 9.4.3.

**Comment by squidfunk** [comment] 2023-10-17 11:33
Thanks @alexvoss and @iBug taking the tim to help here. I'm closing this as not reproducible for now. If @johnthagen provides a minimal reproduction that allows us to inspect the error, we can reopen this issue.

**Closed by squidfunk** 2023-10-17 11:33 UTC
Labels: needs reproduction
