### ISSUE TITLE
Repository stats lost after upgrade to 7.x

### ISSUE THREAD

**Issue by lyz-code** [squidfunk/mkdocs-material#2350] opened 2021-02-26 11:19 UTC
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

The issue occurs too with the default mkdocs template, although I don't find it relevant

## Description

After I've upgraded to the version 7.x the [Github repository stats are not showing up anymore](https://lyz-code.github.io/blue-book/). It looks that [mkdocs-material docs](https://squidfunk.github.io/mkdocs-material) are not showing them either, although I don't know if you had them before.

I've checked that the feature works with 6.2.8 but fails since 7.0.0.

### Expected behavior

Github repository stats are shown in the top right header.

### Actual behavior

They aren't shown.

### Steps to reproduce the bug

1. Have a working mkdocs.yml with the section:

```yaml
repo_url: https://github.com/lyz-code/blue-book
```
2. Check it works with 6.2.8
3. Upgrade to 7.0.0

### Package versions

* Python: 3.7.3
* MkDocs: 1.1.2
* Material: 7.0.x

### Project configuration

``` yaml
repo_url: https://github.com/lyz-code/blue-book
theme:
  name: material
```

### System information

* OS: Debian
* Browser: Firefox

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment] 2021-02-26 11:23
Duplicate of #2339 – it's the same reason.

**Comment by squidfunk** [comment] 2021-02-26 12:35
Closing as duplicate.

**Closed by squidfunk** 2021-02-26 12:35 UTC
Labels: bug, duplicate
