### ISSUE TITLE
GLightBox instructions incomplete?

### ISSUE THREAD

**Issue by coillarach** [squidfunk/mkdocs-material#5332] opened 2023-04-06 11:50 UTC
### Description

I am trying to integrate the GLightBox functionality using the instructions provided which include two steps:

1. Install the package with pip
2. Update the plugins section of the mkdocs.yml file 

I have done both of these, but there is no change in behaviour. I am guessing that there is something missing from the documentation rather than there being a bug in the code. 

The screenshot below shows my view of the yml file in PyCharm with the installed packages in the lower pane.

<img width="621" alt="Screenshot 2023-04-06 at 12 49 45" src="https://user-images.githubusercontent.com/11768242/230368505-732688a7-1728-4796-bb17-34f7db8e6200.png">

### Related links

- [GLightBox](https://squidfunk.github.io/mkdocs-material/reference/images/#lightbox)

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment] 2023-04-07 10:45
I can't replicate what you're experiencing. Once I install the plugin and add it to the configuration exactly as mentioned on our documentation, it works immediately. If you can provide a reproduction, we can look into it, but other than that I'm not able to reproduce the behavior you are reporting. Closing as not reproducible.

**Closed by squidfunk** 2023-04-07 10:45 UTC
Labels: documentation

**Comment by kamilkrzyskow** [comment] 2023-04-07 12:35
In the screenshot above I see some `conda_forge` and `pypi`, which point at 2 different Python package repositories being used? 
I always use `pip freeze` to see the installed packages, so I'm not even sure which command triggered such output.
Make sure you're not running multiple Python installations / site-packages in that project ✌️

**Comment by kamilkrzyskow** [comment] 2023-04-07 13:40
@coillarach 
On second look I see that the `plugins` section is in the `theme` section. This is incorrect.
As per the documentation the `plugins` need to be on the root level of the `mkdocs.yml` file. On the same level as the `theme` not indented inside it.

**Comment by squidfunk** [comment] 2023-04-07 13:42
@kamilkrzyskow woah, good catch! Thanks! I missed that. Yes, that is definitely the problem! Should be:

``` yaml
plugins:
  - glightbox
```

It is highly recommended to set up [configuration validation](https://squidfunk.github.io/mkdocs-material/creating-your-site/#visual-studio-code), which will catch those errors.

**Comment by coillarach** [comment] 2023-04-12 08:45
I can confirm that this is now sorted. Thanks for the assistance!
