### ISSUE TITLE
Mike version selector disappears if documentation header changes due to scrolling down

### ISSUE THREAD

**Issue by framesetter99** [squidfunk/mkdocs-material#7637] opened 2024-10-23 08:46 UTC
### Context

Not sure if this is expected behavior or a bug.

### Bug description

When using mike and displaying the default version selector, the selector disappears when there is a longer document and the user scrolls down. This is happening because the document header changes as one is entering another section.

 I would expect that the version selector stays regardless of the header change.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

This is based on your version example, just added some dummy text to index.md so that the document gets longer.
[9.5.42-sticky_version_selector.zip](https://github.com/user-attachments/files/17487856/9.5.42-sticky_version_selector.zip)

### Steps to reproduce

1. Clone https://github.com/mkdocs-material/example-versioning
2. Apply the changed ``index.md`` from the zip archive
3. Deploy a new version locally ``mike deploy --update-aliases 0.5 latest``
4. Serve it locally ``mike serve``
5. Open version 0.5
6.  Make the browser window a little smaller and scroll down so that the header changes

Header when on top:
![header_default](https://github.com/user-attachments/assets/8d57977e-cc2d-475a-b584-77a238321480)

Header when scrolled down:
![header_scrolled_down](https://github.com/user-attachments/assets/935cb823-6cde-4a6d-b516-a70b7aeb021b)

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-10-23 09:40
Thanks for reporting! This is actually by design, since the version selector is part of the changing header. We would need to move the version selector somewhere else otherwise, and I haven't found a good position other than the header.

Thus, we're closing this as working as intended.

**Closed by squidfunk** 2024-10-23 09:40 UTC
