### ISSUE TITLE
Reset search highlighting

### ISSUE THREAD

**Issue by savchenko** [squidfunk/mkdocs-material#3471] opened 2022-01-17 05:03 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

After user has entered something in the search field and clicked on one of the results, all matching terms stay highlighted indefinitely.

I propose to add a button and a hotkey (how about <kbd>Esc</kbd>?) so these can be removed without resorting to manual address bar editing and subsequent page reload.

Somewhat related to https://github.com/squidfunk/mkdocs-material/issues/3409

### Use Cases

User has search for a common word and navigated to a correct page. There are 200+ occurrences of the word which makes it hard to read the page for an extended period of time.

### Screenshots / Mockups

N/A

**Comment by squidfunk** [comment] 2022-01-17 08:46
Thanks for suggesting. This is an exact duplicate of #2864, which was open for 4 months and got 1 upvote. Therefore I'm currently not considering it a useful addition. Closing.

**Closed by squidfunk** 2022-01-17 08:46 UTC

**Comment by savchenko** [comment] 2022-01-17 09:09
Hm, somehow missed that one. Upvoted.
