### ISSUE TITLE
Include MathJax only if there are formulas on the page

### ISSUE THREAD

**Issue by savchenko** [squidfunk/mkdocs-material#2310] opened 2021-02-19 00:11 UTC
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

MkDocs includes `tex-mml-chtml.js` into every page which is an additional ~752Kb transfer.
Serving the MathJax-specific JS only if rendered page contains `$...$` blocks will save close to the megabyte per page.

### Use Cases

Any case where serving additional traffic is undesirable. Which is... Every case?

### Screenshots / Mockups

N/A

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by facelessuser** [comment] 2021-02-19 00:14
How are you including MathJax? I wasn't aware of Material doing it automatically.

**Comment by savchenko** [comment] 2021-02-19 00:22
> How are you including MathJax? I wasn't aware of Material doing it automatically.

As per manual: https://squidfunk.github.io/mkdocs-material/reference/mathjax/
The only difference in my case is that I have fetched the files from CDN and serving JS from a local folder.

**Comment by facelessuser** [comment] 2021-02-19 01:04
Ah, the problem is that you are including it in `extra_javascript `, which will include it on every page. I actually include it at the end of the page that I want to have MathJax. I do this via the Snippets extension: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/.

1. I point Snippets to my `_snippets` folder: https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml#L131

2. And then I place this at the bottom of the page I want to use MathJax:

    ```
    ---8<---
    mathjax.txt
    ---8<---
    ```

You can see that `mathjax.txt` contains my config and the MathJax lib: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/markdown/_snippets/mathjax.txt

**Comment by squidfunk** [comment] 2021-02-19 08:27
Thanks for submitting an issue. If you wish for selective integration, @facelessuser's proposal is the way to go. Nonetheless, we have an automatic integration for Mermaid in place (#2170), but not for MathJax. Maybe worth considering.

**Comment by squidfunk** [comment] 2021-02-19 16:02
@facelessuser's answer is the way to go. Closing!

**Closed by squidfunk** 2021-02-19 16:02 UTC

**Comment by savchenko** [comment] 2021-02-20 01:12
@facelessuser ,
Works like a charm, thank you!


@squidfunk ,
> we have an automatic integration for Mermaid in place (#2170), but not for MathJax. Maybe worth considering.

Solution from Isaac works well, however having this happening automatically is easier / less confusing for an end-user. Depends on the complexity of implementation I reckon; certainly your call.
