### ISSUE TITLE
Search dialogue remains at "Initializing search"  when search.lang=ja and  with tags in md file

### ISSUE THREAD

**Issue by Changccs** [squidfunk/mkdocs-material#4069] opened 2022-06-27 06:35 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

 search dialogue remains at "Initializing search" when setting search.lang=ja  and  writing md file with tags in the metadata

### Expected behaviour

searching  works as usual.

### Actual behaviour

Search dialogue remains at "Initializing search"

### Steps to reproduce

1. install  mkdocs and mkdocs-material , and create a project by  "mkdocs new ..."
2. edit docs/index.md  like this and mkdocs.yml as Configuration below 
_$ cat docs/index.md
---
tags:
  - t
---
# Welcome to MkDocs

3. start mkdocs by "mkdocs serve"  and click the search dialogue in browser , you'll see "Initializing search" remains , and there is an error in browser like this - 
![error](https://user-images.githubusercontent.com/108253865/175874081-dba2641b-8ad6-4934-b4f3-cd8284f44e87.JPG)

### Package versions

mkdocs: version 1.3.0 from .... Python 3.7
mkdocs-material: Version: 8.3.8

### Configuration

```yaml
site_name: My Docs

theme:
    name: material
    languange: en

plugins:
    - tags
    - search:
        lang: ja
```

### System information

- Operating system: 
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

- Browser: 
firefox 101.0.1

**Comment by squidfunk** [comment] 2022-06-27 06:37
Thanks for reporting. Please provide a minimal reproducible example and attach it here as a zip file.

**Comment by Changccs** [comment] 2022-06-27 06:52
[mkdocs.zip](https://github.com/squidfunk/mkdocs-material/files/8989277/mkdocs.zip)
thanks~

**Comment by Changccs** [comment] 2022-06-27 06:58
I tried the minial reporduce steps this moring : 
1. make a new mkdocs project 
2. change the docs/index.md (add tags  on the top) and mkdocs.yml (set search.lang=ja  and tags) as the zip file shows.
3. "mkdocs serve"  then turn to the browser and  search.

if there's   " no tags information in the md file "  or  "  search.lang=en " , search dialogue can still work properly.

**Comment by squidfunk** [comment] 2022-06-27 07:37
Thanks for providing the reproduction! Indeed, this seems to be a problem with the Japanese segmenter.

**Comment by Changccs** [comment] 2022-06-27 09:57
Thanks alot , then is it possible to be fixed in here or we need to wait for lunr to make some changes

**Comment by squidfunk** [comment] 2022-06-27 10:14
I'll see if we can work around it.

**Comment by squidfunk** [comment] 2022-07-02 07:18
Okay, so I've taken some time to investigate the issue, and I'm confident to say that it's originating from the tokenizer that is shipped with Japanese language support in [lunr-languages](https://github.com/MihaiValentin/lunr-languages) (our upstream dependency), shipping a [custom implementation](https://github.com/MihaiValentin/lunr-languages/blob/177653fb567006478ccb0ab6920b78eb77cad14e/lunr.ja.js#L88-L156) that seems to be incompatible with lunr's implementation (also see https://github.com/MihaiValentin/lunr-languages/issues/45#issuecomment-749662427):

<img width="530" alt="Bildschirmfoto 2022-07-02 um 09 16 18" src="https://user-images.githubusercontent.com/932156/176990806-c549b4a3-a592-4cb0-a634-9fd55e082321.png">

I think you have two options here:

- Create a minimal reproducible example and file the issue [upstream](https://github.com/MihaiValentin/lunr-languages)
- Switch to [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/), since we completely rewrote the search, including segmentation for Japanese and Chinese

I rewrote the tokenizer completely from scratch, since lunr's default tokenizer has several problems. If you're interested how it works, I wrote a [blog article](https://squidfunk.github.io/mkdocs-material/blog/2021/search-better-faster-smaller/) about it. I'm afraid this is not back-portable without pulling in the entire source code of the new tokenizer, which is bound to the [Carolina Reaper funding goal](https://squidfunk.github.io/mkdocs-material/insiders/#10000-carolina-reaper). 

With that said, I'm closing this issue. I understand that switching to Insiders might not be an option for some users, but it's all I can offer right now. Other than that, reporting this upstream might be a good idea nonetheless.

**Closed by squidfunk** 2022-07-02 07:18 UTC
Labels: bug

**Comment by Changccs** [comment] 2022-07-04 22:34
Got it.  Thank you for taking time to investigate on this. You're doing an awesome job , I wish I could afford switching to Insiders someday.
