### ISSUE TITLE
Clicking the sidebar heading (desktop size, JS disabled) makes the sidebar disappear when in a sub-section

### ISSUE THREAD

**Issue by JaneSmith** [squidfunk/mkdocs-material#710] opened 2018-02-22 07:03 UTC
## Description

At a full desktop size, the theme displays the sidebar always visible. However, clicking on the header text for that sidebar makes the entire sidebar disappear when the following conditions are both true:

1. JavaScript is disabled.
2. You're in a sub-section of the site.

I assume this is because the header text is a label for the checkbox, and clicking that toggles the checkbox, which then makes the entire sidebar disappear. The only fix for this when it happens seems to be to shrink the browser size down to a mobile/tablet layout, use the hamburger menu to go back to the sub-section menu, and then expand the browser size again.

I understand that the experience won't be perfect without JavaScript, but couldn't this be fixed by making the `--active` tag override the state of the checkbox when at the full desktop size? If you're at the full desktop size, you always want the sidebar visible, so can't you just ignore the checkbox state and display the `--active` nested sidebar?

### Expected behavior

Clicking on the heading should not do anything.

### Actual behavior

Clicking on the heading makes the entire sidebar disappear.

### Steps to reproduce the bug

1. Open Firefox Nightly and disable JavaScript.
2. Go to https://squidfunk.github.io/mkdocs-material/extensions/admonition/
3. Expand the browser to a large size to get the full desktop layout.
4. Click on the "Extensions" heading on the left sidebar. Poof! It disappears.

### System information

* OS: Windows 10 Pro.
* Browser: Firefox Nightly (60.0a1).

**Comment by squidfunk** [comment] 2018-02-22 18:23
Indeed confirmed. I will check if there's a fix.

**Comment by squidfunk** [comment] 2018-02-22 18:44
> I understand that the experience won't be perfect without JavaScript, but couldn't this be fixed by making the --active tag override the state of the checkbox when at the full desktop size? If you're at the full desktop size, you always want the sidebar visible, so can't you just ignore the checkbox state and display the --active nested sidebar?

The problem is, that there's a lot of CSS hacking to make it work without copying a lot of elements. We need to use the active state, because it is used to determine which part of the menu to render. However, I think I have a simple fix.

**Comment by squidfunk** [comment] 2018-02-22 18:55
Fixed in 060a5df1f5b7a7683ab5fd7398c3be2b8b419d07

**Comment by squidfunk** [comment] 2018-02-22 19:22
Released as part of 2.6.6.

**Closed by squidfunk** 2018-02-22 19:22 UTC
Labels: bug
