### ISSUE TITLE
`_` characters in file paths do not render appropriately in code reference

### ISSUE THREAD

**Issue by arosen93** [squidfunk/mkdocs-material#5864] opened 2023-08-21 01:35 UTC
### Bug description

In my Python package, I have code in folders with underscores, e.g. `quacc.recipes.emt._jobflow.slabs`. When constructing the code reference API, this gets rendered as 95jobflow instead of `_jobflow`.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

See the docs here: https://quantum-accelerators.github.io/quacc/reference/quacc/recipes/emt/_jobflow/slabs.html

![image](https://github.com/squidfunk/mkdocs-material/assets/8674072/5935b942-44bd-43fc-ad2e-b43394b2e614)

### Steps to reproduce

Make a code reference from code with `_` in file path.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [ ] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

This was a pretty simple bug to report, so I haven't supplied a minimal reproduction, but I can certainly do that shortly.

**Comment by squidfunk** [comment] 2023-08-21 06:17
Thanks for reporting. This issue is incomplete – there's no reproduction that we can run. Additionally, we're unable to reproduce it with the information provided. Those are the very reasons that it is mandatory to stick to our [bug reporting process](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Please read the guide carefully and provide the required information. Until then, we're closing this issue as not reproducible:

<img width="203" alt="Bildschirm­foto 2023-08-21 um 08 16 00" src="https://github.com/squidfunk/mkdocs-material/assets/932156/addeb8db-6304-42d7-b197-c7dfa83cb627">

**Closed by squidfunk** 2023-08-21 06:17 UTC

**Comment by arosen93** [comment] 2023-08-21 06:24
That's fair! Apologies --- I was going to update tomorrow. I'll open a new issue the instead.

**Comment by squidfunk** [comment] 2023-08-21 08:53
Thanks! Please try other themes before opening an issue, e.g. `mkdocs` and `readthedocs`. If they exhibit the same behavior, you should report it to MkDocs.
