### ISSUE TITLE
Searching for integers or version numbers does not work

### ISSUE THREAD

**Issue by michael-nok** [squidfunk/mkdocs-material#1773] opened 2020-06-22 16:03 UTC
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

When searching for numbers, either on their own, or as part of a word (e.g. SHA256), the search function does not yield any results.

### Expected behavior

I would expect that, by default, searching for numbers (integers) would be supported.  In fact, it seems like it used to be supported, but has been removed or disabled.

### Steps to reproduce the bug

1. Visit https://squidfunk.github.io/mkdocs-material/releases/changelog/ and search for "2020" or "5.3.2".  No results will be found.
2. Visit https://square.github.io/okhttp/changelog/ and search for "2020" or "4.7.1" and the search function will find results.

On my own installation of Material for Mkdocs, I've tested modifying the search.config.pipeline to remove the trimmer and stopWordFilter, but nothing seems to impact the behavior of looking for numbers or digits with decimal points.

**Comment by squidfunk** [comment] 2020-06-22 18:09
OkHTTP is Running Material 4.x, so I guess this is a regression as there’s no reason why searching for numbers shouldn’t work. It might be related to the transform function that is applied before the query is sent to lunr.js.

**Comment by squidfunk** [comment] 2020-06-23 06:50
Fixed in a3c03aef. Now that was a super funny bug. It's coming from the search transform's first replacement, which removes rogue control characters:

https://github.com/squidfunk/mkdocs-material/blob/e6e7536356be27ad4da49e8d782f2e875ef323c6/src/assets/javascripts/integrations/search/transform/index.ts#L52

The `-` is not escaped, so the left and right characters, namely `+` and `:` are now forming a range from `+-:`, which includes the characters `+,-./0123456789:`. Everything within this range is filtered from the query, as long as it is either at the beginning of the query, preceded by whitespace. 😁 This is now fixed:

https://github.com/squidfunk/mkdocs-material/blob/a3c03aefb9ea273cc4802e6b451e927345934294/src/assets/javascripts/integrations/search/transform/index.ts#L52

**Comment by michael-nok** [comment] 2020-06-23 11:53
Amazing, thank you so much for fixing this!  I'm glad you enjoyed the challenge :)

**Comment by squidfunk** [comment] 2020-06-24 06:37
Released as part of 5.3.3

**Closed by squidfunk** 2020-06-24 06:37 UTC
Labels: bug, fix available

**Comment by michael-nok** [comment] 2020-06-25 14:41
I installed 5.3.3, and the bug does not seem to be fixed completely, or else the behaviour is not quite what I expected.
mkdocs-material                           5.3.3

- If I search for numbers, they aren't highlighted as part of the search identification (i.e. showing what's being matched).
- Using a period seems to break the query. This might be an incorrect configuration on my end. Do I need to include "." as part of the search.separator list, or keep it off the list?

**Comment by squidfunk** [comment] 2020-06-25 15:14
> - If I search for numbers, they aren't highlighted as part of the search identification (i.e. showing what's being matched).

Yes, it should be highlighted.

> - Using a period seems to break the query. This might be an incorrect configuration on my end. Do I need to include "." as part of the search.separator list, or keep it off the list?

What do you mean by "breaks"? Try searching for "5.1.2" on the official docs - everything works fine including type-ahead.

> It looks like this incorrect range "+-:" is used in other files:
> highlighter/index.ts
> 74: .replace(/[\s*+-:~^]+/g, " ")

Oh yes, I guess I missed the other occurrences! Feel free to submit a PR, so we can get highlighting back to work. Using a `.` works for me on the official docs.

> And in the document cleanup, the "." is being stripped out.
> document/index.ts
> 83: .replace(/\s+(?=[,.:;!?])/g, "")

The regex does only apply to those characters if they are preceded by whitespace, i.e. `\s+`.

**Comment by michael-nok** [comment] 2020-06-25 15:34
> > * Using a period seems to break the query. This might be an incorrect configuration on my end. Do I need to include "." as part of the search.separator list, or keep it off the list?
> 
> What do you mean by "breaks"? Try searching for "5.1.2" on the official docs - everything works fine including type-ahead.

Maybe I'm doing something wrong, but if I leave the config.separator as the default value ( "[\s\-]+" ) in partials/language/en.html I am able to look for something like "v1.0.0" 

However, if I include "." as a separator ( "[\s\-\.]+" ), this functionality breaks.  Am I doing something wrong?
Reference: https://www.mkdocs.org/user-guide/configuration/#separator

**Comment by squidfunk** [comment] 2020-06-25 16:24
`[\s-.]+` should be `[\s\-.]+`
