### ISSUE TITLE
Installation of exporter plugin

### ISSUE THREAD

**Issue by sm100327** [squidfunk/mkdocs-material#7488] opened 2024-08-30 09:38 UTC
### Context

I am trying to install mkdocs-exporter in the docker container as described in the documentation 

```
FROM squidfunk/mkdocs-material
RUN pip install mkdocs-exporter
```

https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker

one requirement is "playwright" and this can not be installed because it does not find any usable versions.
It seems to be a problem with the platform (the container)

### Bug description

Try to install playwright

`pip install playwright`

in the container fails with "no version" 

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

The reproduction does not really apply here i think

### Steps to reproduce

Add  

`RUN pip install mkdocs-exporter`

to the Dockerfile and build the container

docker build -t squidfunk/mkdocs-material .

the installation does not finish with this error (error from manual pip install in container)

`ERROR: Could not find a version that satisfies the requirement playwright==1.33.0 (from versions: none)`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by kamilkrzyskow** [comment] 2024-08-30 10:28
Hello @sm100327,
the issue is probably same as https://stackoverflow.com/questions/74254853/installing-playwright-in-docker-image-fails
Material for MkDocs uses Alpine-based containers, and playwright doesn't compile a wheel for this Linux variant.

So I guess your only option now is to make another Docker image based on Ubuntu, or modify the one provided by Microsoft <https://hub.docker.com/r/microsoft/playwright>

**Comment by sm100327** [comment] 2024-08-30 10:35
Hi @kamilkrzyskow 

thank you for the fast answer, ok, we will discuss the option of creating our own container

soeren

**Comment by squidfunk** [comment] 2024-08-30 10:47
Closing as out of scope.

**Closed by squidfunk** 2024-08-30 10:47 UTC
