### ISSUE TITLE
Details: add back-to-top button for long admonitions

### ISSUE THREAD

**Issue by deponovo** [squidfunk/mkdocs-material#7073] opened 2024-04-21 19:54 UTC
### Description

- Content tabs are typically suitable for short contents. However, as per usual, there are exceptions to the rule. In this case with the downside that once a long collapsible content tab is expanded, the page gets long and you better be ready to scroll back to the header of the tab if you would like to re collapse it. For such cases, it would be highly valuable to have a button at the bottom allowing to re collapse the content back. In a way this shares the same philosophy behind the "Back to the top" button.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

See "Description".
Besides having noticed the need for such feature in my own projects, I actually got triggered by this content tab while visiting the pydantic documentation: https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel then locate "Source code in pydantic/main.py"

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment] 2024-04-22 01:41
Thanks for suggesting. I hope I understand you correctly, but this feature request does not talk about [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/), but about [collapsible admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks). I've adjusted the title to reflect that, so others can find this feature request more easily ☺️

From our perspective, albeit a valid feature request, it's a rather edgy use case, and I'm not sure if this helps when you're in the middle of an admonition/details block, as you'd need to scroll further down to find the bottom. Thus, we're considering this out of scope, which means we're currently not considering this to be ready for inclusion.

However, you can achieve something that implements almost the same functionality with a few lines of [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css):

``` css
.md-typeset summary {
  position: sticky;
  top: 48px;
  z-index: 1;
  backdrop-filter: blur(10px);
}
```

Now, when scrolling down, the header of the container will stick to the top, so you can close it at any scroll position:

https://github.com/squidfunk/mkdocs-material/assets/932156/93b1be4c-eef7-494c-9cca-d129d886b46c

**Closed by squidfunk** 2024-04-22 01:41 UTC

**Comment by deponovo** [comment] 2024-04-24 18:40
The video somehow does not play on firefox. On edge was ok. I added the css lines to my css and somehow I do not obtain the same effect. I also tried with a clean css stylesheet, just in case I had some conflicting entries, but still not working. But indeed, that would be a solution to my proposal.

**Comment by squidfunk** [comment] 2024-04-27 00:41
So, I've checked the proposed solution again, and it works for me. I've created a minimal reproduction that you can check out and run and play with: [9.5.19-sticky-details.zip](https://github.com/squidfunk/mkdocs-material/files/15136139/9.5.19-sticky-details.zip)

**Comment by Ast3risk-ops** [comment] 2024-05-10 15:43
You can apply this to specific admonition types like so:

```css
.md-typeset .TYPE>summary {
    position: sticky;
    top: 48px;
    z-index: 1;
    backdrop-filter: blur(10px);
}
```

Or as another class:

```css
.md-typeset .follow > summary {
    position: sticky;
    top: 48px;
    z-index: 1;
    backdrop-filter: blur(10px);
}
```

```md
??? info follow
    This admonition's header will now follow you down the page.
```

**Comment by deponovo** [comment] 2024-05-10 19:00
> So, I've checked the proposed solution again, and it works for me. I've created a minimal reproduction that you can check out and run and play with: [9.5.19-sticky-details.zip](https://github.com/squidfunk/mkdocs-material/files/15136139/9.5.19-sticky-details.zip)

I confirm it is working. Thank you.
