### ISSUE TITLE
Instant Preview w/ Content Tab

### ISSUE THREAD

**Issue by santaimpersonator** [squidfunk/mkdocs-material#6875] opened 2024-03-06 01:30 UTC
### Bug description

When enabling the instant preview feature, the rendering of a linked content tab only show the tabs and not the content below:
![image](https://github.com/squidfunk/mkdocs-material/assets/36016723/0e528139-19d0-47f2-9169-df0da626d75f)

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-previews
- https://github.com/squidfunk/mkdocs-material/issues/6704

### Reproduction

Unfortunately, the build file for the reproduction was 80MB (and too big); probably due to all the images stored. _(*I'll work on processing my commits to the project, so I can submit a reproduction later this week)_

However, the site can be reproduced from our repository:
https://github.com/sparkfun/SparkFun_GNSS_mosaic-X5

*Just enable the instant preview feature globally*:
```yml
# Configuration for webpage theme
theme:
  # Features to Include (ref. theme documentation)
  features:
    # Enables instant previews globally, for all internal links
    - navigation.instant.preview
```

### Steps to reproduce

1. Clone our repo: https://github.com/sparkfun/SparkFun_GNSS_mosaic-X5
2. Enable the instant preview feature globally in the `mkdocs.yml` file
    ```yml
    # Configuration for webpage theme
    theme:
      # Features to Include (ref. theme documentation)
      features:
        # Enables instant previews globally, for all internal links
        - navigation.instant.preview
    ```
2. Install the mkdocs-material _v9.5.12_ + insiders _v4.53.0_
3. Install the required plugins (or disable them in the `mkdocs.yml` file)
    ```bash
    sudo apt-get install pngquant
    pip install mkdocs-monorepo-plugin mkdocs-redirects mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 Pillow 'mkdocs-material[imaging]'
    ```
4. Serve the site locally
    ```bash
    mkdocs serve
    ```
5. Navigate to a section, where the `PPS Output` section is linked and hover over it
    - For example: http://127.0.0.1:8000/SparkFun_GNSS_mosaic-X5/hardware_overview/#status-leds
        ![image](https://github.com/squidfunk/mkdocs-material/assets/36016723/c5b2d43d-b121-4026-be4e-81c3d2bc7cc8)
    - It should produce a preview of this part of the documentation: http://127.0.0.1:8000/SparkFun_GNSS_mosaic-X5/hardware_overview/#pps-output
        ![image](https://github.com/squidfunk/mkdocs-material/assets/36016723/7808d1d9-6592-409b-8293-dfd567ea0922)

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-03-06 01:46
Thanks for reporting. When creating a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), you should not pack up your site but create a new project with the smallest possible content that showcases the problem. It is absolutely mandatory to provide a minimal reproduction, so we can investigate. We cannot work on a site with hundreds or thousands of pages – it just takes too long.

**Comment by squidfunk** [comment] 2024-03-06 02:50
> I'll work on processing my commits to the project, so I can submit a reproduction later this week

We'll reopen this issue when we receive a proper reproduction. Without a reproduction, it is unclear whether the problem is within our code base or hides within your customizations. As can be seen from the screenshots, your site seems to customize Material for MkDocs quite heavily. [Closing as incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues-and-duplicates).

**Comment by santaimpersonator** [comment] 2024-03-08 20:42
### Reproduction

[9.5.13+insiders.4.53.1-tabs.zip](https://github.com/squidfunk/mkdocs-material/files/14542972/9.5.13%2Binsiders.4.53.1-tabs.zip)

### Steps to reproduce

1. Install the mkdocs-material _v9.5.12_ + insiders _v4.53.0_
2. Serve the site locally
    ```bash
    mkdocs serve
    ```
3. Navigate to a section, where the `PPS Output` section is linked and hover over it
    - For example: http://127.0.0.1:8000/SparkFun_GNSS_mosaic-X5/hardware_overview/#status-leds
        ![image](https://github.com/squidfunk/mkdocs-material/assets/36016723/c5b2d43d-b121-4026-be4e-81c3d2bc7cc8)
    - It should preduce a preview of this part of the documentation: http://127.0.0.1:8000/SparkFun_GNSS_mosaic-X5/hardware_overview/#pps-output
        ![image](https://github.com/squidfunk/mkdocs-material/assets/36016723/7808d1d9-6592-409b-8293-dfd567ea0922)


### Browser

Chrome
DuckDuckGo

**Comment by squidfunk** [comment] 2024-03-09 01:28
Thanks for the reproduction. It's still 17 MB due to the images, but I will check if we can work with it.

**Comment by santaimpersonator** [comment] 2024-03-09 01:58
Here is a basic doc with just the **tabbed content** and **instant preview** features:

[9.5.13+insiders.4.53.1-really-basic.zip](https://github.com/squidfunk/mkdocs-material/files/14544579/9.5.13%2Binsiders.4.53.1-really-basic.zip)

## Issue
When you hover over the link... you only see the tab title and not of the content:
![image](https://github.com/squidfunk/mkdocs-material/assets/36016723/8d2a323b-c5f6-4560-abf3-936907113aed)

**Comment by squidfunk** [comment] 2024-03-09 04:25
Thanks! I'll look into it ☺️

**Comment by squidfunk** [comment] 2024-03-09 07:27
Thanks again for reporting and providing the excellent reproduction. Contrary to the title of the reproduction that might have assumed this is a really basic issue, I'm afraid it isn't. Linking of instant previews is currently limited to sites and sections within that site. It does not work with linked content tabs because of how the HTML is structured.

Instant previews fetch the site they point to, then search for the anchor [which currently must point to a headline](https://github.com/squidfunk/mkdocs-material-insiders/blob/29ef2d2bbb447f280a9d8b40c8ac8cdc1f24eb30/src/templates/assets/javascripts/components/content/link/index.ts#L77-L99), and extract all content until the next headline. The structure (schematic) is:

```
Headline#id-1
Content for Headline#id-1

Headline#id-2
Content for Headline#id-2

...
```

It currently does not work with generic anchors, and it will likely never work with tabs, because of the kind of "odd" HTML structure to make tabs work without JavaScript. The structure for content tabs is:

```
Tabs
  TabControl#id-1
  TabControl#id-2
  ...
  TabLabels
    TabLabel for TabControl#id-1
    TabLabel for TabControl#id-2
    ...
  TabContent
    TabContent for TabControl#id-1
    TabContent for TabControl#id-2
    ...
```

This means that we would need to somehow add very specific logic to support referencing of the content associated with a tab to instant previews, which is (currently) too much of an ask. We're still iterating on the basic mechanics and need to keep the scope limited, first fixing all issues we encounter with the current basic functionality, which we then can evaluate to extend later on. Material for MkDocs is used by thousands of users, and everybody uses it a little differently, so we always try to start with a sharp focus and slowly expand once incoming bugs start to cease.

Thus, it's currently not planned, but we will re-evaluate once we consider instant previews stable ☺️ I've adjusted the documentation to better reflect those limitations in fdeafbb87.

**Closed by squidfunk** 2024-03-09 07:27 UTC
Labels: needs investigation
