### ISSUE TITLE
Compatible with mkdocs 0.17.0?

### ISSUE THREAD

**Issue by nodesocket** [squidfunk/mkdocs-material#536] opened 2017-10-24 19:29 UTC
It seems the latest version of `mkdocs` broke material. I am now getting:

```
iMac ➜  :(master) ✗ mkdocs serve
INFO    -  Building documentation...
ERROR   -  Config value: 'theme'. Error: Unrecognised theme name: 'material'. The available installed themes are: readthedocs, mkdocs

Aborted with 1 Configuration Errors!
```

Running: `mkdocs, version 0.17.0`

**Comment by facelessuser** [comment] 2017-10-24 19:32
The latest version of Material is locked to 0.16.3.  So if you update mkdocs after installing the latest Material, it will break things.  Downgrade mkdocs to 0.16.3 to continue using Material.  Material will release a new version when it properly supports the recent mkdocs changes.

**Comment by nodesocket** [comment] 2017-10-24 19:35
OK. Any idea how far off the new release of Material is?

**Comment by facelessuser** [comment] 2017-10-24 19:45
I know that it probably won't be until another release from mkdocs.  Search is busted and they are trying to make it easier for themes like Material to functioning.  I imagine they are looking to release a new mkdocs version soonish.  After that, only @squidfunk could tell you when Material will have a compatible release.

**Comment by squidfunk** [comment] 2017-10-24 19:51
mkdocs 0.17.1 should be out shortly. Then I can make a compatibility release.

**Comment by squidfunk** [comment] 2017-10-24 19:53
Closing as duplicate of #513

**Closed by squidfunk** 2017-10-24 19:53 UTC
