### ISSUE TITLE
Breadcrumbs for Search

### ISSUE THREAD

**Issue by stollero** [squidfunk/mkdocs-material#7392] opened 2024-07-24 07:22 UTC
### Context

Having larger documentation, the chances are high that titles are not unique.

### Description

Having breadcrumbs for the search instead of just the title will help to provide the context needed to find the right search result faster.

Having prototyped it may only be a smaller change in `SearchIndex.create_entry_for_section`, which I could implement.

```
        if page.ancestors:
            chapters = [i.title for i in page.ancestors]
            chapters.reverse()
            title = " → ".join(chapters + [title])
```

We could also add a search setting to enable or disable this behaviour.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://github.com/squidfunk/mkdocs-material/issues/6307

### Use Cases

Provides better overview

### Visuals

![grafik](https://github.com/user-attachments/assets/11f76dbc-2ee5-4e5e-80fb-1ca0ceb354aa)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment] 2024-07-24 07:40
Thanks for suggesting! This is an exact duplicate of #3787. We've already solved this as part of #6307, but we're working on another big topics which must predate the release of search. There will be an announcement later this year, so stay tuned ☺️

**Closed by squidfunk** 2024-07-24 07:40 UTC
