### ISSUE TITLE
[aria-*] attributes do not match their roles

### ISSUE THREAD

**Issue by m4g3s** [squidfunk/mkdocs-material#4910] opened 2023-01-24 08:36 UTC
### Bug description

Seems to be an issue with [aria-*] attributes not matching their roles. I found this bug when running Chrome's Lighthouse feature. 

<img width="692" alt="Screenshot 2023-01-24 at 3 10 11 AM" src="https://user-images.githubusercontent.com/105753540/214241314-93bfccae-6119-41e2-8793-964e32f6268f.png">

Seems to be an issue with the nav

Was able to reproduce this error on a reproduction after adding the following to mkdocs.yml

```
nav:
  - 'Home':
    - 'index.md'
    - 'Test':
      - 'Testing': 'testing.md'
```

Also will mention i'm using the latest version of insiders 4.29.0

### Related links

- [Bug reporting](https://squidfunk.github.io/mkdocs-material/bug-report/)
- I looked though the documentation but couldn't find anything too relevant to link here

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10487675/example.zip)

### Steps to reproduce

1. go to [https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/)
2. Open developer tools
3. Run Lighthouse
4. Check under Accessibility

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment] 2023-01-28 11:07
Thanks for reporting and providing the reproduction! The problem is related to. `aria-expanded` being set on the `label` element, which doesn't match it's role, and was introduced in https://github.com/squidfunk/mkdocs-material/commit/f8f44f58376206903e925d0b3db1e6e5f89e94ca to solve #4804. I check how we can improve the situation.

**Comment by squidfunk** [comment] 2023-01-28 11:57
Okay, I believe I found a better solution in 148c9fdba, at least Lighthouse stopped complaining. Prior to this change, the `label` element hosted the `aria-expanded` attribute, which is semantically not correct, since the `label` itself cannot be expanded. However, the `label` triggers the expansion of the subsequent `nav` element, which is why I've linked the `nav` element to the `label` using `aria-labelledby`, and set the `aria-expanded` attribute on this element.

This fixes the issue described. I've also fixed an issue where the `aria-expanded` state was only triggered when hitting <kbd>Enter</kbd> when the`label` is focused, not when clicking. Now, the attribute is also updated when clicking on the `label`.

**Comment by squidfunk** [comment] 2023-01-28 14:04
Released as part of [9.0.7](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.7)

**Closed by squidfunk** 2023-01-28 14:04 UTC
Labels: bug, resolved

**Comment by IliyaBrook** [comment] 2025-03-23 23:54
I don't know why the <li> tag needs the aria-level attribute, but when we remove it, the check passes successfully, and I haven't found any issues after its removal.  
I'm removing it in the following way:

useEffect(() => {
		const observer = new MutationObserver((mutations: MutationRecord[]) => {
			mutations.forEach(mutation => {
				if (mutation.type === 'attributes' && mutation.attributeName) {
					const attr = mutation.attributeName;
					if (['aria-level'].includes(attr)) {
						(mutation.target as Element).removeAttribute(attr);
					}
				}

				if (mutation.type === 'childList') {
					if (mutation.target instanceof Element) {
						mutation.target.querySelectorAll('[aria-level]').forEach(el =>
							el.removeAttribute('aria-level')
						);
					}
				}
			});
		});

		if (navBarRef.current) {
			observer.observe(navBarRef.current, {
				childList: true,
				subtree: true,
				attributes: true,
				attributeFilter: ['aria-level', 'aria-setsize', 'aria-posinset']
			});
		}
		return () => observer.disconnect();
	}, [])

**Comment by IliyaBrook** [comment] 2025-03-23 23:56
Я не понимаю, почему тегу `<li>` требуется атрибут `aria-level`, но когда мы его удаляем, проверка проходит успешно, и я не обнаружил никаких проблем после его удаления.

Я удаляю его следующим образом:

```javascript
useEffect(() => {
  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      if (mutation.type === 'attributes' && mutation.attributeName) {
        const attr = mutation.attributeName;
        if (['aria-level'].includes(attr)) {
          mutation.target.removeAttribute(attr);
        }
      }

      if (mutation.type === 'childList') {
        if (mutation.target instanceof Element) {
          mutation.target.querySelectorAll('[aria-level]').forEach((el) =>
            el.removeAttribute('aria-level')
          );
        }
      }
    });
  });

  if (navBarRef.current) {
    observer.observe(navBarRef.current, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['aria-level', 'aria-setsize', 'aria-posinset'],
    });
  }
  return () => observer.disconnect();
}, []);

**Comment by IliyaBrook** [comment] 2025-03-23 23:57
I don't know why the <li> tag needs the aria-level attribute, but when we remove it, the check passes successfully, and I haven't found any issues after its removal.  
I'm removing it in the following way:

```javascript
useEffect(() => {
  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      if (mutation.type === 'attributes' && mutation.attributeName) {
        const attr = mutation.attributeName;
        if (['aria-level'].includes(attr)) {
          mutation.target.removeAttribute(attr);
        }
      }

      if (mutation.type === 'childList') {
        if (mutation.target instanceof Element) {
          mutation.target.querySelectorAll('[aria-level]').forEach((el) =>
            el.removeAttribute('aria-level')
          );
        }
      }
    });
  });

  if (navBarRef.current) {
    observer.observe(navBarRef.current, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['aria-level', 'aria-setsize', 'aria-posinset'],
    });
  }
  return () => observer.disconnect();
}, []);
