### ISSUE TITLE
"Sidebars automatically scroll to active item" feature not working in Firefox 97

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#3624] opened 2022-02-25 16:49 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

In Firefox 97, the "Sidebars automatically scroll to active item" feature (see [here](https://github.com/squidfunk/mkdocs-material/issues/2155#issuecomment-1030816004)) isn't working anymore.

### Expected behaviour

When using Firefox 97 and the latest version of Insiders, the navigation should be scrolled into view as described [here](https://github.com/squidfunk/mkdocs-material/issues/2155#issuecomment-1030816004).

### Actual behaviour

Navigation does not scroll into view in Firefox 97. No console errors.

### Steps to reproduce

See description.

### Package versions

- Python: 3.9.10
- MkDocs: 1.2.3
- Material: 8.2.1+insiders.4.9.1

### Configuration

```yaml
N/A
```

### System information

- Operating system: ...
- Browser: ...

**Comment by squidfunk** [comment] 2022-02-26 08:49
I'm not able reproduce this with the latest Firefox. Oddly enough I was when you reached out to me yesterday, but today I'm not seeing this issue anymore. Are you still able to reproduce? This video shows that both sidebars are correctly positioned:

https://user-images.githubusercontent.com/932156/155836779-3e807e4a-2b91-4bb1-bc03-b4a48643e246.mp4

**Comment by wilhelmer** [comment] 2022-02-28 13:29
When I open https://docs.baslerweb.com/line-pitch on Firefox, the sidebar doesn't scroll and "Line Pitch" isn't visible in the navigation.

When I open the same URL in Chrome, scrolling works properly.

Can you reproduce that?

Our docs were last built with Insiders 4.7.0, but I'm seeing the same behaviour on staging with 4.10.0.

**Comment by squidfunk** [comment] 2022-02-28 14:32
Hmm, yes I'm seeing the same behavior on your website, but I'm still not able to reproduce it on the official docs – just checked again. My next thought was that maybe it's triggered by the sidebar having much more entries, but I'm also not able to reproduce it for the changelog which is very long, as can be seen in the video I posted in my last comment.

You have several customizations in place, could you try to remove them and see if the issue persists with a mint installation?

**Comment by wilhelmer** [comment] 2022-02-28 14:59
I removed all of the customizations and the issue persisted. I was finally able to track it down, it's related to the size of the nav object. If `nav` has too many entries, scrolling no longer works. The threshold for my project is around 200 entries. 

I tried to create a dummy project but couldn't reproduce the error, maybe you need >200 different topics? I don't know. I'll keep trying ...

**Comment by squidfunk** [comment] 2022-02-28 15:03
Hmm, super weird. Thanks for your efforts. It's likely an easy fix as soon as you can reproduce it on a mint project.

**Comment by wilhelmer** [comment] 2022-02-28 15:15
Woo, I got it. 

Download, unzip, build, open one of the last topics, e.g., index copy 170.html.

[strange-nav-bug.zip](https://github.com/squidfunk/mkdocs-material/files/8154381/strange-nav-bug.zip)

**Comment by squidfunk** [comment] 2022-02-28 15:41
Jup, confirmed. Thanks for taking the time to create a reproduction!

**Comment by wilhelmer** [comment] 2022-02-28 17:18
Success! I can confirm scrolling works as advertised with the fix.

**Comment by squidfunk** [comment] 2022-03-02 13:57
Released as part of 8.2.4+insiders-4.10.1

**Closed by squidfunk** 2022-03-02 13:57 UTC
Labels: bug, fix available
