### ISSUE TITLE
Usage help - adding files without listing in pages

### ISSUE THREAD

**Issue by mdd41** [squidfunk/mkdocs-material#385] opened 2017-06-28 06:30 UTC
## Description

This is not a bug, rather usage help. There are several situations where we want to add new markdown files without the need to add those to the nav bar. There is an open [Mkdocs issue](https://github.com/mkdocs/mkdocs/issues/699) along the same lines, however, there appears not a clean direct way to do this.

Question to the mkdocs-material community is - is this a requirement anyone has run into? what are the possible options here? Or is the only option is to use one of the workaround given in     mkdocs/mkdocs#699?

### Expected behavior

Will be great to add files without adding those to mkdocs.yml pages section and display in the nav bar.

### Actual behavior

N/A

### Steps to reproduce the bug

N/A

### Package versions

N/A

### Project configuration
N/A

### System information

* OS: CentOS 7
* Browser: Chrome

**Comment by squidfunk** [comment] 2017-06-28 13:35
I think there is no other way around this at the moment, I'm sorry.

**Comment by mdd41** [comment] 2017-07-06 02:10
No real solution I can see until the upstream MkDocs project supports this. 

I would think this is a common situation though - curious to know what the community has to say.

**Comment by squidfunk** [comment] 2017-07-15 16:50
Closing this, as this is an issue with MkDocs, not with Material. If you want to start a discussion, please open an issue on their issue tracker.

**Closed by squidfunk** 2017-07-15 16:50 UTC
Labels: discussion

**Comment by nathancarter** [comment] 2017-11-13 18:06
Actually, it is a material issue, not a MkDocs issue.  The reason is that, as you can see from [this diff file](https://github.com/bloerg/aspectui-documentation/commit/6d643f34dc30ff1d79a98a21f1e30463a2b4981e), there is a trivial solution to the problem that can be implemented in any `base.html` file.  So the request here would be to add that trivial solution to the `base.html` file in the material theme.

**Comment by nathancarter** [comment] 2017-11-13 18:09
Actually, since the material theme is more complicated, perhaps the solution would go here?

https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/nav.html#L49

**Comment by defji** [comment] 2018-07-25 08:20
Just simple add pages like this: 

pages: 
  - home: home.md
  - "": other_not_listed_page.md

**Comment by matchavez** [comment] 2021-01-11 20:45
Martin, this should be in the documentation. A simple two-double-quotes, and the page isn't in the navigation. That's powerful! I've spent too much time looking for this answer, and really, it's a "feature" if you will. 

@defji Bravissimo!

**Comment by squidfunk** [comment] 2021-01-12 16:22
Hmm, sounds like a hack to me that might easily break in a future version of MkDocs. @waylan - is that intended behavior?

**Comment by waylan** [comment] 2021-01-12 19:33
This is a 3 year old issue which links to a 5 year old issue. We closed the MkDocs issue with mkdocs/mkdocs#1504 back in 2018. Hidden pages are a fully supported thing now as [documented][1] .  As the last paragraph of the that section states:

> Any pages not listed in your navigation configuration will still be rendered and included with the built site, however, they will not be linked from the global navigation and will not be included in the `previous` and `next` links. Such pages will be "hidden" unless linked to directly.

No hacks needed. Simply exclude the files from the `nav` setting.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation

**Comment by matchavez** [comment] 2021-01-12 20:31
Sorry about that. Issue mkdocs/mkdocs#699 is not clear, and that's the one that always comes up in search. Hopefully that helps out. I'll reference it. Cheers.

**Comment by waylan** [comment] 2021-01-12 20:49
It is very clear. If you find were is was "closed" you will see a link to the commit which included the change. And the previous line links to the PR. Well, it is clear if you are familiar with how GitHub works and know that merging a PR automatically closes any issues that the PR is linked to. I suppose it may not be clear if you don't know that. Hey, but now you do.

**Comment by matchavez** [comment] 2021-01-12 20:59
You're right. I didn't follow through on the link that said "Pages Refactor". Well, I suppose it wasn't the most clear description if you didn't know that. Hey, but now you do.

**Comment by squidfunk** [comment] 2021-01-12 21:14
Thank you @waylan for the explanation. However, MkDocs will always complain when building or serving that there are unreferenced pages in the nav which feels like the user made a mistake, which is why I didn't feel this to be “the” solution for hiding pages.

**Comment by waylan** [comment] 2021-01-12 21:22
@squidfunk that is the subject of mkdocs/mkdocs#1888. As pointed out there, it is not a "warning" but an "info" message, which means it is not suggesting that you did nothing wrong. However, I can see how some might misunderstand it that way.

**Comment by squidfunk** [comment] 2021-01-13 09:03
@waylan ah yes, thanks! That's the one. With the quotation marks, I meant whether it is the official solution, because of the printed warning message. Personally, I don't care about the info message, but I've encountered some users that do.
