### ISSUE TITLE
Browser compatibility 

### ISSUE THREAD

**Issue by bradumbaugh** [squidfunk/mkdocs-material#3437] opened 2022-01-06 17:51 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi @squidfunk, I've been testing out Material for MkDocs on some older browsers, thought I would capture some issues I'm seeing here. Will probably add to this a bit over time, if that's OK.

### 1. Icon sizing
Browser: Chrome 84 on macOS Monterey (but I've seen this on other older browsers, too)

Icons are sized very large. A few screenshots from the current theme documentation, as published:

![Screen Shot 2022-01-05 at 8 57 57 PM](https://user-images.githubusercontent.com/6285/148425030-23aab725-20ec-44b1-b5f2-64116c9e0dbd.png)

![Screen Shot 2022-01-05 at 9 00 20 PM](https://user-images.githubusercontent.com/6285/148424957-638dedb7-f5cc-46d0-946c-dc702ac46355.png)

![Screen Shot 2022-01-05 at 8 59 53 PM](https://user-images.githubusercontent.com/6285/148424964-7e21b7b4-ccdb-480f-b56d-495a1b7e4d3d.png)

![Screen Shot 2022-01-05 at 9 00 33 PM](https://user-images.githubusercontent.com/6285/148424947-d5c69fd4-ce15-4ae5-8c3f-b60a11358695.png)

### 2. Admonition styling
Browser: Chrome 84 on macOS Monterey

Admonition styling isn't showing up as expected (looks like plain text)

![Screen Shot 2022-01-05 at 9 01 12 PM](https://user-images.githubusercontent.com/6285/148425570-e5d91abd-610a-46f4-a449-4e380d19f020.png)

![Screen Shot 2022-01-06 at 10 35 22 AM](https://user-images.githubusercontent.com/6285/148425854-094b12c3-134c-49ef-99f6-07e5a65e6e5a.png)

### 3. Header sizing
Browser: Firefox 66 on Windows 11

Project icon shows up large. Header dominates the screen until I click in the search field, at which point it resizes down some, but not fully.

Before clicking in search field:

![Screen Shot 2022-01-06 at 10 38 02 AM](https://user-images.githubusercontent.com/6285/148426538-8c8203f4-f0f5-46cd-9ade-db21292ae0f2.png)

After clicking in search field:

![Screen Shot 2022-01-06 at 10 45 40 AM](https://user-images.githubusercontent.com/6285/148427164-44737fdb-7477-42ea-afdd-b33310b943a3.png)

### 4. Search doesn't initialize
Browser: Tested on Firefox 66 on Windows 11

When clicking in the search field, it never in initializes. Any time I type a character while the search field is in focus, it opens an entire new browser window (doesn't enter the text).

![Screen Shot 2022-01-06 at 10 38 14 AM](https://user-images.githubusercontent.com/6285/148426672-bf68227d-98c0-405a-9c7a-ac1497cf8fa8.png)

### Expected behaviour

(as described in the issue)

### Actual behaviour

(as described in issue)

### Steps to reproduce

(as described in issue)

### Package versions

Observed these issues on the current published, site for Material for MkDocs — looks like v8.1.4

### Configuration

```yaml
As published on the site
```

### System information

Various browsers, operating systems

**Comment by squidfunk** [comment] 2022-01-06 19:13
Thanks for reporting. I've started work on improving compatibility in #3441, adding back polyfills as we discover issues. The SVG issue you reported is fixed. It was related to missing support for `:is`, which I just pathed with a small self-written PostCSS plugin.

I've tested FIrefox 57 and it's almost working.

Anything else you discovered?

**Comment by bradumbaugh** [comment] 2022-01-06 20:30
I'm really impressed, @squidfunk. Thank you for looking at this so quickly. 

I saw one other thing where links were always opening in new tabs, and similarly where typing was causing new tabs to open. But I don't remember what browser I was looking at, so I'll try to figure that out and report back.

**Comment by squidfunk** [comment] 2022-01-06 20:33
Perfect. The last commit also fixes search on older versions of Safari and `details` elements now not render a marker (selector was invalid due to `::marker` not being supported).

**Comment by squidfunk** [comment] 2022-01-06 20:41
@alkisg you also had several problems with browser compatibility. Could you check #3441? It might resolve many of them. Also Firefox 57 ESR should now work pretty good.

**Comment by alkisg** [comment] 2022-01-06 21:49
A quick test on Ubuntu 12.04, I'll do more tomorrow.
I visited https://squidfunk.github.io/mkdocs-material/getting-started.

In Firefox 52, the header fills about 200% of the screen height, e.g. the twitter bird icon is around 1500x1000 pixels. If I scroll past the huge bird and the banner, the content seems to be usable (but it only has 100 pixel available height). In the console, I see:

```
ReferenceError: ResizeObserver is not defined
TypeError: e.split(...).map(...).join(...).replace(...).split(...).flatMap is not a function
```

The situation is similar in Chromium 37, but I think that one is older, not worth the trouble at all. Its console errors were:

```
Uncaught SyntaxError: Unexpected token >
Uncaught SyntaxError: Unexpected identifier
Uncaught SyntaxError: Unexpected token |
Uncaught SyntaxError: __md_hash is not defined
Uncaught SyntaxError: Unexpected token )
Uncaught SyntaxError: Unexpected token >)
```

Firefox 52 is available for both Ubuntu 12.04+ and Windows XP+, so if that can browse the site even with very limited functionality, it'd be great.
More tests tomorrow...

**Comment by squidfunk** [comment] 2022-01-06 23:18
Many thanks. It would be amazing if you could check #3441, which should resolve (almost?) all issues you reported.

**Comment by bradumbaugh** [comment] 2022-01-07 04:50
> I saw one other thing where links were always opening in new tabs, and similarly where typing was causing new tabs to open. But I don't remember what browser I was looking at, so I'll try to figure that out and report back.

@squidfunk I can't seem to replicate this—have no idea how I did that. Will try a bit more and let you know if I do find it.

In the meantime, going to try to figure out how to test your changes. Thanks again for this PR!

**Comment by alkisg** [comment] 2022-01-07 06:37
> going to try to figure out how to test your changes

Indeed a "proposed changes" site would help a lot in testing!
E.g. maybe in https://squidfunk.github.io/mkdocs-material-proposed/, with a robots.txt that would prohibit google from indexing it...

**Comment by squidfunk** [comment] 2022-01-07 07:43
You can install the branch with:

```
pip install git+https://github.com/squidfunk/mkdocs-material.git@refactor/compatibility
```

Sorry, no plans to deploy this. It's more work syncing stuff as I would need a separate repository to deploy a separate documentation site on pages. I would be very grateful if you could test it locally.

**Comment by bradumbaugh** [comment] 2022-01-07 15:45
I'll try to put up a simple test site somewhere, either today or this weekend, and post here when I have a link!

**Comment by bradumbaugh** [comment] 2022-01-07 20:25
@squidfunk @alkisg 

OK, I set some things up to make cross-browser testing a little easier:

1. Created this repo, which is just a new MkDocs project configured to use the Material theme: https://github.com/bradumbaugh/material-mkdocs-test-site
2. Configured Netlify to deploy this site, using the `refactor/compatibility` branch of the Material theme: https://angry-wiles-f26cbe.netlify.app
3. To test how some particular kind of docs content renders, or an update to `refactor/compatibility`, open up a PR in the test repo. Any time you commit to the branch associated with the PR, Netify will generate a "deploy preview" and link to it in the thread of the PR. So, in your PR, configure `mkdocs.yml` and the Markdown files however you'd like, and Netlify will build the site and give you a link to view it. For example, see this [sample PR](https://github.com/bradumbaugh/material-mkdocs-test-site/pull/1).

With all that set up, I'll do bit more cross-browser testing with BrowserStack this weekend.

**Comment by alkisg** [comment] 2022-01-08 11:27
Wow, brilliant! Thank you both!

Ubuntu 12.04, Firefox 52 => everything shows up fine, there aren't even any warnings or errors in the console!
In the ancient chrome the site shows much better than before, but it has javascript errors, but we don't care about them.

Firefox 52 is enough for all our sites that have users with ancient operating systems! Finally we can move from material-mkdocs 4 to 8! I'll report if something is wrong in bigger sites that use more stuff than the minimal site that bradumbaugh uploaded.
Thanks again!

**Comment by squidfunk** [comment] 2022-01-08 11:56
> In the ancient chrome the site shows much better than before, but it has javascript errors, but we don't care about them.

Could you please provide more details?

**Comment by alkisg** [comment] 2022-01-08 12:07
Sure, here's the related screenshot:
![VirtualBox_precise-lyk_08_01_2022_14_06_01](https://user-images.githubusercontent.com/88025/148643554-c9a75c10-430f-4b06-bc95-0e74ceffeab7.png)

I'll test with the latest Google Chrome for XP later on in the afternoon, that will be more important than the old chromium-browser of Ubuntu 12.04.

**Comment by squidfunk** [comment] 2022-01-08 12:14
Which version of Chrome is this? Chrome 69 is probably the earliest to work, as it's the first to support [CSS variables](https://caniuse.com/?search=css%20variables).

**Comment by alkisg** [comment] 2022-01-08 12:38
That was Chromium 37.

I also tried on Windows XP with Google Chrome 49 (the latest available there), but it says ERR_CONNECTION_CLOSED on netlify, I'll need to test elsewhere later.

Firefox 52 on Windows XP again works fine. It serves as a great baseline browser in all platforms. It's enough for all my use cases.

**Comment by squidfunk** [comment] 2022-01-08 13:21
Okay. We'll not get past Chrome/Chromium 69 for the same reasons we won't support IE anymore: CSS variables. There are PostCSS plugins that allow us to transpile CSS variables to declarations, but that has some caveats which would severely limit our use of them. Thus, it's not worth it.

The Netlify error you're seeing is likely related to SSL/TLS support.

**Comment by alkisg** [comment] 2022-01-08 14:06
I build ltsp.org locally and I was able to quickly test with the proposed mkdocs-material version.

First, Google Chrome 49 (which does support CSS variables) on Windows XP, shows up fine, but has the following problem when clicking on a nav link:

![VirtualBox_XPEl_08_01_2022_16_04_18](https://user-images.githubusercontent.com/88025/148647172-bf180d1b-c82e-44cb-b85e-d8508330c65a.png)

**Comment by alkisg** [comment] 2022-01-08 14:15
Second, Firefox 52 on Windows XP works fine with or without navigation.instant. The only problem I could find was the badly drawn "extend submenu" icon. Firefox 52 on Ubuntu 12.04 didn't have that issue. Google Chrome on XP didn't have that issue.

![VirtualBox_XPEl_08_01_2022_16_14_07](https://user-images.githubusercontent.com/88025/148647479-363bafca-b449-42df-8c91-8b55d0478f0a.png)

**Comment by alkisg** [comment] 2022-01-08 14:24
Third, Chromium 37 on Ubuntu 12.04 almost works when navigation.instant is disabled. The problem with the nav icon happens there too, and the switch from light to dark mode doesn't work.
We don't care about that browser, I just mention it for completeness.

![VirtualBox_precise-lyk_08_01_2022_16_22_55](https://user-images.githubusercontent.com/88025/148647778-a25600cd-32d8-4e10-89f5-8fff976c08ed.png)

**Comment by alkisg** [comment] 2022-01-08 14:26
Finally, Firefox 52 on Ubuntu 12.04 has only the problem with the nav icon, no other problems, with or without navigation.instant.

![VirtualBox_precise-lyk_08_01_2022_16_25_55](https://user-images.githubusercontent.com/88025/148647846-6888a0f3-3d5c-4463-ae5f-207b077ebfb5.png)

**Comment by squidfunk** [comment] 2022-01-08 14:31
Thanks for testing all those. The navigation icon issue is related to [missing support for `mask-image`](https://caniuse.com/mdn-css_properties_mask-image). Sadly, it's not polyfillable, but maybe we can provide some fallback based on `background-image`. I'm yet unsure if I want to go through the troubles of maintaining this.

**Comment by alkisg** [comment] 2022-01-08 14:35
Thank you for looking into this.
Indeed the admonition icons are also affected.

Is there anything that can be done from our side, e.g. some local CSS that we could use?
Even if it won't be maintained long-term, switching from mkdocs-material 4.x to 8.x will be a big step up!

**Comment by squidfunk** [comment] 2022-01-08 14:36
Yes. I'm glad it works for you now. Thanks for testing it. I'll look into it asap.

**Comment by alkisg** [comment] 2022-01-09 06:47
I switched https://ltsp.org to use this proposed branch, to make it easier for anyone that wants to test other browsers for compatibility issues.

**Comment by fottsia** [comment] 2022-01-09 09:26
- Ubuntu 18.04, Firefox 95: OK
- Ubuntu 18.04, Chromium 95: OK (no dependency warning)

**Comment by squidfunk** [comment] 2022-01-09 10:11
Thanks for testing again. I will see if we can fix the remaining issues and merge the branch into `master` and Insiders `master` (used to build the official docs) today.

**Comment by squidfunk** [comment] 2022-01-09 10:47
Regarding the `mask-image` issues: I don't think we can fix those. We're using `mask-image` when we need to inject SVGs for icons from CSS for repeated components, e.g. navigation expander or copy-to-clipboard button, or for specimen for which we can't influence the resulting HTML (admonitions). We can't use `background-image`, because we cannot control the `fill` color of the SVG files then, which is necessary for icons to work with light and dark mode. Our options:

1. Use `background-image` and live with the fact that you will not see the icons in dark mode. Also, admonition icons etc. would not be colored - icons would be all black at all times
2. Inline SVGs into the source were possible, which will blow up the size of the resulting HTML, and won't solve the admonition issues.
3. Hide all icons.

None of those options sounds good to me.

**Comment by squidfunk** [comment] 2022-01-09 10:57
The range of supported browsers should now be:

- Firefox: __53+__ (latest is __97__)
- Chrome: __49+__ (latest is __100__)
- Safari: 10+ (iOS and macOS, latest is __15.2__)
- Opera: 36+ (latest is __82__)
- Edge: 79+ (latest is __97__)

**Comment by squidfunk** [comment] 2022-01-09 12:05
So, it turns out that `-webkit-any()` (and probably `:-moz-any()`) have a specificity different from `:is()`. I'm trying to fix all issues that I discover, but we will probably have some regressions after releasing the latest changes.

**Comment by squidfunk** [comment] 2022-01-09 14:03
All changes were released as part of 8.1.5 and 8.1.5-insiders-4.5.2. I invested the time in a new page on [browser support](https://squidfunk.github.io/mkdocs-material/browser-support/) which should answer almost all questions when choosing Material for MkDocs, explains because of which missing features older browsers are not supported, and gives some directions on how to add support if necessary.

<img width="634" alt="Bildschirmfoto 2022-01-09 um 15 02 54" src="https://user-images.githubusercontent.com/932156/148685515-bad7c663-8953-458e-905d-eae7dfd235d1.png">

**Closed by squidfunk** 2022-01-09 14:03 UTC
Labels: enhancement, fix available

**Comment by alkisg** [comment] 2022-01-09 19:00
Thank you very much for all your work!

I managed to set the nav-icon color with the following CSS. This is hacky and definitely **not** for upstream, I'm just noting it here in case someone needs Firefox 35+ compatibility:

```css
.md-nav__icon::after {
  background-color: initial;
  background-image: var(--md-nav-icon--next);
  mask-image: none;
}

[data-md-color-scheme="default"] .md-nav__icon::after {
  filter: invert(100%) brightness(0.5) sepia(1) hue-rotate(140deg) saturate(5);
}

[data-md-color-scheme="slate"] .md-nav__icon::after {
  filter: invert(100%) brightness(0.5) sepia(1) hue-rotate(-40deg) saturate(5);
}
```

**Comment by squidfunk** [comment] 2023-11-22 15:28
👋 I'm currently revisiting the browser support version range topic – two years after we improved browser support in this issue, we will need to up the range of supported browsers again in order to move this project forward in a meaningful way. The absolute minimum we will need to go for is to get support for `script[type=module]`, since ESM is here to stay, and [browser support is at 97% already](https://caniuse.com/es6-module). This would, however, mean, that we will discontinue to support some very old browsers, including Firefox 53, which was part of the discussion here. I'd be interested to learn whether this use case still exists.

We will try to raise the bar as minimal as possible, but in order to keep this project fresh, progress has to happen. After all, the world is moving forward, and we can't support ancient browsers forever. In case you need to keep support for ancient browsers, there's always the possibility to switch to an older version of Material for MkDocs, as for example 4.6.3 to support Internet Explorer. I hope for your understanding and I'm happy to learn about your use cases and experiences.

**Comment by squidfunk** [comment] 2023-11-22 19:32
Awesome, thanks for sharing those insights very valuable!

**Comment by squidfunk** [comment] 2023-12-06 08:56
If you can provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), please create a new issue, and we're happy to look into it.

Please see our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
