### ISSUE TITLE
Instant Previews disable content tabs

### ISSUE THREAD

**Issue by lampensau** [squidfunk/mkdocs-material#7408] opened 2024-08-01 08:56 UTC
### Bug description

Using the instant preview feature on a document heading that includes a content tab will disable the content tabs inside the section after previewing (hovering) the link.

**Initial state:**
![Content tabs are active; content is visible](https://github.com/user-attachments/assets/001704c0-3803-4eee-bb9a-813913424813)

**After hovering the preview link:**
![grafik](https://github.com/user-attachments/assets/a83207b7-4ac9-4c99-bd1a-a5042e930f53)

To view a content tab's content again, the user must click its heading or reload the page, making the content much easier to overlook.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Instant previews](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-previews)
- #6704
- #6875

### Reproduction

[9.5.30+insiders.4.53.11-instant-preview-disables-tabs.zip](https://github.com/user-attachments/files/16452563/9.5.30%2Binsiders.4.53.11-instant-preview-disables-tabs.zip)

> Sidenote: Why does the `mkdocs-material-insiders` repository currently report the `9.5.29` as _latest version_?

### Steps to reproduce

1. Install and enable material insiders theme
2. Enable and [configure](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#configuration) the Markdown extensions `pymdownx.superfences`, and `pymdownx.tabbed` using the `alternate_style`
3. Use the [instant preview feature](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-previews) to a document heading containing one or multiple content tabs. Content tabs only get disabled if the instant preview tooltip includes them.

> Note: I found no real difference between the different options to enable instant previews; the minimal reproduction uses the method relying on the `attr_list` Markdown extension.

### Browser

Chrome, Edge, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-08-01 09:15
Thanks for reporting. Confirmed. I'll look into it.

**Comment by squidfunk** [comment] 2024-08-01 09:42
Fixed in [`1e58ebecc`](https://github.com/squidfunk/mkdocs-material-insiders/commit/1e58ebecc4880e056d30399fe47abb9a72b7c9a2). The problem was that for content tabs on the same page there were elements with the same id, and if the preview comes before those content tabs, it influenced the actual content tabs. Content tabs should now work as expected inside previews. Can you confirm? Please note that this is still an experimental feature.

**Comment by lampensau** [comment] 2024-08-01 09:42
Appreciated!

**Comment by lampensau** [comment] 2024-08-01 10:36
I think I found another (edge-) case?

Using the [anchor link](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#anchor-links) configuration for `pymdownx.tabbed` will still disable the content tabs when using the link preview:

```
markdown_extensions:
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```

**Comment by squidfunk** [comment] 2024-08-01 10:49
Could you please create another issue with a minimal reproduction? You can keep the issue itself brief, just link to this issue for context.

**Closed** 2024-08-02 09:48 UTC
Labels: bug, resolved
