### ISSUE TITLE
Search function not be available when use 'zh' as language and file contains tags

### ISSUE THREAD

**Issue by ShenMian** [squidfunk/mkdocs-material#4236] opened 2022-08-10 17:01 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have not enabled any plugins and markdown_extensions as `Configuration` shows. Only one markdown file contains a tag.  
If there is no problem with my configuration, I guess is a problem with Chinese search and tags(Even if tags plugin and meta markdown extension are not enabled).  

### Expected behaviour

![image](https://user-images.githubusercontent.com/70068015/183975061-789be107-4beb-4c0a-b2ff-8b6f64012761.png)  

`没有找到符合条件的结果` means `No matching results were found`.  

The search function and tag can be used normally.

### Actual behaviour

![image](https://user-images.githubusercontent.com/70068015/183973215-37c6aef8-a57b-4f12-b242-c077ae8ef938.png)  

`正在初始化搜索引擎` means `Initializing search engine`.  

The search function will not be available and displaying `正在初始化搜索引擎`, but initialization never seems complete.

### Steps to reproduce

Set `theme.language` to `zh` and write tags to any markdown file.
Everything works fine, if:  

- Set `theme.language` to `en`.
- Don't write any tags to any markdown file.

### Package versions

- MkDocs: `1.3.1`
- Material: `8.3.9`

### Configuration

```yaml
theme:
  name: material
  language: zh
```

### System information

- Operating system: Windows/Android
- Browser: Edge

**Comment by squidfunk** [comment] 2022-08-12 08:59
Thanks for reporting. Please provide a minimum reproducible example and attach it here as a zip file.

**Comment by ShenMian** [comment] 2022-08-12 09:45
@squidfunk [test.zip](https://github.com/squidfunk/mkdocs-material/files/9315391/test.zip).

**Comment by squidfunk** [comment] 2022-08-13 07:28
Thanks! Turns out this is a duplicate of #4069. Possible mitigations in https://github.com/squidfunk/mkdocs-material/issues/4069#issuecomment-1172851670.

**Closed by squidfunk** 2022-08-13 07:28 UTC
Labels: input needed
