### ISSUE TITLE
Broken emojis

### ISSUE THREAD

**Issue by StarfallProjects** [squidfunk/mkdocs-material#4853] opened 2023-01-11 16:08 UTC
### Bug description

Emojis are not displaying properly.

![image](https://user-images.githubusercontent.com/10284570/211855920-1914c973-3153-45a5-8c85-007e4c15ddab.png)
(from https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#usage)

![image](https://user-images.githubusercontent.com/10284570/211855962-3601f896-d620-44b7-9818-2d410455d2eb.png)
(from https://docs.n8n.io/code-examples/methods-variables-reference/)

### Related links

- [Bug reporting](https://squidfunk.github.io/mkdocs-material/bug-report/)
- [Emoji docs](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)

### Reproduction

Given it also affects your own docs, and is presumably a general bug, please can I skip this? Let me know if you still want me to.

### Steps to reproduce

Given it also affects your own docs, and is presumably a general bug, please can I skip this? Let me know if you still want me to.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by facelessuser** [comment] 2023-01-11 16:21
This is an upstream issue that I'm aware of. I haven't had a chance to construct a bugfix release for Pymdown Extensions. The short of it is the CDN for the emoji went away and we have to use a different CDN for the emoji.

**Comment by StarfallProjects** [comment] 2023-01-11 16:28
@facelessuser any ETA? Not to hassle, just so I know if I should do the work to remove emojis from our docs, or just live with it for a bit?

**Comment by facelessuser** [comment] 2023-01-11 16:44
I imagine this evening I should get one out. The issue was brought to my attention yesterday. The fix is in, I just need to make time today if possible.

**Comment by StarfallProjects** [comment] 2023-01-11 16:51
Awesome!

**Comment by provTheodoreNewell** [comment] 2023-01-11 18:29
More details on the underlying issue for anyone interested: https://github.com/twitter/twemoji/issues/580

**Comment by facelessuser** [comment] 2023-01-11 18:32
I just [tagged a release with the fix](https://github.com/facelessuser/pymdown-extensions/releases/tag/9.9.1). It should be up on PyPI soon-ish.

**Comment by squidfunk** [comment] 2023-01-12 07:57
Duplicate of #4843.

**Closed by squidfunk** 2023-01-12 07:57 UTC
