### ISSUE TITLE
Feature suggestion: Sort rendered tag index case-insensitively

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#4640] opened 2022-11-15 13:59 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

When using a tags index as described [here](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags#adding-a-tags-index), the tag list gets sorted case-sensitively. 

This means, tags will get sorted from A-Z, and then from a-z, e.g.:

- Installation
- Maintenance
- Software
- macOS

That's not really a bug, it's just how Python's `sorted()` method works by default, which is [used in tags/plugin.py](https://github.com/squidfunk/mkdocs-material/blob/31518177b3bf0edfc719fecb1058385876703cf7/material/plugins/tags/plugin.py#L108).

However, I think in most cases, users want a case-insensitive list:

- Installation
- macOS
- Maintenance
- Software

So I suggest we use [`str.casefold()`](https://docs.python.org/3/library/stdtypes.html#str.casefold) method that's specifically designed for caseless matching:

```python
sorted(unsorted_list, key=str.casefold)
```

### Use Cases

See description.

**Comment by squidfunk** [comment] 2022-11-15 14:33
Duplicate of #4549. Use [`tags_compare`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#+tags.tags_compare):

plugins:
  - tags:
      tags_compare: !!python/name:material.plugins.tags.plugin.casefold

**Closed by squidfunk** 2022-11-15 14:33 UTC
