### ISSUE TITLE
Inconsistent ID of <pre> result in misalignment of element selection by script

### ISSUE THREAD

**Issue by ile-24556** [squidfunk/mkdocs-material#5213] opened 2023-03-18 12:10 UTC
### Description

This is reported by [SPyofgame2](https://github.com/SPyofgame2)  in discussion #5210.

If you click on the "change color scheme" tile, the color scheme will change and the value of the `scheme` in the code block above should also change. Instead, the value in the next code block changes. This also occurs on the tiles in subsequent two sections.

---

The behavior of the IDs of the code block(`<pre>`)s are inconsistent, and it seems to be the cause.
- The IDs start with `__code_0` in the official documentation.
- The IDs start with `__code_1` on the cloned site and other users' sites.

The value-changing scripts on the reported page [expect the latter](https://github.com/squidfunk/mkdocs-material/blob/4ad2dc1e288a0ffe78a8db3a04978a6e089ce35e/docs/setup/changing-the-colors.md?plain=1#L43).
The IDs are added by [code copy button feature].

[code copy button feature]: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button

### Related links

- [Changing the colors - Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/)
  
  ![changing targets are off by one](https://user-images.githubusercontent.com/110268848/226102343-d8f78316-066d-4534-a7b6-4c26b22520aa.png)

### Proposed change

Could you please check [code copy button feature].

[code copy button feature]: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by jeremy-feng** [comment] 2023-03-19 01:21
Sorry I think the link to the issue is not correct. You may consider changing it to https://github.com/squidfunk/mkdocs-material/discussions/5210

**Comment by ile-24556** [comment] 2023-03-19 01:33
Thank you, fixed the link. Sorry for the unrelated mention history in your issue.

**Comment by jeremy-feng** [comment] 2023-03-19 01:35
> Thank you, fixed the link. Sorry for the unrelated mention history in your issue.

No worry!

**Comment by squidfunk** [comment] 2023-03-19 16:31
Thanks for reporting and investigating! Fixed in 5f02d02dc.

**Closed by squidfunk** 2023-03-19 16:31 UTC
Labels: documentation
