### ISSUE TITLE
Building Error with 7.1.0; jinja2.exceptions.UndefinedError: 

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [squidfunk/mkdocs-material#2527] opened 2021-04-05 13:10 UTC
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Experiencing a bizarre error message when building the documentation using the latest version of mkdocs-material (7.1.0) and readthedocs with Linux. Was able to reproduce the bug
```bash
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/mkdocs/__main__.py", line 192, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/mkdocs/commands/build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/mkdocs/commands/build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/mkdocs/commands/build.py", line 87, in _build_template
    output = template.render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/material/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/material/base.html", line 118, in top-level template code
    {% block header %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/material/base.html", line 119, in block "header"
    {% include "partials/header.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/material/partials/header.html", line 36, in top-level template code
    <label class="md-header__button md-icon" title="{{ option.toggle.name }}" for="__palette_{{ loop.index0 or loop.length }}" hidden>
  File "/home/docs/checkouts/readthedocs.org/user_builds/openhivenpy/envs/merge/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'toggle'
```

### Expected behaviour

The documentation should build without any errors

### Actual behaviour

Throws an error that does not indicate an issue with the configuration or the files. 

### Steps to reproduce the bug

1. Use the latest version (7.1.0). Does not appear on 7.0.7 or lower
2. Build docs with the passed configuration
(Docs if needed are open-source: https://github.com/FrostbyteSpace/docs_openhiven.py)

### Package versions

* Python: 3.8/3.9 (Appeared on both)
* MkDocs: 1.1.2
* Material: 7.1.0

### Project configuration

``` yaml
site_name: 'OpenHiven.py Docs'
site_description: 'Documentation Page for OpenHiven.py'
site_author: 'Nicolas Klatzer'
site_url: 'https://openhivenpy.readthedocs.io'
site_dir: './build/'
edit_uri: 'https://github.com/FrostbyteSpace/docs_openhiven.py/edit/main/docs/'

copyright: Copyright &copy; 2020 - 2021 Nicolas-Klatzer

use_directory_urls: false
nav:
  - Home:
      - Home: index.md
      - home/contributing.md
      - home/license.md
      - home/troubleshooting.md
      - home/bug_reporting.md
  - Getting Started:
      - getting_started/index.md
      - getting_started/deploying_your_first_bot.md
      - getting_started/logging.md
      - getting_started/event_handling.md
  - API Reference:
      - api_reference/index.md
      - api_reference/hiven_endpoints.md
      - api_reference/hiven_swarm.md
      - api_reference/object_reference.md
  - Reference:
      - reference/index.md
      - reference/hivenclient.md
      - reference/botclient.md
      - reference/userclient.md
      - reference/http.md
      - reference/execution_loop.md
      - reference/event_handler.md
      - reference/types/index.md
  - Changelog:
      - changelog.md
extra_css:
    - assets/css/index.css

repo_url: https://github.com/FrostbyteSpace/OpenHiven.py
repo_name: FrostbyteSpace/OpenHiven.py

theme:
  name: material
  favicon: ./openhivenpy.ico
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  hljs_languages:
    - yaml
    - python
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
  logo: ./assets/images/openhivenpy.png
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - toc.integrate

plugins:
  - git-revision-date:
      enabled_if_env: CI
  - search:
      lang: en
      prebuild_index: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tilde
  - pymdownx.keys
  - attr_list
  - abbr
  - pymdownx.snippets
  - admonition

extra:
  version:
      method: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thekudofox
      name: The author on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/FrostbyteSpace/
      name: The Github Organisation managing the project
```

### System information

* OS: Linux and Windows (Likely Mac as well)
* Browser: Any

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment] 2021-04-05 13:13
Thanks for reporting. Closing as duplicate of #2511

**Closed by squidfunk** 2021-04-05 13:13 UTC
