### ISSUE TITLE
Instant loading makes print dialog autoclose

### ISSUE THREAD

**Issue by majkinetor** [squidfunk/mkdocs-material#2261] opened 2021-01-31 19:48 UTC
When I add `navigation.instant` theme option CTRL + P dialog closes on any page. The problem is gone when I remove that option.

## To reproduce

1. Go to https://majkinetor.github.io/mm-docs-template/
1. Hit CTRL + P wait 2 seconds
1. Print dialog should close by itself

Sometimes CTRL + P works the first time but just hitting F5 or ctrl + F5 and then doing it again can change the outcome.

- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Package versions

* Python: 3.6
* MkDocs: 1.1.2
* Material: 6.2.6

- All other: https://github.com/majkinetor/mm-docs/blob/master/requirements.txt

### Project configuration

- https://github.com/majkinetor/mm-docs-template/blob/master/source/mkdocs.yml

### System information

- Windows 10 10.0.19042 N/A Build 19042
- Chrome  88.0.4324.104  (sometimes work, mostly doesn't)
- Edge 88.0.705.56 (never works)

**Comment by squidfunk** [comment] 2021-02-01 09:09
Please provide more details - browser, operating system..., basically everything that is listed in the issue template. It does not reproduce in Chrome 88 on macOS.

**Comment by majkinetor** [comment] 2021-02-01 09:58
Sorry for being hasty. Added everything in original post, and animated gif.

**Comment by squidfunk** [comment] 2021-02-02 19:38
So it seems that this only happens when you activate instant loading, load the page and hit CMD+P immediately. As soon as you navigate and instant loading kicks in, the print modal remains open (at least for me). Can you confirm?

**Comment by squidfunk** [comment] 2021-02-02 19:52
Potential fix in e3c608ac. Interestingly it seems to be related to scroll restoration. Could you check the latest `master`?

**Comment by majkinetor** [comment] 2021-02-02 19:57
> So it seems that this only happens when you activate instant loading, load the page and hit CMD+P immediately. As soon as you navigate and instant loading kicks in, the print modal remains open (at least for me). Can you confirm?

No. Any time after I CTRL + P it gets shut down ASAP. If it doesn't happen the first time, I CTRL + F5, then it happens.

> Could you check the latest master?

I can't do it fast but can get you back on that later (I keep all this in container its not that easy to just pip it from github.

**Comment by squidfunk** [comment] 2021-02-02 20:00
No worries. If you can verify before the weekend, that would be awesome, as the fix would be part of the next release.

**Comment by majkinetor** [comment] 2021-02-02 20:00
No problem. Thanks.

**Comment by majkinetor** [comment] 2021-02-03 22:43
I can confirm that master works.

**Comment by squidfunk** [comment] 2021-02-04 20:17
Released as part of 6.2.8!

**Closed by squidfunk** 2021-02-04 20:17 UTC
Labels: bug, fix available
