### ISSUE TITLE
`navigation.sections` + `navigation.indexes` causes the first page of the first section to turn into a section index

### ISSUE THREAD

**Issue by iBug** [squidfunk/mkdocs-material#5802] opened 2023-08-04 18:16 UTC
### Context

I was trying to replace the top section name (which defaults to `site_name`) when I ran into this issue.

### Bug description

When both `navigation.sections` and `navigation.indexes` are enabled and all top-level navigations are sections (not pages), the first page of the first section turns into the section index page even if it has a title. This does not occur with subsequent sections.

Example of the generated page:

> ![image](https://github.com/squidfunk/mkdocs-material/assets/7273074/24ba8e12-14b2-4115-9e4c-ed2810186f6c)

Expected result (using F12):

> ![image](https://github.com/squidfunk/mkdocs-material/assets/7273074/147c0410-40c3-483f-972b-6b834f1fb501)

Desired result (best outcome, but I would understand if declined):

> ![image](https://github.com/squidfunk/mkdocs-material/assets/7273074/2d2545d3-9c58-4a5a-9b07-3e0802d73b3a)

### Related links

- [Navigation sections](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections)
- [Section index pages](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages)

### Reproduction

File: [example.zip](https://github.com/squidfunk/mkdocs-material/files/12264556/example.zip)

### Steps to reproduce

The following is a minimal `mkdocs.yml` that reproduces the issue:

```yaml
site_name: Example

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections

nav:
  - Main:
    - Home: index.md
    - Page 1: 1.md
  - Section 1:
    - Page 1: 1.md
```

Create two empty files `docs/index.md` and `docs/1.md`, then use the above content for `mkdocs.yml`. Either `mkdocs build` or `mkdocs serve` works.

The reproduction works with versions 7.3.6, 8.5.11, 9.1.21 and 9.2.0b3. I could not backtrace further as `navigation.indexes` is not picked up by older versions.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-08-04 19:48
Thanks for reporting. The zip is required. Please provide a reproduction and upload it as a zip file.

**Comment by iBug** [comment] 2023-08-04 20:36
Here it is: [example.zip](https://github.com/squidfunk/mkdocs-material/files/12264429/example.zip)

Below are my responses that aren't directly related to the issue or its reproduction.

---

> you even checked the checkbox that says you uploaded it

It's a mandatory option such that if I don't check it it doesn't let me submit the issue in the first place. This goes against my intention but I had no other option.

> eating away our time ... need to set up an environment

I tested multiple environments locally and they all reproduce the issue. I am confident that my description is sufficient to allow the entire reproduction steps to complete in 30 seconds on the command line, so I do not see any real need for the ZIP archive other than sticking to the procedure.

I do appreciate that such a standard process exists in the first place and I'm willing to comply, but I see minimal value in upholding it pedantically (except in highly specialized situations like legal or medical cases). Some level of flexibility makes participants feel more welcome as we're all humans after all.

**Comment by squidfunk** [comment] 2023-08-04 20:47
> It's a mandatory option such that if I don't check it it doesn't let me submit the issue in the first place. This goes against my intention but I had no other option.

Yes, that is there for a reason. Otherwise we spend time copy and pasting your input into separate Markdown files. A runnable reproduction makes it easy for us to fix bugs. If you want a bug fixed, we require you to provide us with the best input that we can fix it quickly. I think this is fair, as you're requesting us to work _for free_ for you.

> I tested multiple environments locally and they all reproduce the issue. I am confident that my description is sufficient to allow the entire reproduction steps to complete in 30 seconds on the command line, so I do not see any real need for the ZIP archive other than sticking to the procedure, or feeding into automated systems (which could be mentioned in the documentation to justify its necessity to readers as I was not aware of any kind of it).

If you read the issue template carefully, it explains exactly that it is mandatory to provide a reproduction for the reasons stated. Additionally, the issue template links to our documentation where every step is explained, and why it is necessary to follow it. Managing a project of this size is extremly hard. We need to budget our time. Please understant that.

> I do appreciate that such a standard process exists in the first place and I'm willing to comply, but I see minimal value in upholding it pedantically (except in highly specialized situations like legal or medical cases). Some level of flexibility makes participants feel more welcome as we're all humans after all.

This is our process. Please stick to it. Please respect that. As said, most of our users are not sponsors, and we're happy to help them for free (or at the cost of our sponsors). For that, we require some cooperation.

**Comment by squidfunk** [comment] 2023-08-04 21:52
So turns out this is intended behavior. The site name is always printed as part of the navigation (or the name of the tab, if using `navigation.tabs`), and since the page under the `Home` entry in `nav`  is named `index.md`, it turns into a section page and is hoisted into the section. If you rename it to something else, e.g., `home.md`, it will be left as-is, but you'd need another top-level `index.md` page then. If this is not what you want, I'm sorry, but we need to strive a balance between functionatity and supporting a multitude of use cases.

Closing as working as intended.

**Closed by squidfunk** 2023-08-04 21:52 UTC
Labels: needs investigation

**Comment by iBug** [comment] 2023-08-05 06:37
Thanks for clarification.

As the documentation is currently written, it gives the impression that the section index page is selected from the first unnamed item, rather than the first item with a filename `index.md`. It would help to be explicit that the criterion is the filename, like adding an admonition to note this down.

I can put together a PR for the documentation change if you like.

**Comment by squidfunk** [comment] 2023-08-05 10:15
I'm not sure what is unclear here, we explicitly mention `index.md`:

<img width="719" alt="Bildschirmfoto 2023-08-05 um 12 15 28" src="https://github.com/squidfunk/mkdocs-material/assets/932156/ecf6d724-77d0-4191-8708-1e1cdbaabe45">

**Comment by iBug** [comment] 2023-08-10 19:58
Let me make it clear:

When I first glanced through this section, the most prominent differences are:

- It's listed as the first item of a section, and
- It does not have a title

It was not immediately obvious to me that the determining factor was the file name. The instruction above gave the impression that using `index.md` was a *convention*.

I'm sure there are others with the same concern. If I were to write this section, I would add an admonition box to call it out about file names.
