### ISSUE TITLE
Add support for Custom Element

### ISSUE THREAD

**Issue by vtsvetkov-splunk** [squidfunk/mkdocs-material#6652] opened 2024-01-15 11:34 UTC
### Context

I added Custom Elements with shadow root via custom elements because I don't want the styles of mkdocs has influence on forms I am adding. When I have a form inside my custom component, the global keyboard handler catches some keys I am typing like `s` and takes focus to search.
The reason is if there is input focused inside the shadow root, the parent's `document.activeElement` would point to the custom element itself, not to it's underlying element.

Since 'the bug' is caused by extra javascript, I cannot mark it as a bug, so I am asking about adding support for custom elements.

### Description

While having additional functionality via extra_javascript is a great feature, it lacks a full support for adding custom elements. I was able to add the custom element, but the keyboard shortcut is not aware about such type of element. 
There is a check for activeElement which works differently for elements with shadowRoot. I am asking to add support for such kind of elements here:
https://github.com/squidfunk/mkdocs-material/blob/44982451f7759ed65e31d1151b3c49566b8c6ca0/src/templates/assets/javascripts/browser/element/_/index.ts#L116-L120

The active element of shadowRoot can be accessed via `document.activeElement.shadowRoot.activeElement`.

### Related links

- [Custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements)
- [Shadow DOM v1 - Self-Contained Web Components # Handling Focus](https://web.dev/articles/shadowdom-v1#handling_focus).

### Use Cases

It will allow to have forms inside custom elements

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment] 2024-01-17 03:48
Thanks for reporting. Please provide a reproduction that showcases the issues. We cannot merge a PR without knowing what it impacts and for that we need to see it in action.

**Comment by vtsvetkov-splunk** [comment] 2024-01-17 10:32
@squidfunk sure
- a repo: https://github.com/vtsvetkov-splunk/mkdocs-material-custom-element-demo
- a deployed version: https://vtsvetkov-splunk.github.io/mkdocs-material-custom-element-demo/

**Comment by squidfunk** [comment] 2024-01-19 02:52
We can make hotkeys configurable in the future, but it is currently not a priority for us, so no ETA.

**Comment by vtsvetkov-splunk** [comment] 2024-01-19 08:27
@humitos,
> I'm also working with Custom Elements that contain inputs/forms inside them

If you use `open` mode when attaching shadow root, then my PR would mitigate that issue.

**Comment by vtsvetkov-splunk** [comment] 2024-01-22 10:56
To workaround the issue, I added a `keyDown` event listener for every input inside the custom element and called `stopPropagation`. I hope that would help who also experiences the issue.

**Comment by squidfunk** [comment] 2024-01-24 04:05
Fixed in https://github.com/squidfunk/mkdocs-material/commit/be95f4901ab4d61fa95ef78b6bc577b1c4071800 (superseding #6653) and released as part of [9.5.5](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.5).

**Closed by squidfunk** 2024-01-24 04:05 UTC
Labels: bug, resolved

**Comment by humitos** [comment] 2024-01-24 10:31
I can confirm that this fix works for me. I created a small example at https://test-builds.readthedocs.io/en/mkdocs-material/ and opening the search modal (`CustomElement`) and typing `n` or `p` inside the text input doesn't trigger the Next or Previous MkDocs hotkey 🎉 . Thanks @vtsvetkov-splunk and @squidfunk for the fix 💪🏼
