### ISSUE TITLE
q= parameter remains in URL after closing search dialog

### ISSUE THREAD

**Issue by jbms** [squidfunk/mkdocs-material#3622] opened 2022-02-25 00:14 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When using the `search.share` feature and loading a url with a `?q=` query parameter, the search dialog opens as expected, showing the search results.

However, if you close the search dialog without selecting a search result, the `?q=` parameter remains, meaning if you reload the page the search dialog opens again.

### Expected behaviour

The `?q=` parameter should be removed automatically when you close the search dialog.

In fact, the `?q=` parameter could be added automatically when opening the search dialog.  Then there would be no need for a separate share button at all.

### Actual behaviour

The `?q=` parameter remains after closing the search dialog.

### Steps to reproduce

1. Visit a URL obtained via the `seach.share` feature, such as: <https://squidfunk.github.io/mkdocs-material/?q=search*+share*>
2. Close the seach dialog by pressing escape.  Note that the `?q=` parameter remains in the URL.
3. Reload the page.

### Package versions

4f641cc0ee7befd440956e53b8798899482f6ed4 (master as of 2022-02-21)

### Configuration

```yaml
N/A
```

### System information

N/A

**Comment by squidfunk** [comment] 2022-02-25 08:53
Thanks for reporting. Auto-appending `q` is a great idea.

**Comment by squidfunk** [comment] 2022-02-26 09:09
Okay, so I thought about this again and I'm not sure if we want the 1:1 mapping between URL and search field. Thus, I'm currently not considering adding it. However, as of e3c26215d, the query parameter is now automatically removed when the search is closed, resolving the issue at hand.

In retrospect, this was not a bug, but it's an opinionated UI change because one could also make the same argument for keeping the query parameter. Nonetheless, I think removing the parameter is what the majority of users would expect.

**Comment by squidfunk** [comment] 2022-02-26 09:33
Released as part of 8.2.2.

**Closed by squidfunk** 2022-02-26 09:33 UTC
Labels: enhancement, fix available
