### ISSUE TITLE
Add possibility to show nav link both in left navigation and top panel

### ISSUE THREAD

**Issue by Kanaduchi** [squidfunk/mkdocs-material#1545] opened 2020-03-27 10:36 UTC
## Description

Sometimes it will be good to have possibility to show navigation link both in left navigation and top panel. 

Currently there is no such possibility. If we specify nested item, it becomes hidden in the main menu. I want to display it without dropdown elements, just link

### Screenshots / Mockups
![example](https://user-images.githubusercontent.com/7042994/77747282-35bcb980-7040-11ea-8efb-7d477de9e998.PNG)

**Comment by squidfunk** [comment] 2020-03-27 10:59
The sections are only hidden with CSS. You can open the developer tools of your browser and override the default CSS with some [additional stylesheets](https://squidfunk.github.io/mkdocs-material/customization/#additional-stylesheets).

**Comment by Kanaduchi** [comment] 2020-03-31 14:43
Ok, thank you. 

During implementing my idea I found some small issue:

1. In mkdocs.yml I specified several main pages:
nav:
  - Main: index.md
  - Another page: sub/index.md

2. All tabs are shown as active by default
3. When I go to 'Another page' all tabs are shown as inactive

Correct behavior: only tab of current page should has active style

**Comment by squidfunk** [comment] 2020-03-31 15:06
I'm sorry, but I don't follow. There's only one tab called `Main` and the rest of the pages are grouped under this tab:

<img width="232" alt="Bildschirmfoto 2020-03-31 um 17 05 25" src="https://user-images.githubusercontent.com/932156/78042158-f0ff8e00-7371-11ea-8a8c-5efc33922401.png">

**Comment by Kanaduchi** [comment] 2020-03-31 15:31
My example
[test.zip](https://github.com/squidfunk/mkdocs-material/files/4410055/test.zip)

**Comment by squidfunk** [comment] 2020-03-31 15:43
I'm sorry, but we cannot help you debug, because unfortunately, we cannot give support for customizations. This is also reflected in the criteria/checkboxes when creating a new issue when you say that the error does not originate in your customization. As I tested your configuration with the original docs and have found no error, I'm closing this. Please understand, that we try to invest as much time as possible in the theme as such, so everyone benefits.

**Closed by squidfunk** 2020-03-31 15:43 UTC

**Comment by Kanaduchi** [comment] 2020-03-31 16:14
My example from test.zip is made on stable version 4.6.3. And there is a bug with incorrect styles for tabs. All tabs are shown as active - but I expect that active can be only current tab.
Please look carefully into my example.

**Comment by squidfunk** [comment] 2020-03-31 16:16
On the [official website](https://squidfunk.github.io/mkdocs-material/), only the active tab is shown as active, therefore the error must be within your customization.

**Comment by Kanaduchi** [comment] 2020-03-31 16:19
Please look at my example from zip. I made it on stable version without any customization.

Here is screenshot
![screen](https://user-images.githubusercontent.com/7042994/78050104-4731f880-7395-11ea-8544-2ef85185e2b0.PNG)

**Comment by Kanaduchi** [comment] 2020-03-31 16:20
As you can see tabs has same color. That is the problem.

I guess reason is that I have 2 index.md files but in different locations

**Comment by squidfunk** [comment] 2020-03-31 16:25
You're using a custom directory, probably a fork, not the original theme:

```
INFO    -  Building documentation... 
ERROR   -  Config value: 'theme'. Error: The path set in theme.custom_dir ('.../material') does not exist. 
```

**Comment by Kanaduchi** [comment] 2020-03-31 16:55
[Uploading test_full.zip…]() 
I'm sorry. He is full package. `/material` directory contains latest stable version without any modifications

**Comment by squidfunk** [comment] 2020-03-31 17:12
Please post your question on StackOverflow or another general support forum.

**Comment by Kanaduchi** [comment] 2020-03-31 17:25
Em.. I've provided you example and description of problem with active tabs. What else?

**Comment by Kanaduchi** [comment] 2020-03-31 17:33
btw, I found a solution. I renamed files to main.md. And now tabs works as expected. 
But I can have several index.md files in different folders and this is eligible.

**Comment by facelessuser** [comment] 2020-03-31 17:45
@Kanaduchi I think what he is saying is simply that support is provided mainly for the default configuration of CSS or CSS configuration through the features options, but problems with custom JS and CSS is not supported.

The current CSS is not meant to handle every custom CSS a user would like to do, it is up to the user to figure what they need to do to support their custom stuff. It is too much for a maintainer of a library like this to help every user figure out how to customize the theme to fit their own personal taste. Just not enough time in the day for an open source project that isn't paying the bills.

**Comment by squidfunk** [comment] 2020-03-31 17:47
> Em.. I've provided you example and description of problem with active tabs. What else?

Material for MkDocs is an Open Source project, which I work on in my spare time. Besides, I always have forgone some small client projects to finish the next major version, v5. This project has a lot of users, big companies like Netflix, Samsung, AWS, and many more, but also many Open Source projects. When investing time into this project, I always try to make sure that the things I work on benefit as many people as possible. For this reason, I (or we) cannot potentially provide support for customization requests. This is clearly stated in the issue guidelines.

The problem you're mentioning doesn't happen with the official documentation. Everything works as expected, therefore the problem does very likely lie in your customizations for which we cannot provide any support. I hope you understand.

**Comment by Kanaduchi** [comment] 2020-03-31 17:53
I got your position. But what I described is not customization.

I created sample with 2 index files:

**Comment by squidfunk** [comment] 2020-03-31 17:58
Then it is probably related to MkDocs itself, as I cannot see anything from the template that might be causing this. Probably the `.is_homepage` member of the `page` object is `true` if the page is named `index.md`. @waylan could that be possible?

**Comment by facelessuser** [comment] 2020-03-31 18:09
@Kanaduchi for subtabs, you need to group them under a folder:

```
nav:
  - Main page: index.md
  - Other page:
    - Other: other/index.md
```

You only get one tab for files in the root, and this is based off the `index.md`. Others need to be a logically nested structure. That isn't controlled by Material. @waylan can probably give more info on group behavior.

**Comment by waylan** [comment] 2020-03-31 19:17
The MkDocs dev team (including myself) are also volunteers who do not have time to provide support for custom themes. However, I will note that if you are putting the `material` theme within a `custom_dir`, then you will need to replicate the entire theme config (usually found in `mkdocs_theme.yml)` under the `theme` setting in your `mkdocs.yml` file. `custom_dir` does not load theme config files by design. 

If you want to customize an existing theme, my suggestion would be to take one of two approaches:

1. Install the base theme and use [theme customization][1] to override bits and pieces of it.
2. Fork the theme and install your fork as a separate Python package. Then you would enable the theme using `theme.name` rather than `theme.custom_dir`.

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by squidfunk** [comment] 2020-03-31 19:20
@waylan thanks for the explanation. My question, however, was more directed whether `page.is_homepage` is `true` if the file is called `index.md` regardless of level, which seems to be the behavior, the OP seems to be referencing. Sounded like a potential bug to me, and I was just curious whether you've heard this before.

**Comment by waylan** [comment] 2020-03-31 19:30
@squidfunk I didn't take the time to read the entire discussion. My first assumption is that any issues are related to what I discussed. If someone can demonstrate the issue with a normal setup, then, yes, they should open an issue on the mkdocs project and provide the minimum necessary to replicate the bug. There appear to be way to many other factors here to be sure this is a bug (as opposed user error) and I don't have time to parse through them all.

**Comment by squidfunk** [comment] 2020-03-31 20:10
@waylan understood and seconded

**Comment by Kanaduchi** [comment] 2020-04-01 03:07
thank you all for explanation!

I have one more question.

In src/partials/tabs-item.html I see
```
<li class="md-tabs__item">
      {% if nav_item.active %}
        <a href="{{ (nav_item.children | first).url | url }}"
            class="md-tabs__link md-tabs__link--active">
          {{ title }}
        </a>
```
Will it be more correct to move md-tabs__link--active class to li element? Currently this prevents to style active tabs the same way as in https://material.io/components/

Thank you!
