### ISSUE TITLE
`pipenv install mkdocs-material` fails

### ISSUE THREAD

**Issue by borekb** [squidfunk/mkdocs-material#1692] opened 2020-05-13 20:41 UTC
Noted in #1690 but it's a separate issue: when I do `pipenv install mkdocs-material`, it fails.

### Steps to reproduce

Run:

```
mkdir mkdocs-pipenv
cd mkdocs-pipenv
pipenv install mkdocs-material
```

Observe this error:

```
ERROR: ERROR: Could not find a version that matches mkdocs-material-extensions>=1.0b1
Skipped pre-versions: 1.0b1, 1.0b1, 1.0b2, 1.0b2
There are incompatible versions in the resolved dependencies.
```

![Screenshot 2020-05-13 at 22 35 13](https://user-images.githubusercontent.com/101152/81862445-07505a80-956a-11ea-8f1d-b425c89fd0ae.png)

### Workarounds?

Adding `--pre` seems to work:

```
pipenv install mkdocs-material --pre
```

However, it installs (logically) pre-release dependencies which also doesn't seem quite right, see e.g. https://github.com/squidfunk/mkdocs-material/issues/1690#issuecomment-628228611.

### Disclaimer

I'm not a Python developer so maybe I'm missing something simple, but pip / pipenv installation is mentioned as the first one [in the Getting Started guide](https://squidfunk.github.io/mkdocs-material/getting-started/#with-pip-recommended). Commonly, I'm a happy user of the official Docker container which works nicely.

**Comment by squidfunk** [comment] 2020-05-13 20:50
Duplicate of #1674

**Comment by borekb** [comment] 2020-05-13 21:00
Doesn't look like a duplicate to me – I don't get any cyclic dependencies error.

What's the right way to install using `pipenv` then? Shouldn't `pipenv install mkdocs-material` just work?

**Comment by squidfunk** [comment] 2020-05-13 21:03
No, you’re right. I corrected my in initial comment. I was too quick 😅

**Comment by facelessuser** [comment] 2020-05-13 21:08
Looks like you may need to use the `--pre` option. The mentioned extension is a prerelease :shrug:.

**Comment by squidfunk** [comment] 2020-05-13 21:12
@facelessuser any plans to release the find version? Otherwise, with more users falling into this trap we might need to remove it from the `requirements.txt` at some point, which would be very sad.

**Comment by facelessuser** [comment] 2020-05-13 21:22
Yeah, there are plans. I think at this point, it is as solid as it's going to be. The only issues I've received is user errors, so I think it is good to go.

**Comment by squidfunk** [comment] 2020-05-13 21:23
Don't want to push you. Just asking how your plans are. Current errors are only with `pipenv` and `pipdeptree`. Don't know how widespread those tools are.

**Comment by facelessuser** [comment] 2020-05-13 21:27
🤷‍♂️ Generally, my response is it will be ready when it is ready. Based on what I've seen and tested, I think it is solid at this point. If we are going to continue to require it, we need at least one stable version out. I've got a couple things that are a little higher on my priority list, but I should be able to get a stable version out soon.

**Comment by borekb** [comment] 2020-05-13 21:55
Isn't there a way to lock dependencies more explicitly? The following is a screenshot where:

- **The left side** is generated by `docker run --rm -it -v ${PWD}:/docs --entrypoint pip squidfunk/mkdocs-material freeze`
- **The right side** is generated by my local `pip freeze` and removing packages that are not related to mkdocs-material.

<img width="1285" alt="Screenshot 2020-05-13 at 23 48 45" src="https://user-images.githubusercontent.com/101152/81869614-a4b08c00-9574-11ea-84bf-34bb1813f044.png">

There are some "scary" differences like MarkupSafe being a 1.0 locally vs. 1.1.1 in the Docker image. Generally, _any_ difference is risky (JS/npm thought us that 😄) and there's a ton of differences here.

**Comment by facelessuser** [comment] 2020-05-13 22:09
I don't know. I've used `pip-compile`: https://github.com/facelessuser/label-bot/blob/master/requirements.txt

**Comment by facelessuser** [comment] 2020-05-13 22:10
I don't know what the best way is though 🤷‍♂️ .

**Comment by facelessuser** [comment] 2020-05-14 03:42
It is released as an official stable release.

**Comment by squidfunk** [comment] 2020-05-14 05:50
Thanks @facelessuser! I'll update the requirements as soon as I get my hands on a computer 😊

**Comment by facelessuser** [comment] 2020-05-14 13:27
The good news is that even if you don't update requirements, people should start getting it anyways.

**Comment by squidfunk** [comment] 2020-05-14 15:48
Great, resolved, closing!

**Closed by squidfunk** 2020-05-14 15:48 UTC
