### ISSUE TITLE
icon/emoji is rendered incorrectly in the header

### ISSUE THREAD

**Issue by botkero** [squidfunk/mkdocs-material#6315] opened 2023-11-09 10:45 UTC
### Bug description

If you set an icon for a page, then under certain circumstances it is not displayed correctly when you scroll down the page.

### Related links

- docs:
  - [icons-emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)
  - [setting the page icon](https://squidfunk.github.io/mkdocs-material/reference/?h=icon#setting-the-page-icon)
  - [typeset](https://squidfunk.github.io/mkdocs-material/plugins/typeset/)
- discussions
  - [Icon is rendered incorrectly in the header ](https://github.com/squidfunk/mkdocs-material/discussions/6314)

### Reproduction

[minimal_reproduction.zip](https://github.com/squidfunk/mkdocs-material/files/13306880/minimal_reproduction.zip)

### Steps to reproduce

1. Click on `More`
2. Scroll down

[icon_header_bug.webm](https://github.com/squidfunk/mkdocs-material/assets/105428599/45f8d792-9cf6-4c00-bfa5-2a4f49ae91eb)

_I use the latest Firefox Version (119.1) and tested it on iPhone8 Safari (16.7.1)_

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-11-09 10:49
Thanks for reporting. This is a duplicate of #5893, and we must consider it an upstream issue. The behavior was introduced in MkDocs 1.5 and reported in mkdocs/mkdocs#3357. There's an open PR already at mkdocs/mkdocs#3394.

**Closed by squidfunk** 2023-11-09 10:49 UTC
