### ISSUE TITLE
The sidebar toggle doesn’t work properly on 12.9" iPad

### ISSUE THREAD

**Issue by walkccc** [squidfunk/mkdocs-material#762] opened 2018-04-16 06:33 UTC
## Description 

The sidebar toggle cannot unfold on 12.9" iPad unless I long pressed it.

### Expected behavior

The sidebar toggle can unfold properly like on a laptop or desktop when I press the menu directory.

### Actual behavior

When I long pressed it, the sidebar doesn't unfold. If I long press it(try to make it accent), then press it, it squeezed together. Like this:

![clrs](https://user-images.githubusercontent.com/14782909/38796506-36a01c26-418e-11e8-9f75-fb5d246f4da5.jpg)

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Package versions

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information
* OS: iOS 11.2.6
* Browser: Safari/Chrome

My iPad is 12.9 inches.

**Comment by squidfunk** [comment] 2018-04-16 09:35
I'm afraid I cannot really reproduce this error, because I don't have an iPad - can you try to isolate the problem and PR a fix?

**Comment by squidfunk** [comment] 2018-04-19 11:56
Thanks for your feedback, I'll see what we can do about it.

**Comment by walkccc** [comment] 2018-06-05 21:52
Hey, is this in progress?
Thank you!

**Comment by squidfunk** [comment] 2018-06-06 05:49
My time is very limited at the moment. I hope I can find some to address the open issues but I cannot say when, I'm sorry.

**Comment by szcf-weiya** [comment] 2018-09-24 06:46
Same problem on iPad Pro 12.9.

**Comment by squidfunk** [comment] 2019-02-13 17:05
Should be fixed by 4ca20f1.

**Comment by szcf-weiya** [comment] 2019-02-13 17:23
Thank you very much! Now it works pretty well!!

**Comment by squidfunk** [comment] 2019-02-13 17:28
Great, thanks for testing. I will issue a release with the latest bugfixes.

**Comment by squidfunk** [comment] 2019-02-13 17:37
Released as part of 4.0.1

**Closed by squidfunk** 2019-02-13 17:37 UTC
Labels: bug, fixed in master
