### ISSUE TITLE
Cant build site using 8.1.11

### ISSUE THREAD

**Issue by MAGICCC** [squidfunk/mkdocs-material#3576] opened 2022-02-12 19:32 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Build using GitHub actions or locally fails with a stacktrace when using 8.1.11. When I downgrade to 8.1.10 I can build the docs fine.
I noticed this while testing docs in my fork
https://github.com/MAGICCC/mailcow-dockerized-docs/runs/5169208337

### Expected behaviour

Build shouldnt fail

### Actual behaviour

Build fails with following stacktrace
```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mkdocs/__main__.py", line 187, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.8/dist-packages/mkdocs/commands/build.py", line 306, in build
    _build_theme_template(template, env, files, config, nav)
  File "/usr/local/lib/python3.8/dist-packages/mkdocs/commands/build.py", line 111, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/usr/local/lib/python3.8/dist-packages/mkdocs/commands/build.py", line 90, in _build_template
    output = template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.8/dist-packages/material/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/usr/local/lib/python3.8/dist-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.8/dist-packages/material/base.html", line 175, in top-level template code
    {% block footer %}
  File "/usr/local/lib/python3.8/dist-packages/material/base.html", line 176, in block 'footer'
    {% include "partials/footer.html" %}
  File "/usr/local/lib/python3.8/dist-packages/material/partials/footer.html", line 45, in top-level template code
    {% include "partials/social.html" %}
  File "/usr/local/lib/python3.8/dist-packages/material/partials/social.html", line 12, in top-level template code
    {% include ".icons/" ~ social.icon ~ ".svg" %}
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/fontawesome/solid/globe-americas.svg
```

### Steps to reproduce

1. Install mkdocs-material 8.1.11
2. `mkdocs build -c`
3. fails with stacktrace

### Package versions

- Python: `python --version`: Python3 3.8.10
- MkDocs: `mkdocs --version`: mkdocs, version 1.2.3 from /usr/local/lib/python3.8/dist-packages/mkdocs (Python 3.8)
- Material: `pip show mkdocs-material | grep -E ^Version`: Version: 8.1.11

### Configuration

```yaml
site_name: 'mailcow: dockerized documentation'
site_url: https://mailcow.github.io/mailcow-dockerized-docs/
copyright: "Copyright &copy; 2022 Servercow Team & Community"
repo_name: mailcow/mailcow-dockerized
repo_url: https://github.com/mailcow/mailcow-dockerized
edit_uri: ../mailcow-dockerized-docs/edit/master/docs/
remote_branch: gh-pages

theme:
  name: material
  palette:
   - scheme: default
     toggle:
       icon: material/toggle-switch-off-outline
       name: Dark Mode
   - scheme: slate
     toggle:
       icon: material/toggle-switch
       name: Light Mode
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.top
    - navigation.tracking
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - footnotes

nav:
  - 'Information & Support': 'index.md'
  [...]

plugins:
  - search
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Europe/Berlin
  - i18n: # <--- Translation plugin
      default_language: en
      languages:
        en: English
        de: Deutsch
      nav_translations:
      #### Begin of german translation
        de:
          'Information & Support': 'Informationen & Support'
          [...]
       #### End of german translation
  - redirects:
      redirect_maps:
        # 'old': 'new'
        [...]

  theme:
    palette:
      primary: indigo
      accent: orange
extra_css: [ assets/stylesheets/extra.css ]
extra_javascript:
  - assets/javascripts/client.js
```

### System information

Locally using Ubuntu 20.04 with latest updates and using GitHub [latest](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md) runner to build and deploy the page

**Comment by eyllanesc** [comment] 2022-02-13 04:11
As indicated in the CHANGELOG: 

https://github.com/squidfunk/mkdocs-material/blob/92c11bb1e098b377249ba6d85a886821eaf08c94/CHANGELOG#L8

And that is the case of the `.icons/fontawesome/solid/globe-americas.svg` icon.

So the solution is to change the icon in https://github.com/MAGICCC/mailcow-dockerized-docs/blob/master/mkdocs.yml#L362

**Comment by squidfunk** [comment] 2022-02-13 06:33
Duplicate of #3572. Please see
https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6

**Closed by squidfunk** 2022-02-13 06:33 UTC

**Comment by eyllanesc** [comment] 2022-02-13 16:17
@squidfunk You should indicate that link be checked in the CHANGELOG as it is a great reference.

**Comment by squidfunk** [comment] 2022-02-13 16:21
Good idea. 90137011e.
