### ISSUE TITLE
Allow title of social cards to respect MkDocs hooks

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#7023] opened 2024-04-07 22:05 UTC
### Description

I would like to change the title default to be derived from the `h1`. This PR from the maintainer of MkDocs introduced a hook that satisfies every relevant component that I can see except for the generated social cards: https://github.com/pypa/hatch/pull/1239

I'm using the latest version of the insiders edition.

### Related links

https://squidfunk.github.io/mkdocs-material/plugins/social/#option.title

### Use Cases

Full context is here: https://github.com/mkdocs/mkdocs/issues/3532

### Visuals

Inside https://github.com/pypa/hatch/blob/gh-pages/dev/how-to/publish/auth/index.html I see:

```html
<title>How to authenticate for index publishing - Hatch</title>
```

But the card uses the `nav`: https://github.com/pypa/hatch/blob/gh-pages/dev/assets/images/social/how-to/publish/auth.png

![social card](https://raw.githubusercontent.com/pypa/hatch/gh-pages/dev/assets/images/social/how-to/publish/auth.png)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment] 2024-04-08 00:37
Thanks for suggesting. [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) already allows to change many attributes for the default social card layouts by using the `on_page_markdown` hook, which deliberately uses a "latest" event priority to allow other plugins and hooks to change metadata before the social card is queued up for rendering. Moving rendering to `on_page_content` might be possible, but the problem is that the `_title_from_render` might contain markup, which will jam the social plugin.

Sticking to the title MkDocs derives _before_ rendering is safe in regards to that it does not contain markup. Also note, that there are currently issues with title handling in MkDocs:

- https://github.com/mkdocs/mkdocs/issues/3357

It seems that it was fixed, but we're still awaiting a release. We can re-evaluate this request once the changes are finally released, because it is unclear whether the title from rendering can "just be used" due to the potential presence of markup or unresolved icon short codes. Until then, here's a self-contained minimal reproduction that showcases how to change attributes for social cards programmatically in `on_page_markdown` for demo purposes:

[social-card-title-hook.zip](https://github.com/squidfunk/mkdocs-material/files/14899563/social-card-title-hook.zip)

Additionally, to work around the problem manually, you can use the following metadata in your page:

``` md
---
social:
  cards_layout_options:
    title: My page social card title
---

# My page title
```

Closing as resolved with configuration change.

**Closed** 2024-04-08 00:38 UTC
Labels: change request, resolved by config change

**Comment by ofek** [comment] 2024-04-08 02:18
That hook works beautifully, thank you very much!
