### ISSUE TITLE
Strange HTML at the bottom of documentation pages

### ISSUE THREAD

**Issue by mondeja** [squidfunk/mkdocs-material#6734] opened 2024-02-03 05:19 UTC
### Context

In all pages of documentation, at the bottom.

### Bug description

![image](https://github.com/squidfunk/mkdocs-material/assets/23049315/1bbf5e22-7fce-436d-8321-ef9a9501350c)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

Must be something like:

![image](https://github.com/squidfunk/mkdocs-material/assets/23049315/f04df5db-4581-499b-a8f8-1c6614b7a1f0)

### Steps to reproduce

Go to documentation, scroll down.

### Browser

Chrome

### Before submitting

- [ ] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [ ] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2024-02-03 05:31
Thanks for reporting. You did not provide the mandatory minimal reproduction. [Closing as incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues). Please __carefully__ read our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) and provide all necessary information. Thank you.

**Comment by squidfunk** [comment] 2024-02-03 05:32
Okay, sorry, this is _on our_ documentation. You should've opened a documentation issue for that. We'll investigate.

**Comment by squidfunk** [comment] 2024-02-03 05:38
I reported this upstream, as it's caused by a change to the git-revision-date-localized plugin:
https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/127

**Comment by squidfunk** [comment] 2024-02-03 06:02
Temporary mitigation in https://github.com/squidfunk/mkdocs-material/commit/94894f67bc22f47ea496b4ab667135840d7d5003, which also fixes the problem on our docs. If you also experience this problem, please use the following version of the git-revision-date-localized plugin, until the matters are resolved upstream, or the maintainers of MkDocs provided clear instructions how we should react to the impending changes as discussed in https://github.com/mkdocs/mkdocs/issues/3357.

**Closed by squidfunk** 2024-02-03 06:02 UTC
Labels: bug, upstream

**Comment by oprypin** [comment] 2024-02-03 07:49
I am not able to observe this. Could you please show me a way to reproduce this, it is very important. You say "our documentation" and that you can see it, but there is no `git-revision-date-localized` plugin in https://github.com/squidfunk/mkdocs-material/blob/bcad9cecd18b47409988ebb0aa69bea6a7edd70c/mkdocs.yml#L95 so I'm very confused
