### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Timber232** [squidfunk/mkdocs-material#260] opened 2017-04-07 13:53 UTC
## Description

I was not able to search anything but the home page that was generated when the project was created.
Typing a keyword (that actually exists in a document) in the search bar did not return any results.

### Expected behavior

![image](https://cloud.githubusercontent.com/assets/627637/24802602/8da9a918-1b76-11e7-9002-8d1c47cf6bec.png)

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/627637/24803208/7b607f0a-1b78-11e7-8835-7bce53300765.png)

Markdown source for the "Macaroon" example shown above:

File name: Lorem.md

```
# Macaroon

Macaroon croissant caramels dessert jelly-o. Toffee gingerbread chocolate. Ice cream apple pie cupcake cake danish biscuit sweet roll chocolate jelly-o. Caramels powder candy canes. Caramels powder soufflé jelly beans bear claw jelly-o. Ice cream gummies chocolate bar marzipan ice cream muffin gingerbread cake pudding. Soufflé icing pastry toffee dragée jujubes jelly-o. Toffee pie candy sweet roll fruitcake jelly. Caramels soufflé halvah marzipan cake biscuit sugar plum cotton candy tart. Chocolate bar liquorice liquorice chocolate fruitcake chocolate cake sweet roll sweet roll powder. Oat cake cotton candy tart cheesecake chocolate bar. Candy canes donut dessert. Lollipop croissant cake cookie chocolate bar croissant danish cake icing. Cake sweet sweet roll topping.
```

![image](https://cloud.githubusercontent.com/assets/627637/24803500/71b5a7f4-1b79-11e7-8485-3e7bbb878e93.png)

### Steps to reproduce the bug

1. Create a new mkdocs project with mkdocs-material theme
2. Add a new markdown document with text
3. Run `mkdocs serve`
4. Search for words that you know exists in the documents that you just created

I've also tried building the project, and noticed that the `search_index.json` is being generated:

``` json
{
    "docs": [
        {
            "location": "/", 
            "text": "Welcome to MkDocs\n\n\nFor full documentation visit \nmkdocs.org\n.\n\n\nCommands\n\n\n\n\nmkdocs new [dir-name]\n - Create a new project.\n\n\nmkdocs serve\n - Start the live-reloading docs server.\n\n\nmkdocs build\n - Build the documentation site.\n\n\nmkdocs help\n - Print this help message.\n\n\n\n\nProject layout\n\n\nmkdocs.yml    # The configuration file.\ndocs/\n    index.md  # The documentation homepage.\n    ...       # Other markdown pages, images and other files.", 
            "title": "Home"
        }, 
        {
            "location": "/#welcome-to-mkdocs", 
            "text": "For full documentation visit  mkdocs.org .", 
            "title": "Welcome to MkDocs"
        }, 
        {
            "location": "/#commands", 
            "text": "mkdocs new [dir-name]  - Create a new project.  mkdocs serve  - Start the live-reloading docs server.  mkdocs build  - Build the documentation site.  mkdocs help  - Print this help message.", 
            "title": "Commands"
        }, 
        {
            "location": "/#project-layout", 
            "text": "mkdocs.yml    # The configuration file.\ndocs/\n    index.md  # The documentation homepage.\n    ...       # Other markdown pages, images and other files.", 
            "title": "Project layout"
        }, 
        {
            "location": "/Lorem/", 
            "text": "Macaroon croissant caramels dessert jelly-o. Toffee gingerbread chocolate. Ice cream apple pie cupcake cake danish biscuit sweet roll chocolate jelly-o. Caramels powder candy canes. Caramels powder souffl\u00e9 jelly beans bear claw jelly-o. Ice cream gummies chocolate bar marzipan ice cream muffin gingerbread cake pudding. Souffl\u00e9 icing pastry toffee drag\u00e9e jujubes jelly-o. Toffee pie candy sweet roll fruitcake jelly. Caramels souffl\u00e9 halvah marzipan cake biscuit sugar plum cotton candy tart. Chocolate bar liquorice liquorice chocolate fruitcake chocolate cake sweet roll sweet roll powder. Oat cake cotton candy tart cheesecake chocolate bar. Candy canes donut dessert. Lollipop croissant cake cookie chocolate bar croissant danish cake icing. Cake sweet sweet roll topping.", 
            "title": "Lorem"
        }, 
        {
            "location": "/Test/", 
            "text": "Candy canes liquorice chocolate cake cake cupcake danish jujubes pie gummi bears. Gingerbread oat cake danish tootsie roll croissant fruitcake cupcake oat cake halvah. Chocolate cake apple pie dessert pie candy cheesecake. Jujubes gummi bears pastry tiramisu cake cupcake sweet jelly beans. Bear claw caramels cheesecake sweet roll. Tiramisu chocolate bar tootsie roll cake tart halvah. Bonbon lollipop chocolate cake pastry apple pie. Cotton candy muffin bonbon. Danish carrot cake carrot cake tart gummi bears marshmallow. Dessert pudding carrot cake sweet roll. Oat cake pastry cotton candy topping cake cupcake cake gummies. Sweet roll gummies toffee gummi bears brownie fruitcake danish fruitcake sweet. Bonbon biscuit apple pie gummi bears candy canes jelly-o ice cream chocolate cake pastry.", 
            "title": "Test"
        }
    ]
}
```

### Package versions

* Python: Python 2.7.12
* MkDocs: mkdocs, version 0.16.3
* Material: Version: 1.5.3

### Project configuration

``` yaml
site_name: My Docs
theme: 'material'
```

### System information

* OS: Windows 10 (Using [WSL](https://msdn.microsoft.com/en-us/commandline/wsl/about) [Ubuntu 16.04.2 LTS] to run the mkdocs command)
* Browser: Chrome, Vivaldi, Firefox

**Comment by squidfunk** [comment] 2017-04-07 13:55
You have a typo in your search query. Lunr does not handle fuzzy search, only wildcards for type-ahead.

**Comment by Timber232** [comment] 2017-04-07 13:57
@squidfunk Opps, sorry about that, I've updated the screenshot. Same problem.

**Comment by squidfunk** [comment] 2017-04-07 14:00
Please post the Markdown source of your Macaroon example page.

**Comment by Timber232** [comment] 2017-04-07 14:05
@squidfunk I've updated the issue with the Markdown source of the Macaroon example.

**Comment by squidfunk** [comment] 2017-04-07 14:06
Please post it as text (not image), so I can reproduce it.

**Comment by Timber232** [comment] 2017-04-07 14:07
The text version is just above it.

**Comment by squidfunk** [comment] 2017-04-07 14:08
Does the problem go away if you insert a second paragraph, e.g. like:

``` markdown
# Macaroon

## Lorem

...

## Ipsum
```

**Comment by Timber232** [comment] 2017-04-07 14:10
Yup! that worked:

![image](https://cloud.githubusercontent.com/assets/627637/24803795/5e3c01e0-1b7a-11e7-8bdf-2ab4c7f24ebe.png)

**Comment by squidfunk** [comment] 2017-04-07 14:10
Okay, then I think I know what the problem is. Will provide a fix soon.

**Comment by Timber232** [comment] 2017-04-07 14:10
Awesome! Thanks :).

**Comment by squidfunk** [comment] 2017-04-08 17:20
Fixed and released in 1.5.4

**Closed by squidfunk** 2017-04-08 17:20 UTC
Labels: bug, fixed in master

**Comment by damithnh** [comment] 2020-03-31 15:49
Hi, 
Does the search feature work in the built static html? Search works fine when served by `mkdocs serve` but doesn't work on built static html with `mkdocs build`
Thanks

**Comment by squidfunk** [comment] 2020-03-31 15:51
It works if you use the [localsearch](https://github.com/wilhelmer/mkdocs-localsearch) plugin.

**Comment by damithnh** [comment] 2020-04-01 07:35
> It works if you use the [localsearch](https://github.com/wilhelmer/mkdocs-localsearch) plugin.

Thanks so much

**Comment by busanaboina** [comment] 2025-02-18 13:10
> It works if you use the [localsearch](https://github.com/wilhelmer/mkdocs-localsearch) plugin.

I try to chnage the theme to material in mkdocs.yml file but ends up with error saying that:

ERROR   -  Config value 'theme': Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs
