### ISSUE TITLE
Blog: missing integrated table of contents in pagination

### ISSUE THREAD

**Issue by jiegec** [squidfunk/mkdocs-material#5715] opened 2023-07-15 04:32 UTC
### Bug description

A table of contents is generated for the index page, but not in pagination (`/page/2/` etc.)

- [index page](https://jia.je/): has TOC
- [pagination page 2](https://jia.je/page/2/) does not have TOC

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Setting up a blog](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/)

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/12060303/example.zip)

### Steps to reproduce

1. mkdocs serve
2. View `localhost:8000/page/2`

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-08-01 11:54
I'm not able to reproduce the problem. The first problem is that your example is not runnable for us - it is far too big to be useful. However, I checked it on our own blog, and I'm unable to reproduce the behavior you're describing. The table of contents renders just fine on any page. For example, if I limit the number of posts to 2:

![screenshot-localhost-8000-mkdocs-material-blog-page-2-1690890765816](https://github.com/squidfunk/mkdocs-material/assets/932156/80d93d1f-395d-4e3a-b683-eccc322600f5)

If you're still experiencing the issue, please create a minimal reproduction, and we can look into it.

**Comment by squidfunk** [comment] 2023-08-01 12:08
This is still not a proper reproduction. There's additional JavaScript, some wavedrom snippets that we can't run, pages that don't seem to belong to the blog and are not relevant for this problem, etc.

__Please remove everything that is not necessary to observe the problem__. Thank you! 😊

**Comment by jiegec** [comment] 2023-08-01 12:14
Please check this one: [example.zip](https://github.com/squidfunk/mkdocs-material/files/12228988/example.zip)

**Comment by squidfunk** [comment] 2023-08-01 15:01
Finally reproducible, thanks you!

**Comment by squidfunk** [comment] 2023-08-01 15:14
Okay, so this is actually tricky to fix, because the integrated table of contents will only be rendered for the currently active page. Since the paginated page is not part of the navigation, but essentially a shadow of the index page, the integrated table of contents is not rendered, This does not apply for the non-integrated table of contents which is rendered just fine.

We'll address this issue as part of the refactoring which we'll be doing shortly.

**Comment by squidfunk** [comment] 2023-08-21 16:13
Resolved in 38b7282b204d5c8d6a17990a72a4be4a8238a78b – it's going to be released as part of 9.2.

**Closed** 2023-08-21 17:32 UTC
Labels: bug, resolved

**Comment by fungaren** [comment] 2023-08-24 08:42
Still unable to work. Have you retried it? @squidfunk

**Comment by squidfunk** [comment] 2023-08-24 09:28
Yes, and it works. Your example structure is however wrong. You have `blog_dir`set to `.` which means the posts folder must be at `docs/posts`, not at `docs/blog/posts`. If you move the folder up, it works as expected:

![screenshot-localhost-8000-page-2-1692869273161](https://github.com/squidfunk/mkdocs-material/assets/932156/8e969e45-1590-48fb-b313-0f61d5ff829d)
