### ISSUE TITLE
"Home" title using "navigation.instant" feature

### ISSUE THREAD

**Issue by Belface** [squidfunk/mkdocs-material#4924] opened 2023-01-27 16:27 UTC
### Bug description

Hello
when I navigate back to the index page of my website, my title in the top left corner of the page (div class="md-header__title") is changed into "Home" label. If I remove "navigation.instant" feature from mkdocs.yml, the issue disappears.

### Related links

- [Bug reporting](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/)
- Nothing much

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10534380/example.zip)

### Steps to reproduce

1. Display the index page --> Title = site_name (from mkdocs.yml) --> **OK**
2. Display a page from navigation menu --> Title = site_name --> **OK**
3. Scroll on this page --> Title = name of the page (also from mkdocs.yml/nav:) --> **OK**
4. Click the logo on left top of page (without scrolling back to top)
5. The index page is displaying --> Title = "Home" --> **NOK**

If I replace the last 2 steps by :
4. Scrolling back to top --> Title = site_name (from mkdocs.yml) --> **OK**
5. Click the logo, the index page is displaying --> site_name (from mkdocs.yml) --> **OK**

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment] 2023-01-27 18:27
Thanks for reporting. However, this issue is incomplete. We need a [reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/). Please follow the reproduction guide, it's actually super easy to create one, but helps us maintainers save a lot of time, providing bugfixes much quicker.

[Closing as incomplete](https://squidfunk.github.io/mkdocs-material/bug-report/#incomplete-issues). We'll reopen when this issue has a reproduction.

**Comment by Belface** [comment] 2023-01-30 09:48
Hello Martin,
I've updated the post by adding the reproduction file.
I noticed that when I add a first tree tag in the index.md (#Test for example), the issue disappear

**Comment by squidfunk** [comment] 2023-02-09 20:20
Thanks for the excellent reproduction – that made observing and fixing the problem straight forward! The reason was that the header title state was not reset when navigating, and when the document contains no headline, it stayed in the state it was in before. Fixed in ff99e1974 by resetting the title state on navigation.

**Closed** 2023-02-09 20:31 UTC
Labels: bug, resolved

**Comment by Belface** [comment] 2023-02-10 07:34
Thanks Martin
Good job !
