### ISSUE TITLE
Search hotkey does not work in tablet view

### ISSUE THREAD

**Issue by matjaeck** [squidfunk/mkdocs-material#1067] opened 2019-04-10 23:15 UTC
Description

Pressing "S" in tablet screen size does not open the search overlay. It will focus the hidden search field instead and write into it, as you can see when resizing to screen size. This can be reproduced on the demo page and happens in chrome and firefox.

Reproduction: Go to the demo page, resize screen to tablet size, type "stest", resize to screen size.

**Comment by squidfunk** [comment] 2019-04-11 07:19
That is in fact correct. <kbd>ESC</kbd> seems to work. Shouldn't be too hard to fix.

**Comment by squidfunk** [comment] 2019-04-28 08:35
Revisiting the source code it's clear that this was initially done by design - the search should not triggerable by hotkey if the search bar was not visible. However, the focus did actually execute, leaving the user in the invalid state in which it was search was not visible but focused.

8049185 removes the breakpoint guard for the hotkeys, so search does now consistently trigger on hotkeys for all screen sizes.

**Comment by squidfunk** [comment] 2019-04-28 10:08
Released as part of 4.2.0.

**Closed by squidfunk** 2019-04-28 10:09 UTC
Labels: bug, fixed in master
