### ISSUE TITLE
long unbreakable headings break mobile table-of-contents view

### ISSUE THREAD

**Issue by thesuperzapper** [squidfunk/mkdocs-material#6344] opened 2023-11-15 23:14 UTC
### Bug description

If you have a very long unbreakable heading in a page, the table of contents view (in the mobile sidebar) will not wrap it, and it will be scrollable off-screen.

I am not sure what the most desirable behavior here is, e.g. force wrapping (even in the middle of words), or making an ellipsis, or something else.

![Screenshot 2023-11-15 at 15 13 29](https://github.com/squidfunk/mkdocs-material/assets/5735406/bbbaad08-7e80-45b9-bb08-862a192d92ae)

### Related links

- https://github.com/squidfunk/mkdocs-material/issues/84

### Reproduction

[9.4.8-long-headings-break-toc.zip](https://github.com/squidfunk/mkdocs-material/files/13370590/9.4.8-long-headings-break-toc.zip)

### Steps to reproduce

1. Create a very long heading in a page (which is not breakable with spaces, dashes, etc)
2. Open page on mobile
3. View sidebar table of contents
4. Notice that the heading link goes off page in a way which is not scrollable on mobile that

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment] 2023-11-16 09:15
I assume that the long unbreakable title is generated from source code so you cannot just avoid it? I am not entirely sure there is a generic solution for this, so would suggest a customization. You could write a [hook](https://www.mkdocs.org/user-guide/configuration/#hooks) that plugs into the [`on_nav` event](https://www.mkdocs.org/dev-guide/plugins/#on_nav) to modify the navigation where necessary?

**Comment by alexvoss** [comment] 2023-11-17 05:48
Coming back to this, I should have looked at your reproduction first. I do not get the behaviour you describe when I use the Insider version of Material but when I use the public version I get the same result as you do. This does seem to be an unintended divergence between the two versions to me.

This is with insiders:
<img width="374" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/4134224/1c2f11f7-e3ce-440e-86d5-f4a699a9d68d">

**Comment by alexvoss** [comment] 2023-11-17 06:14
I think I have spotted where the problem lies. In the `toc-item` partial in the public version, there is no `span` that attaches the `.md-ellipsis` class. That is present in the Insiders version. Will do a PR.

**Comment by squidfunk** [comment] 2023-11-17 09:26
Keeping open, until released.

**Comment by squidfunk** [comment] 2023-11-17 11:26
Released as part of [9.4.9](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.9).

**Closed by squidfunk** 2023-11-17 11:26 UTC
Labels: bug, resolved
