### ISSUE TITLE
Back-to-top button does not follow palette settings

### ISSUE THREAD

**Issue by zx80** [squidfunk/mkdocs-material#7124] opened 2024-04-29 07:02 UTC
### Bug description

On

```
theme:
  features:
    - navigation.top
  palette:
    primary: orange
```

The back-to-top button seems to be highlighted with the default indigo color, whereas it would make sense to use the palette setting.

### Related links

- [Navigation Integration](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration)

### Reproduction

[9.5.19-back-to-top-button-highlight-color.zip](https://github.com/squidfunk/mkdocs-material/files/15145978/9.5.19-back-to-top-button-highlight-color.zip)

### Steps to reproduce

Open the minimal example, move down then up the page, go to the "back-to-top" button and look at its indigo color, whereas another color would make sense.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-04-29 08:09
Thanks for reporting. Material Design mandates the user of two complementing color tints, [primary](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color) and [accent](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color). The back-to-top button uses the accent color for highlighting to denote that you can click it:

<img width="416" alt="Bildschirm­foto 2024-04-29 um 15 07 20" src="https://github.com/squidfunk/mkdocs-material/assets/932156/54cc6c30-0601-4f89-838e-2ecd6234067b">

If you do not like that, you can easily override the back-to-top button styling with some [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) ☺️ Or, if you want to change it to orange, just use:

``` yaml
theme:
  features:
    - navigation.top
  palette:
    primary: orange
    accent: orange
```

Closing as working as intended.

**Closed by squidfunk** 2024-04-29 08:09 UTC

**Comment by zx80** [comment] 2024-04-30 03:14
Argh, sorry for the noise!

**Comment by zx80** [comment] 2024-04-30 19:54
After giving it some thought, think that it would make sense to keep `primary` and `accent` synchronized by default, i.e. the default `accent` value should be the same as `primary` unless _explicitely_ told otherwise.

I do not see the value of having to switch **two** configuration directives to have a consistent choice of color, and this
was my underlying expectation when I (wrongly) reported this as a bug: some color-clever people made informed choices, and I wanted to have the benefit with minimal effort: the colors of the _same_ name are not actually the same colors for `primary` and `accent`, the former is a brighter version if I'm not mistaken.

**Comment by squidfunk** [comment] 2024-05-01 00:22
Thanks for suggesting. Regardless of whether one would consider this sensical (I kindly disagree), whis would be a departure from the current behavior, which must considered to be a breaking change, as the output changes without the author doing anything. Since this change has zero upside, we cannot consider it.

I hope you understand this decision and just change the color to your liking 😅

**Comment by zx80** [comment] 2024-05-01 07:57
> I hope you understand this decision and just change the color to your liking 😅

Obviously!
