### ISSUE TITLE
Add a button to hide/show left-hand and right-hand navigation panel

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [squidfunk/mkdocs-material#4272] opened 2022-08-22 15:46 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

Hi!

There was an issue on GitHub where you added settings to hide/show the side panels: https://github.com/squidfunk/mkdocs-material/issues/1930

However, this option is not dynamic. Would it be difficult to implement a button to show/hide left/right panels to stretch the contents of the page?

For example, you choose to collapse left/right panel to the left/to the right side by default in the settings to allow more centered view space and a user can any time toggle a button to unfold the panels.

### Use Cases

Side panels in Material take too much space by default, so it is not always convenient to read technical docs. At the same time it would be useful to be able to check right/left panels so they are present but folded.

**Comment by squidfunk** [comment] 2022-08-23 07:43
Thanks for suggesting! This feature request is a duplicate of #3428. Support for this feature is currently not planned but might be re-evaluated in the future. The reason is lack of interest among users + it's tricky to implement UX-wise.

**Closed by squidfunk** 2022-08-23 07:43 UTC

**Comment by xsa** [comment] 2023-05-26 09:32
Too bad. I would find it useful too. Especially for the right-hand side toc.

**Comment by squidfunk** [comment] 2023-05-26 10:09
Noted, as said, we might add this in the future. Up to now, there hasn't been much interest.

**Comment by squidfunk** [comment] 2023-05-27 10:16
We've re-opened #3428 and are considering this change!

**Comment by squidfunk** [comment] 2023-05-27 12:19
Prototype in https://github.com/squidfunk/mkdocs-material/issues/3428#issuecomment-1565389397
