### ISSUE TITLE
Built-in info plugin can't be used since a beta version of Material is released with an upper version

### ISSUE THREAD

**Issue by Guts** [squidfunk/mkdocs-material#5792] opened 2023-08-01 04:49 UTC
### Bug description

I'm trying to create a reproduction issue specific to Insiders flavor (9.1.21-insiders-4.38.0). So I enable the info plugin in mkdocs.yml but building the site, I've got this error:

```sh
> mkdocs build -s
ERROR   -  Please upgrade to the latest version.

  When reporting issues, please first upgrade to the latest
  version of Material for MkDocs, as the problem might already
  be fixed in the latest version. This helps reduce duplicate
  efforts and saves us maintainers time.

  Please update from 9.1.21+insiders.4.38.0 to 9.2.0b2.

  pip install --upgrade --force-reinstall mkdocs-material
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Create a reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/)

### Reproduction

Because this field is mandatory and info plugin not working, I've created an archive manually:

[material_info_not_working.zip](https://github.com/squidfunk/mkdocs-material/files/12224741/material_info_not_working.zip)

### Steps to reproduce

1. Create a new mkdocs site
2. Add info plugins
3. Run mkdocs build

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-08-01 07:20
Thanks for reporting. Exact duplicate of #5773, which also explains how to mitigate it until we sort this out.

**Closed by squidfunk** 2023-08-01 07:20 UTC

**Comment by Guts** [comment] 2023-08-01 07:35
Ups sorry, i was pretty sure that I've searched before to create. Obviously, I missed my search!
