### ISSUE TITLE
Optimizations for large documentation

### ISSUE THREAD

**Issue by aimeos** [squidfunk/mkdocs-material#1887] opened 2020-08-27 15:57 UTC
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

We are currently trying to optimize page render times of the generated docs. It largely depends on the content and we have a lot in our documentation, e.g.: https://aimeos.org/docs/2020.x/config/client-html/account-download/

We found out that the biggest problem is the navigation, which contains all navigation items on all pages. Google Lighthouse reports an exessive number of DOM nodes for each page (~1400) and an extremely long largest contentful paint:

![image](https://user-images.githubusercontent.com/8647429/91450180-50f45500-e87c-11ea-8ec0-9cf360bb33b7.png)

The first though was to reduce the number of navigation items but that isn't that easy as we can't merge more pages because they are rather long in most cases and the value/experience for the user would get worse.

We identified two things that could be optimized and have a big effect:

1.) The biggest problem is how Disqus is added
The Material theme uses `document.write()` to add it's HTML code but we can use in `partials/integrations/disqus.html` instead:
```
  <script>
    var disqus_config=function(){
      this.page.url="{{ page.canonical_url }}",
      this.page.identifier="{{ page.canonical_url | replace(config.site_url, '') }}"
    };

    if('IntersectionObserver' in window) {
      let observer = new IntersectionObserver(function(entries, observer) {
        for(let entry of entries) {
          if(entry.isIntersecting) {
            observer.unobserve(entry.target);
            el=document.createElement("script");
            el.src="https://{{ disqus }}.disqus.com/embed.js";
            el.setAttribute("data-timestamp",+new Date);
            document.body.appendChild(el);
          }
        }
      },{
        threshold: 0.01
      });
      observer.observe(document.querySelector('#__comments'));
    } else {
      el=document.createElement("script");
      el.src="https://{{ disqus }}.disqus.com/embed.js";
      el.setAttribute("data-timestamp",+new Date);
      document.body.appendChild(el);
    }
  </script>
```
This postpones the `document.write` until the user scrolls to the comment section.

2.) Reduce the HTML tags per nested navigation
There are 65 span tags `<span class="md-nav__icon md-icon">` on each page which contains an `<svg><path/></svg>`. If we remove them and add a `label.md-nav__link:after { content: url(caret.svg); }` in CSS, we save ~200 nodes at once. Also, the file size reduces because the icon is only defined once.

Afterwards we get:
![image](https://user-images.githubusercontent.com/8647429/91465507-26ab9300-e88e-11ea-9615-b6aa797f9ca2.png)

### Use Cases

We only have >300 pages which I consider a medium sized documentation. Nevertheless, the DOM nodes are currently >5x the number of navigation items, which has a big effect the more pages are added.

**Comment by squidfunk** [comment] 2020-08-27 16:11
Thanks for digging into this.

> We found out that the biggest problem is the navigation, which contains all navigation items on all pages. Google Lighthouse reports an exessive number of DOM nodes for each page (~1400) and an extremely long largest contentful paint:

That's necessary for navigation on mobile devices. Navigation is only included once and used inside the drawer on mobile and the sidebar on desktop. It's not possible to drop any items here, even when using tabs, as we would lose mobile navigation. If you don't need mobile navigation, you might remove it using overrides as documented in the [customization guide](https://squidfunk.github.io/mkdocs-material/customization/).

> The biggest problem is how Disqus is added
The Material theme uses document.write() to add it's HTML code but we can use in partials/integrations/disqus.html instead.

I guess we could use `IntersectionObserver`, as [support seems to be solid](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), but yes, we need to provide the fallback. Note, however, that your solution might leak memory (need to check) when used together with instant loading, as the observers are not unregistered upon page unload.

> Reduce the HTML tags per nested navigation
There are 65 span tags <span class="md-nav__icon md-icon"> on each page which contains an <svg><path/></svg>. If we remove them and add a label.md-nav__link:after { content: url(caret.svg); } in CSS, we save ~200 nodes at once. Also, the file size reduces because the icon is only defined once

We can think about moving this to CSS, yes.

**Comment by squidfunk** [comment] 2020-08-28 16:22
The latest commit moves the SVG icon definitions which are part of the navigation to CSS, as suggested. The number of nodes should now be greatly reduced for large documentation projects. I (currently) don't see the Disqus optimizations as being necessary, so we'll leave it as it is. Also, overriding Disqus is simple.

Reopening until released.

**Comment by squidfunk** [comment] 2020-08-28 16:27
Okay, one little change to the Disqus integration – it's now wrapped with an event listener to be executed on `load`, thus it shouldn't block the first paint anymore. Added in 96f58eda.

**Comment by squidfunk** [comment] 2020-08-28 16:48
Released as part of 5.5.10. Thanks for your effort digging into this topic!

**Closed by squidfunk** 2020-08-28 16:48 UTC
Labels: enhancement, fix available

**Comment by aimeos** [comment] 2020-08-29 08:14
> Okay, one little change to the Disqus integration – it's now wrapped with an event listener to be executed on `load`, thus it shouldn't block the first paint anymore. Added in [96f58ed](https://github.com/squidfunk/mkdocs-material/commit/96f58edae6ca0c0f99eed81e80e98b7b15dc70ea).

Unfortunately, it's not the case. The results are still the same with an extremely long contentful paint:
![image](https://user-images.githubusercontent.com/8647429/91632143-2e2e8180-e9df-11ea-8a7e-7735a8cf25c4.png)

Only if we use the intersection observer to load it if the user scrolls down, the problem is solved. The intersection observer also has the advantage that the Disqus threads wouldn't be loaded most of time.

There's one further optimization for the future:
Due to the nature of the Mkdocs documentation to include the whole navigation tree in each page, a lot of HTML code is included. You've already reduced the number of DOM elements and it also makes a difference how much characters each node contains. Thus, reducing the length of the class names and avoiding additional attributes if possible also makes a difference the bigger the documentation will get:

![image](https://user-images.githubusercontent.com/8647429/91632341-5d91be00-e9e0-11ea-9126-125cf6ad3a8e.png)

**Comment by squidfunk** [comment] 2020-08-29 14:00
> Unfortunately, it's not the case. The results are still the same with an extremely long contentful paint

Interesting, as my testing showed improvements, but Lighthouse scores will always depend on the actual, final HTML being used. Note that you're only escaping from Lighthouse taking notice of the Disqus integration when using the `IntersectionObserver` approach. It is the same, if the page is loaded at the bottom, rendering the comments straight away. If you feel that the integration doesn't work for you, overriding it is plain and simple, as you've already proposed.

> Due to the nature of the Mkdocs documentation to include the whole navigation tree in each page, a lot of HTML code is included. You've already reduced the number of DOM elements and it also makes a difference how much characters each node contains. Thus, reducing the length of the class names and avoiding additional attributes if possible also makes a difference the bigger the documentation will get

This isn't big of a problem when content is served with `gzip` anyway, which is an established best-practice. It will make no difference in the compressed source delivered to the browser. The browser has to do a little more parsing, but that difference is negligible.

Yes, we could compress or shorten class names, but that would either come at the cost of worse maintainability if done directly in the SCSS code that is compiled to CSS, or result in unstable class names when done as a post-processing step. This would mean that it would be much harder for authors to override certain parts, as class names are less readable or might change in unexpected ways, increasing cost of maintenance downstream. Material for MkDocs strives to be a hackable and extendable theme and clear and concise CSS naming is an essential part of it.

**Comment by wilhelmer** [comment] 2021-08-23 07:28
> > We found out that the biggest problem is the navigation, which contains all navigation items on all pages. Google Lighthouse reports an exessive number of DOM nodes for each page (~1400) and an extremely long largest contentful paint:
> 
> That's necessary for navigation on mobile devices. Navigation is only included once and used inside the drawer on mobile and the sidebar on desktop. It's not possible to drop any items here, even when using tabs, as we would lose mobile navigation. If you don't need mobile navigation, you might remove it using overrides as documented in the [customization guide](https://squidfunk.github.io/mkdocs-material/customization/).

@squidfunk I still think it would be nice to be able to exclude all nav items from other tabs when `navigation.tabs` is enabled. At least make that an option. As for mobile navigation, why not display the tab level, but if you click on a tab, load the tab index page, closing the drawer? I could live with that.

I think `navigation.tabs` is mostly used for larger documentation projects, and in those projects (like ours), all the excess nav items really become a PITA. We have a lot of pages where the nav items make up 90% (!!) of the file size. It just doesn't scale well.

If you think that's an edge case, some help on how to get this done via customization would be much appreciated.

**Comment by squidfunk** [comment] 2021-08-23 07:58
> If you think that's an edge case, some help on how to get this done via customization would be much appreciated.

I'd really consider this as an edge case, as most document projects are not that large. However, I understand that the file size is causing you trouble. I would have thought that gzip compression should be quite efficient, as there are a lot of shared strings/prefixes, but I may be wrong.

So in general, one could replace the non-active tab in the drawer with a link to that tab page, as you said, and only render the navigation hierarchy for the active tab. This would need to be done in [`nav-item.html`](https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/nav-item.html). If you take a look at the code, you realize why I'm not keen on making this more complex than it already is.

I'm pretty sure that it _could_ be done, but some research is definitely necessary. I'm unsure whether this could be an option that goes into `master` or will remain a customization. IMHO, this can only be decided after implementing it. If you need help, ping me at martin.donath@squidfunk.com.

**Comment by flanciskinho** [comment] 2021-08-23 08:08
I think that this is a edge case.

Have you tried techniques on your web server like using compression when sending documents, add expiration time for the content, or enabling the cache?

**Comment by wilhelmer** [comment] 2021-08-23 08:16
IMHO, it's just 90% unnecessary data that shouldn't be there, regardless of whether any web server techniques can work around it. We also deliver the documentation as a download for local use, so every byte matters.

**Comment by squidfunk** [comment] 2021-08-23 08:41
> The main problem are the huge number of HTML nodes due to the full navigation menu that can cause a slow down of rendering for smartphones. It takes several seconds until the page becomes usable.

I'd be curious to see a reproducible case with some benchmarks (before + after trimming down the navigation structure). This would yield the necessary baseline on how much improvement could be expected, and if it's worth going down that path.

**Comment by wilhelmer** [comment] 2021-08-23 18:45
The more I think about it, the more I like the idea of removing the nav items from other tabs. Right now (as you pointed out), with `navigation.tabs` enabled, the template switches to "tabbed mode" on desktop, but the mobile view remains the same, which is inconsistent. Users who only visit the site on mobile won't notice any difference, despite the setting.

If we had a real "tabbed mode" in both desktop and mobile – maybe with more visual clues in the mobile version, not just with replaced links – that would bring a consistent experience for all users **and** dramatically reduce the file/DOM size on large doc projects.

**Comment by squidfunk** [comment] 2021-08-23 19:04
> but the mobile view remains the same, which is inconsistent.

I don't agree with this point. While it might be possible to show the tabs on all screen sizes (by making them scrollable, which would make it harder to discover navigation), you're effectively breaking navigation into multiple UI elements on mobile. My personal experience is that users have learned that navigation on mobile hides entirely behind the hamburger menu. Breaking navigation into multiple components might in fact be less intuitive. This is the main reason navigation is entirely contained in the drawer on mobile.

> If we had a real "tabbed mode" in both desktop and mobile – maybe with more visual clues in the mobile version, not just with replaced links – that would bring a consistent experience for all users AND dramatically reduce the file/DOM size on large doc projects.

Yes, larger docs projects _might_ benefit from this. However, this would mean a significant change in behavior + a serious refactoring for which I currently can't afford the time, given the current funding situation. I have too many other things on my plate, so if somebody really really wants this, there are two options:

1. A user-provided PR, which is completely backward compatible with all existing features (and Insider features), that doesn't introduce too much additional complexity, because, in the end, it is me who has to maintain it. As a starter, [this discussion](https://github.com/squidfunk/mkdocs-material/discussions/2399) contains a checklist what has to be considered when implementing features for Material for MkDocs.
2. Somebody pays me to implement this as part of a freelance gig, so I can set aside enough time to pull this off

I'm hoping for your understanding. This project is very, very complex already. When adding more features, especially regarding navigation, many things have to be considered. Nonetheless, a benchmark, which clearly shows the upside of this refactoring (given gzip compression) is a mandatory requirement that has yet to be provided.

**Comment by wilhelmer** [comment] 2021-08-24 08:55
I don't think we can argue whether it's inconsistent (it is, unless you rename the option to `navigation.desktop.tabs`), only if the behavior is in*consequential*. But that's just words, I get your point. And I think you're right, in most cases, users will benefit more from the non-breaking mobile navigation than they do from the reduced file/DOM size.

For what it's worth, I came up with a fairly simple solution that only requires customizing `nav-item.html`. I'd be happy to hear your thoughts. This is not intended as a general solution, but as a personal customization. (Also, thanks for your mail.)

### Step 1: Nav items should only be generated for the active main navigation item and its nested item list

We change this:

https://github.com/squidfunk/mkdocs-material/blob/702de8258588f2602054f915a2a6b64ec32648f2/src/partials/nav-item.html#L32-L33

To this:

```jinja
  <!-- Main navigation item with nested items -->
  {% if nav_item.children and (nav_item.active or level > 1 ) %}
```

That's it! Does all the magic. (I hope.)

### Step 2: The main level of the mobile view should behave like tabs

To achieve this, we can borrow some code from `tabs-item.html`. We change this:

https://github.com/squidfunk/mkdocs-material/blob/702de8258588f2602054f915a2a6b64ec32648f2/src/partials/nav-item.html#L129-L136

To this:

```jinja
  <!-- Main navigation item with nested items -->
  {% elif nav_item.children %}
    {% set title = title | d(nav_item.title) %}
    {% set nav_item = nav_item.children | first %}

    <!-- Recurse, if the first item has further nested items -->
    {% if nav_item.children %}
      {% include "partials/nav-item.html" %}

    <!-- Render item -->
    {% else %}
      <li class="{{ class }}">
      <a href="{{ nav_item.url | url }}" class="md-nav__link">
        {{ title }}
      </a>
    </li>
    {% endif %}

  <!-- Main navigation item -->
  {% else %}
    <li class="{{ class }}">
      <!-- EDIT: Added data-title -->
      <a href="{{ nav_item.url | url }}" class="md-nav__link">
        {{ nav_item.title }}
      </a>
    </li>
  {% endif %}
```

**Comment by squidfunk** [comment] 2021-08-24 09:13
Thanks for providing your solution. I'm yet waiting for somebody to provide some real-world data that proves that dropping the navigation items from the DOM really benefits loading times on slower connections and/or devices.

**Comment by wilhelmer** [comment] 2021-08-24 10:08
File size difference in our project (yes, I know, doesn't say much about the loading time, but maybe still helpful)

Before:
788 HTML files, 151 MB (159,291,985 bytes)

After:
788 HTML files, 62.8 MB (65,954,416 bytes)

-> ~41.6 % of original size

**Comment by squidfunk** [comment] 2021-12-12 21:38
Optimizations for large documentation projects are now on the Insiders roadmap, called "navigation pruning":
https://squidfunk.github.io/mkdocs-material/insiders/#12000-piri-piri

**Comment by malohr** [comment] 2021-12-22 17:43
@squidfunk 

I think this is not an edge case and makes mkdocs unusable for bigger projects. We've got over 4k md files and have now an 8GB build, which is definitly anything other than great . The build times are extremly long (approx 15-20min) and if I enable the minify plugin, it can go up to an hour. I guess we really need some optimization otherwise it wont work properly for bigger projects. Still thanks for all the effort you put in there :) I really hope this gets fixed.

**Comment by wilhelmer** [comment] 2021-12-22 17:49
@malohr Did you try my solution?

**Comment by squidfunk** [comment] 2021-12-22 19:18
@malohr – I'm actively working on bringing down the size of the final output and think I have a working prototype ready soon. Regarding build times – I think this should be raised over at the MkDocs repository.

**Comment by malohr** [comment] 2021-12-22 21:04
@wilhelmer Haven’t tried it but will definitely give this a shot until there is an official release that will fix it, thank you :)

@squidfunk Awesome, really appreciate all your work. This is just the missing piece to make the project perfect for big docs.

**Comment by zilom75** [comment] 2022-01-18 14:38
@wilhelmer 
I tried it! :)
I run my mkdocs site in a docker container as an Azure web app. The image was getting too big and it had problems being unpacked in Azure.
With this fix, my docker image went from 1.89GB to 789MB. 
I'm more worried about storage sizes in cloud, but the performance improvement in runtime is welcome as well.

Thanks! :)

**Comment by wilhelmer** [comment] 2022-03-01 09:40
@squidfunk Here's a project with a large topic: [large-topic.zip](https://github.com/squidfunk/mkdocs-material/files/8160448/large-topic.zip)

Yes I know, the `index.md` content is horrible, it's auto generated. Still: Why does it take so long to render `index.html`?

If I remove the assets and load the pure HTML file, it's loading fast. So it must be something about Material. It would be great if you could take a look at this.

**Comment by squidfunk** [comment] 2022-03-01 10:50
@wilhelmer please open a new issue, as this issue has become too high-level.

**Comment by squidfunk** [comment] 2022-05-22 08:27
I've got a working solution for navigation pruning ready to be tested 😊 Does somebody have a public Open Source project with a huge navigation structure that might benefit from those optimizations? I'd like to run some numbers before releasing.

**Comment by aimeos** [comment] 2022-05-24 06:23
Our docs are not that large as the ones from @wilhelmer but you can see if there's an improvement:
https://github.com/aimeos/aimeos-docs

**Comment by squidfunk** [comment] 2022-05-24 20:40
Thanks for providing the link to your docs. I've tested with the new `navigation.prune` feature, and the total size of the documentation reduced from `70MB to `47MB, so –33% by pruning navigation nodes alone. Lighthouse shows that on an average page, DOM nodes could be reduced from 1,268 to 247 (–81%). I'll wrap these findings up in a blog article tomorrow.

**Comment by squidfunk** [comment] 2022-06-07 08:57
Yeah! Love it! Definitely need to write a blog article about this, as it might get lost in the vast amount of options that we offer.

**Comment by wilhelmer** [comment] 2022-06-07 20:08
However ... the downside of your implementation is that it actually changes the UX. You can't just look around and expand different sections of the nav anymore while staying on the same page. Expanding a section will always cause a page reload. 

I'm not sure this is worth the extra gain in file size. I think I'd rather go with my 72 MB and not sacrifice the UX for it.

No offense though - you know I absolutely admire your work, and maybe that's the best way to go for most users. I'm just not sure whether it's right for my project.

**Comment by squidfunk** [comment] 2022-06-07 20:42
Jup, the current solution is really the maximum we can save without sacrificing navigation layout. My motivation for the navigation pruning feature was the main use case being "download for offline use", where a page load doesn't matter at all, because loading from the file system is instant anyway.

**Comment by wilhelmer** [comment] 2022-06-08 06:45
I'd argue that even when browsing locally, the page load affects the UX – the screen flickers, and the content changes as you are effectively moving to a new page. It just doesn't feel as smooth as browsing through the nav tree without any reloads.

My point is that you can still save a lot without *any* noticeable change if `navigation.tabs` is enabled. Because then, you can simply cut off all navigation items within the non-active tabs, which you can't access anyway (as discussed above).

So maybe `navigation.prune` could behave differently depending on whether `navigation.tabs` is enabled or not.  But then again, you run into problems with the mobile drawer. Might be too complex.

**Comment by glenn-jocher** [comment] 2024-02-04 15:55
@wilhelmer @squidfunk stumbled upon this issue today after a poor lightspeed test of our Mkdocs page showing the same excessive DOM elements.

We have about 300 docs pages and lightspeed is showing 1500 DOM elements. I inspected the page in Chrome and was surprised to see that the entire navigation is apparently loaded into the HTML of every single docs page, even for pages that I would think are incapable of displaying those navigation elements.

I really like the `navigation.sections` option, but we need to improve our page load speeds and this seems like an area that is suboptimal. This example page at https://docs.ultralytics.com/help/ only appears to show a maximum of 22 possible navigation links in the top and left bars, but 300 other links are loaded in the background (!). I'm using `navigation.prune` also, my YAML is at https://github.com/ultralytics/ultralytics/blob/main/mkdocs.yml.

<img width="1820" alt="Screenshot 2024-02-04 at 16 53 57" src="https://github.com/squidfunk/mkdocs-material/assets/26833433/2bca5f69-cf93-4009-96d6-d2c149e19cd8">

**Comment by squidfunk** [comment] 2024-02-05 01:08
> if I add new pages in other remote regions of my documentation, this /help page will continue to get larger and slower, which runs quite contrary to what I'd expect.

@glenn-jocher I'm not sure I understand.

`navigation.prune` should only include links that are actually reachable from the current page. Thus, you might either have found a bug in navigation pruning, or there's a misconception we need to clarify. Could you please provide a minimal reproduction, so we have something to discuss? 1,400 nodes is a sign that pruning is not active (see https://github.com/squidfunk/mkdocs-material/issues/1887#issuecomment-1136410156), so it might be an error on your or on our side. 300 pages should not be a problem at all.

**Comment by glenn-jocher** [comment] 2024-02-09 00:11
@squidfunk thanks for your patience. I've isolated a minimum reproducible example in a new `mkdocs_reproduce` branch in https://github.com/ultralytics/ultralytics/tree/mkdocs-reproduce

### Reproduce

```python
# Clone the repo
git clone https://github.com/ultralytics/ultralytics
git checkout mkdocs_reproduce
cd ultralytics
pip install mkdocs-material

mkdocs serve
```

**Comment by squidfunk** [comment] 2024-02-09 06:31
Thanks for the reproduction. Indeed, pruning does not work correctly, as there's a bug when the following three feature flags are all enabled at once:

- `navigation.prune`
- `navigation.sections`
- `navigation.tabs`

It works correctly if the last two features are not enabled, or if either one is enabled, but not if both are enabled. This should now be fixed with 292d563cb, where I also expanded the kind of cryptic boolean condition to make it more explicit. My testing shows the issue is now fixed, and pruning works as expected. Can you confirm, @glenn-jocher?

For debugging, it's good to add the following CSS to see pruning in action:

``` css
.md-nav__item--section {
  background: green !important;
}
.md-nav__item--pruned {
  background: red !important;
}
```

**Comment by glenn-jocher** [comment] 2024-02-09 11:44
@squidfunk the update works! Also our Docs without any plugins build 3x faster now, from 3s to 1s. Everything feels a little faster while navigating too. Nice work on the fix.

Please release a pip update when possible, thank you!

**Comment by squidfunk** [comment] 2024-02-10 06:21
Released as part of [9.5.9](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.9). For all other navigation pruning related bugs, please open new issues.

**Comment by glenn-jocher** [comment] 2024-02-10 12:22
Perfect, thank you!

**Comment by vincentkelleher** [comment] 2024-02-27 08:48
Fantastic work @squidfunk, thanks for your work on this subject 👍 

I had the issue with the Gitlab Pages size limit being attained, the `navigation.prune` feature saved the day by cutting our documentation from ~870MB to ~165MB 👏
