### ISSUE TITLE
LinkedIn no longer able to generate previews

### ISSUE THREAD

**Issue by dgoosens** [squidfunk/mkdocs-material#7294] opened 2024-06-25 12:11 UTC
### Bug description

When sharing a link on LinkedIn, it should generate a preview...    
Just noticed this no longer works

First thought it was something on my end, but it appears something is wrong with mkdocs  
when trying to share a link to the squidfunk, I get the same issue

this can be tested here, in the LinkedIn Post Inspector:  
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fsquidfunk.github.io%2Fmkdocs-material%2Fblog%2F2023%2F10%2F02%2Fsunsetting-gitter-towards-efficient-community-engagement%2F

This used to work...

### Related links

n/a

### Reproduction

n/a

### Steps to reproduce

See https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fsquidfunk.github.io%2Fmkdocs-material%2Fblog%2F2023%2F10%2F02%2Fsunsetting-gitter-towards-efficient-community-engagement%2F

it is no longer able to generate a preview and it shows a 500 ERROR  
am getting the same for my blog:  
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fnotes.belgeek.dev%2Fmisc%2F2024%2F06%2F25%2Fdeclaration-universelle-des-droits-de-l-esprit-humain%2F

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment] 2024-06-25 12:19
Thanks for reporting! A 500 error denotes that LinkedIn has a problem generating previews. I've just checked and preview work perfectly on Twitter, and the Open Graph checker also says that preview are fine:

https://www.opengraph.xyz/url/https%3A%2F%2Fsquidfunk.github.io%2Fmkdocs-material
https://www.opengraph.xyz/url/https%3A%2F%2Fsquidfunk.github.io%2Fmkdocs-material%2Freference%2F

Thus, it's probably LinkedIn that's broken. Closing as non-actionable.

**Closed by squidfunk** 2024-06-25 12:19 UTC

**Comment by kamilkrzyskow** [comment] 2024-06-26 02:48
These home pages work on LinkedIn as well:
[mkdocs-material home page](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fsquidfunk.github.io%2Fmkdocs-material%2F)
[privacy guides home page](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.privacyguides.org%2Fen%2F)

However, nested, deeper paths break:
[getting-started page](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fsquidfunk.github.io%2Fmkdocs-material%2Fgetting-started%2F)
[about privacy guides](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.privacyguides.org%2Fen%2Fabout%2F)

So I initially thought, the issue could be related to relative paths in the HTML tags 🤔 
But this doesn't connect with your blog home page not working either 😅 
[your site home page](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fnotes.belgeek.dev%2F)

Also [this random community blog page](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fopendatasicilia.github.io%2Fguida-umap%2Fblog%2F2023%2F12%2F21%2F4-giorni-a-natale-vi-facciamo-un-regalo-una-guida-per-visionare-e-creare-mappe-con-umap%2F) taken from the comments here: https://squidfunk.github.io/mkdocs-material/blog/2023/11/30/adding-a-badge-to-your-project/ works 🤯 
The page uses the non-Insiders version of the theme, and not the newest version.

So hard to say what causes LinkedIn to throw up, I did a diff compare of the `<head>` and didn't see anything suspicious, we also don't know if the issue is inside the `<head>` section or if something else in the HTML breaks the parser. If you want to get to the bottom of this, there are a couple of things you could debug:
- Remove custom `<head>` content
- Turn off Insiders if possible
- Play around with the `<meta>` values and set them to be static

otherwise report it to LinkedIn and wait for a fix.
