### ISSUE TITLE
bug: navigating to anchor links within an admonition not working with navigation.instant

### ISSUE THREAD

**Issue by Valastiri** [squidfunk/mkdocs-material#5239] opened 2023-03-21 19:01 UTC
### Context

We have a "reported issues" tracking page on our documentation that utilizes H3 elements within collapsed admonitions to help provide navigation on page with the TOC and create a more condensed page (reading wise).

Recently we reintroduced `navigation.instant` to our docs as part of mkdocs-material 9.1.1 to solve the following issues outlined in this PR:

- https://github.com/flybywiresim/docs/pull/745

Ideally what usually happens is when a user clicks on a link in the TOC it would take them to the relevant section on the page and open the admontion. 

*removed live site example as we removed instant navigation on production*
*example.zip with minimal repro provided below*

#### Issue

With `navigation.instant` enabled on our build we recently discovered that clicking on links in the table of contents in certain browsers outlined below would not jump to the relevant anchor/section when the header is positioned within a collapsible admonition.

It is currently not working on:
- Safari (all devices)
- Firefox (Windows + iPadOS tested)

Example:

```
??? bug "Title of Admonition"
		### header

		text
```

---

#### Additional Context

This setup has worked for us on all browsers and devices until we discovered this issue recently with no changes to our build. Currently, it only works on the Chrome Browser (Windows + MacOS + Mobile Devices).

---

It is important to note that anchor links / section links work flawlessly on any browser when the header is not placed within an admonition.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)

Relevant Discussions I looked at:
- https://github.com/squidfunk/mkdocs-material/discussions/5073
- https://github.com/squidfunk/mkdocs-material/issues/3797

### Reproduction

Example provided below

Please see the page titled `Example Issue:` it is a clone of our reported issues page on our live site. 

[example.zip](https://github.com/squidfunk/mkdocs-material/files/11032531/example.zip)

### Steps to reproduce

1. Ensure `navigation.instant` is active in the config.
2. Ensure that admonitions is configured in the config.
3. Create a collapsible admonition with a header element nested within (example in bug section or below here) on a page of your choice
4. Spin up `mkdocs serve` or build
5. Navigate to `localhost:8000` or open index.html on Safari or Firefox
6. Using Safari or Firefox // on the page try and navigate to a header nested within an admonition (samples available in repro zip file)

Expected outcome: You would be taken to the link you clicked on in the TOC + admonition would open to reveal content.

Current outcome: Navigation does not happen and TOC links are inoperable.

---

Example admonition setup:

```
??? bug "Title of Admonition"
		### header

		text
```

### Browser

Safari, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment] 2023-03-24 11:34
Thanks for reporting, and especially for the excellent reproduction. That made troubleshooting straightforward. This is a regression of the latest refactoring in instant loading and I took the time to investigate why this is the case. My findings:

Previously, [instant loading filtered hash changes](https://github.com/squidfunk/mkdocs-material/blob/c64493760e517361b58bd6aa198e959377830603/src/assets/javascripts/integrations/instant/index.ts#L152-L160) (= clicking on anchors) that happen on the same page, and leave them to the browser. This triggered the logic we have in place to detect whether an anchor is targeting something that is located in a hidden element, which is currently only implemented for `details` elements:

https://github.com/squidfunk/mkdocs-material/blob/ab23604fb0c19c0d7b8cfb9cdada55780cf393ba/src/assets/javascripts/components/content/details/index.ts#L86-L94

Now, if you look at the commit history, these lines were added two years ago before the advent of code annotations, content tabs with anchor links and other features that may include anchors in hidden elements. The latest refactoring of instant loading that was released in [9.1.1](https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.1) has a different behavior as it will now also handle anchor links. The reason is primarily to correctly implement scroll restoration, i.e., when you click on a link, then scroll down, then navigate away and go back to that section. Additionally, instant loading had sometimes problems on slow connections, which were also fixed with this release. However, it leads to the problem that in some browsers (notably Firefox and Safari), the `hashchange` event is not triggered anymore, as observed. While I would attribute this to a browser implementation inconsistency, it is likely related to us now also calling `Event.preventDefault` for pure anchor navigation events:

https://github.com/squidfunk/mkdocs-material/blob/ab23604fb0c19c0d7b8cfb9cdada55780cf393ba/src/assets/javascripts/integrations/instant/index.ts#L141-L146

The issue should be fixed with 183b0be12. I consider this a temporary bandaid, as we must defer control of anchor links to instant loading for the reasons stated. We will soon tackle proper expansion of nested hidden elements, which is not solely relevant when following anchor links, but also for search highlighting (see #4125). Also, see https://github.com/squidfunk/mkdocs-material/issues/4125#issuecomment-1442089570 why this is particularly challenging, as cases become pathological quite quickly.

**Closed** 2023-03-24 12:54 UTC
Labels: bug, resolved

**Comment by endel** [comment] 2023-05-02 00:28
Sorry for commenting on a closed thread but `navigation.instant` is causing the page to scroll when clicking on code tab anchors for me. Is this something happening for you as well? (I'm using the insiders version)

(If that's not a known issue, I can prepare a repro scenario soon!)

**Comment by squidfunk** [comment] 2023-05-02 06:02
Not known. Please create a [bug report](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/), provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), and we're happy to look into it!
