### ISSUE TITLE
Double-click required for collapsed navigation menus on desktop

### ISSUE THREAD

**Issue by markmcb** [squidfunk/mkdocs-material#6726] opened 2024-02-01 03:48 UTC
### Bug description

In a desktop browser, if the page is narrowed such that the "hamburger" (three bars) icon appears, you can open the menu with a single click, but all sub items require two distinct clicks. Expected: single clicks in all cases.

On mobile this is not an issue, i.e., a single tap activates the sub items.

### Related links

- [Navigation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navi)

### Reproduction

I get a warning that the zip is too big.

### Steps to reproduce

This page exhibits the problem: https://markmcb.com/
Shrink width to see hamburger/3-bar menu icon, click/double-click sub items.

relevant mkdocs.yml
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow
    - header.autohide

### Browser

Safari, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment] 2024-02-01 08:57
Thanks for reporting. This must be a bad interaction between features or between features and customization. Can you please provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/)? If you got the warning that the `.zip` file was too big to upload to GitHub then chances are what you tried to share was not minimal enough. 

We are talking about removing all but the essential content, all customizations and removing things from `mkdocs.yml` until the problem no longer occurs, then adding back in the last bit removed. This usually provides a good indication of where the problem lies so we can start looking in the right place. This is particularly important in the case of bad interactions. This will help you get a speedy resolution.

**Comment by squidfunk** [comment] 2024-02-01 10:15
>   I get a warning that the zip is too big.

Please carefully read our [reproduction guide](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). If your zip file is too big, your reproduction is not minimal, so you like did not follow the required steps as outlined in our bug reporting guide.

Closing as incomplete. We're happy to reopen once you manage to provide a reproduction, so we can observe the issue, which we currently can't. No double click is necessary, so it boils down to "works on my machine".

**Comment by markmcb** [comment] 2024-02-01 16:37
@squidfunk if you want to ignore the bug, totally up to you. Just letting you know it exists. When I get a chance, I'll try the triage steps to narrow down the source. I see now that I misread it and a new project is required, not an existing one.

When you say you can't observe it, are you saying markmcb.com works for you with single clicks, or just that I didn't follow your process? If you did get it to work on that site, I'd be curious what platform it works for you on. I've tested on Linux Firefox, FreeBSD Firefox, macOS M2 Firefox/Safari, macOS Intel Firefox/Safari/Chrome, Windows 10 Edge. All exhibit the same issue every time, double-click required "sub-hamburger" (to be clear, the hamburger/3-bar menu expands with one click, the sub menus do not).

**Comment by alexvoss** [comment] 2024-02-01 16:45
I could see the effect on your website (MacOS, both Firefox and Safari). We do need a reproduction so we can play with it locally, know what versions are used, etc. Debugging someone else's site and now knowing these details is not feasible.

**Comment by markmcb** [comment] 2024-02-01 16:50
@alexvoss thanks. Just validating I'm not crazy. Will follow up on using the steps outlined. As for versions, it's fully up-to-date as of last night. I updated everything one last time before reporting. The bug has existed for months, since I first starting using mkdocs-material, I just never got around to reporting it.

**Comment by markmcb** [comment] 2024-02-01 17:59
[9.5.6-double-click.zip](https://github.com/squidfunk/mkdocs-material/files/14129102/9.5.6-double-click.zip)

It seems navigation.expand is the trigger for the issue.

**Comment by squidfunk** [comment] 2024-02-02 05:47
> @squidfunk if you want to ignore the bug, totally up to you. 

I did not mention that at any point. We did not receive something we can work with, and we cannot observe it, so it is currently not considered a bug. I also said, that we will reopen it once you provide the reproduction, which we do now.

**Comment by markmcb** [comment] 2024-02-02 06:26
@squidfunk no worries, I get it. We're victims of the same clock. You don't have time for reading terse bug reports, I don't have time for writing proper ones. ;) Hopefully you have what you need now. Thanks for the help!

**Comment by markmcb** [comment] 2024-02-03 00:10
Just for clarity, in case anyone reads the thread and looks to markmcb.com for an example, I have removed that feature from my config and therefore the double-click is no longer required.

**Comment by squidfunk** [comment] 2024-02-03 02:58
Thanks for providing the reproduction. I'm not able to reproduce this in either Chrome, Firefox or Safari on macOS:

Case 1:

1. Open http://localhost:8000 on narrow viewport
2. Click on hamburger menu which opens on single click
3. Click on "Subpage" which opens on single click

Case 2:

1. Open http://localhost:8000 on wide viewport
2. Narrow screen so hambruger shows
3. Click on hamburger menu which opens on single click
4. Click on "Subpage" which opens on single click

In both cases, only a single click is necessary in Firefox or Safari. Thus, I cannot reproduce it on my machine, which is weird. Could you please provide _exact_ instructions what you do? The instructions provided are either incomplete or do not reproduce the problem.

**Comment by squidfunk** [comment] 2024-02-03 03:08
Closing as not reproducible. Happy for more input on this issue, but it's currently not an issue, as we cannot observe the problem you reported. If you or somebody else manages to come up with something that reproduces the problem, we're happy to reopen and investigate.

**Closed by squidfunk** 2024-02-03 03:08 UTC
Labels: needs reproduction

**Comment by markmcb** [comment] 2024-02-03 05:28
Very strange. I'm on a different computer now and just set it up and reproduced it again (macOS, both Firefox and Safari).

Exact steps copied from cli:

```
mkdir /tmp/retestbug
cd /tmp/retestbug
python3 -m venv venv
source venv/bin/activate
pip install --upgrade --force-reinstall mkdocs-material
deactivate
source venv/bin/activate
mkdocs new .
mkdir docs/sublevel
touch docs/sublevel/index.md
nvim mkdocs.yml

site_name: My Docs
theme:
  name: material
  features:
  - navigation.expand
plugins:
  - info
mkdocs serve
```

Double-click required. New zip attached using 9.5.7 this time.

[9.5.7-double-click-2ndexample.zip](https://github.com/squidfunk/mkdocs-material/files/14150045/9.5.7-double-click-2ndexample.zip)

**Comment by alexvoss** [comment] 2024-02-03 06:18
I have had a look and was able to reproduce it in Safari. A double click was needed when first opening the hamburger menu and clicking on "Sublevel". In Firefox the problem did not seem to occur. This is odd because I think it did show the behavior on the website the OP pointed to (before it was changed).

https://github.com/squidfunk/mkdocs-material/assets/4134224/a6706208-c08d-4f2e-9d15-c7fd44007149

Running Safari Version 17.2.1 (19617.1.17.11.12) on MacOS 14.2.1 (23C71).

**Comment by squidfunk** [comment] 2024-02-03 07:10
Thanks for checking. I did the exact same – opens immediately on my machine. Interestingly, I'm running Safari 16.1 (can't currently update), so it might be related to this discrepancy. However, since this seems to affect a tiny fraction of users, and is pretty much an edge case (hamburger menu = rather mobile users = touch, only happens on pointer), I'd close it as currently infeasible for investigation. We'll reconsider this once we do the facelift, since navigation mechanics might change.

**Comment by soronpo** [comment] 2024-05-08 01:50
I'm also experiencing this on both my computer and mobile website at https://dfianthdl.github.io/
Tried both firefox and edge on my computer. 
Can someone look to confirm they see it too?

**Comment by soronpo** [comment] 2024-05-08 02:02
I noticed that on my website we have this md-toggle--indeterminate whereas it does not exist on the mkdocs material documentation website. Unclear as to why.
![bad](https://github.com/squidfunk/mkdocs-material/assets/8167952/8d552499-1020-4857-a4aa-c12b8e506e0e)

**Comment by soronpo** [comment] 2024-05-08 02:20
I found a workaround. I created a javascript that removes the `md-toggle-indeterminate` class from the element:
```js
document.addEventListener("DOMContentLoaded", function() {
  const inputs = document.querySelectorAll('input.md-nav__toggle.md-toggle');
  inputs.forEach(function(input) {
      input.classList.remove('md-toggle--indeterminate');
  });
});
```
Not sure if I'm doing something bad here or not, but everything seems to workout fine.
