### ISSUE TITLE
About TOC of 'Blog'

### ISSUE THREAD

**Issue by AIGC2024** [squidfunk/mkdocs-material#7064] opened 2024-04-19 07:05 UTC
### Description

[blog_toc](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.blog_toc)
After add the configure
`
plugins:
  - blog:
      blog_toc: true
`
into yml file . It doesn't work when i click 'Blog' , no Toc in the right 

### Related links

- [blog_toc](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.blog_toc)
-

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by alexvoss** [comment] 2024-04-19 07:10
Works fine for me. You could help us investigate the problem by creating a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). Without a way to reproduce the problem on our own systems there is nothing we can do.

**Comment by katharinalisalin** [comment] 2024-04-19 07:12
Thanks for reporting. However, you did follow our [bug reporting guideline](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) and did not attach a [.zip file with a minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file).
Please provide us with a minimal reproduction, and we'll be happy to take a look. Until then, I'll mark this issue as [incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues-and-duplicates) and close it for now.

**Closed by katharinalisalin** 2024-04-19 07:12 UTC
Labels: needs reproduction

**Comment by AIGC2024** [comment] 2024-04-19 11:58
> Works fine for me. You could help us investigate the problem by creating a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). Without a way to reproduce the problem on our own systems there is nothing we can do.

HERE is the minimal reproduction
[9.5.18-example.zip](https://github.com/squidfunk/mkdocs-material/files/15039887/9.5.18-example.zip)

Thank you so much

**Comment by alexvoss** [comment] 2024-04-19 13:17
I am unable to reproduce this. The blog index pages have a table of contents as expected.

**Comment by AIGC2024** [comment] 2024-04-19 14:41
> I am unable to reproduce this. The blog index pages have a table of contents as expected.

So what should i do with the blog index pages .

**Comment by AIGC2024** [comment] 2024-04-20 04:09
> 好的，原来修复方法是在文件中添加一个标题，然后出现 ToC。你有一个完全空的文件。`blog/index.md`
> 
> ![图像](https://private-user-images.githubusercontent.com/4134224/324030831-6e5c6616-5d9f-4184-b2cf-4024a250df8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1ODYyNTIsIm5iZiI6MTcxMzU4NTk1MiwicGF0aCI6Ii80MTM0MjI0LzMyNDAzMDgzMS02ZTVjNjYxNi01ZDlmLTQxODQtYjJjZi00MDI0YTI1MGRmOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMDQwNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdiOTIwNjBmNTA3YTAwMDc2ZTRhMTliNTllZTJmYTliYWRjZWQwNmE5NDM0NTk5NDQ1NmYwNjFhNmVlN2NiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fg3GMvlAQKrPz5Q_TQADRchEgVP2q2Xs0n-l3ySOJog)

wow, so cool. It's done. thanks a lot.
